//! Principal uid/gid allocation for the foundation seed.
//!
//! Manifests declare principals by name only; the numeric identity is
//! allocated once by the packaging generator and persisted in the committed
//! allocation document this module loads. The daemon never mints an id at
//! runtime: a declared principal the committed document does not name is a
//! seed refusal, so the identity a worker runs as is stable across restarts
//! and hosts, and a re-seed can never renumber a live principal.
//!
//! Allocation (generator side) hands each unseen name the next free id inside
//! the reserved range and refuses a candidate that some host account already
//! owns, so a generated allocation cannot collide with the host account
//! table.

use std::collections::{BTreeMap, BTreeSet};

use serde_json::{Map, Value};

/// First uid/gid the allocator hands to an unseen principal name.
#[allow(dead_code)]
pub const PRINCIPAL_RANGE_START: u32 = 900;
/// Last uid/gid the allocator hands to an unseen principal name.
#[allow(dead_code)]
pub const PRINCIPAL_RANGE_END: u32 = 999;
/// Largest id the committed document may carry.
pub const MAX_PRINCIPAL_ID: u32 = 0x00FF_FFFF;
/// Maximum bytes of one principal name.
pub const MAX_PRINCIPAL_NAME_BYTES: usize = 63;
/// The committed allocation document, generated by the packaging generator.
pub const COMMITTED_ALLOCATION: &str =
    include_str!("../../../docs/reference/policy/principal-allocation.json");

/// One allocated principal identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct PrincipalId {
    uid: u32,
    gid: u32,
}

impl PrincipalId {
    /// Construct one identity from its numeric pair.
    pub const fn new(uid: u32, gid: u32) -> Self {
        Self { uid, gid }
    }

    /// The uid the principal executes as.
    ///
    /// Read by the packaging generator and the launch path; the daemon's seed
    /// only checks that an allocated entry exists.
    #[allow(dead_code)]
    pub const fn uid(&self) -> u32 {
        self.uid
    }

    /// The gid the principal executes as.
    #[allow(dead_code)]
    pub const fn gid(&self) -> u32 {
        self.gid
    }
}

/// The committed name-to-id document.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PrincipalAllocation {
    principals: BTreeMap<String, PrincipalId>,
}

impl PrincipalAllocation {
    /// Load one committed allocation document.
    pub fn from_json(bytes: &[u8]) -> Result<Self, PrincipalAllocationError> {
        let value: Value =
            serde_json::from_slice(bytes).map_err(|_| PrincipalAllocationError::Malformed)?;
        let object = value
            .as_object()
            .ok_or(PrincipalAllocationError::Malformed)?;
        let version = object
            .get("version")
            .and_then(Value::as_u64)
            .ok_or(PrincipalAllocationError::Malformed)?;
        if version != 1 {
            return Err(PrincipalAllocationError::Malformed);
        }
        let entries = object
            .get("principals")
            .and_then(Value::as_object)
            .ok_or(PrincipalAllocationError::Malformed)?;
        let mut principals = BTreeMap::new();
        let mut seen: BTreeMap<u32, String> = BTreeMap::new();
        for (name, entry) in entries {
            if !valid_principal_name(name) {
                return Err(PrincipalAllocationError::InvalidName);
            }
            let entry = entry
                .as_object()
                .ok_or(PrincipalAllocationError::Malformed)?;
            let uid = entry
                .get("uid")
                .and_then(Value::as_u64)
                .and_then(|uid| u32::try_from(uid).ok())
                .filter(|uid| (1..=MAX_PRINCIPAL_ID).contains(uid))
                .ok_or(PrincipalAllocationError::Malformed)?;
            let gid = entry
                .get("gid")
                .and_then(Value::as_u64)
                .and_then(|gid| u32::try_from(gid).ok())
                .filter(|gid| (1..=MAX_PRINCIPAL_ID).contains(gid))
                .ok_or(PrincipalAllocationError::Malformed)?;
            if let Some(existing) = seen.insert(uid, name.clone())
                && existing != *name
            {
                return Err(PrincipalAllocationError::DuplicateId);
            }
            principals.insert(name.clone(), PrincipalId::new(uid, gid));
        }
        Ok(Self { principals })
    }

    /// Load the committed allocation document this build ships.
    pub fn committed() -> Result<Self, PrincipalAllocationError> {
        Self::from_json(COMMITTED_ALLOCATION.as_bytes())
    }

    /// Render the document back to its committed form.
    ///
    /// The packaging generator persists the document; the daemon only loads
    /// it, so this renderer has no production caller in the daemon crate and
    /// is exercised by this module's tests.
    #[allow(dead_code)]
    pub fn to_json(&self) -> String {
        let principals: Map<String, Value> = self
            .principals
            .iter()
            .map(|(name, id)| {
                (
                    name.clone(),
                    serde_json::json!({ "gid": id.gid, "uid": id.uid }),
                )
            })
            .collect();
        let document = serde_json::json!({
            "version": 1,
            "range": { "start": PRINCIPAL_RANGE_START, "end": PRINCIPAL_RANGE_END },
            "principals": Value::Object(principals),
        });
        format!(
            "{}\n",
            serde_json::to_string_pretty(&document).expect("allocation document renders")
        )
    }

    /// The identity of one allocated name.
    pub fn get(&self, name: &str) -> Option<PrincipalId> {
        self.principals.get(name).copied()
    }

    /// Allocate every name that has no entry yet, in sorted order.
    ///
    /// This is the packaging generator's path; the daemon only reads the
    /// committed document, so this entry point has no production caller in
    /// the daemon crate and is exercised by this module's tests.
    ///
    /// An existing name keeps its committed id forever; an unseen name takes
    /// the next free id in the reserved range. A candidate the host account
    /// table already owns (`taken`) is skipped, and exhausting the range is a
    /// refusal, never a silent reuse.
    #[allow(dead_code)]
    pub fn allocate_names(
        &mut self,
        names: impl IntoIterator<Item = String>,
        taken: &BTreeSet<u32>,
    ) -> Result<Vec<(String, PrincipalId)>, PrincipalAllocationError> {
        let mut wanted: BTreeSet<String> = names.into_iter().collect();
        wanted.retain(|name| !self.principals.contains_key(name));
        let mut allocated = Vec::with_capacity(wanted.len());
        for name in wanted {
            if !valid_principal_name(&name) {
                return Err(PrincipalAllocationError::InvalidName);
            }
            let mut candidate = PRINCIPAL_RANGE_START;
            loop {
                if candidate > PRINCIPAL_RANGE_END {
                    return Err(PrincipalAllocationError::RangeExhausted);
                }
                let used = self.principals.values().any(|id| id.uid == candidate)
                    || taken.contains(&candidate);
                if !used {
                    break;
                }
                candidate += 1;
            }
            let id = PrincipalId::new(candidate, candidate);
            self.principals.insert(name.clone(), id);
            allocated.push((name, id));
        }
        Ok(allocated)
    }
}

/// One invalid allocation document or allocation request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PrincipalAllocationError {
    /// The document is not the committed allocation shape.
    Malformed,
    /// A principal name is empty, over bound, or not a bounded token.
    InvalidName,
    /// Two names claim the same uid.
    DuplicateId,
    /// The reserved range holds no free id.
    RangeExhausted,
}

impl core::fmt::Display for PrincipalAllocationError {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str(match self {
            Self::Malformed => "principal allocation document is malformed",
            Self::InvalidName => "principal name is not a bounded token",
            Self::DuplicateId => "principal allocation reuses one uid for two names",
            Self::RangeExhausted => "principal allocation range holds no free id",
        })
    }
}

impl std::error::Error for PrincipalAllocationError {}

/// Whether one name is a well-formed principal name.
pub fn valid_principal_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= MAX_PRINCIPAL_NAME_BYTES
        && name.bytes().enumerate().all(|(index, byte)| {
            if index == 0 {
                byte.is_ascii_lowercase()
            } else {
                byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-'
            }
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_committed_document_loads_and_names_the_host_principals() {
        let allocation = PrincipalAllocation::committed().expect("committed allocation loads");
        assert_eq!(
            allocation.get("d2b-zonert"),
            Some(PrincipalId::new(2_373_244, 2_373_244))
        );
        assert_eq!(allocation.get("d2bd"), Some(PrincipalId::new(997, 997)));
    }

    #[test]
    fn allocation_is_reused_across_reloads() {
        let mut allocation = PrincipalAllocation::default();
        let taken = BTreeSet::new();
        let first = allocation
            .allocate_names(vec!["worker-alpha".to_owned()], &taken)
            .expect("allocates");
        assert_eq!(first[0].1.uid(), PRINCIPAL_RANGE_START);
        let persisted = allocation.to_json();
        let reloaded = PrincipalAllocation::from_json(persisted.as_bytes()).expect("reloads");
        assert_eq!(reloaded.get("worker-alpha"), Some(first[0].1));
        // A restarted generator allocates the next name without renumbering.
        let mut restarted = reloaded;
        let second = restarted
            .allocate_names(vec!["worker-beta".to_owned()], &taken)
            .expect("allocates");
        assert_eq!(second[0].1.uid(), PRINCIPAL_RANGE_START + 1);
        assert_eq!(restarted.get("worker-alpha"), Some(first[0].1));
    }

    #[test]
    fn host_uid_overlaps_and_range_exhaustion_are_refused() {
        let mut allocation = PrincipalAllocation::default();
        let taken = BTreeSet::from([PRINCIPAL_RANGE_START, PRINCIPAL_RANGE_START + 1]);
        let allocated = allocation
            .allocate_names(vec!["worker".to_owned()], &taken)
            .expect("allocates around taken ids");
        assert_eq!(allocated[0].1.uid(), PRINCIPAL_RANGE_START + 2);

        let mut exhausted = PrincipalAllocation::default();
        let taken = (PRINCIPAL_RANGE_START..=PRINCIPAL_RANGE_END).collect();
        assert_eq!(
            exhausted.allocate_names(vec!["worker".to_owned()], &taken),
            Err(PrincipalAllocationError::RangeExhausted)
        );
    }

    #[test]
    fn malformed_names_and_duplicate_ids_are_refused() {
        for name in ["", "Upper", "with space", "a".repeat(MAX_PRINCIPAL_NAME_BYTES + 1).as_str()]
        {
            let mut allocation = PrincipalAllocation::default();
            assert_eq!(
                allocation.allocate_names(vec![name.to_owned()], &BTreeSet::new()),
                Err(PrincipalAllocationError::InvalidName)
            );
        }
        let duplicate = r#"{"version":1,"principals":{"alpha":{"uid":900,"gid":900},"beta":{"uid":900,"gid":900}}}"#;
        assert_eq!(
            PrincipalAllocation::from_json(duplicate.as_bytes()),
            Err(PrincipalAllocationError::DuplicateId)
        );
    }
}
