//! Principal uid/gid allocation for the foundation seed.
//!
//! Manifests declare principals by name only; the numeric identity is
//! allocated once by the packaging generator and persisted in the committed
//! allocation document this module loads. The daemon never mints an id at
//! runtime: a declared principal the committed document does not name is a
//! seed refusal, so the identity a worker runs as is stable across restarts
//! and hosts, and a re-seed can never renumber a live principal.
//!
//! Allocation (generator side) hands each unseen name the next free id inside
//! the reserved range and refuses a candidate that some host account already
//! owns, so a generated allocation cannot collide with the host account
//! table. The same refusal is reachable from the document side:
//! [`check_committed_against`] is handed a host account table and refuses a
//! committed allocation that table already overlaps, which is what
//! `d2bd principal-allocation` runs.

use std::collections::BTreeMap;
#[cfg(test)]
use std::collections::BTreeSet;

use serde_json::Value;
#[cfg(test)]
use serde_json::Map;

/// First uid/gid the allocator hands to an unseen principal name.
#[cfg(test)]
pub const PRINCIPAL_RANGE_START: u32 = 900;
/// Last uid/gid the allocator hands to an unseen principal name.
#[cfg(test)]
pub const PRINCIPAL_RANGE_END: u32 = 999;
/// Largest id the committed document may carry.
pub const MAX_PRINCIPAL_ID: u32 = 0x00FF_FFFF;
/// Maximum bytes of one principal name.
pub const MAX_PRINCIPAL_NAME_BYTES: usize = 63;
/// The committed allocation document, generated by the packaging generator.
pub const COMMITTED_ALLOCATION: &str =
    include_str!("../../../docs/reference/policy/principal-allocation.json");

/// One allocated principal identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct PrincipalId {
    uid: u32,
    gid: u32,
}

impl PrincipalId {
    /// Construct one identity from its numeric pair.
    pub const fn new(uid: u32, gid: u32) -> Self {
        Self { uid, gid }
    }

    /// The uid the principal executes as.
    ///
    /// Read by the packaging generator and the launch path; the daemon's seed
    /// only checks that an allocated entry exists.
    #[cfg(test)]
    pub const fn uid(&self) -> u32 {
        self.uid
    }

    /// The gid the principal executes as.
    #[cfg(test)]
    pub const fn gid(&self) -> u32 {
        self.gid
    }
}

/// The committed name-to-id document.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PrincipalAllocation {
    principals: BTreeMap<String, PrincipalId>,
}

impl PrincipalAllocation {
    /// Load one committed allocation document.
    pub fn from_json(bytes: &[u8]) -> Result<Self, PrincipalAllocationError> {
        let value: Value =
            serde_json::from_slice(bytes).map_err(|_| PrincipalAllocationError::Malformed)?;
        let object = value
            .as_object()
            .ok_or(PrincipalAllocationError::Malformed)?;
        let version = object
            .get("version")
            .and_then(Value::as_u64)
            .ok_or(PrincipalAllocationError::Malformed)?;
        if version != 1 {
            return Err(PrincipalAllocationError::Malformed);
        }
        let entries = object
            .get("principals")
            .and_then(Value::as_object)
            .ok_or(PrincipalAllocationError::Malformed)?;
        let mut principals = BTreeMap::new();
        let mut seen: BTreeMap<u32, String> = BTreeMap::new();
        for (name, entry) in entries {
            if !valid_principal_name(name) {
                return Err(PrincipalAllocationError::InvalidName);
            }
            let entry = entry
                .as_object()
                .ok_or(PrincipalAllocationError::Malformed)?;
            let uid = entry
                .get("uid")
                .and_then(Value::as_u64)
                .and_then(|uid| u32::try_from(uid).ok())
                .filter(|uid| (1..=MAX_PRINCIPAL_ID).contains(uid))
                .ok_or(PrincipalAllocationError::Malformed)?;
            let gid = entry
                .get("gid")
                .and_then(Value::as_u64)
                .and_then(|gid| u32::try_from(gid).ok())
                .filter(|gid| (1..=MAX_PRINCIPAL_ID).contains(gid))
                .ok_or(PrincipalAllocationError::Malformed)?;
            if let Some(existing) = seen.insert(uid, name.clone())
                && existing != *name
            {
                return Err(PrincipalAllocationError::DuplicateId);
            }
            principals.insert(name.clone(), PrincipalId::new(uid, gid));
        }
        Ok(Self { principals })
    }

    /// Load the committed allocation document this build ships.
    pub fn committed() -> Result<Self, PrincipalAllocationError> {
        Self::from_json(COMMITTED_ALLOCATION.as_bytes())
    }

    /// Render the document back to its committed form.
    ///
    /// The packaging generator persists the document; the daemon only loads
    /// it, so this renderer has no production caller in the daemon crate and
    /// is exercised by this module's tests.
    #[cfg(test)]
    pub fn to_json(&self) -> String {
        let principals: Map<String, Value> = self
            .principals
            .iter()
            .map(|(name, id)| {
                (
                    name.clone(),
                    serde_json::json!({ "gid": id.gid, "uid": id.uid }),
                )
            })
            .collect();
        let document = serde_json::json!({
            "version": 1,
            "range": { "start": PRINCIPAL_RANGE_START, "end": PRINCIPAL_RANGE_END },
            "principals": Value::Object(principals),
        });
        format!(
            "{}\n",
            serde_json::to_string_pretty(&document).expect("allocation document renders")
        )
    }

    /// The identity of one allocated name.
    pub fn get(&self, name: &str) -> Option<PrincipalId> {
        self.principals.get(name).copied()
    }

    /// Allocate every name that has no entry yet, in sorted order.
    ///
    /// This is the packaging generator's path; the daemon only reads the
    /// committed document, so this entry point has no production caller in
    /// the daemon crate and is exercised by this module's tests.
    ///
    /// An existing name keeps its committed id forever; an unseen name takes
    /// the next free id in the reserved range. A candidate the host account
    /// table already owns (`taken`) is skipped, and exhausting the range is a
    /// refusal, never a silent reuse.
    #[cfg(test)]
    pub fn allocate_names(
        &mut self,
        names: impl IntoIterator<Item = String>,
        taken: &BTreeSet<u32>,
    ) -> Result<Vec<(String, PrincipalId)>, PrincipalAllocationError> {
        let mut wanted: BTreeSet<String> = names.into_iter().collect();
        wanted.retain(|name| !self.principals.contains_key(name));
        let mut allocated = Vec::with_capacity(wanted.len());
        for name in wanted {
            if !valid_principal_name(&name) {
                return Err(PrincipalAllocationError::InvalidName);
            }
            let mut candidate = PRINCIPAL_RANGE_START;
            loop {
                if candidate > PRINCIPAL_RANGE_END {
                    return Err(PrincipalAllocationError::RangeExhausted);
                }
                let used = self.principals.values().any(|id| id.uid == candidate)
                    || taken.contains(&candidate);
                if !used {
                    break;
                }
                candidate += 1;
            }
            let id = PrincipalId::new(candidate, candidate);
            self.principals.insert(name.clone(), id);
            allocated.push((name, id));
        }
        Ok(allocated)
    }

    /// Every committed principal one host account table overlaps.
    ///
    /// The rule is the allocator's, seen from the document side: an id the
    /// host account table already hands to a differently named account is a
    /// collision, and so is a principal name the host declares with another
    /// id - the host would run that principal under an identity the document
    /// does not name.
    pub fn host_overlaps(&self, host: &HostAccounts) -> Vec<HostAccountOverlap> {
        let mut overlaps = Vec::new();
        for (principal, id) in &self.principals {
            if let Some(account) = host.account_of(id.uid)
                && account != principal.as_str()
            {
                overlaps.push(HostAccountOverlap {
                    principal: principal.clone(),
                    id: id.uid,
                    host_account: account.to_owned(),
                    host_id: id.uid,
                    kind: HostOverlapKind::IdOwnedByOtherAccount,
                });
            }
            if let Some(host_id) = host.uid_of(principal)
                && host_id != id.uid
            {
                overlaps.push(HostAccountOverlap {
                    principal: principal.clone(),
                    id: id.uid,
                    host_account: principal.clone(),
                    host_id,
                    kind: HostOverlapKind::NameDeclaredWithOtherId,
                });
            }
        }
        overlaps
    }
}

/// The host account table one allocation check is handed.
///
/// The daemon loads no host table at load time: whether a uid the committed
/// allocation pins is free is a property of the host the build deploys to,
/// and that host's account table is an explicit input of the check rather
/// than an assumption of the load path.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct HostAccounts {
    by_name: BTreeMap<String, u32>,
}

impl HostAccounts {
    /// Parse one `passwd`-format account table.
    ///
    /// Blank lines and comments are skipped. An account line that carries no
    /// name and numeric uid is a refusal rather than a silently dropped
    /// account, so a truncated table cannot pass for an empty one.
    pub fn parse_passwd(table: &str) -> Result<Self, PrincipalAllocationError> {
        let mut by_name = BTreeMap::new();
        for line in table.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let mut fields = line.split(':');
            let name = fields.next().unwrap_or_default();
            let uid = fields.nth(1).and_then(|uid| uid.parse::<u32>().ok());
            let Some(uid) = uid.filter(|_| !name.is_empty()) else {
                return Err(PrincipalAllocationError::MalformedHostAccounts);
            };
            by_name.insert(name.to_owned(), uid);
        }
        Ok(Self { by_name })
    }

    /// The uid one host account owns.
    pub fn uid_of(&self, account: &str) -> Option<u32> {
        self.by_name.get(account).copied()
    }

    /// The host account that owns one uid, in name order.
    pub fn account_of(&self, uid: u32) -> Option<&str> {
        self.by_name
            .iter()
            .find(|(_, held)| **held == uid)
            .map(|(name, _)| name.as_str())
    }

    /// Whether the table names no accounts at all.
    pub fn is_empty(&self) -> bool {
        self.by_name.is_empty()
    }
}

/// How a committed principal overlaps a host account table.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HostOverlapKind {
    /// The host account table hands the committed id to another account.
    IdOwnedByOtherAccount,
    /// The host account table declares the principal's own name with another
    /// id.
    NameDeclaredWithOtherId,
}

/// One overlap between the committed allocation and a host account table.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HostAccountOverlap {
    /// The allocated principal.
    pub principal: String,
    /// The id the allocation pins for it.
    pub id: u32,
    /// The host account the overlap is with.
    pub host_account: String,
    /// The id the host account table hands that account.
    pub host_id: u32,
    /// Which overlap this is.
    pub kind: HostOverlapKind,
}

impl core::fmt::Display for HostAccountOverlap {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let text = match self.kind {
            HostOverlapKind::IdOwnedByOtherAccount => format!(
                "principal {} pins uid {} which host account {} already owns",
                self.principal, self.id, self.host_account
            ),
            HostOverlapKind::NameDeclaredWithOtherId => format!(
                "principal {} pins uid {} while the host account table declares it as {}",
                self.principal, self.id, self.host_id
            ),
        };
        formatter.write_str(&text)
    }
}

/// The outcome of one allocation check.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AllocationCheck {
    overlaps: Vec<HostAccountOverlap>,
}

impl AllocationCheck {
    /// Every overlap the check refused.
    pub fn overlaps(&self) -> &[HostAccountOverlap] {
        &self.overlaps
    }

    /// Whether the committed allocation is clear of the host account table.
    pub fn is_clear(&self) -> bool {
        self.overlaps.is_empty()
    }
}

/// Check the committed allocation against one host account table.
///
/// This is the reachable half of the allocator's host-uid refusal: the
/// generator refuses to hand a candidate id the host already owns, and this
/// check refuses a committed document that already carries one, against a
/// table the caller supplies.
pub fn check_committed_against(
    host: &HostAccounts,
) -> Result<AllocationCheck, PrincipalAllocationError> {
    let allocation = PrincipalAllocation::committed()?;
    Ok(AllocationCheck {
        overlaps: allocation.host_overlaps(host),
    })
}

/// One invalid allocation document or allocation request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PrincipalAllocationError {
    /// The document is not the committed allocation shape.
    Malformed,
    /// A principal name is empty, over bound, or not a bounded token.
    InvalidName,
    /// Two names claim the same uid.
    DuplicateId,
    /// The reserved range holds no free id.
    RangeExhausted,
    /// The host account table is not a `passwd`-format account table.
    MalformedHostAccounts,
}

impl core::fmt::Display for PrincipalAllocationError {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str(match self {
            Self::Malformed => "principal allocation document is malformed",
            Self::InvalidName => "principal name is not a bounded token",
            Self::DuplicateId => "principal allocation reuses one uid for two names",
            Self::RangeExhausted => "principal allocation range holds no free id",
            Self::MalformedHostAccounts => "host account table is malformed",
        })
    }
}

impl std::error::Error for PrincipalAllocationError {}

/// Whether one name is a well-formed principal name.
pub fn valid_principal_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= MAX_PRINCIPAL_NAME_BYTES
        && name.bytes().enumerate().all(|(index, byte)| {
            if index == 0 {
                byte.is_ascii_lowercase()
            } else {
                byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-'
            }
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_committed_document_loads_and_names_the_host_principals() {
        let allocation = PrincipalAllocation::committed().expect("committed allocation loads");
        assert_eq!(
            allocation.get("d2b-zonert"),
            Some(PrincipalId::new(2_373_244, 2_373_244))
        );
        assert_eq!(allocation.get("d2bd"), Some(PrincipalId::new(997, 997)));
    }

    #[test]
    fn allocation_is_reused_across_reloads() {
        let mut allocation = PrincipalAllocation::default();
        let taken = BTreeSet::new();
        let first = allocation
            .allocate_names(vec!["worker-alpha".to_owned()], &taken)
            .expect("allocates");
        assert_eq!(first[0].1.uid(), PRINCIPAL_RANGE_START);
        let persisted = allocation.to_json();
        let reloaded = PrincipalAllocation::from_json(persisted.as_bytes()).expect("reloads");
        assert_eq!(reloaded.get("worker-alpha"), Some(first[0].1));
        // A restarted generator allocates the next name without renumbering.
        let mut restarted = reloaded;
        let second = restarted
            .allocate_names(vec!["worker-beta".to_owned()], &taken)
            .expect("allocates");
        assert_eq!(second[0].1.uid(), PRINCIPAL_RANGE_START + 1);
        assert_eq!(restarted.get("worker-alpha"), Some(first[0].1));
    }

    #[test]
    fn host_uid_overlaps_and_range_exhaustion_are_refused() {
        let mut allocation = PrincipalAllocation::default();
        let taken = BTreeSet::from([PRINCIPAL_RANGE_START, PRINCIPAL_RANGE_START + 1]);
        let allocated = allocation
            .allocate_names(vec!["worker".to_owned()], &taken)
            .expect("allocates around taken ids");
        assert_eq!(allocated[0].1.uid(), PRINCIPAL_RANGE_START + 2);

        let mut exhausted = PrincipalAllocation::default();
        let taken = (PRINCIPAL_RANGE_START..=PRINCIPAL_RANGE_END).collect();
        assert_eq!(
            exhausted.allocate_names(vec!["worker".to_owned()], &taken),
            Err(PrincipalAllocationError::RangeExhausted)
        );
    }

    #[test]
    fn malformed_names_and_duplicate_ids_are_refused() {
        for name in ["", "Upper", "with space", "a".repeat(MAX_PRINCIPAL_NAME_BYTES + 1).as_str()]
        {
            let mut allocation = PrincipalAllocation::default();
            assert_eq!(
                allocation.allocate_names(vec![name.to_owned()], &BTreeSet::new()),
                Err(PrincipalAllocationError::InvalidName)
            );
        }
        let duplicate = r#"{"version":1,"principals":{"alpha":{"uid":900,"gid":900},"beta":{"uid":900,"gid":900}}}"#;
        assert_eq!(
            PrincipalAllocation::from_json(duplicate.as_bytes()),
            Err(PrincipalAllocationError::DuplicateId)
        );
    }

    #[test]
    fn a_host_account_table_that_owns_a_committed_id_is_refused() {
        // The committed document pins d2bd at 997; a host that hands 997 to
        // another account would run the principal as the wrong identity.
        let host = HostAccounts::parse_passwd("root:x:0:0::/root:/bin/sh\nnm-iodine:x:997:57::/var/empty:/\n")
            .expect("host table parses");
        let check = check_committed_against(&host).expect("the committed document loads");
        assert!(!check.is_clear());
        assert_eq!(
            check.overlaps()[0],
            HostAccountOverlap {
                principal: "d2bd".to_owned(),
                id: 997,
                host_account: "nm-iodine".to_owned(),
                host_id: 997,
                kind: HostOverlapKind::IdOwnedByOtherAccount,
            }
        );

        // A host that declares the principal's own name under another id is
        // the other half of the same refusal.
        let host = HostAccounts::parse_passwd("d2bd:x:978:978::/var/empty:/\n").expect("parses");
        let check = check_committed_against(&host).expect("the committed document loads");
        assert_eq!(
            check.overlaps(),
            [HostAccountOverlap {
                principal: "d2bd".to_owned(),
                id: 997,
                host_account: "d2bd".to_owned(),
                host_id: 978,
                kind: HostOverlapKind::NameDeclaredWithOtherId,
            }]
        );
        assert!(check.overlaps()[0].to_string().contains("978"));
    }

    #[test]
    fn a_host_account_table_that_owns_none_of_the_committed_ids_is_accepted() {
        let host = HostAccounts::parse_passwd(
            "# accounts the allocation does not name\nroot:x:0:0::/root:/bin/sh\nnixbld1:x:30001:30000::/var/empty:/\n",
        )
        .expect("host table parses");
        assert!(!host.is_empty());
        assert_eq!(host.uid_of("root"), Some(0));
        assert_eq!(host.account_of(30001), Some("nixbld1"));
        let check = check_committed_against(&host).expect("the committed document loads");
        assert!(check.is_clear(), "{:?}", check.overlaps());

        // The deployment's own table - one account per committed principal,
        // under the committed id - is clear as well.
        let host = HostAccounts::parse_passwd("d2bd:x:997:997::/var/empty:/\n")
            .expect("parses");
        let check = check_committed_against(&host).expect("the committed document loads");
        assert!(check.is_clear(), "{:?}", check.overlaps());
    }

    #[test]
    fn a_malformed_host_account_table_is_refused() {
        for table in ["d2bd:x:not-a-uid:997::/var/empty:/\n", "x:!:\n"] {
            assert_eq!(
                HostAccounts::parse_passwd(table),
                Err(PrincipalAllocationError::MalformedHostAccounts),
                "{table:?} must be refused"
            );
        }
    }
}
