module(
    name = "d2b",
    version = "3.0.0",
)

bazel_dep(name = "rules_rust", version = "0.67.0")
bazel_dep(name = "rules_go", version = "0.59.0")
bazel_dep(name = "gazelle", version = "0.47.0")
bazel_dep(name = "gazelle_rust", version = "0.1.0")
bazel_dep(name = "protobuf", version = "33.4")
bazel_dep(name = "rules_shell", version = "0.6.1")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    versions = ["1.97.0"],
)
use_repo(rust, "rust_toolchains")
register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//:Cargo.lock",
    manifests = ["//:Cargo.toml"],
)
use_repo(crate, "crates")

bazel_only_crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")
bazel_only_crate.from_cargo(
    name = "bazel_only_crates",
    cargo_lockfile = "//bazel/checks/rust:Cargo.lock",
    manifests = ["//bazel/checks/rust:Cargo.toml"],
)
use_repo(bazel_only_crate, "bazel_only_crates")
