//! Shared authority scaffolding: the provider-crate enumeration and the
//! per-crate declaration coverage gate every declaration authority reads
//! through, the recursive `.rs` collector, and the committed-artifact drift
//! check. One home instead of four byte-identical private copies.
//!
//! The coverage gate exists because an absent declaration file and a renamed
//! one look the same on disk. A loader that skips what it cannot find turns a
//! rename into a smaller registry: the generated type authority, the committed
//! Nix registry, and the new-graph projection all shrink together, and every
//! gate compares the generated bytes against the same shrunken input, so the
//! suite stays green over a silent loss. [`declaration_paths`] therefore
//! refuses a provider crate that carries no file for a declaration kind unless
//! [`DECLARATION_ABSENCES`] names it and states why it owns no such surface.

use std::{
    fs,
    path::{Path, PathBuf},
};

/// The directory the per-crate declarations live under.
const PACKAGES_DIR: &str = "packages";
/// The directory-name prefix that marks a package as a provider crate.
const PROVIDER_PREFIX: &str = "d2b-provider-";

/// One per-crate declaration file a provider crate may carry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) enum Declaration {
    /// The ResourceType and role vocabulary a crate registers.
    ResourceTypes,
    /// The broker operation rows a crate owns.
    Operations,
    /// The provider identity and effect-service ids a crate registers.
    Registrations,
    /// The Provider identities a crate owns, one slot per identity surface.
    ProviderIdentity,
    /// The service packages a crate publishes.
    ServiceCatalog,
}

impl Declaration {
    /// Every declaration kind, in the order the coverage gate reads them.
    ///
    /// Each authority names the one kind it loads by name, so the closed
    /// enumeration is read by the coverage-gate tests: they stage a crate
    /// that carries every kind and refuse it one kind at a time, which is
    /// what keeps a kind from escaping the gate by never being exercised.
    #[cfg(test)]
    pub(crate) const ALL: [Self; 5] = [
        Self::ResourceTypes,
        Self::Operations,
        Self::Registrations,
        Self::ProviderIdentity,
        Self::ServiceCatalog,
    ];

    /// The file name, exactly as it sits in the crate's own directory.
    pub(crate) const fn file_name(self) -> &'static str {
        match self {
            Self::ResourceTypes => "resource-types.json",
            Self::Operations => "operations.json",
            Self::Registrations => "registrations.json",
            Self::ProviderIdentity => "provider-identity.json",
            Self::ServiceCatalog => "service-catalog.json",
        }
    }
}

/// Whether one declared Provider identity is a name the contracts admit as
/// a resource name.
///
/// A declaration states the identity its own crate registers, and the
/// crate's directory name is not that identity: `d2b-provider-guest-qemu-media`
/// registers `runtime-qemu-media` and `d2b-provider-process-minijail`
/// registers `system-minijail`. A convention that read the identity back out
/// of the directory name therefore both published references the product
/// does not have and refused the ones it does, which made a crate's real
/// identity inexpressible. What a declaration owes is the grammar, not the
/// spelling of the directory beside it, so this is the whole of what both
/// declaration authorities gate: an identity the resource-name grammar
/// refuses could never be written as a `Provider/<name>` reference, so a
/// declaration naming one states a row no production surface could carry.
pub(crate) fn admits_provider_identity(identity: &str) -> bool {
    d2b_contracts_resource::v3::ResourceName::parse(identity).is_ok()
}

/// One provider crate that deliberately carries no file for `absent`, and
/// why.
///
/// A crate owns the plane-facing surfaces it declares and no others: the crate
/// that registers a ResourceType vocabulary declares it, the crate that owns an
/// operation declares its row, and the crate that publishes a service package
/// declares it in its catalog. A crate that owns no surface of a kind has no
/// file for it, and that has to be written down. The gate refuses a crate that
/// carries none without a row, so every deliberate absence is a reviewable
/// line here rather than a branch in a loader.
///
/// The rows are one per crate and the table only ever needs to grow when a new
/// provider crate appears; a crate that gains a declaration is read normally
/// and its row simply stops naming that kind.
struct DeclarationAbsence {
    /// The provider crate that owns no file for `absent`.
    crate_name: &'static str,
    /// The declaration kinds it declares nothing of.
    absent: &'static [Declaration],
    /// Why the crate owns no surface of those kinds.
    reason: &'static str,
}

/// A crate that implements other crates' surfaces and declares none itself.
const IMPLEMENTS_OTHER_CRATES_SURFACES: &str = "declares no ResourceType vocabulary, no Provider identity on any surface, no operation row, and no service package; every plane-facing surface this crate implements is declared by the crate that owns that surface";
/// A crate that declares its ResourceType vocabulary and its provider identity.
const DECLARES_VOCABULARY_AND_IDENTITY: &str = "declares the ResourceType vocabulary it registers and its provider identity; the operation rows it serves and the service package it publishes are declared by the crates that own them";
/// A crate that declares only its ResourceType vocabulary.
const DECLARES_VOCABULARY_ONLY: &str = "declares the ResourceType vocabulary it owns and nothing else; it owns no Provider identity on any surface, declares no operation row, and publishes no service package";
/// A crate that publishes a service package and owns no other surface.
const PUBLISHES_A_SERVICE_PACKAGE: &str = "publishes a service package through its session catalog; it owns no ResourceType vocabulary and declares no operation row";
/// A crate that declares its vocabulary, its identity, and its operation rows.
const DECLARES_VOCABULARY_IDENTITY_AND_ROWS: &str = "declares the ResourceType vocabulary it registers, its provider identity, and its operation rows; the service package it serves is declared by the crate that publishes it";
/// A crate that declares its identity and its operation rows only.
const DECLARES_IDENTITY_AND_ROWS: &str = "declares its provider identity and its operation rows; it owns no ResourceType vocabulary and publishes no service package";
/// A crate that declares its provider identity and owns no other surface.
const DECLARES_IDENTITY_ONLY: &str = "declares its provider identity and nothing else; it owns no ResourceType vocabulary, declares no operation row, and publishes no service package";
/// A crate that owns a ResourceType vocabulary and spells an effect service
/// the daemon's own composition hosts, where a registration row could carry
/// neither half without claiming a hosting the composition does not do.
const REGISTERS_NO_PLANE_FACING_SURFACE: &str = "declares the ResourceType vocabulary it registers; the effect service it spells is hosted by the daemon's own composition rather than through a registration row, so a `registrations.json` could carry neither half truthfully, and it owns no session identity, so it publishes no service package";
/// A crate whose session identity answers no closed service package.
const PUBLISHES_NO_SERVICE_PACKAGE: &str = "publishes no service package: the crate owns a session identity that answers no closed service package on the zone-plane session contract and states no fixed bootstrap resource UID, so a `service-catalog.json` would carry no routing fact at all";

/// Every declaration kind but the Provider identity one, in declaration
/// order: it is the one kind no row below is ever absent for, because every
/// provider crate carries it.
const ALL_BUT_PROVIDER_IDENTITY: &[Declaration] = &[
    Declaration::ResourceTypes,
    Declaration::Operations,
    Declaration::Registrations,
    Declaration::ServiceCatalog,
];

/// Every provider crate that owns no file for a declaration kind, in crate-name
/// order.
const DECLARATION_ABSENCES: &[DeclarationAbsence] = &[
    // Which identities a crate owns, and on which surface, is stated by that
    // crate's own `provider-identity.json` and by nothing else. A row here
    // says one thing only: the crate owns no file of a declaration kind. It
    // never restates which identities the crate carries, so no declaration
    // kind can be inferred from it and no row here is a second authority for
    // an identity.
    //
    // The rows that carry no `Declaration::Registrations` therefore state a
    // deliberate null for one reason: nothing outside the crate graph
    // registers that crate as a runtime Provider - no `ServiceDecl` its own
    // sources spell, no descriptor that registers one, no composed factory
    // that hosts one. A crate in that position has no runtime identity to
    // register, so a `registrations.json` would carry a services list with no
    // family to register them for. The committed Provider matrix is not such
    // a source: it is the packaging inventory the per-crate identity
    // declarations replace, so restating it here would make the matrix and
    // this table two authorities for one fact.
    DeclarationAbsence { crate_name: "d2b-provider-activation-nixos", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    DeclarationAbsence { crate_name: "d2b-provider-audio-binding", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    DeclarationAbsence { crate_name: "d2b-provider-audio-pipewire", absent: ALL_BUT_PROVIDER_IDENTITY, reason: IMPLEMENTS_OTHER_CRATES_SURFACES },
    DeclarationAbsence { crate_name: "d2b-provider-audio-service", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    DeclarationAbsence { crate_name: "d2b-provider-clipboard-wayland", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::Registrations], reason: PUBLISHES_A_SERVICE_PACKAGE },
    DeclarationAbsence { crate_name: "d2b-provider-config-nixos", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::Registrations], reason: PUBLISHES_A_SERVICE_PACKAGE },
    DeclarationAbsence { crate_name: "d2b-provider-credential", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    // The three Credential sub-families register an identity the
    // configuration layer names outside the crate graph: the
    // `credential-entra` Zone assertions in
    // `nixos-modules/options-zones-resources.nix`, the secret-service and
    // managed-identity domain-placement refusals in
    // `nixos-modules/options-resources.nix`, the relay `allowedProviders`
    // sets in `nixos-modules/provider-runtime-contracts.nix`, and
    // `CredentialProviderKind::as_str`'s closed match in
    // `d2b-contracts-provider`.
    DeclarationAbsence { crate_name: "d2b-provider-credential-entra", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-credential-managed-identity", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-credential-secret-service", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-device", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    // `device-gpu` is named by the physical-DRM, x86_64-only, video-mode and
    // shared-arbitration assertions in `nixos-modules/assertions.nix` and
    // `nixos-modules/resources-device.nix`, and by
    // `d2b-core`'s `DEVICE_GPU_PROVIDER_REF` dispatch constant.
    DeclarationAbsence { crate_name: "d2b-provider-device-gpu", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-device-security-key", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    // `device-tpm` stays null: the identity is named by production sources
    // (`nixos-modules/assertions.nix`'s emulated-shape and startup-clear
    // refusals, `nixos-modules/lib.nix`'s host account rows, and
    // `d2b-core`'s `DEVICE_TPM_PROVIDER_REF` dispatch constant), but this
    // crate spells a `ServiceDecl` (`tpm.d2bus.org/effects`) that no
    // `registrations.json` can carry without also making the daemon host it:
    // the crate has no `DriverDescriptor`, so declaring the service would
    // fail the declaration-to-source parity gate, and declaring no service
    // would leave a published service out of the registration table. Until
    // the production composition carries a TPM effects factory the two
    // forms are both false, and a documented null is the honest row.
    DeclarationAbsence { crate_name: "d2b-provider-device-tpm", absent: ALL_BUT_PROVIDER_IDENTITY, reason: REGISTERS_NO_PLANE_FACING_SURFACE },
    DeclarationAbsence { crate_name: "d2b-provider-device-usbip", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    DeclarationAbsence { crate_name: "d2b-provider-display-wayland", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::Registrations], reason: PUBLISHES_A_SERVICE_PACKAGE },
    // The vocabulary-owning rows that state no `Declaration::Registrations`
    // are the second group held at null by the rule above: each of these
    // crates owns a ResourceType vocabulary and no identity any production
    // source outside the crate graph names - `d2b-provider-emergency-policy`,
    // `d2b-provider-execution-policy`, `d2b-provider-operation`,
    // `d2b-provider-provider`, `d2b-provider-quota`,
    // `d2b-provider-resource-export`, `d2b-provider-resource-import`,
    // `d2b-provider-role`, `d2b-provider-role-binding`,
    // `d2b-provider-seccomp-profile`, `d2b-provider-telemetry-binding`,
    // `d2b-provider-telemetry-service`, `d2b-provider-zone`, and
    // `d2b-provider-zone-link`.
    //
    // `d2b-provider-execution-policy` is the one that read closest to a
    // counterexample, which is why it is recorded here rather than left
    // implicit: the contract used to publish
    // `EXECUTION_POLICY_PROVIDER_REF = "Provider/execution-policy"`, but
    // nothing read it - no admission compared a row's `providerRef` against
    // it - so it named an identity with no enforcement behind it and no
    // crate owning it. That constant is gone, and every `Provider/<name>`
    // reference a declaration emits is now resolved against the identity
    // authority, so a reference to an identity no crate declares is a refusal
    // rather than a dangling name.
    DeclarationAbsence { crate_name: "d2b-provider-emergency-policy", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-endpoint", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    DeclarationAbsence { crate_name: "d2b-provider-execution-policy", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-guest", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    // The four runtime families register identities the configuration layer
    // names outside the crate graph: the `runtimeProviderRefs` list and its
    // per-provider assertion branches in
    // `nixos-modules/provider-runtime-contracts.nix`, the qemu-media
    // assertion block in `nixos-modules/assertions.nix`, and the
    // `runtime-cloud-hypervisor` closure gate in
    // `nixos-modules/guest-closures.nix`.
    DeclarationAbsence { crate_name: "d2b-provider-guest-azure-container-apps", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-guest-azure-virtual-machine", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-guest-cloud-hypervisor", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-guest-qemu-media", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-host", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    DeclarationAbsence { crate_name: "d2b-provider-network-local", absent: &[Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_IDENTITY_AND_ROWS },
    DeclarationAbsence { crate_name: "d2b-provider-notification-desktop", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::Registrations], reason: PUBLISHES_A_SERVICE_PACKAGE },
    DeclarationAbsence { crate_name: "d2b-provider-observability-otel", absent: ALL_BUT_PROVIDER_IDENTITY, reason: IMPLEMENTS_OTHER_CRATES_SURFACES },
    DeclarationAbsence { crate_name: "d2b-provider-operation", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-process", absent: &[Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_IDENTITY_AND_ROWS },
    DeclarationAbsence { crate_name: "d2b-provider-process-minijail", absent: ALL_BUT_PROVIDER_IDENTITY, reason: IMPLEMENTS_OTHER_CRATES_SURFACES },
    DeclarationAbsence { crate_name: "d2b-provider-process-systemd", absent: &[Declaration::ResourceTypes, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_AND_ROWS },
    DeclarationAbsence { crate_name: "d2b-provider-provider", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-quota", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-resource-export", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-resource-import", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-role", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-role-binding", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-seccomp-profile", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-shell-pool", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    DeclarationAbsence { crate_name: "d2b-provider-shell-session", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    // `shell-terminal` owns a session identity, but nothing routes to it
    // yet: no closed service package on the zone-plane session contract is
    // answered by this crate, and it states no fixed bootstrap resource UID.
    // A `service-catalog.json` holding only the identity it used to restate
    // would carry no routing fact at all, so the file is absent and the
    // identity stays where it belongs - in the identity authority.
    DeclarationAbsence { crate_name: "d2b-provider-shell-terminal", absent: ALL_BUT_PROVIDER_IDENTITY, reason: PUBLISHES_NO_SERVICE_PACKAGE },
    DeclarationAbsence { crate_name: "d2b-provider-supervisor", absent: ALL_BUT_PROVIDER_IDENTITY, reason: IMPLEMENTS_OTHER_CRATES_SURFACES },
    DeclarationAbsence { crate_name: "d2b-provider-system-core", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::Registrations], reason: PUBLISHES_A_SERVICE_PACKAGE },
    DeclarationAbsence { crate_name: "d2b-provider-telemetry-binding", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-telemetry-service", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-test-controller", absent: ALL_BUT_PROVIDER_IDENTITY, reason: IMPLEMENTS_OTHER_CRATES_SURFACES },
    DeclarationAbsence { crate_name: "d2b-provider-toolkit", absent: ALL_BUT_PROVIDER_IDENTITY, reason: IMPLEMENTS_OTHER_CRATES_SURFACES },
    // `transport-azure-relay` is named by the `runtimeProviderRefs` list and
    // its credential-boundary assertion branch in
    // `nixos-modules/provider-runtime-contracts.nix`, and by the gateway
    // composition's refusal to take a Zone with no relay Provider.
    DeclarationAbsence { crate_name: "d2b-provider-transport-azure-relay", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_ONLY },
    // The identity this crate registers is named by four independent
    // production sources - the `runtimeProviderRefs` assertions in
    // `nixos-modules/provider-runtime-contracts.nix`, the committed Provider
    // matrix row, `ZoneLinkSpec::transport_provider_ref`, and the gateway
    // composition's refusal to take a non-relay transport - so the crate
    // declares it rather than leaving the configuration layer to assert an
    // identity nothing states.
    DeclarationAbsence { crate_name: "d2b-provider-transport-vsock", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-user", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    DeclarationAbsence { crate_name: "d2b-provider-volume", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    DeclarationAbsence { crate_name: "d2b-provider-volume-binding", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    // `volume-local` is named by the network-config Volume admission fence
    // in `packages/d2bd/src/shared_provider_effects.rs`, which refuses any
    // config Volume whose `providerRef` is not this family.
    DeclarationAbsence { crate_name: "d2b-provider-volume-local", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_ONLY },
    // `volume-virtiofs` is named by `d2b-core`'s
    // `SERVING_WORKER_PROVIDER_REF`, by the broker's serving-worker
    // predicate, by the daemon's provider-ticket lookup, by the resource
    // compiler's worker projection, and by the Zone template account in
    // `nixos-modules/lib.nix`.
    DeclarationAbsence { crate_name: "d2b-provider-volume-virtiofs", absent: &[Declaration::ResourceTypes, Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_IDENTITY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-wayland-policy", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    DeclarationAbsence { crate_name: "d2b-provider-wayland-session", absent: &[Declaration::Operations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_AND_IDENTITY },
    DeclarationAbsence { crate_name: "d2b-provider-zone", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
    DeclarationAbsence { crate_name: "d2b-provider-zone-link", absent: &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog], reason: DECLARES_VOCABULARY_ONLY },
];

/// The provider crates in the tree, each paired with its own directory, in
/// crate-name order.
///
/// This is the one enumeration every declaration authority reads through, so
/// the set of crates the loaders consider is stated once rather than
/// re-derived - and restated - by each of them.
#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
pub(crate) fn provider_crates(repo_root: &Path) -> Result<Vec<(String, PathBuf)>, String> {
    let packages_dir = repo_root.join(PACKAGES_DIR);
    let entries = fs::read_dir(&packages_dir)
        .map_err(|error| format!("cannot read {}: {error}", packages_dir.display()))?;
    let mut crates = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|error| format!("cannot read a packages entry: {error}"))?;
        let crate_name = entry.file_name().to_string_lossy().into_owned();
        if crate_name.starts_with(PROVIDER_PREFIX) {
            crates.push((crate_name, entry.path()));
        }
    }
    crates.sort();
    Ok(crates)
}

/// The provider crates that carry `declaration`, each paired with its path, in
/// crate-name order.
///
/// Every provider crate the enumeration reaches either appears in this list or
/// has a [`DECLARATION_ABSENCES`] row naming the kinds it owns no file for. A
/// crate that carries none without such a row is refused by name, and the
/// refusal lists every such crate at once, so a renamed declaration file fails
/// the render instead of quietly removing its family from it.
///
/// The rows are not themselves checked against the tree here: the same
/// enumeration runs over partial trees - a test fixture, or the sandbox a
/// generator's drift target stages - where a listed crate may legitimately
/// carry a file its row does not name. The tree-level truth of the table is
/// asserted over the repository instead.
#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
pub(crate) fn declaration_paths(
    repo_root: &Path,
    declaration: Declaration,
) -> Result<Vec<(String, PathBuf)>, String> {
    let mut carried = Vec::new();
    let mut missing = Vec::new();
    for (crate_name, crate_dir) in provider_crates(repo_root)? {
        let path = crate_dir.join(declaration.file_name());
        let recorded = DECLARATION_ABSENCES.iter().find(|row| row.crate_name == crate_name);
        if path.is_file() {
            carried.push((crate_name, path));
        } else if !recorded.is_some_and(|row| row.absent.contains(&declaration)) {
            // A row naming this kind as one the crate owns none of is the
            // only absence the table may state; anything else is a lost file.
            missing.push(missing_declaration(&crate_name, declaration, recorded));
        }
    }
    if !missing.is_empty() {
        return Err(missing.join("\n"));
    }
    Ok(carried)
}

/// The refusal for one crate whose declaration file is missing, carrying the
/// row that already exists for it when it has one: whoever hits this is
/// repairing a declaration that used to be there, and the recorded reason is
/// what tells them which side of the line the crate is on.
fn missing_declaration(
    crate_name: &str,
    declaration: Declaration,
    recorded: Option<&DeclarationAbsence>,
) -> String {
    let mut message = format!(
        "missing-declaration: crate {crate_name} has no {PACKAGES_DIR}/{crate_name}/{}; a provider crate carries every declaration file, or has a row in authority_common::DECLARATION_ABSENCES naming why it owns none",
        declaration.file_name()
    );
    if let Some(row) = recorded {
        message.push_str(&format!(
            " ({} is recorded as owning none of {} because: {})",
            crate_name,
            row.absent
                .iter()
                .map(|kind| kind.file_name())
                .collect::<Vec<_>>()
                .join(", "),
            row.reason
        ));
    }
    message
}

/// Recursively collect every `.rs` file under one source tree.
#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
pub(crate) fn collect_rs_files(dir: &Path) -> Result<Vec<PathBuf>, String> {
    let mut out = Vec::new();
    if !dir.is_dir() {
        return Err(format!(
            "missing-src: the declaring crate has no src tree at {}",
            dir.display()
        ));
    }
    let entries = fs::read_dir(dir)
        .map_err(|error| format!("cannot read {}: {error}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|error| format!("cannot read a source entry: {error}"))?;
        let path = entry.path();
        if path.is_dir() {
            out.extend(collect_rs_files(&path)?);
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            out.push(path);
        }
    }
    Ok(out)
}

/// Fail when the committed copy of one generated artifact differs from the
/// declarations' render. `authority` names the owning authority and is the
/// only per-caller difference between the former private copies.
#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
pub(crate) fn verify_committed(
    repo_root: &Path,
    relative: &str,
    rendered: &str,
    authority: &str,
) -> Result<(), String> {
    let artifact_path = repo_root.join(relative);
    let on_disk = fs::read_to_string(&artifact_path).map_err(|_| {
        format!(
            "{authority} artifact is missing at {}; run `cargo xtask check-provider-crate-layout --fix`",
            artifact_path.display()
        )
    })?;
    if on_disk != rendered {
        return Err(format!(
            "{authority} drift: the committed generated artifact {} differs from the declarations' output; a hand edit or a stale generation must be repaired by `cargo xtask check-provider-crate-layout --fix`",
            artifact_path.display()
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;


    /// A throwaway tree holding one provider crate, used to plant the
    /// negative cases the coverage gate has to catch.
    struct Fixture {
        root: PathBuf,
    }

    impl Fixture {
        #[allow(clippy::disallowed_methods, reason = "cfg(test) helper")]
        fn new(name: &str) -> Self {
            let nonce = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .expect("clock")
                .as_nanos();
            let root = std::env::temp_dir().join(format!(
                "d2b-declaration-coverage-{name}-{}-{nonce}",
                std::process::id()
            ));
            fs::create_dir_all(&root).expect("create the fixture root");
            Self { root }
        }

        #[allow(clippy::disallowed_methods, reason = "cfg(test) helper")]
        fn crate_dir(&self, crate_name: &str) -> PathBuf {
            self.root.join(PACKAGES_DIR).join(crate_name)
        }

        /// A provider crate carrying exactly the named declarations, and no
        /// source tree: this gate reads declarations, not code.
        #[allow(clippy::disallowed_methods, reason = "cfg(test) helper")]
        fn write_crate(&self, crate_name: &str, declarations: &[Declaration]) {
            for declaration in declarations {
                let path = self.crate_dir(crate_name).join(declaration.file_name());
                fs::create_dir_all(path.parent().expect("parent")).expect("mkdir");
                fs::write(path, "{}\n").expect("write");
            }
        }
    }

    impl Drop for Fixture {
        #[allow(clippy::disallowed_methods, reason = "cfg(test) helper")]
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.root);
        }
    }

    /// The defect this gate exists for: a provider crate whose declaration
    /// file is absent is refused by name rather than dropped from the render,
    /// so renaming the file cannot shrink the registry with the suite green.
    #[test]
    fn a_provider_crate_missing_a_declaration_is_refused_by_name() {
        let fixture = Fixture::new("missing");
        fixture.write_crate("d2b-provider-complete", &Declaration::ALL);
        fixture.write_crate(
            "d2b-provider-renamed",
            &[Declaration::Operations, Declaration::Registrations, Declaration::ServiceCatalog],
        );
        let error = declaration_paths(&fixture.root, Declaration::ResourceTypes)
            .expect_err("a crate with no resource-types.json is refused");
        assert_eq!(
            error,
            "missing-declaration: crate d2b-provider-renamed has no packages/d2b-provider-renamed/resource-types.json; a provider crate carries every declaration file, or has a row in authority_common::DECLARATION_ABSENCES naming why it owns none",
            "the refusal names the crate and the declaration it lost"
        );
    }

    /// Every kind is gated, not just the resource-type vocabulary: a crate that
    /// loses its operation rows is refused the same way.
    #[test]
    fn every_declaration_kind_is_gated() {
        for declaration in Declaration::ALL {
            let fixture = Fixture::new(declaration.file_name());
            fixture.write_crate(
                "d2b-provider-complete",
                &Declaration::ALL
                    .into_iter()
                    .filter(|kind| kind != &declaration)
                    .collect::<Vec<_>>(),
            );
            let error = declaration_paths(&fixture.root, declaration)
                .expect_err("a crate with no declaration file is refused");
            assert!(
                error.contains("d2b-provider-complete") && error.contains(declaration.file_name()),
                "the refusal names the crate and the declaration it lost: {error}"
            );
        }
    }

    /// A complete tree passes for every kind, which is what the four
    /// authorities read over the repository.
    #[test]
    fn a_tree_whose_crates_all_carry_the_declaration_passes() {
        let fixture = Fixture::new("complete");
        fixture.write_crate("d2b-provider-complete", &Declaration::ALL);
        for declaration in Declaration::ALL {
            let carried = declaration_paths(&fixture.root, declaration).expect("the tree passes");
            assert_eq!(
                carried
                    .iter()
                    .map(|(crate_name, _)| crate_name.as_str())
                    .collect::<Vec<_>>(),
                vec!["d2b-provider-complete"],
                "{} names every crate that carries it",
                declaration.file_name()
            );
        }
    }

    /// The repository's own tree: every provider crate carries every
    /// declaration kind or has a row saying why it owns none. This is the
    /// positive statement the whole table rests on, and it is what makes a
    /// deliberate absence reviewable rather than a branch in a loader.
    #[test]
    fn every_provider_crate_carries_each_declaration_or_names_its_absence() {
        let repo_root = crate::repo_root().expect("the aggregate passes D2B_REPO_ROOT");
        for declaration in Declaration::ALL {
            declaration_paths(repo_root, declaration).unwrap_or_else(|error| {
                panic!("every provider crate carries {declaration:?} or names its absence: {error}")
            });
        }
    }

    /// The table names each crate once: two rows for one crate are a split
    /// allowance a reviewer cannot read as one statement about one crate.
    #[test]
    fn the_absence_table_names_each_provider_crate_once() {
        let mut seen = BTreeSet::new();
        for row in DECLARATION_ABSENCES {
            assert!(
                seen.insert(row.crate_name),
                "{} is named by more than one absence row",
                row.crate_name
            );
            assert!(!row.absent.is_empty(), "{} names no kind at all", row.crate_name);
            assert!(!row.reason.is_empty(), "{} states no reason", row.crate_name);
        }
    }

    /// The ratchet on the table itself: a row claims a crate carries no file
    /// for a kind, so the repository has to agree. A crate that gains a
    /// declaration drops the kind from its row here.
    #[test]
    fn every_absence_the_table_names_is_really_absent() {
        let repo_root = crate::repo_root().expect("the aggregate passes D2B_REPO_ROOT");
        let crates = provider_crates(repo_root).expect("the provider crates enumerate");
        let present: BTreeSet<&str> = crates.iter().map(|(name, _)| name.as_str()).collect();
        for row in DECLARATION_ABSENCES {
            assert!(
                present.contains(row.crate_name),
                "{} is absent from the tree; delete its absence row",
                row.crate_name
            );
            let (_, crate_dir) = crates
                .iter()
                .find(|(name, _)| name == row.crate_name)
                .expect("the row's crate is in the tree");
            for declaration in row.absent {
                assert!(
                    !crate_dir.join(declaration.file_name()).is_file(),
                    "{} now carries {}; drop it from the crate's absence row",
                    row.crate_name,
                    declaration.file_name()
                );
            }
        }
    }
}
