//! The broker operation catalog generator.
//!
//! `gen-broker-operations` reads the committed operation rows in
//! `docs/reference/policy/broker-operations.json` and writes every derived
//! view of them:
//!
//! - `packages/d2b-contracts-broker/src/generated/broker_operation_profiles.rs`
//!   - the closed Host and Guest profile catalogs.
//! - `packages/d2b-contracts/src/generated/w3_broker_operations.rs` - the
//!   `W3BrokerOperation` inventory.
//! - `packages/d2b-core/src/generated/broker_operation_authz.rs` - the
//!   private broker authorization rows.
//! - `packages/d2b-broker/src/generated/broker_operation_catalog.rs` - the
//!   canonical row table the broker envelope resolves and the completeness
//!   gates compare every view against.
//! - `docs/reference/broker-operation-triage.md` - the human triage view.
//!
//! The committed rows are the single source of truth. Nothing here restates
//! a facet, so a row cannot move without moving every view, which is what
//! makes the drift gate meaningful.

use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
};

use serde::{Deserialize, Serialize};

/// The committed operation rows.
const POLICY_PATH: &str = "docs/reference/policy/broker-operations.json";
/// The generated profile catalog view.
const PROFILES_OUT: &str = "packages/d2b-contracts-broker/src/generated/broker_operation_profiles.rs";
/// The generated `W3BrokerOperation` inventory view.
const W3_OUT: &str = "packages/d2b-contracts/src/generated/w3_broker_operations.rs";
/// The generated private broker authorization row view.
const AUTHZ_OUT: &str = "packages/d2b-core/src/generated/broker_operation_authz.rs";
/// The generated canonical row table.
const CATALOG_OUT: &str = "packages/d2b-broker/src/generated/broker_operation_catalog.rs";
/// The generated triage view.
const TRIAGE_OUT: &str = "docs/reference/broker-operation-triage.md";

const HEADER: &str = "@generated by `cargo run -p xtask -- gen-broker-operations`.\n// Do not hand-edit: `//packages/xtask:gen_broker_operations_drift`\n// regenerates this file and compares it byte-for-byte.";

/// One committed broker operation row.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Row {
    operation: String,
    #[serde(default)]
    wire_variant: Option<String>,
    owner: String,
    #[serde(default)]
    family: Option<String>,
    #[serde(default)]
    declaring_provider: Option<String>,
    /// The declaring service the operation resolves to, when the row is
    /// family-owned (U7/KD6). The service id is the session-layer address
    /// the declaring provider publishes in its service declaration, and the
    /// method names the declared method that serves this row.
    #[serde(default)]
    service: Option<String>,
    #[serde(default)]
    method: Option<String>,
    /// Why a row no family owns is not provider-owned.
    ///
    /// A row the broker or a transport concern owns records what owns it and
    /// why, so a non-provider row's triage is a committed fact rather than an
    /// omission; a family-owned row carries its declaring provider instead.
    #[serde(default)]
    justification: Option<String>,
    profiles: Vec<String>,
    w3: bool,
    capabilities: bool,
    disposition: String,
    disposition_target: String,
    authz: Authz,
    audit: Audit,
    payload: Payload,
    #[serde(default)]
    fds: Fds,
    #[serde(default)]
    state_cell: StateCell,
    #[serde(default)]
    deadline: Deadline,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Authz {
    subject: String,
    scope: String,
    allowed_groups: Vec<String>,
    destructive: bool,
    secret_access: String,
    broker_required: String,
    audit_mode: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Audit {
    #[serde(default)]
    fields: Vec<String>,
    required: bool,
    mode: String,
    /// The payload fields the row's audit join is derived from.
    #[serde(default)]
    join: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Payload {
    provenance: String,
    #[serde(default)]
    schema: Option<serde_json::Value>,
}

/// The fd-carrying facet of one committed operation row..
///
/// A row with no carriage declares `maxFds: 0` and no `fdKind`,which
/// admits only the empty leg;a row that declares carriage names the ceiling
/// and the single kernel kind every attached descriptor must present.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Fds {
    #[serde(default)]
    max_fds: u32,
    #[serde(default)]
    fd_kind: Option<String>,
}

/// The state-cell facet of one committed operation row (U3/KTD3).
///
/// A row with no declared cell leaves both fields absent; a row that names a
/// cell declares the broker-owned state its operation lives on and the
/// cell's durability (one-time records persist under the state root and
/// refuse re-consume across restarts; ephemeral cells reset in-process).
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct StateCell {
    #[serde(default)]
    cell: Option<String>,
    #[serde(default)]
    durability: Option<String>,
}

/// The deadline-tier facet of one committed operation row (U4/KTD4).
///
/// A row that declares no tier sits on the standard tier, and every row
/// name outside the closed set fails generation instead of widening what a
/// row may mean.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Deadline {
    #[serde(default)]
    tier: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Catalog {
    version: u32,
    rows: Vec<Row>,
}

/// The row owners the three-way triage admits.
const OWNERS: [&str; 3] = ["family", "broker-generic", "transport-excluded"];
/// The profiles a row may admit.
const PROFILES: [&str; 2] = ["host", "guest"];
/// The payload provenances a row may declare.
const PAYLOAD_PROVENANCE: [&str; 2] = ["wire", "request"];
/// The deadline tiers a row may declare; a row that declares none sits on
/// the standard tier.
const DEADLINE_TIERS: [&str; 2] = ["standard", "extended"];

/// The method-name spelling every operation-serving method carries: a
/// lower-kebab token. A method outside the grammar cannot be addressed by
/// the session layer, so generation fails instead of admitting an
/// unreachable method.
fn valid_method_name(method: &str) -> bool {
    let mut bytes = method.bytes();
    matches!(bytes.next(), Some(first) if first.is_ascii_lowercase())
        && bytes.all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
}

/// The service-id spelling every declaring service id carries: a dotted
/// lowercase identifier, so a service the session layer addresses is
/// addressable as committed. A service id outside the grammar fails
/// generation.
fn valid_service_id(service: &str) -> bool {
    fn segment(segment: &str) -> bool {
        !segment.is_empty()
            && segment
                .bytes()
                .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
    }
    service.split('.').all(segment)
}

fn render_error(message: impl Into<String>) -> Box<dyn std::error::Error> {
    message.into().into()
}

#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
fn parse(repo_root: &Path) -> Result<Catalog, Box<dyn std::error::Error>> {
    let text = fs::read_to_string(repo_root.join(POLICY_PATH))
        .map_err(|error| render_error(format!("read {POLICY_PATH}: {error}")))?;
    parse_text(&text)
}

/// The closed-set validation over one committed catalog document, split out
/// of [`parse`] so the tests can drive it over mutated documents without a
/// repository root.
fn parse_text(text: &str) -> Result<Catalog, Box<dyn std::error::Error>> {
    let catalog: Catalog = serde_json::from_str(text)
        .map_err(|error| render_error(format!("parse {POLICY_PATH}: {error}")))?;
    if catalog.version != 1 {
        return Err(render_error(format!(
            "{POLICY_PATH}: unsupported catalog version {}",
            catalog.version
        )));
    }
    if catalog.rows.is_empty() {
        return Err(render_error(format!("{POLICY_PATH}: no committed rows")));
    }
    let mut operations = BTreeSet::new();
    let mut wire_variants = BTreeSet::new();
    // The toolkit envelope resolves operation names case-insensitively
    // (provider-side ResourceRef names are lowercase-only while committed
    // row names are PascalCase), so two committed rows differing only in
    // case would silently alias; reject them alongside exact duplicates.
    let mut casefolded_operations = BTreeSet::new();
    // One row per declared service method: two rows resolving to the same
    // service+method could not be told apart by the declaring driver.
    let mut service_methods = BTreeSet::new();
    for row in &catalog.rows {
        if !operations.insert(row.operation.as_str()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: duplicate operation {}",
                row.operation
            )));
        }
        if !casefolded_operations.insert(row.operation.to_ascii_lowercase()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: operation {} collides case-insensitively with a committed row",
                row.operation
            )));
        }
        if let Some(variant) = row.wire_variant.as_deref() {
            if !wire_variants.insert(variant) {
                return Err(render_error(format!(
                    "{POLICY_PATH}: duplicate wire variant {variant}"
                )));
            }
            if variant != row.operation {
                return Err(render_error(format!(
                    "{POLICY_PATH}: {} names wire variant {variant}",
                    row.operation
                )));
            }
        }
        if !OWNERS.contains(&row.owner.as_str()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} has unknown owner {}",
                row.operation, row.owner
            )));
        }
        if row.owner == "family" && row.family.is_none() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} is family-owned without a family",
                row.operation
            )));
        }
        if row.owner != "family" && (row.family.is_some() || row.declaring_provider.is_some()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} is not family-owned but names a family",
                row.operation
            )));
        }
        // A family-owned row resolves to a declared service method (KD6): it
        // names the service and the method that serves it, both spelled so
        // the session layer can address them. A row without the resolution
        // cannot be dispatched to a declaring driver, and a non-family row
        // naming one would invent a service surface no row owns.
        if row.service.is_some() != row.method.is_some() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} declares a partial service resolution (service and method must travel together)",
                row.operation
            )));
        }
        if row.owner == "family" && row.service.is_none() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} is family-owned without a resolvable service+method",
                row.operation
            )));
        }
        if row.owner != "family" && row.service.is_some() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} is not family-owned but names a service+method",
                row.operation
            )));
        }
        if let Some(service) = row.service.as_deref() {
            let method = row.method.as_deref().expect("validated pairing above");
            if !valid_service_id(service) {
                return Err(render_error(format!(
                    "{POLICY_PATH}: {} names an invalid service id {service:?}",
                    row.operation
                )));
            }
            if !valid_method_name(method) {
                return Err(render_error(format!(
                    "{POLICY_PATH}: {} names an invalid method {method:?}",
                    row.operation
                )));
            }
            if !service_methods.insert((service, method)) {
                return Err(render_error(format!(
                    "{POLICY_PATH}: rows resolve to duplicate service+method {service}/{method}",
                    service = service,
                    method = method
                )));
            }
        }
        if row.owner != "family" && row.justification.is_none() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} is not family-owned without a recorded justification",
                row.operation
            )));
        }
        if row.owner == "family" && row.justification.is_some() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} is family-owned but records a justification",
                row.operation
            )));
        }
        if row
            .justification
            .as_deref()
            .is_some_and(|value| value.trim().is_empty())
        {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} records an empty justification",
                row.operation
            )));
        }
        for profile in &row.profiles {
            if !PROFILES.contains(&profile.as_str()) {
                return Err(render_error(format!(
                    "{POLICY_PATH}: {} has unknown profile {profile}",
                    row.operation
                )));
            }
        }
        if !row.profiles.contains(&"host".to_owned()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} admits no profile",
                row.operation
            )));
        }
        if row.authz.allowed_groups.is_empty() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} admits no allowed group",
                row.operation
            )));
        }
        if !PAYLOAD_PROVENANCE.contains(&row.payload.provenance.as_str()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} has unknown payload provenance {}",
                row.operation, row.payload.provenance
            )));
        }
        if row.payload.provenance == "wire" && row.payload.schema.is_some() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} inherits the wire payload but declares a schema",
                row.operation
            )));
        }
        if row.payload.provenance == "request" && row.payload.schema.is_none() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} admits a request payload without a schema",
                row.operation
            )));
        }
        if let Some(field) = undeclared_join_field(row) {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} joins on a payload field it does not require: {field}",
                row.operation
            )));
        }
        if row.state_cell.cell.as_deref().is_some() != row.state_cell.durability.is_some() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} declares a partial state cell (cell and durability must travel together)",
                row.operation
            )));
        }
        if let Some(cell) = row.state_cell.cell.as_deref() {
            if cell.is_empty()
                || cell
                    .chars()
                    .any(|character| !character.is_ascii_alphanumeric() && character != '-')
            {
                return Err(render_error(format!(
                    "{POLICY_PATH}: {} names an invalid state cell {cell:?}",
                    row.operation
                )));
            }
            match row.state_cell.durability.as_deref() {
                Some("one-time") | Some("ephemeral") => {}
                Some(other) => {
                    return Err(render_error(format!(
                        "{POLICY_PATH}: {} declares unknown state cell durability {other:?}",
                        row.operation
                    )));
                }
                None => unreachable!("validated pairing above"),
            }
        }
        if let Some(tier) = row.deadline.tier.as_deref()
            && !DEADLINE_TIERS.contains(&tier)
        {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} declares unknown deadline tier {tier:?}",
                row.operation
            )));
        }
        if !["deny-only", "errors", "yes"].contains(&row.audit.mode.as_str()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} declares audit mode {}",
                row.operation, row.audit.mode
            )));
        }
        if row.disposition == "promoted-live" && !row.audit.required {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} is live but its audit is not required",
                row.operation
            )));
        }
        if row.disposition == "stubbed-unimplemented" && stub_target_variant(row).is_none() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} is a reserved stub whose disposition target is outside the closed set: {}",
                row.operation, row.disposition_target
            )));
        }
        if row.disposition_target.is_empty() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} names no disposition target",
                row.operation
            )));
        }
    }
    Ok(catalog)
}

#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
fn write(
    repo_root: &Path,
    relative: &str,
    contents: String,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let path = repo_root.join(relative);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| render_error(format!("create {}: {error}", parent.display())))?;
    }
    fs::write(&path, contents)
        .map_err(|error| render_error(format!("write {relative}: {error}")))?;
    Ok(path)
}

fn string_list(items: impl IntoIterator<Item = String>, indent: &str) -> String {
    items
        .into_iter()
        .map(|item| format!("{indent}\"{item}\",\n"))
        .collect()
}

/// The generated `StubTarget` variant a reserved stub's committed disposition
/// target maps to.
///
/// A still-stubbed operation's refusal carries this marker on the wire and in
/// its audit record, so it is a closed set: a reserved row whose disposition
/// target is not one of these spellings fails generation instead of widening
/// what a refusal may say.
fn stub_target_variant(row: &Row) -> Option<&'static str> {
    if row.disposition != "stubbed-unimplemented" {
        return None;
    }
    const TARGETS: [(&str, &str); 3] = [
        ("future work", "FutureWork"),
        ("reserved", "Reserved"),
        ("bootstrap-only", "BootstrapOnly"),
    ];
    TARGETS
        .iter()
        .find(|(target, _)| *target == row.disposition_target)
        .map(|(_, variant)| *variant)
}

/// The first declared join field a row's payload does not carry as a
/// required, non-secret property.
fn undeclared_join_field(row: &Row) -> Option<&str> {
    if row.audit.join.is_empty() {
        return None;
    }
    let schema = row.payload.schema.as_ref()?;
    let properties = schema.get("properties")?.as_object()?;
    let required: BTreeSet<&str> = schema
        .get("required")
        .and_then(serde_json::Value::as_array)
        .map(|names| names.iter().filter_map(serde_json::Value::as_str).collect())
        .unwrap_or_default();
    row.audit.join.iter().find_map(|field| {
        let Some(property) = properties.get(field) else {
            return Some(field.as_str());
        };
        let secret = property
            .get("writeOnly")
            .and_then(serde_json::Value::as_bool)
            .unwrap_or(false);
        (!required.contains(field.as_str()) || secret).then_some(field.as_str())
    })
}

/// One optional string list as the generated row facet.
fn optional_str_list(fields: &[String]) -> String {
    if fields.is_empty() {
        return "None".to_owned();
    }
    format!(
        "Some(&[{}])",
        fields
            .iter()
            .map(|field| format!("\"{field}\""))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn profile_catalog(rows: &[Row], profile: &str) -> Vec<String> {
    rows.iter()
        .filter(|row| row.profiles.iter().any(|item| item == profile))
        .filter_map(|row| row.wire_variant.clone())
        .collect()
}

fn generate_profiles(catalog: &Catalog) -> String {
    format!(
        "// {HEADER}\n\n\
         /// Every request currently defined by the broker wire. Host mode is closed\n\
         /// over this list rather than using an open-ended default.\n\
         pub const HOST_OPERATION_CATALOG: &[&str] = &[\n{}\
         ];\n\n\
         /// Guest-local process and broker lifecycle effects. Host networking,\n\
         /// devices, storage, realm, and allocator operations are intentionally\n\
         /// absent from this catalog.\n\
         pub const GUEST_OPERATION_CATALOG: &[&str] = &[\n{}\
         ];\n",
        string_list(profile_catalog(&catalog.rows, "host"), "    "),
        string_list(profile_catalog(&catalog.rows, "guest"), "    "),
    )
}

fn generate_w3(catalog: &Catalog) -> String {
    let variants = catalog
        .rows
        .iter()
        .filter(|row| row.w3)
        .map(|row| format!("            Self::{},\n", row.operation))
        .collect::<String>();
    format!("// {HEADER}\n\n        &[\n{variants}        ]\n")
}

fn generate_authz(catalog: &Catalog) -> String {
    let mut rows = String::new();
    for row in &catalog.rows {
        rows.push_str("    row(\n");
        rows.push_str(&format!("        \"{}\",\n", row.operation));
        rows.push_str(&format!("        \"{}\",\n", row.authz.subject));
        rows.push_str(&format!("        \"{}\",\n", row.authz.scope));
        rows.push_str(&format!(
            "        &[{}],\n",
            row.authz
                .allowed_groups
                .iter()
                .map(|group| format!("\"{group}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        rows.push_str(&format!("        {},\n", row.authz.destructive));
        rows.push_str(&format!("        SecretAccess::{},\n", row.authz.secret_access));
        rows.push_str(&format!(
            "        BrokerRequirement::{},\n",
            row.authz.broker_required
        ));
        rows.push_str(&format!("        AuditMode::{},\n", row.authz.audit_mode));
        rows.push_str("    ),\n");
    }
    format!(
        "// {HEADER}\n\n\
         /// Complete private broker enum authorization matrix from the committed\n\
         /// operation rows.\n\
         pub const BROKER_OPERATION_AUTHZ: &[OperationAuthzRow] = &[\n{rows}];\n"
    )
}

fn owner_variant(owner: &str) -> &'static str {
    match owner {
        "family" => "OperationOwner::Family",
        "broker-generic" => "OperationOwner::BrokerGeneric",
        "transport-excluded" => "OperationOwner::TransportExcluded",
        other => unreachable!("validated owner class {other}"),
    }
}

fn generate_catalog(catalog: &Catalog) -> String {
    let mut rows = String::new();
    for row in &catalog.rows {
        let profiles = row
            .profiles
            .iter()
            .map(|profile| match profile.as_str() {
                "host" => "BrokerProfileId::Host",
                "guest" => "BrokerProfileId::Guest",
                other => unreachable!("validated profile {other}"),
            })
            .collect::<Vec<_>>()
            .join(", ");
        rows.push_str("    BrokerOperationRow {\n");
        rows.push_str(&format!("        operation: \"{}\",\n", row.operation));
        rows.push_str(&format!(
            "        wire_variant: {},\n",
            optional_str(row.wire_variant.as_deref())
        ));
        rows.push_str(&format!("        owner: {},\n", owner_variant(&row.owner)));
        rows.push_str(&format!("        family: {},\n", optional_str(row.family.as_deref())));
        rows.push_str(&format!(
            "        declaring_provider: {},\n",
            optional_str(row.declaring_provider.as_deref())
        ));
        rows.push_str(&format!(
            "        justification: {},\n",
            optional_str(row.justification.as_deref())
        ));
        rows.push_str(&format!("        profiles: &[{profiles}],\n"));
        rows.push_str(&format!("        w3: {},\n", row.w3));
        rows.push_str(&format!("        capabilities: {},\n", row.capabilities));
        rows.push_str(&format!("        disposition: \"{}\",\n", row.disposition));
        rows.push_str(&format!(
            "        stub_target: {},\n",
            match stub_target_variant(row) {
                Some(variant) => format!("Some(StubTarget::{variant})"),
                None => "None".to_owned(),
            }
        ));
        rows.push_str(&format!(
            "        audit_fields: &[{}],\n",
            row.audit
                .fields
                .iter()
                .map(|field| format!("\"{field}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        rows.push_str("        authz: BrokerAuthzFacets {\n");
        rows.push_str(&format!("            subject: \"{}\",\n", row.authz.subject));
        rows.push_str(&format!("            scope: \"{}\",\n", row.authz.scope));
        rows.push_str(&format!(
            "            allowed_groups: &[{}],\n",
            row.authz
                .allowed_groups
                .iter()
                .map(|group| format!("\"{group}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        rows.push_str(&format!("            destructive: {},\n", row.authz.destructive));
        rows.push_str(&format!(
            "            secret_access: \"{}\",\n",
            row.authz.secret_access
        ));
        rows.push_str(&format!(
            "            broker_required: \"{}\",\n",
            row.authz.broker_required
        ));
        rows.push_str(&format!("            audit_mode: \"{}\",\n", row.authz.audit_mode));
        rows.push_str("        },\n");
        rows.push_str(&format!(
            "        payload_provenance: PayloadProvenance::{},\n",
            if row.payload.provenance == "wire" {
                "Wire"
            } else {
                "Request"
            }
        ));
        rows.push_str(&format!(
            "        payload_fields: &[{}],\n",
            payload_names(&row.payload, "properties")
        ));
        rows.push_str(&format!(
            "        payload_required: &[{}],\n",
            payload_names(&row.payload, "required")
        ));
        rows.push_str(&format!(
            "        audit_join: {},\n",
            optional_str_list(&row.audit.join)
        ));
        rows.push_str(&format!("        max_fds: {},\n", row.fds.max_fds));
        rows.push_str(&format!(
            "        fd_kind: {},\n",
            match row.fds.fd_kind.as_deref() {
                Some(kind) => format!("Some(FdKind::{kind})"),
                None => "None".to_owned(),
            }
        ));
        rows.push_str(&format!(
            "        state_cell: {},\n",
            optional_str(row.state_cell.cell.as_deref())
        ));
        rows.push_str(&format!(
            "        cell_durability: {},\n",
            match row.state_cell.durability.as_deref() {
                Some("one-time") => "Some(CellDurability::OneTime)".to_owned(),
                Some("ephemeral") => "Some(CellDurability::Ephemeral)".to_owned(),
                _ => "None".to_owned(),
            }
        ));
        rows.push_str(&format!(
            "        deadline_tier: {},\n",
            match row.deadline.tier.as_deref() {
                Some("standard") | None => "DeadlineTier::Standard".to_owned(),
                Some("extended") => "DeadlineTier::Extended".to_owned(),
                Some(other) => unreachable!("validated tier {other:?}"),
            }
        ));
        rows.push_str("    },\n");
    }
    format!(
        "// {HEADER}\n\n\
         /// Every committed broker operation row, in declared order.\n\
         pub const BROKER_OPERATION_CATALOG: &[BrokerOperationRow] = &[\n{rows}];\n\n\
         /// The number of committed operation rows.\n\
         pub const BROKER_OPERATION_COUNT: usize = {count};\n",
        count = catalog.rows.len()
    )
}

fn optional_str(value: Option<&str>) -> String {
    match value {
        Some(value) => format!("Some(\"{value}\")"),
        None => "None".to_owned(),
    }
}

/// The declared property or required names of one payload schema.
fn payload_names(payload: &Payload, key: &str) -> String {
    let Some(schema) = payload.schema.as_ref() else {
        return String::new();
    };
    let names = match key {
        "properties" => schema
            .get("properties")
            .and_then(|value| value.as_object())
            .map(|object| object.keys().cloned().collect::<Vec<_>>()),
        _ => schema
            .get("required")
            .and_then(|value| value.as_array())
            .map(|array| {
                array
                    .iter()
                    .filter_map(|value| value.as_str().map(str::to_owned))
                    .collect::<Vec<_>>()
            }),
    };
    names
        .unwrap_or_default()
        .into_iter()
        .map(|name| format!("\"{name}\""))
        .collect::<Vec<_>>()
        .join(", ")
}

fn generate_triage(catalog: &Catalog) -> String {
    let family = catalog.rows.iter().filter(|row| row.owner == "family").count();
    let generic = catalog
        .rows
        .iter()
        .filter(|row| row.owner == "broker-generic")
        .count();
    let excluded = catalog
        .rows
        .iter()
        .filter(|row| row.owner == "transport-excluded")
        .count();
    let wire = catalog
        .rows
        .iter()
        .filter(|row| row.wire_variant.is_some())
        .count();
    let mut out = String::from(
        "<!-- @generated by `cargo run -p xtask -- gen-broker-operations`.\n\
         Do not hand-edit: `//packages/xtask:gen_broker_operations_drift`\n\
         regenerates this file and compares it byte-for-byte. -->\n\n\
         # Broker operation triage\n\n\
         Every broker operation row has exactly one owner. The committed rows in\n\
         [`policy/broker-operations.json`](./policy/broker-operations.json) are the\n\
         source; this table is one of their views, and the completeness gates\n\
         compare every other view (the wire enum, the profile catalogs, the\n\
         broker-operation inventory, the authorization rows, and the audit\n\
         fields) against the same rows.\n\n\
         - `family` - a resource-family driver declares the operation's handler\n\
           (`OperationDef`) in its own crate.\n\
         - `broker-generic` - the broker itself owns the effect; the operation has\n\
           no resource family.\n\
         - `transport-excluded` - the name is a transport-layer concern the\n\
           operation envelope does not carry.\n\n",
    );
    out.push_str(&format!(
        "Counts: {family} family-owned, {generic} broker-generic, {excluded} transport-excluded ({wire} rows carry a wire discriminant, {} rows do not).\n\n",
        catalog.rows.len() - wire
    ));
    out.push_str(
        "| Operation | Owner | Family | Declaring provider | Service | Method | Profiles | Disposition | Target | Justification |\n",
    );
    out.push_str("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n");
    for row in &catalog.rows {
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
            row.operation,
            row.owner,
            row.family.as_deref().unwrap_or("-"),
            row.declaring_provider.as_deref().unwrap_or("-"),
            row.service.as_deref().unwrap_or("-"),
            row.method.as_deref().unwrap_or("-"),
            row.profiles.join(", "),
            row.disposition,
            row.disposition_target,
            row.justification.as_deref().unwrap_or("-")
        ));
    }
    out
}

/// Write every view of the committed broker operation rows.
pub fn gen_broker_operations(repo_root: &Path) -> Result<Vec<PathBuf>, Box<dyn std::error::Error>> {
    let catalog = parse(repo_root)?;
    let written = vec![
        write(repo_root, PROFILES_OUT, generate_profiles(&catalog))?,
        write(repo_root, W3_OUT, generate_w3(&catalog))?,
        write(repo_root, AUTHZ_OUT, generate_authz(&catalog))?,
        write(repo_root, CATALOG_OUT, generate_catalog(&catalog))?,
        write(repo_root, TRIAGE_OUT, generate_triage(&catalog))?,
    ];
    Ok(written)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed catalog document, read once for the validation tests.
    #[allow(clippy::disallowed_methods, reason = "cfg(test) helper")]
    fn committed_catalog_text() -> String {
        let root = crate::repo_root().expect("repository root");
        fs::read_to_string(root.join(POLICY_PATH)).expect("committed row catalog")
    }

    /// The committed triage view, read for the drift comparison.
    #[allow(clippy::disallowed_methods, reason = "cfg(test) helper")]
    fn committed_triage() -> String {
        let root = crate::repo_root().expect("repository root");
        fs::read_to_string(root.join(TRIAGE_OUT)).expect("committed triage view")
    }

    /// The first family-owned row of a catalog document, as a mutable object.
    fn first_family_row(catalog: &mut Catalog) -> &mut Row {
        catalog
            .rows
            .iter_mut()
            .find(|row| row.owner == "family")
            .expect("a family-owned row")
    }

    /// A catalog document with one facet mutation applied to the first
    /// family-owned row.
    fn catalog_with_first_family_row_mutated(mutate: impl FnOnce(&mut Row)) -> Catalog {
        let mut catalog = parse_text(&committed_catalog_text()).expect("committed rows validate");
        mutate(first_family_row(&mut catalog));
        catalog
    }

    /// A committed row without a resolvable service+method fails the closed
    /// set: a family-owned operation the rows cannot resolve to a declared
    /// service method cannot be dispatched to a declaring driver.
    #[test]
    fn a_family_row_without_a_resolvable_service_method_fails_generation() {
        let catalog = catalog_with_first_family_row_mutated(|row| {
            row.service = None;
            row.method = None;
        });
        // Render the mutated catalog back to a document and run the closed
        // set over it: serde round-trips exactly what a committed edit would
        // produce.
        let document = serde_json::to_string(&catalog).expect("catalog serializes");
        let error = parse_text(&document).expect_err("generation refuses the row");
        let message = error.to_string();
        assert!(
            message.contains("without a resolvable service+method"),
            "{message}"
        );
    }

    /// A row carrying exactly one half of the resolution is refused: the
    /// resolution is one pair or none.
    #[test]
    fn a_partial_service_resolution_fails_generation() {
        let catalog = catalog_with_first_family_row_mutated(|row| {
            row.method = None;
        });
        let document = serde_json::to_string(&catalog).expect("catalog serializes");
        let error = parse_text(&document).expect_err("generation refuses the row");
        assert!(
            error.to_string().contains("partial service resolution"),
            "{error}"
        );
    }

    /// A non-family row naming a service+method invents a service surface no
    /// row owns.
    #[test]
    fn a_non_family_row_naming_a_resolution_fails_generation() {
        let mut catalog = parse_text(&committed_catalog_text()).expect("committed rows validate");
        let row = catalog
            .rows
            .iter_mut()
            .find(|row| row.owner != "family")
            .expect("a broker-generic row");
        row.service = Some("d2b.process".to_owned());
        row.method = Some("spawn-runner".to_owned());
        let document = serde_json::to_string(&catalog).expect("catalog serializes");
        let error = parse_text(&document).expect_err("generation refuses the row");
        assert!(error.to_string().contains("not family-owned"), "{error}");
    }

    /// A misspelled service id or method name is refused: the session layer
    /// can only address spellings inside the closed grammar.
    #[test]
    fn a_misspelled_resolution_fails_generation() {
        let catalog = catalog_with_first_family_row_mutated(|row| {
            row.service = Some("D2b.process".to_owned());
        });
        let document = serde_json::to_string(&catalog).expect("catalog serializes");
        let error = parse_text(&document).expect_err("generation refuses the row");
        assert!(error.to_string().contains("invalid service id"), "{error}");

        let catalog = catalog_with_first_family_row_mutated(|row| {
            row.method = Some("SpawnRunner".to_owned());
        });
        let document = serde_json::to_string(&catalog).expect("catalog serializes");
        let error = parse_text(&document).expect_err("generation refuses the row");
        assert!(error.to_string().contains("invalid method"), "{error}");
    }

    /// Two rows resolving to one service+method cannot be told apart by the
    /// declaring driver, so the pair is a closed set of one row.
    #[test]
    fn a_duplicate_service_method_resolution_fails_generation() {
        let catalog = catalog_with_first_family_row_mutated(|row| {
            let second = catalog_second_family_row();
            row.service = second.service.clone();
            row.method = second.method.clone();
        });
        let document = serde_json::to_string(&catalog).expect("catalog serializes");
        let error = parse_text(&document).expect_err("generation refuses the row");
        assert!(
            error.to_string().contains("duplicate service+method"),
            "{error}"
        );
    }

    fn catalog_second_family_row() -> Row {
        let catalog = parse_text(&committed_catalog_text()).expect("committed rows validate");
        catalog
            .rows
            .iter()
            .filter(|row| row.owner == "family")
            .nth(1)
            .expect("a second family-owned row")
            .clone()
    }

    /// The triage view moves byte-for-byte with the rows: a committed edit
    /// that regeneration has not absorbed is a byte-exact drift failure, and
    /// the view the generator emits today matches the committed artifact.
    #[test]
    fn the_triage_view_is_byte_exact_and_a_row_edit_moves_it() {
        let catalog = parse_text(&committed_catalog_text()).expect("committed rows validate");
        assert_eq!(generate_triage(&catalog), committed_triage());

        let mutated = first_family_row_edit_moves_triage();
        assert_ne!(mutated, committed_triage());
    }

    fn first_family_row_edit_moves_triage() -> String {
        let catalog = catalog_with_first_family_row_mutated(|row| {
            row.service = Some("d2b.process-renamed".to_owned());
        });
        generate_triage(&catalog)
    }

    /// Every family-owned committed row carries its resolution, and every
    /// broker-generic row carries none: the committed authority is exactly
    /// the shape the generator admits.
    #[test]
    fn the_committed_rows_carry_exactly_the_admitted_resolutions() {
        let catalog = parse_text(&committed_catalog_text()).expect("committed rows validate");
        for row in &catalog.rows {
            assert_eq!(
                row.owner == "family",
                row.service.is_some() && row.method.is_some(),
                "{}",
                row.operation
            );
        }
    }

    /// A row declaring an fd kind renders exactly one comma after the kind:
    /// the inner and outer format strings both used to append one, emitting
    /// `Some(FdKind::Any),,` - invalid Rust that only a row with a declared
    /// kind could hit, so the all-None catalog never caught it (U10
    /// regression).
    #[test]
    fn a_row_declaring_an_fd_kind_renders_exactly_one_comma() {
        let mut catalog = parse_text(&committed_catalog_text()).expect("committed rows validate");
        let row = catalog
            .rows
            .iter_mut()
            .find(|row| row.fds.fd_kind.is_none())
            .expect("a row without a declared fd kind");
        row.fds.max_fds = 1;
        row.fds.fd_kind = Some("Any".to_owned());
        let rendered = generate_catalog(&catalog);
        let line = rendered
            .lines()
            .find(|line| line.contains("fd_kind: Some(FdKind::Any)"))
            .expect("the declared kind renders");
        assert_eq!(line, "        fd_kind: Some(FdKind::Any),");
    }
}
