//! The broker operation catalog generator.
//!
//! `gen-broker-operations` merges the retained committed operation rows in
//! `docs/reference/policy/broker-operations.json` with the per-crate
//! operation declarations (`operations.json`, one per declaring
//! `d2b-provider-*` crate, KTD3/U2) and writes every derived view of the
//! merged catalog:
//!
//! - `docs/reference/policy/broker-operations.json` - the committed rows
//!   themselves, regenerated as one view of the declarations plus the
//!   retained non-declared rows.
//! - `packages/d2b-contracts-broker/src/generated/broker_operation_profiles.rs`
//!   - the closed Host and Guest profile catalogs.
//! - `packages/d2b-contracts/src/generated/w3_broker_operations.rs` - the
//!   `W3BrokerOperation` inventory.
//! - `packages/d2b-core/src/generated/broker_operation_authz.rs` - the
//!   private broker authorization rows.
//! - `packages/d2b-broker/src/generated/broker_operation_catalog.rs` - the
//!   canonical row table the broker envelope resolves and the completeness
//!   gates compare every view against.
//! - `docs/reference/broker-operation-triage.md` - the human triage view.
//!
//! A row a provider crate declares is the declaration in that crate; every
//! row no crate declares stays committed. A declared operation replaces a
//! committed family row of the same declaring provider (so the migration
//! moves without editing the committed file), appends when it is new, and is
//! refused when the committed file covers it only as a broker-generic row or
//! as another provider's family row. Nothing here restates a facet, so a row
//! cannot move without moving every view, which is what makes the drift gate
//! meaningful.

use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use serde::{Deserialize, Serialize};

/// The committed operation rows.
const POLICY_PATH: &str = "docs/reference/policy/broker-operations.json";
/// The generated profile catalog view.
const PROFILES_OUT: &str = "packages/d2b-contracts-broker/src/generated/broker_operation_profiles.rs";
/// The generated `W3BrokerOperation` inventory view.
const W3_OUT: &str = "packages/d2b-contracts/src/generated/w3_broker_operations.rs";
/// The generated private broker authorization row view.
const AUTHZ_OUT: &str = "packages/d2b-core/src/generated/broker_operation_authz.rs";
/// The generated canonical row table.
const CATALOG_OUT: &str = "packages/d2b-broker/src/generated/broker_operation_catalog.rs";
/// The generated triage view.
const TRIAGE_OUT: &str = "docs/reference/broker-operation-triage.md";
/// The directory-glob root the per-crate declarations live under.
const PACKAGES_DIR: &str = "packages";
const PROVIDER_PREFIX: &str = "d2b-provider-";
/// The per-crate operation declaration file (KTD3/U2).
const DECLARATION_FILE: &str = "operations.json";

const HEADER: &str = "@generated by `cargo run -p xtask -- gen-broker-operations`.\n// Do not hand-edit: `//packages/xtask:gen_broker_operations_drift`\n// regenerates this file and compares it byte-for-byte.";

/// One committed broker operation row.
///
/// The field order is the emitted committed-file key order: the generator
/// rewrites `docs/reference/policy/broker-operations.json` from the retained
/// committed rows plus the per-crate declarations, so the emitted bytes must
/// be stable across runs. A facet a row does not carry is omitted rather
/// than emitted as `null`, except the triage trio (`family`,
/// `declaringProvider`, `justification`) and the payload schema, which the
/// historical committed rows spell explicitly.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Row {
    operation: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    wire_variant: Option<String>,
    owner: String,
    #[serde(default)]
    family: Option<String>,
    #[serde(default)]
    declaring_provider: Option<String>,
    /// Why a row no family owns is not provider-owned.
    ///
    /// A row the broker or a transport concern owns records what owns it and
    /// why, so a non-provider row's triage is a committed fact rather than an
    /// omission; a family-owned row carries its declaring provider instead.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    justification: Option<String>,
    profiles: Vec<String>,
    w3: bool,
    capabilities: bool,
    disposition: String,
    disposition_target: String,
    authz: Authz,
    audit: Audit,
    payload: Payload,
    /// The deadline tier one row sits on (standard unless extended).
    #[serde(default)]
    deadline: Deadline,
    /// The declaring service the operation resolves to, when the row is
    /// family-owned (U7/KD6). The service id is the session-layer address
    /// the declaring provider publishes in its service declaration, and the
    /// method names the declared method that serves this row.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    service: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    method: Option<String>,
    /// The broker-owned state cell the row lives on, when the row declares
    /// one (U3/KTD3).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    state_cell: Option<StateCell>,
    /// The fd-carrying facet of one committed operation row, when the row
    /// declares carriage. A row with no carriage omits the facet, which
    /// admits only the empty leg; a row that declares carriage names the
    /// ceiling and the single kernel kind every attached descriptor must
    /// present.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    fds: Option<Fds>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct Authz {
    subject: String,
    scope: String,
    allowed_groups: Vec<String>,
    destructive: bool,
    secret_access: String,
    broker_required: String,
    audit_mode: String,
}

impl Authz {
    /// The required privilege a declared method carries: the authz
    /// subject/scope pair the authority bound names when it widens (U4).
    pub(crate) fn privilege(&self) -> String {
        format!("{}/{}", self.subject, self.scope)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct Audit {
    #[serde(default)]
    fields: Vec<String>,
    required: bool,
    mode: String,
    /// The payload fields the row's audit join is derived from.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    join: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct Payload {
    provenance: String,
    #[serde(default)]
    schema: Option<serde_json::Value>,
}

/// The fd-carrying facet of one committed operation row.
///
/// A row with no carriage declares `maxFds: 0` and no `fdKind`, which
/// admits only the empty leg; a row that declares carriage names the ceiling
/// and the single kernel kind every attached descriptor must present.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct Fds {
    #[serde(default)]
    max_fds: u32,
    #[serde(default)]
    fd_kind: Option<String>,
}

impl Fds {
    /// The descriptor-leg rights ceiling a declared method carries.
    pub(crate) fn max_fds(&self) -> u32 {
        self.max_fds
    }

    /// The descriptor-leg type a declared method carries (U4).
    pub(crate) fn fd_kind(&self) -> Option<&str> {
        self.fd_kind.as_deref()
    }
}

/// The state-cell facet of one committed operation row (U3/KTD3).
///
/// A row with no declared cell leaves both fields absent; a row that names a
/// cell declares the broker-owned state its operation lives on and the
/// cell's durability (one-time records persist under the state root and
/// refuse re-consume across restarts; ephemeral cells reset in-process).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct StateCell {
    #[serde(default)]
    cell: Option<String>,
    #[serde(default)]
    durability: Option<String>,
}

impl StateCell {
    /// The declared state-cell name one method lives on (U4).
    pub(crate) fn cell(&self) -> Option<&str> {
        self.cell.as_deref()
    }
}

/// The deadline-tier facet of one committed operation row (U4/KTD4).
///
/// A row that declares no tier sits on the standard tier, and every row
/// name outside the closed set fails generation instead of widening what a
/// row may mean.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct Deadline {
    #[serde(default)]
    tier: Option<String>,
}

/// One provider crate's operation declaration file (KTD3/U2).
///
/// The declaration is the crate's row surface: the facets a crate can state
/// for each operation it serves - operation name, family, declaring
/// provider, payload schema reference, audit facets, fd and state-cell
/// declarations, and the deadline tier - plus the service resolution. The
/// owner is `family` by construction and a declared row never carries a wire
/// variant or a justification: those are broker-side facts, not crate facts.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct DeclarationFile {
    /// The crate the declaration self-binds to; the file must live in that
    /// crate's directory.
    #[serde(rename = "crate")]
    crate_name: String,
    /// The family operations the crate declares, in declaration order.
    operations: Vec<DeclaredRow>,
}

/// One declared family operation row.
///
/// Every facet a committed family row can carry, minus the facets only the
/// broker side states (`owner`, `wireVariant`, `justification`).
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct DeclaredRow {
    pub(crate) operation: String,
    pub(crate) family: String,
    pub(crate) declaring_provider: String,
    pub(crate) service: String,
    pub(crate) method: String,
    pub(crate) profiles: Vec<String>,
    #[serde(default)]
    pub(crate) w3: bool,
    #[serde(default)]
    pub(crate) capabilities: bool,
    pub(crate) disposition: String,
    pub(crate) disposition_target: String,
    pub(crate) authz: Authz,
    pub(crate) audit: Audit,
    pub(crate) payload: Payload,
    #[serde(default)]
    pub(crate) deadline: Deadline,
    #[serde(default)]
    pub(crate) state_cell: Option<StateCell>,
    #[serde(default)]
    pub(crate) fds: Option<Fds>,
}

/// The declaring crates' operation declarations, as `(crate-name, rows)`
/// pairs in crate order.
pub(crate) type DeclaringCrates = Vec<(String, Vec<DeclaredRow>)>;

impl DeclaredRow {
    /// The committed-row shape of a declared row: family-owned, with no wire
    /// variant and no justification.
    fn into_row(self) -> Row {
        Row {
            operation: self.operation,
            wire_variant: None,
            owner: "family".to_owned(),
            family: Some(self.family),
            declaring_provider: Some(self.declaring_provider),
            justification: None,
            profiles: self.profiles,
            w3: self.w3,
            capabilities: self.capabilities,
            disposition: self.disposition,
            disposition_target: self.disposition_target,
            authz: self.authz,
            audit: self.audit,
            payload: self.payload,
            deadline: self.deadline,
            service: Some(self.service),
            method: Some(self.method),
            state_cell: self.state_cell,
            fds: self.fds,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Catalog {
    version: u32,
    rows: Vec<Row>,
}

/// The row owners the three-way triage admits.
const OWNERS: [&str; 3] = ["family", "broker-generic", "transport-excluded"];
/// The profiles a row may admit.
const PROFILES: [&str; 2] = ["host", "guest"];
/// The payload provenances a row may declare.
const PAYLOAD_PROVENANCE: [&str; 2] = ["wire", "request"];
/// The deadline tiers a row may declare; a row that declares none sits on
/// the standard tier.
const DEADLINE_TIERS: [&str; 2] = ["standard", "extended"];

/// The method-name spelling every operation-serving method carries: a
/// lower-kebab token. A method outside the grammar cannot be addressed by
/// the session layer, so generation fails instead of admitting an
/// unreachable method.
fn valid_method_name(method: &str) -> bool {
    let mut bytes = method.bytes();
    matches!(bytes.next(), Some(first) if first.is_ascii_lowercase())
        && bytes.all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
}

/// The service-id spelling every declaring service id carries: a dotted
/// lowercase identifier, so a service the session layer addresses is
/// addressable as committed. A service id outside the grammar fails
/// generation.
fn valid_service_id(service: &str) -> bool {
    fn segment(segment: &str) -> bool {
        !segment.is_empty()
            && segment
                .bytes()
                .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
    }
    service.split('.').all(segment)
}

fn render_error(message: impl Into<String>) -> Box<dyn std::error::Error> {
    message.into().into()
}

#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
fn parse(repo_root: &Path) -> Result<Catalog, Box<dyn std::error::Error>> {
    let text = fs::read_to_string(repo_root.join(POLICY_PATH))
        .map_err(|error| render_error(format!("read {POLICY_PATH}: {error}")))?;
    parse_text(&text)
}

/// The closed-set validation over one committed catalog document, split out
/// of [`parse`] so the tests can drive it over mutated documents without a
/// repository root.
fn parse_text(text: &str) -> Result<Catalog, Box<dyn std::error::Error>> {
    let catalog: Catalog = serde_json::from_str(text)
        .map_err(|error| render_error(format!("parse {POLICY_PATH}: {error}")))?;
    if catalog.version != 1 {
        return Err(render_error(format!(
            "{POLICY_PATH}: unsupported catalog version {}",
            catalog.version
        )));
    }
    if catalog.rows.is_empty() {
        return Err(render_error(format!("{POLICY_PATH}: no committed rows")));
    }
    for row in &catalog.rows {
        validate_row(row, POLICY_PATH)?;
    }
    validate_row_ids(&catalog.rows, POLICY_PATH)?;
    Ok(catalog)
}

/// The closed-set validation of one row, shared by the committed document
/// and the per-crate declarations: a row outside the admitted facets fails
/// generation instead of widening what a row may mean. `source` names the
/// document the row came from in the error.
fn validate_row(row: &Row, source: &str) -> Result<(), Box<dyn std::error::Error>> {
    let label = |operation: &str| format!("{source}: {operation}");
    if !OWNERS.contains(&row.owner.as_str()) {
        return Err(render_error(format!(
            "{} has unknown owner {}",
            label(&row.operation),
            row.owner
        )));
    }
    if row.owner == "family" && row.family.is_none() {
        return Err(render_error(format!(
            "{} is family-owned without a family",
            label(&row.operation)
        )));
    }
    if row.owner != "family" && (row.family.is_some() || row.declaring_provider.is_some()) {
        return Err(render_error(format!(
            "{} is not family-owned but names a family",
            label(&row.operation)
        )));
    }
    // A family-owned row resolves to a declared service method (KD6): it
    // names the service and the method that serves it, both spelled so
    // the session layer can address them. A row without the resolution
    // cannot be dispatched to a declaring driver, and a non-family row
    // naming one would invent a service surface no row owns.
    if row.service.is_some() != row.method.is_some() {
        return Err(render_error(format!(
            "{} declares a partial service resolution (service and method must travel together)",
            label(&row.operation)
        )));
    }
    if row.owner == "family" && row.service.is_none() {
        return Err(render_error(format!(
            "{} is family-owned without a resolvable service+method",
            label(&row.operation)
        )));
    }
    if row.owner != "family" && row.service.is_some() {
        return Err(render_error(format!(
            "{} is not family-owned but names a service+method",
            label(&row.operation)
        )));
    }
    if let Some(service) = row.service.as_deref() {
        let method = row.method.as_deref().expect("validated pairing above");
        if !valid_service_id(service) {
            return Err(render_error(format!(
                "{} names an invalid service id {service:?}",
                label(&row.operation)
            )));
        }
        if !valid_method_name(method) {
            return Err(render_error(format!(
                "{} names an invalid method {method:?}",
                label(&row.operation)
            )));
        }
    }
    if row.owner != "family" && row.justification.is_none() {
        return Err(render_error(format!(
            "{} is not family-owned without a recorded justification",
            label(&row.operation)
        )));
    }
    if row.owner == "family" && row.justification.is_some() {
        return Err(render_error(format!(
            "{} is family-owned but records a justification",
            label(&row.operation)
        )));
    }
    if row
        .justification
        .as_deref()
        .is_some_and(|value| value.trim().is_empty())
    {
        return Err(render_error(format!(
            "{} records an empty justification",
            label(&row.operation)
        )));
    }
    for profile in &row.profiles {
        if !PROFILES.contains(&profile.as_str()) {
            return Err(render_error(format!(
                "{} has unknown profile {profile}",
                label(&row.operation)
            )));
        }
    }
    if !row.profiles.contains(&"host".to_owned()) {
        return Err(render_error(format!(
            "{} admits no profile",
            label(&row.operation)
        )));
    }
    if row.authz.allowed_groups.is_empty() {
        return Err(render_error(format!(
            "{} admits no allowed group",
            label(&row.operation)
        )));
    }
    if !PAYLOAD_PROVENANCE.contains(&row.payload.provenance.as_str()) {
        return Err(render_error(format!(
            "{} has unknown payload provenance {}",
            label(&row.operation),
            row.payload.provenance
        )));
    }
    if row.payload.provenance == "wire" && row.payload.schema.is_some() {
        return Err(render_error(format!(
            "{} inherits the wire payload but declares a schema",
            label(&row.operation)
        )));
    }
    if row.payload.provenance == "request" && row.payload.schema.is_none() {
        return Err(render_error(format!(
            "{} admits a request payload without a schema",
            label(&row.operation)
        )));
    }
    if let Some(field) = undeclared_join_field(row) {
        return Err(render_error(format!(
            "{} joins on a payload field it does not require: {field}",
            label(&row.operation)
        )));
    }
    let state_cell = row.state_cell.as_ref();
    if state_cell.is_some_and(|cell| cell.cell.is_some() != cell.durability.is_some()) {
        return Err(render_error(format!(
            "{} declares a partial state cell (cell and durability must travel together)",
            label(&row.operation)
        )));
    }
    if let Some(cell) = state_cell.and_then(|cell| cell.cell.as_deref()) {
        if cell.is_empty()
            || cell
                .chars()
                .any(|character| !character.is_ascii_alphanumeric() && character != '-')
        {
            return Err(render_error(format!(
                "{} names an invalid state cell {cell:?}",
                label(&row.operation)
            )));
        }
        match state_cell.and_then(|cell| cell.durability.as_deref()) {
            Some("one-time") | Some("ephemeral") => {}
            Some(other) => {
                return Err(render_error(format!(
                    "{} declares unknown state cell durability {other:?}",
                    label(&row.operation)
                )));
            }
            None => unreachable!("validated pairing above"),
        }
    }
    if let Some(tier) = row.deadline.tier.as_deref()
        && !DEADLINE_TIERS.contains(&tier)
    {
        return Err(render_error(format!(
            "{} declares unknown deadline tier {tier:?}",
            label(&row.operation)
        )));
    }
    if !["deny-only", "errors", "yes"].contains(&row.audit.mode.as_str()) {
        return Err(render_error(format!(
            "{} declares audit mode {}",
            label(&row.operation),
            row.audit.mode
        )));
    }
    if row.disposition == "promoted-live" && !row.audit.required {
        return Err(render_error(format!(
            "{} is live but its audit is not required",
            label(&row.operation)
        )));
    }
    if row.disposition == "stubbed-unimplemented" && stub_target_variant(row).is_none() {
        return Err(render_error(format!(
            "{} is a reserved stub whose disposition target is outside the closed set: {}",
            label(&row.operation),
            row.disposition_target
        )));
    }
    if row.disposition_target.is_empty() {
        return Err(render_error(format!(
            "{} names no disposition target",
            label(&row.operation)
        )));
    }
    Ok(())
}

/// The cross-row closed-set checks over one row set: unique operation names,
/// unique wire variants, case-insensitive operation uniqueness (the toolkit
/// envelope resolves operation names case-insensitively, so two rows
/// differing only in case would silently alias), and one row per declared
/// service+method (two rows resolving to the same pair could not be told
/// apart by the declaring driver).
fn validate_row_ids(rows: &[Row], source: &str) -> Result<(), Box<dyn std::error::Error>> {
    let mut operations = BTreeSet::new();
    let mut wire_variants = BTreeSet::new();
    let mut casefolded_operations = BTreeSet::new();
    let mut service_methods = BTreeSet::new();
    for row in rows {
        if !operations.insert(row.operation.as_str()) {
            return Err(render_error(format!(
                "{source}: duplicate operation {}",
                row.operation
            )));
        }
        if !casefolded_operations.insert(row.operation.to_ascii_lowercase()) {
            return Err(render_error(format!(
                "{source}: operation {} collides case-insensitively with a committed row",
                row.operation
            )));
        }
        if let Some(variant) = row.wire_variant.as_deref() {
            if !wire_variants.insert(variant) {
                return Err(render_error(format!(
                    "{source}: duplicate wire variant {variant}"
                )));
            }
            if variant != row.operation {
                return Err(render_error(format!(
                    "{source}: {} names wire variant {variant}",
                    row.operation
                )));
            }
        }
        if let (Some(service), Some(method)) = (row.service.as_deref(), row.method.as_deref())
            && !service_methods.insert((service, method))
        {
            return Err(render_error(format!(
                "{source}: rows resolve to duplicate service+method {service}/{method}",
                service = service,
                method = method
            )));
        }
    }
    Ok(())
}

/// Read every declaring crate's operation declaration file into
/// (crate-name, declared rows) pairs, in crate order.
#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
pub(crate) fn load_declarations(
    repo_root: &Path,
) -> Result<DeclaringCrates, Box<dyn std::error::Error>> {
    let packages_dir = repo_root.join(PACKAGES_DIR);
    let mut entries: Vec<_> = fs::read_dir(&packages_dir)
        .map_err(|error| render_error(format!("read {}: {error}", packages_dir.display())))?
        .collect::<Result<_, _>>()
        .map_err(|error| render_error(format!("read a packages entry: {error}")))?;
    entries.sort_by_key(|entry| entry.file_name());
    let mut crates = Vec::new();
    for entry in entries {
        let crate_name = entry.file_name().to_string_lossy().into_owned();
        if !crate_name.starts_with(PROVIDER_PREFIX) {
            continue;
        }
        let declaration_path = entry.path().join(DECLARATION_FILE);
        if !declaration_path.is_file() {
            continue;
        }
        let text = fs::read_to_string(&declaration_path).map_err(|error| {
            render_error(format!("read {}: {error}", declaration_path.display()))
        })?;
        let file: DeclarationFile = serde_json::from_str(&text).map_err(|error| {
            render_error(format!("parse {}: {error}", declaration_path.display()))
        })?;
        if file.crate_name != crate_name {
            return Err(render_error(format!(
                "declaration-crate-mismatch: {} names crate \"{}\" but lives in crate \"{crate_name}\"",
                declaration_path.display(),
                file.crate_name
            )));
        }
        crates.push((crate_name, file.operations));
    }
    Ok(crates)
}

/// Merge the retained committed rows with the per-crate declarations.
///
/// A declared operation replaces the committed family row of the same family
/// and declaring provider (the migration path: the declaration moves the
/// row's facets into the crate with no edit to the committed file), appends
/// when no committed row carries the operation (a new operation needs no
/// outside-crate edit), and is refused when the committed file covers the
/// operation only as a broker-generic row or as another provider's family
/// row - a declaration would claim a surface no committed row covers for it.
fn merge_catalog(
    committed: &Catalog,
    declarations: &[(String, Vec<DeclaredRow>)],
) -> Result<Catalog, Box<dyn std::error::Error>> {
    let mut declared_rows: Vec<(String, Row)> = Vec::new();
    for (crate_name, rows) in declarations {
        for row in rows {
            let row = row.clone().into_row();
            let source = format!("{PACKAGES_DIR}/{crate_name}/{DECLARATION_FILE}");
            validate_row(&row, &source)?;
            declared_rows.push((crate_name.clone(), row));
        }
    }
    // One declaring crate per operation: two crates declaring the same
    // operation would both claim the committed row.
    let mut declared_by: BTreeMap<String, &str> = BTreeMap::new();
    for (crate_name, row) in &declared_rows {
        if let Some(other) = declared_by.insert(row.operation.clone(), crate_name) {
            return Err(render_error(format!(
                "operation {} is declared by both {other} and {crate_name}",
                row.operation
            )));
        }
    }
    let declaring_crates: BTreeSet<&str> = declarations
        .iter()
        .map(|(crate_name, _)| crate_name.as_str())
        .collect();
    let mut merged: Vec<Row> = Vec::with_capacity(committed.rows.len() + declared_rows.len());
    for row in &committed.rows {
        if let Some((crate_name, declared)) = declared_rows
            .iter()
            .find(|(_, declared)| declared.operation == row.operation)
        {
            if row.owner != "family" {
                return Err(render_error(format!(
                    "operation {} declared by crate {crate_name} is a committed broker-generic row; no committed row covers it as a family operation",
                    row.operation
                )));
            }
            if row.family.as_deref() != declared.family.as_deref()
                || row.declaring_provider.as_deref() != declared.declaring_provider.as_deref()
            {
                return Err(render_error(format!(
                    "operation {} declared by crate {crate_name} is committed to family {} by provider {}; no committed row covers it for {crate_name}",
                    row.operation,
                    row.family.as_deref().unwrap_or("-"),
                    row.declaring_provider.as_deref().unwrap_or("-"),
                )));
            }
            continue;
        }
        // A committed family row a declaring crate owns but no declaration
        // covers, with no wire discriminant, is a declaration-generated row
        // whose declaration was deleted; the generator drops it so deleting
        // an operation needs no edit outside the crate (KTD5). A row with a
        // wire discriminant stays committed even from a declaring provider:
        // it is served in-broker beside the forwarded family rows.
        if row.owner == "family"
            && row.wire_variant.is_none()
            && row
                .declaring_provider
                .as_deref()
                .is_some_and(|provider| declaring_crates.contains(provider))
        {
            continue;
        }
        merged.push(row.clone());
    }
    for (_, row) in declared_rows {
        merged.push(row);
    }
    validate_row_ids(&merged, POLICY_PATH)?;
    Ok(Catalog {
        version: committed.version,
        rows: merged,
    })
}

/// The merged catalog the generator emits: the committed rows plus the
/// per-crate declarations, validated end to end.
fn build_catalog(repo_root: &Path) -> Result<Catalog, Box<dyn std::error::Error>> {
    let committed = parse(repo_root)?;
    let declarations = load_declarations(repo_root)?;
    merge_catalog(&committed, &declarations)
}

#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
fn write(
    repo_root: &Path,
    relative: &str,
    contents: String,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let path = repo_root.join(relative);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| render_error(format!("create {}: {error}", parent.display())))?;
    }
    fs::write(&path, contents)
        .map_err(|error| render_error(format!("write {relative}: {error}")))?;
    Ok(path)
}

fn string_list<'a>(items: impl IntoIterator<Item = &'a str>, indent: &str) -> String {
    items
        .into_iter()
        .map(|item| format!("{indent}\"{item}\",\n"))
        .collect()
}

/// The generated `StubTarget` variant a reserved stub's committed disposition
/// target maps to.
///
/// A still-stubbed operation's refusal carries this marker on the wire and in
/// its audit record, so it is a closed set: a reserved row whose disposition
/// target is not one of these spellings fails generation instead of widening
/// what a refusal may say.
fn stub_target_variant(row: &Row) -> Option<&'static str> {
    if row.disposition != "stubbed-unimplemented" {
        return None;
    }
    const TARGETS: [(&str, &str); 3] = [
        ("future work", "FutureWork"),
        ("reserved", "Reserved"),
        ("bootstrap-only", "BootstrapOnly"),
    ];
    TARGETS
        .iter()
        .find(|(target, _)| *target == row.disposition_target)
        .map(|(_, variant)| *variant)
}

/// The first declared join field a row's payload does not carry as a
/// required, non-secret property.
fn undeclared_join_field(row: &Row) -> Option<&str> {
    if row.audit.join.is_empty() {
        return None;
    }
    let schema = row.payload.schema.as_ref()?;
    let properties = schema.get("properties")?.as_object()?;
    let required: BTreeSet<&str> = schema
        .get("required")
        .and_then(serde_json::Value::as_array)
        .map(|names| names.iter().filter_map(serde_json::Value::as_str).collect())
        .unwrap_or_default();
    row.audit.join.iter().find_map(|field| {
        let Some(property) = properties.get(field) else {
            return Some(field.as_str());
        };
        let secret = property
            .get("writeOnly")
            .and_then(serde_json::Value::as_bool)
            .unwrap_or(false);
        (!required.contains(field.as_str()) || secret).then_some(field.as_str())
    })
}

/// One optional string list as the generated row facet.
fn optional_str_list(fields: &[String]) -> String {
    if fields.is_empty() {
        return "None".to_owned();
    }
    format!(
        "Some(&[{}])",
        fields
            .iter()
            .map(|field| format!("\"{field}\""))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn profile_catalog<'a>(rows: &'a [Row], profile: &str) -> Vec<&'a str> {
    rows.iter()
        .filter(|row| row.profiles.iter().any(|item| item == profile))
        .filter_map(|row| row.wire_variant.as_deref())
        .collect()
}

fn generate_profiles(catalog: &Catalog) -> String {
    format!(
        "// {HEADER}\n\n\
         /// Every request currently defined by the broker wire. Host mode is closed\n\
         /// over this list rather than using an open-ended default.\n\
         pub const HOST_OPERATION_CATALOG: &[&str] = &[\n{}\
         ];\n\n\
         /// Guest-local process and broker lifecycle effects. Host networking,\n\
         /// devices, storage, realm, and allocator operations are intentionally\n\
         /// absent from this catalog.\n\
         pub const GUEST_OPERATION_CATALOG: &[&str] = &[\n{}\
         ];\n",
        string_list(profile_catalog(&catalog.rows, "host"), "    "),
        string_list(profile_catalog(&catalog.rows, "guest"), "    "),
    )
}

fn generate_w3(catalog: &Catalog) -> String {
    let variants = catalog
        .rows
        .iter()
        .filter(|row| row.w3)
        .map(|row| format!("            Self::{},\n", row.operation))
        .collect::<String>();
    format!("// {HEADER}\n\n        &[\n{variants}        ]\n")
}

fn generate_authz(catalog: &Catalog) -> String {
    let mut rows = String::new();
    for row in &catalog.rows {
        rows.push_str("    row(\n");
        rows.push_str(&format!("        \"{}\",\n", row.operation));
        rows.push_str(&format!("        \"{}\",\n", row.authz.subject));
        rows.push_str(&format!("        \"{}\",\n", row.authz.scope));
        rows.push_str(&format!(
            "        &[{}],\n",
            row.authz
                .allowed_groups
                .iter()
                .map(|group| format!("\"{group}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        rows.push_str(&format!("        {},\n", row.authz.destructive));
        rows.push_str(&format!("        SecretAccess::{},\n", row.authz.secret_access));
        rows.push_str(&format!(
            "        BrokerRequirement::{},\n",
            row.authz.broker_required
        ));
        rows.push_str(&format!("        AuditMode::{},\n", row.authz.audit_mode));
        rows.push_str("    ),\n");
    }
    format!(
        "// {HEADER}\n\n\
         /// Complete private broker enum authorization matrix from the committed\n\
         /// operation rows.\n\
         pub const BROKER_OPERATION_AUTHZ: &[OperationAuthzRow] = &[\n{rows}];\n"
    )
}

fn owner_variant(owner: &str) -> &'static str {
    match owner {
        "family" => "OperationOwner::Family",
        "broker-generic" => "OperationOwner::BrokerGeneric",
        "transport-excluded" => "OperationOwner::TransportExcluded",
        other => unreachable!("validated owner class {other}"),
    }
}

fn generate_catalog(catalog: &Catalog) -> String {
    let mut rows = String::new();
    for row in &catalog.rows {
        let profiles = row
            .profiles
            .iter()
            .map(|profile| match profile.as_str() {
                "host" => "BrokerProfileId::Host",
                "guest" => "BrokerProfileId::Guest",
                other => unreachable!("validated profile {other}"),
            })
            .collect::<Vec<_>>()
            .join(", ");
        rows.push_str("    BrokerOperationRow {\n");
        rows.push_str(&format!("        operation: \"{}\",\n", row.operation));
        rows.push_str(&format!(
            "        wire_variant: {},\n",
            optional_str(row.wire_variant.as_deref())
        ));
        rows.push_str(&format!("        owner: {},\n", owner_variant(&row.owner)));
        rows.push_str(&format!("        family: {},\n", optional_str(row.family.as_deref())));
        rows.push_str(&format!(
            "        declaring_provider: {},\n",
            optional_str(row.declaring_provider.as_deref())
        ));
        rows.push_str(&format!(
            "        justification: {},\n",
            optional_str(row.justification.as_deref())
        ));
        rows.push_str(&format!("        profiles: &[{profiles}],\n"));
        rows.push_str(&format!("        w3: {},\n", row.w3));
        rows.push_str(&format!("        capabilities: {},\n", row.capabilities));
        rows.push_str(&format!("        disposition: \"{}\",\n", row.disposition));
        rows.push_str(&format!(
            "        stub_target: {},\n",
            match stub_target_variant(row) {
                Some(variant) => format!("Some(StubTarget::{variant})"),
                None => "None".to_owned(),
            }
        ));
        rows.push_str(&format!(
            "        audit_fields: &[{}],\n",
            row.audit
                .fields
                .iter()
                .map(|field| format!("\"{field}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        rows.push_str("        authz: BrokerAuthzFacets {\n");
        rows.push_str(&format!("            subject: \"{}\",\n", row.authz.subject));
        rows.push_str(&format!("            scope: \"{}\",\n", row.authz.scope));
        rows.push_str(&format!(
            "            allowed_groups: &[{}],\n",
            row.authz
                .allowed_groups
                .iter()
                .map(|group| format!("\"{group}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        rows.push_str(&format!("            destructive: {},\n", row.authz.destructive));
        rows.push_str(&format!(
            "            secret_access: SecretAccess::{},\n",
            row.authz.secret_access
        ));
        rows.push_str(&format!(
            "            broker_required: BrokerRequirement::{},\n",
            row.authz.broker_required
        ));
        rows.push_str(&format!(
            "            audit_mode: AuditMode::{},\n",
            row.authz.audit_mode
        ));
        rows.push_str("        },\n");
        rows.push_str(&format!(
            "        payload_provenance: PayloadProvenance::{},\n",
            if row.payload.provenance == "wire" {
                "Wire"
            } else {
                "Request"
            }
        ));
        rows.push_str(&format!(
            "        payload_fields: &[{}],\n",
            payload_names(&row.payload, "properties")
        ));
        rows.push_str(&format!(
            "        payload_required: &[{}],\n",
            payload_names(&row.payload, "required")
        ));
        rows.push_str(&format!(
            "        audit_join: {},\n",
            optional_str_list(&row.audit.join)
        ));
        rows.push_str(&format!(
            "        max_fds: {},\n",
            row.fds.as_ref().map(|fds| fds.max_fds).unwrap_or(0)
        ));
        rows.push_str(&format!(
            "        fd_kind: {},\n",
            match row.fds.as_ref().and_then(|fds| fds.fd_kind.as_deref()) {
                Some(kind) => format!("Some(FdKind::{kind})"),
                None => "None".to_owned(),
            }
        ));
        rows.push_str(&format!(
            "        state_cell: {},\n",
            optional_str(row.state_cell.as_ref().and_then(|cell| cell.cell.as_deref()))
        ));
        rows.push_str(&format!(
            "        cell_durability: {},\n",
            match row.state_cell.as_ref().and_then(|cell| cell.durability.as_deref()) {
                Some("one-time") => "Some(CellDurability::OneTime)".to_owned(),
                Some("ephemeral") => "Some(CellDurability::Ephemeral)".to_owned(),
                _ => "None".to_owned(),
            }
        ));
        rows.push_str(&format!(
            "        deadline_tier: {},\n",
            match row.deadline.tier.as_deref() {
                Some("standard") | None => "DeadlineTier::Standard".to_owned(),
                Some("extended") => "DeadlineTier::Extended".to_owned(),
                Some(other) => unreachable!("validated tier {other:?}"),
            }
        ));
        rows.push_str("    },\n");
    }
    format!(
        "// {HEADER}\n\n\
         /// Every committed broker operation row, in declared order.\n\
         pub const BROKER_OPERATION_CATALOG: &[BrokerOperationRow] = &[\n{rows}];\n\n\
         /// The number of committed operation rows.\n\
         pub const BROKER_OPERATION_COUNT: usize = {count};\n",
        count = catalog.rows.len()
    )
}

fn optional_str(value: Option<&str>) -> String {
    match value {
        Some(value) => format!("Some(\"{value}\")"),
        None => "None".to_owned(),
    }
}

/// The declared property or required names of one payload schema.
fn payload_names(payload: &Payload, key: &str) -> String {
    let Some(schema) = payload.schema.as_ref() else {
        return String::new();
    };
    let names = match key {
        "properties" => schema
            .get("properties")
            .and_then(|value| value.as_object())
            .map(|object| object.keys().cloned().collect::<Vec<_>>()),
        _ => schema
            .get("required")
            .and_then(|value| value.as_array())
            .map(|array| {
                array
                    .iter()
                    .filter_map(|value| value.as_str().map(str::to_owned))
                    .collect::<Vec<_>>()
            }),
    };
    names
        .unwrap_or_default()
        .into_iter()
        .map(|name| format!("\"{name}\""))
        .collect::<Vec<_>>()
        .join(", ")
}

fn generate_triage(catalog: &Catalog) -> String {
    let family = catalog.rows.iter().filter(|row| row.owner == "family").count();
    let generic = catalog
        .rows
        .iter()
        .filter(|row| row.owner == "broker-generic")
        .count();
    let excluded = catalog
        .rows
        .iter()
        .filter(|row| row.owner == "transport-excluded")
        .count();
    let wire = catalog
        .rows
        .iter()
        .filter(|row| row.wire_variant.is_some())
        .count();
    let mut out = String::from(
        "<!-- @generated by `cargo run -p xtask -- gen-broker-operations`.\n\
         Do not hand-edit: `//packages/xtask:gen_broker_operations_drift`\n\
         regenerates this file and compares it byte-for-byte. -->\n\n\
         # Broker operation triage\n\n\
         Every broker operation row has exactly one owner. The committed rows in\n\
         [`policy/broker-operations.json`](./policy/broker-operations.json) are the\n\
         source; this table is one of their views, and the completeness gates\n\
         compare every other view (the wire enum, the profile catalogs, the\n\
         broker-operation inventory, the authorization rows, and the audit\n\
         fields) against the same rows.\n\n\
         - `family` - a resource-family driver declares the operation's handler\n\
           (`OperationDef`) in its own crate.\n\
         - `broker-generic` - the broker itself owns the effect; the operation has\n\
           no resource family.\n\
         - `transport-excluded` - the name is a transport-layer concern the\n\
           operation envelope does not carry.\n\n",
    );
    out.push_str(&format!(
        "Counts: {family} family-owned, {generic} broker-generic, {excluded} transport-excluded ({wire} rows carry a wire discriminant, {} rows do not).\n\n",
        catalog.rows.len() - wire
    ));
    out.push_str(
        "| Operation | Owner | Family | Declaring provider | Service | Method | Profiles | Disposition | Target | Justification |\n",
    );
    out.push_str("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n");
    for row in &catalog.rows {
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
            row.operation,
            row.owner,
            row.family.as_deref().unwrap_or("-"),
            row.declaring_provider.as_deref().unwrap_or("-"),
            row.service.as_deref().unwrap_or("-"),
            row.method.as_deref().unwrap_or("-"),
            row.profiles.join(", "),
            row.disposition,
            row.disposition_target,
            row.justification.as_deref().unwrap_or("-")
        ));
    }
    out
}

/// The committed rows document, rendered from the merged catalog.
///
/// The rendering is the byte shape the drift gate pins: the historical
/// two-space pretty format with the triage trio (`family`,
/// `declaringProvider`, `justification`) and the payload schema spelled
/// explicitly, every other absent facet omitted, and no trailing newline.
fn render_catalog_json(catalog: &Catalog) -> String {
    serde_json::to_string_pretty(catalog).expect("the merged catalog serializes")
}

/// Render every view of the merged broker operation rows, in committed
/// order: the committed rows document first, then the five derived views.
///
/// The callers are the `gen-broker-operations` command and the
/// operation-row authority's drift and idempotence gates, so the emission is
/// one path.
#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
pub(crate) fn render_artifacts(
    repo_root: &Path,
) -> Result<Vec<(String, String)>, Box<dyn std::error::Error>> {
    let catalog = build_catalog(repo_root)?;
    Ok(vec![
        (POLICY_PATH.to_owned(), render_catalog_json(&catalog)),
        (PROFILES_OUT.to_owned(), generate_profiles(&catalog)),
        (W3_OUT.to_owned(), generate_w3(&catalog)),
        (AUTHZ_OUT.to_owned(), generate_authz(&catalog)),
        (CATALOG_OUT.to_owned(), generate_catalog(&catalog)),
        (TRIAGE_OUT.to_owned(), generate_triage(&catalog)),
    ])
}

/// Write every view of the merged broker operation rows.
pub fn gen_broker_operations(
    repo_root: &Path,
) -> Result<Vec<PathBuf>, Box<dyn std::error::Error>> {
    render_artifacts(repo_root)?
        .into_iter()
        .map(|(relative, contents)| write(repo_root, &relative, contents))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed catalog document, read once for the validation tests.
    #[allow(clippy::disallowed_methods, reason = "cfg(test) helper")]
    fn committed_catalog_text() -> String {
        let root = crate::repo_root().expect("repository root");
        fs::read_to_string(root.join(POLICY_PATH)).expect("committed row catalog")
    }

    /// The committed triage view, read for the drift comparison.
    #[allow(clippy::disallowed_methods, reason = "cfg(test) helper")]
    fn committed_triage() -> String {
        let root = crate::repo_root().expect("repository root");
        fs::read_to_string(root.join(TRIAGE_OUT)).expect("committed triage view")
    }

    /// The first family-owned row of a catalog document, as a mutable object.
    fn first_family_row(catalog: &mut Catalog) -> &mut Row {
        catalog
            .rows
            .iter_mut()
            .find(|row| row.owner == "family")
            .expect("a family-owned row")
    }

    /// A catalog document with one facet mutation applied to the first
    /// family-owned row.
    fn catalog_with_first_family_row_mutated(mutate: impl FnOnce(&mut Row)) -> Catalog {
        let mut catalog = parse_text(&committed_catalog_text()).expect("committed rows validate");
        mutate(first_family_row(&mut catalog));
        catalog
    }

    /// A committed row without a resolvable service+method fails the closed
    /// set: a family-owned operation the rows cannot resolve to a declared
    /// service method cannot be dispatched to a declaring driver.
    #[test]
    fn a_family_row_without_a_resolvable_service_method_fails_generation() {
        let catalog = catalog_with_first_family_row_mutated(|row| {
            row.service = None;
            row.method = None;
        });
        // Render the mutated catalog back to a document and run the closed
        // set over it: serde round-trips exactly what a committed edit would
        // produce.
        let document = serde_json::to_string(&catalog).expect("catalog serializes");
        let error = parse_text(&document).expect_err("generation refuses the row");
        let message = error.to_string();
        assert!(
            message.contains("without a resolvable service+method"),
            "{message}"
        );
    }

    /// A row carrying exactly one half of the resolution is refused: the
    /// resolution is one pair or none.
    #[test]
    fn a_partial_service_resolution_fails_generation() {
        let catalog = catalog_with_first_family_row_mutated(|row| {
            row.method = None;
        });
        let document = serde_json::to_string(&catalog).expect("catalog serializes");
        let error = parse_text(&document).expect_err("generation refuses the row");
        assert!(
            error.to_string().contains("partial service resolution"),
            "{error}"
        );
    }

    /// A non-family row naming a service+method invents a service surface no
    /// row owns.
    #[test]
    fn a_non_family_row_naming_a_resolution_fails_generation() {
        let mut catalog = parse_text(&committed_catalog_text()).expect("committed rows validate");
        let row = catalog
            .rows
            .iter_mut()
            .find(|row| row.owner != "family")
            .expect("a broker-generic row");
        row.service = Some("d2b.process".to_owned());
        row.method = Some("spawn-runner".to_owned());
        let document = serde_json::to_string(&catalog).expect("catalog serializes");
        let error = parse_text(&document).expect_err("generation refuses the row");
        assert!(error.to_string().contains("not family-owned"), "{error}");
    }

    /// A misspelled service id or method name is refused: the session layer
    /// can only address spellings inside the closed grammar.
    #[test]
    fn a_misspelled_resolution_fails_generation() {
        let catalog = catalog_with_first_family_row_mutated(|row| {
            row.service = Some("D2b.process".to_owned());
        });
        let document = serde_json::to_string(&catalog).expect("catalog serializes");
        let error = parse_text(&document).expect_err("generation refuses the row");
        assert!(error.to_string().contains("invalid service id"), "{error}");

        let catalog = catalog_with_first_family_row_mutated(|row| {
            row.method = Some("SpawnRunner".to_owned());
        });
        let document = serde_json::to_string(&catalog).expect("catalog serializes");
        let error = parse_text(&document).expect_err("generation refuses the row");
        assert!(error.to_string().contains("invalid method"), "{error}");
    }

    /// Two rows resolving to one service+method cannot be told apart by the
    /// declaring driver, so the pair is a closed set of one row.
    #[test]
    fn a_duplicate_service_method_resolution_fails_generation() {
        let catalog = catalog_with_first_family_row_mutated(|row| {
            let second = catalog_second_family_row();
            row.service = second.service.clone();
            row.method = second.method.clone();
        });
        let document = serde_json::to_string(&catalog).expect("catalog serializes");
        let error = parse_text(&document).expect_err("generation refuses the row");
        assert!(
            error.to_string().contains("duplicate service+method"),
            "{error}"
        );
    }

    fn catalog_second_family_row() -> Row {
        let catalog = parse_text(&committed_catalog_text()).expect("committed rows validate");
        catalog
            .rows
            .iter()
            .filter(|row| row.owner == "family")
            .nth(1)
            .expect("a second family-owned row")
            .clone()
    }

    /// The triage view moves byte-for-byte with the rows: a committed edit
    /// that regeneration has not absorbed is a byte-exact drift failure, and
    /// the view the generator emits today matches the committed artifact.
    #[test]
    fn the_triage_view_is_byte_exact_and_a_row_edit_moves_it() {
        let catalog = parse_text(&committed_catalog_text()).expect("committed rows validate");
        assert_eq!(generate_triage(&catalog), committed_triage());

        let mutated = first_family_row_edit_moves_triage();
        assert_ne!(mutated, committed_triage());
    }

    fn first_family_row_edit_moves_triage() -> String {
        let catalog = catalog_with_first_family_row_mutated(|row| {
            row.service = Some("d2b.process-renamed".to_owned());
        });
        generate_triage(&catalog)
    }

    /// Every family-owned committed row carries its resolution, and every
    /// broker-generic row carries none: the committed authority is exactly
    /// the shape the generator admits.
    #[test]
    fn the_committed_rows_carry_exactly_the_admitted_resolutions() {
        let catalog = parse_text(&committed_catalog_text()).expect("committed rows validate");
        for row in &catalog.rows {
            assert_eq!(
                row.owner == "family",
                row.service.is_some() && row.method.is_some(),
                "{}",
                row.operation
            );
        }
    }

    /// A row declaring an fd kind renders exactly one comma after the kind:
    /// the inner and outer format strings both used to append one, emitting
    /// `Some(FdKind::Any),,` - invalid Rust that only a row with a declared
    /// kind could hit, so the all-None catalog never caught it (U10
    /// regression).
    #[test]
    fn a_row_declaring_an_fd_kind_renders_exactly_one_comma() {
        let mut catalog = parse_text(&committed_catalog_text()).expect("committed rows validate");
        let row = catalog
            .rows
            .iter_mut()
            .find(|row| row.fds.is_none())
            .expect("a row without a declared fd kind");
        row.fds = Some(Fds {
            max_fds: 1,
            fd_kind: Some("Any".to_owned()),
        });
        let rendered = generate_catalog(&catalog);
        let line = rendered
            .lines()
            .find(|line| line.contains("fd_kind: Some(FdKind::Any)"))
            .expect("the declared kind renders");
        assert_eq!(line, "        fd_kind: Some(FdKind::Any),");
    }

    /// A declared-row fixture for the merge tests: one family operation with
    /// the minimal admitted facets plus the given operation name and family.
    fn declared_fixture(operation: &str, family: &str, provider: &str) -> DeclaredRow {
        DeclaredRow {
            operation: operation.to_owned(),
            family: family.to_owned(),
            declaring_provider: provider.to_owned(),
            service: "d2b.fixture".to_owned(),
            method: operation.to_ascii_lowercase(),
            profiles: vec!["host".to_owned()],
            w3: false,
            capabilities: false,
            disposition: "promoted-live".to_owned(),
            disposition_target: "live in production broker".to_owned(),
            authz: Authz {
                subject: "fixture".to_owned(),
                scope: "global".to_owned(),
                allowed_groups: vec!["d2bd".to_owned()],
                destructive: false,
                secret_access: "None".to_owned(),
                broker_required: "Yes".to_owned(),
                audit_mode: "Yes".to_owned(),
            },
            audit: Audit {
                fields: vec![operation.to_owned()],
                required: true,
                mode: "yes".to_owned(),
                join: Vec::new(),
            },
            payload: Payload {
                provenance: "wire".to_owned(),
                schema: None,
            },
            deadline: Deadline { tier: None },
            state_cell: None,
            fds: None,
        }
    }

    /// The committed catalog document parsed once.
    fn committed_catalog() -> Catalog {
        parse_text(&committed_catalog_text()).expect("committed rows validate")
    }

    /// A declared operation that the committed file already carries as a
    /// committed family row of the same provider replaces it in the merge,
    /// and the emitted catalog keeps every row exactly once.
    #[test]
    fn a_declared_operation_replaces_its_committed_family_row() {
        let committed = committed_catalog();
        let row = committed
            .rows
            .iter()
            .find(|row| row.owner == "family")
            .expect("a family row");
        let operation = row.operation.clone();
        let family = row.family.clone().expect("a family");
        let provider = row
            .declaring_provider
            .clone()
            .expect("a declaring provider");
        let mut declared = declared_fixture(&operation, &family, &provider);
        declared.disposition = "stubbed-unimplemented".to_owned();
        declared.disposition_target = "reserved".to_owned();
        let declarations = vec![("d2b-provider-fixture".to_owned(), vec![declared])];
        let merged = merge_catalog(&committed, &declarations).expect("the migration merge");
        assert_eq!(merged.rows.len(), committed.rows.len());
        let merged_row = merged
            .rows
            .iter()
            .find(|entry| entry.operation == operation)
            .expect("the declared row is present");
        assert_eq!(merged_row.owner, "family");
        assert_eq!(
            merged_row.declaring_provider.as_deref(),
            Some(provider.as_str())
        );
        // The declared facets win over the committed copy.
        assert_eq!(merged_row.disposition, "stubbed-unimplemented");
    }

    /// A brand-new declared operation appends to the merge with no committed
    /// counterpart: adding an operation needs no edit outside the crate.
    #[test]
    fn a_new_declared_operation_appends_without_a_committed_row() {
        let committed = committed_catalog();
        let merged = merge_catalog(
            &committed,
            &[(
                "d2b-provider-fixture".to_owned(),
                vec![declared_fixture("BrandNewOperation", "fixture", "d2b-provider-fixture")],
            )],
        )
        .expect("a new operation appends");
        assert_eq!(merged.rows.len(), committed.rows.len() + 1);
        assert!(
            merged
                .rows
                .iter()
                .any(|row| row.operation == "BrandNewOperation"),
            "the new operation is committed"
        );
    }

    /// A declaration for an operation the committed file covers only as a
    /// broker-generic row fails generation naming both the operation and the
    /// declaring crate: no committed row covers it as a family operation.
    #[test]
    fn a_declared_broker_generic_operation_fails_generation_naming_both() {
        let committed = committed_catalog();
        let generic = committed
            .rows
            .iter()
            .find(|row| row.owner != "family")
            .expect("a broker-generic row");
        let error = merge_catalog(
            &committed,
            &[(
                "d2b-provider-fixture".to_owned(),
                vec![declared_fixture(
                    &generic.operation,
                    "fixture",
                    "d2b-provider-fixture",
                )],
            )],
        )
        .expect_err("generation refuses a broker-generic claim");
        let message = error.to_string();
        assert!(
            message.contains(&generic.operation) && message.contains("d2b-provider-fixture"),
            "{message}"
        );
        assert!(
            message.contains("broker-generic"),
            "refuses the broker-generic claim: {message}"
        );
    }

    /// A declaration for an operation the committed file assigns to another
    /// provider's family row fails generation naming both the operation and
    /// the declaring crate.
    #[test]
    fn a_declared_operation_claimed_by_another_provider_fails_generation() {
        let committed = committed_catalog();
        let family = committed
            .rows
            .iter()
            .find(|row| row.owner == "family")
            .expect("a family row");
        let error = merge_catalog(
            &committed,
            &[(
                "d2b-provider-fixture".to_owned(),
                vec![declared_fixture(
                    &family.operation,
                    "other-family",
                    "d2b-provider-fixture",
                )],
            )],
        )
        .expect_err("generation refuses a foreign family claim");
        let message = error.to_string();
        assert!(
            message.contains(&family.operation) && message.contains("d2b-provider-fixture"),
            "{message}"
        );
    }

    /// Two crates declaring the same operation fails generation naming both
    /// crates.
    #[test]
    fn two_crates_declaring_the_same_operation_fail_generation_naming_both() {
        let committed = committed_catalog();
        let row = committed
            .rows
            .iter()
            .find(|row| row.owner == "family")
            .expect("a family row");
        let operation = row.operation.clone();
        let family = row.family.clone().expect("a family");
        let provider = row.declaring_provider.clone().expect("a provider");
        let declarations = vec![
            (
                "d2b-provider-fixture-a".to_owned(),
                vec![declared_fixture(&operation, &family, &provider)],
            ),
            (
                "d2b-provider-fixture-b".to_owned(),
                vec![declared_fixture(&operation, &family, &provider)],
            ),
        ];
        let error = merge_catalog(&committed, &declarations)
            .expect_err("generation refuses a double declaration");
        let message = error.to_string();
        assert!(
            message.contains("d2b-provider-fixture-a") && message.contains("d2b-provider-fixture-b"),
            "{message}"
        );
        assert!(message.contains(&operation), "{message}");
    }

    /// A committed family row of a declaring crate that no declaration
    /// covers, with no wire discriminant, is dropped from the merge: it is a
    /// declaration-generated row whose declaration was deleted, so deleting
    /// an operation needs no edit outside the crate (KTD5).
    #[test]
    fn a_declaration_generated_row_without_a_declaration_is_dropped() {
        let committed = Catalog {
            version: 1,
            rows: vec![
                {
                    let mut row = declared_fixture("GhostOperation", "fixture", "d2b-provider-fixture").into_row();
                    row.operation = "GhostOperation".to_owned();
                    row
                },
                {
                    let mut row = declared_fixture("LiveOperation", "fixture", "d2b-provider-fixture").into_row();
                    row.operation = "LiveOperation".to_owned();
                    row
                },
            ],
        };
        // The declaration covers only LiveOperation; GhostOperation is an
        // orphan of the declaring crate and must not survive.
        let merged = merge_catalog(
            &committed,
            &[(
                "d2b-provider-fixture".to_owned(),
                vec![declared_fixture("LiveOperation", "fixture", "d2b-provider-fixture")],
            )],
        )
        .expect("the merge");
        assert_eq!(merged.rows.len(), 1);
        assert_eq!(merged.rows[0].operation, "LiveOperation");
    }

    /// A retained family row with a wire discriminant survives the orphan
    /// rule even when it belongs to a declaring crate: the sandwich rows are
    /// served in-broker beside the forwarded family operations.
    #[test]
    fn a_wire_discriminant_family_row_from_a_declaring_crate_survives() {
        let mut retained = declared_fixture("SandwichOperation", "fixture", "d2b-provider-fixture").into_row();
        retained.wire_variant = Some("SandwichOperation".to_owned());
        let committed = Catalog {
            version: 1,
            rows: vec![retained],
        };
        let merged = merge_catalog(
            &committed,
            &[(
                "d2b-provider-fixture".to_owned(),
                vec![declared_fixture("LiveOperation", "fixture", "d2b-provider-fixture")],
            )],
        )
        .expect("the merge");
        assert_eq!(merged.rows.len(), 2);
        assert!(
            merged
                .rows
                .iter()
                .any(|row| row.operation == "SandwichOperation"),
            "the wire-discriminant row stays committed"
        );
    }

    /// The emitted committed document round-trips: parsing it back yields the
    /// merged catalog, so the drift gate compares one stable byte shape.
    #[test]
    fn the_emitted_committed_document_round_trips() {
        let committed = committed_catalog();
        let merged = merge_catalog(
            &committed,
            &[(
                "d2b-provider-fixture".to_owned(),
                vec![declared_fixture("BrandNewOperation", "fixture", "d2b-provider-fixture")],
            )],
        )
        .expect("the merge");
        let rendered = render_catalog_json(&merged);
        let reparsed = parse_text(&rendered).expect("the emitted document validates");
        assert_eq!(reparsed.rows.len(), merged.rows.len());
        for (a, b) in reparsed.rows.iter().zip(merged.rows.iter()) {
            assert_eq!(a.operation, b.operation);
        }
    }
}
