//! The broker operation catalog generator.
//!
//! `gen-broker-operations` reads the committed operation rows in
//! `docs/reference/policy/broker-operations.json` and writes every derived
//! view of them:
//!
//! - `packages/d2b-contracts-broker/src/generated/broker_operation_profiles.rs`
//!   - the closed Host and Guest profile catalogs.
//! - `packages/d2b-contracts/src/generated/w3_broker_operations.rs` - the
//!   `W3BrokerOperation` inventory.
//! - `packages/d2b-core/src/generated/broker_operation_authz.rs` - the
//!   private broker authorization rows.
//! - `packages/d2b-broker/src/generated/broker_operation_catalog.rs` - the
//!   canonical row table the broker envelope resolves and the completeness
//!   gates compare every view against.
//! - `docs/reference/broker-operation-triage.md` - the human triage view.
//!
//! The committed rows are the single source of truth. Nothing here restates
//! a facet, so a row cannot move without moving every view, which is what
//! makes the drift gate meaningful.

use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
};

use serde::Deserialize;

/// The committed operation rows.
const POLICY_PATH: &str = "docs/reference/policy/broker-operations.json";
/// The generated profile catalog view.
const PROFILES_OUT: &str = "packages/d2b-contracts-broker/src/generated/broker_operation_profiles.rs";
/// The generated `W3BrokerOperation` inventory view.
const W3_OUT: &str = "packages/d2b-contracts/src/generated/w3_broker_operations.rs";
/// The generated private broker authorization row view.
const AUTHZ_OUT: &str = "packages/d2b-core/src/generated/broker_operation_authz.rs";
/// The generated canonical row table.
const CATALOG_OUT: &str = "packages/d2b-broker/src/generated/broker_operation_catalog.rs";
/// The generated triage view.
const TRIAGE_OUT: &str = "docs/reference/broker-operation-triage.md";

const HEADER: &str = "@generated by `cargo run -p xtask -- gen-broker-operations`.\n// Do not hand-edit: `//packages/xtask:gen_broker_operations_drift`\n// regenerates this file and compares it byte-for-byte.";

/// One committed broker operation row.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Row {
    operation: String,
    #[serde(default)]
    wire_variant: Option<String>,
    owner: String,
    #[serde(default)]
    family: Option<String>,
    #[serde(default)]
    declaring_provider: Option<String>,
    profiles: Vec<String>,
    w3: bool,
    capabilities: bool,
    disposition: String,
    disposition_target: String,
    #[serde(default)]
    stub_wave: Option<String>,
    authz: Authz,
    audit: Audit,
    payload: Payload,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Authz {
    subject: String,
    scope: String,
    allowed_groups: Vec<String>,
    destructive: bool,
    secret_access: String,
    broker_required: String,
    audit_mode: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Audit {
    #[serde(default)]
    fields: Vec<String>,
    required: bool,
    mode: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Payload {
    provenance: String,
    #[serde(default)]
    schema: Option<serde_json::Value>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Catalog {
    version: u32,
    rows: Vec<Row>,
}

/// The row owners the three-way triage admits.
const OWNERS: [&str; 3] = ["family", "broker-generic", "transport-excluded"];
/// The profiles a row may admit.
const PROFILES: [&str; 2] = ["host", "guest"];
/// The payload provenances a row may declare.
const PAYLOAD_PROVENANCE: [&str; 2] = ["wire", "request"];

fn render_error(message: impl Into<String>) -> Box<dyn std::error::Error> {
    message.into().into()
}

fn parse(repo_root: &Path) -> Result<Catalog, Box<dyn std::error::Error>> {
    let text = fs::read_to_string(repo_root.join(POLICY_PATH))
        .map_err(|error| render_error(format!("read {POLICY_PATH}: {error}")))?;
    let catalog: Catalog = serde_json::from_str(&text)
        .map_err(|error| render_error(format!("parse {POLICY_PATH}: {error}")))?;
    if catalog.version != 1 {
        return Err(render_error(format!(
            "{POLICY_PATH}: unsupported catalog version {}",
            catalog.version
        )));
    }
    if catalog.rows.is_empty() {
        return Err(render_error(format!("{POLICY_PATH}: no committed rows")));
    }
    let mut operations = BTreeSet::new();
    let mut wire_variants = BTreeSet::new();
    for row in &catalog.rows {
        if !operations.insert(row.operation.as_str()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: duplicate operation {}",
                row.operation
            )));
        }
        if let Some(variant) = row.wire_variant.as_deref() {
            if !wire_variants.insert(variant) {
                return Err(render_error(format!(
                    "{POLICY_PATH}: duplicate wire variant {variant}"
                )));
            }
            if variant != row.operation {
                return Err(render_error(format!(
                    "{POLICY_PATH}: {} names wire variant {variant}",
                    row.operation
                )));
            }
        }
        if !OWNERS.contains(&row.owner.as_str()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} has unknown owner {}",
                row.operation, row.owner
            )));
        }
        if row.owner == "family" && row.family.is_none() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} is family-owned without a family",
                row.operation
            )));
        }
        if row.owner != "family" && (row.family.is_some() || row.declaring_provider.is_some()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} is not family-owned but names a family",
                row.operation
            )));
        }
        for profile in &row.profiles {
            if !PROFILES.contains(&profile.as_str()) {
                return Err(render_error(format!(
                    "{POLICY_PATH}: {} has unknown profile {profile}",
                    row.operation
                )));
            }
        }
        if !row.profiles.contains(&"host".to_owned()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} admits no profile",
                row.operation
            )));
        }
        if row.authz.allowed_groups.is_empty() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} admits no allowed group",
                row.operation
            )));
        }
        if !PAYLOAD_PROVENANCE.contains(&row.payload.provenance.as_str()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} has unknown payload provenance {}",
                row.operation, row.payload.provenance
            )));
        }
        if row.payload.provenance == "wire" && row.payload.schema.is_some() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} inherits the wire payload but declares a schema",
                row.operation
            )));
        }
        if row.payload.provenance == "request" && row.payload.schema.is_none() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} admits a request payload without a schema",
                row.operation
            )));
        }
        if !["deny-only", "errors", "yes"].contains(&row.audit.mode.as_str()) {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} declares audit mode {}",
                row.operation, row.audit.mode
            )));
        }
        if row.disposition == "promoted-live" && !row.audit.required {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} is live but its audit is not required",
                row.operation
            )));
        }
        if row.disposition == "stubbed-unimplemented" && row.stub_wave.is_none() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} is a stub without a reserved wave",
                row.operation
            )));
        }
        if row.disposition_target.is_empty() {
            return Err(render_error(format!(
                "{POLICY_PATH}: {} names no disposition target",
                row.operation
            )));
        }
    }
    Ok(catalog)
}

fn write(
    repo_root: &Path,
    relative: &str,
    contents: String,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let path = repo_root.join(relative);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| render_error(format!("create {}: {error}", parent.display())))?;
    }
    fs::write(&path, contents)
        .map_err(|error| render_error(format!("write {relative}: {error}")))?;
    Ok(path)
}

fn string_list(items: impl IntoIterator<Item = String>, indent: &str) -> String {
    items
        .into_iter()
        .map(|item| format!("{indent}\"{item}\",\n"))
        .collect()
}

fn profile_catalog(rows: &[Row], profile: &str) -> Vec<String> {
    rows.iter()
        .filter(|row| row.profiles.iter().any(|item| item == profile))
        .filter_map(|row| row.wire_variant.clone())
        .collect()
}

fn generate_profiles(catalog: &Catalog) -> String {
    format!(
        "// {HEADER}\n\n\
         /// Every request currently defined by the broker wire. Host mode is closed\n\
         /// over this list rather than using an open-ended default.\n\
         pub const HOST_OPERATION_CATALOG: &[&str] = &[\n{}\
         ];\n\n\
         /// Guest-local process and broker lifecycle effects. Host networking,\n\
         /// devices, storage, realm, and allocator operations are intentionally\n\
         /// absent from this catalog.\n\
         pub const GUEST_OPERATION_CATALOG: &[&str] = &[\n{}\
         ];\n",
        string_list(profile_catalog(&catalog.rows, "host"), "    "),
        string_list(profile_catalog(&catalog.rows, "guest"), "    "),
    )
}

fn generate_w3(catalog: &Catalog) -> String {
    let variants = catalog
        .rows
        .iter()
        .filter(|row| row.w3)
        .map(|row| format!("            Self::{},\n", row.operation))
        .collect::<String>();
    format!("// {HEADER}\n\n        &[\n{variants}        ]\n")
}

fn generate_authz(catalog: &Catalog) -> String {
    let mut rows = String::new();
    for row in &catalog.rows {
        rows.push_str("    row(\n");
        rows.push_str(&format!("        \"{}\",\n", row.operation));
        rows.push_str(&format!("        \"{}\",\n", row.authz.subject));
        rows.push_str(&format!("        \"{}\",\n", row.authz.scope));
        rows.push_str(&format!(
            "        &[{}],\n",
            row.authz
                .allowed_groups
                .iter()
                .map(|group| format!("\"{group}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        rows.push_str(&format!("        {},\n", row.authz.destructive));
        rows.push_str(&format!("        SecretAccess::{},\n", row.authz.secret_access));
        rows.push_str(&format!(
            "        BrokerRequirement::{},\n",
            row.authz.broker_required
        ));
        rows.push_str(&format!("        AuditMode::{},\n", row.authz.audit_mode));
        rows.push_str("    ),\n");
    }
    format!(
        "// {HEADER}\n\n\
         /// Complete private broker enum authorization matrix from the committed\n\
         /// operation rows.\n\
         pub const BROKER_OPERATION_AUTHZ: &[OperationAuthzRow] = &[\n{rows}];\n"
    )
}

fn owner_variant(owner: &str) -> &'static str {
    match owner {
        "family" => "OperationOwner::Family",
        "broker-generic" => "OperationOwner::BrokerGeneric",
        "transport-excluded" => "OperationOwner::TransportExcluded",
        other => unreachable!("validated owner class {other}"),
    }
}

fn generate_catalog(catalog: &Catalog) -> String {
    let mut rows = String::new();
    for row in &catalog.rows {
        let profiles = row
            .profiles
            .iter()
            .map(|profile| match profile.as_str() {
                "host" => "BrokerProfileId::Host",
                "guest" => "BrokerProfileId::Guest",
                other => unreachable!("validated profile {other}"),
            })
            .collect::<Vec<_>>()
            .join(", ");
        rows.push_str("    BrokerOperationRow {\n");
        rows.push_str(&format!("        operation: \"{}\",\n", row.operation));
        rows.push_str(&format!(
            "        wire_variant: {},\n",
            optional_str(row.wire_variant.as_deref())
        ));
        rows.push_str(&format!("        owner: {},\n", owner_variant(&row.owner)));
        rows.push_str(&format!("        family: {},\n", optional_str(row.family.as_deref())));
        rows.push_str(&format!(
            "        declaring_provider: {},\n",
            optional_str(row.declaring_provider.as_deref())
        ));
        rows.push_str(&format!("        profiles: &[{profiles}],\n"));
        rows.push_str(&format!("        w3: {},\n", row.w3));
        rows.push_str(&format!("        capabilities: {},\n", row.capabilities));
        rows.push_str(&format!("        disposition: \"{}\",\n", row.disposition));
        rows.push_str(&format!(
            "        stub_wave: {},\n",
            optional_str(row.stub_wave.as_deref())
        ));
        rows.push_str(&format!(
            "        audit_fields: &[{}],\n",
            row.audit
                .fields
                .iter()
                .map(|field| format!("\"{field}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        rows.push_str("        authz: BrokerAuthzFacets {\n");
        rows.push_str(&format!("            subject: \"{}\",\n", row.authz.subject));
        rows.push_str(&format!("            scope: \"{}\",\n", row.authz.scope));
        rows.push_str(&format!(
            "            allowed_groups: &[{}],\n",
            row.authz
                .allowed_groups
                .iter()
                .map(|group| format!("\"{group}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        rows.push_str(&format!("            destructive: {},\n", row.authz.destructive));
        rows.push_str(&format!(
            "            secret_access: \"{}\",\n",
            row.authz.secret_access
        ));
        rows.push_str(&format!(
            "            broker_required: \"{}\",\n",
            row.authz.broker_required
        ));
        rows.push_str(&format!("            audit_mode: \"{}\",\n", row.authz.audit_mode));
        rows.push_str("        },\n");
        rows.push_str(&format!(
            "        payload_provenance: PayloadProvenance::{},\n",
            if row.payload.provenance == "wire" {
                "Wire"
            } else {
                "Request"
            }
        ));
        rows.push_str(&format!(
            "        payload_fields: &[{}],\n",
            payload_names(&row.payload, "properties")
        ));
        rows.push_str(&format!(
            "        payload_required: &[{}],\n",
            payload_names(&row.payload, "required")
        ));
        rows.push_str("    },\n");
    }
    format!(
        "// {HEADER}\n\n\
         /// Every committed broker operation row, in declared order.\n\
         pub const BROKER_OPERATION_CATALOG: &[BrokerOperationRow] = &[\n{rows}];\n\n\
         /// The number of committed operation rows.\n\
         pub const BROKER_OPERATION_COUNT: usize = {count};\n",
        count = catalog.rows.len()
    )
}

fn optional_str(value: Option<&str>) -> String {
    match value {
        Some(value) => format!("Some(\"{value}\")"),
        None => "None".to_owned(),
    }
}

/// The declared property or required names of one payload schema.
fn payload_names(payload: &Payload, key: &str) -> String {
    let Some(schema) = payload.schema.as_ref() else {
        return String::new();
    };
    let names = match key {
        "properties" => schema
            .get("properties")
            .and_then(|value| value.as_object())
            .map(|object| object.keys().cloned().collect::<Vec<_>>()),
        _ => schema
            .get("required")
            .and_then(|value| value.as_array())
            .map(|array| {
                array
                    .iter()
                    .filter_map(|value| value.as_str().map(str::to_owned))
                    .collect::<Vec<_>>()
            }),
    };
    names
        .unwrap_or_default()
        .into_iter()
        .map(|name| format!("\"{name}\""))
        .collect::<Vec<_>>()
        .join(", ")
}

fn generate_triage(catalog: &Catalog) -> String {
    let family = catalog.rows.iter().filter(|row| row.owner == "family").count();
    let generic = catalog
        .rows
        .iter()
        .filter(|row| row.owner == "broker-generic")
        .count();
    let excluded = catalog
        .rows
        .iter()
        .filter(|row| row.owner == "transport-excluded")
        .count();
    let wire = catalog
        .rows
        .iter()
        .filter(|row| row.wire_variant.is_some())
        .count();
    let mut out = String::from(
        "<!-- @generated by `cargo run -p xtask -- gen-broker-operations`.\n\
         Do not hand-edit: `//packages/xtask:gen_broker_operations_drift`\n\
         regenerates this file and compares it byte-for-byte. -->\n\n\
         # Broker operation triage\n\n\
         Every broker operation row has exactly one owner. The committed rows in\n\
         [`policy/broker-operations.json`](./policy/broker-operations.json) are the\n\
         source; this table is one of their views, and the completeness gates\n\
         compare every other view (wire enum, profile catalogs, W3 inventory,\n\
         authorization rows, and audit fields) against the same rows.\n\n\
         - `family` - a resource-family driver declares the operation's handler\n\
           (`OperationDef`) in its own crate.\n\
         - `broker-generic` - the broker itself owns the effect; the operation has\n\
           no resource family.\n\
         - `transport-excluded` - the name is a transport-layer concern the\n\
           operation envelope does not carry.\n\n",
    );
    out.push_str(&format!(
        "Counts: {family} family-owned, {generic} broker-generic, {excluded} transport-excluded ({wire} rows carry a wire discriminant, {} rows do not).\n\n",
        catalog.rows.len() - wire
    ));
    out.push_str(
        "| Operation | Owner | Family | Declaring provider | Profiles | Disposition | Target |\n",
    );
    out.push_str("| --- | --- | --- | --- | --- | --- | --- |\n");
    for row in &catalog.rows {
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {} |\n",
            row.operation,
            row.owner,
            row.family.as_deref().unwrap_or("-"),
            row.declaring_provider.as_deref().unwrap_or("-"),
            row.profiles.join(", "),
            row.disposition,
            row.disposition_target
        ));
    }
    out
}

/// Write every view of the committed broker operation rows.
pub fn gen_broker_operations(repo_root: &Path) -> Result<Vec<PathBuf>, Box<dyn std::error::Error>> {
    let catalog = parse(repo_root)?;
    let mut written = Vec::new();
    written.push(write(repo_root, PROFILES_OUT, generate_profiles(&catalog))?);
    written.push(write(repo_root, W3_OUT, generate_w3(&catalog))?);
    written.push(write(repo_root, AUTHZ_OUT, generate_authz(&catalog))?);
    written.push(write(repo_root, CATALOG_OUT, generate_catalog(&catalog))?);
    written.push(write(repo_root, TRIAGE_OUT, generate_triage(&catalog))?);
    Ok(written)
}
