//! The client-layer catalog generator.
//!
//! `gen-layer-catalogs` projects the declared resource-plane vocabulary into
//! the crate-local views the client-facing layers consume, so no layer keeps
//! a hand copy of a list the declaration already owns:
//!
//! - `packages/d2b/src/generated/surface_catalog.rs` - the CLI's resource
//!   type registry, its typed nouns, its typed-verb gates, the execution
//!   targets, the controller-owned types, and the no-isolation vocabulary.
//! - `packages/d2b-audit/src/generated/audit_catalog.rs` - the audit record
//!   type vocabulary, the resource mutation verbs, and the process-provider
//!   vocabulary.
//! - `packages/d2b-contracts-provider/src/v3/generated/telemetry_catalog.rs` -
//!   the metric label resource-type, verb, process-provider, and
//!   broker-operation domains.
//!
//! Every list is either projected from a committed authority (the standard
//! and converted resource type registries in `d2b-contracts`, the Role
//! resource verbs in `d2b-contracts-zone-session`, the committed broker
//! operation rows in `docs/reference/policy/broker-operations.json`) or
//! declared by one table here. Nothing is restated beside a generated copy,
//! and each emitted file is compared byte-for-byte against this generator by
//! its drift target.

use std::{
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use serde::Deserialize;

use d2b_contracts::identity::{STANDARD_RESOURCE_TYPES, V3_CONVERTED_RESOURCE_TYPES};
use d2b_contracts_zone_session::v3::RoleResourceVerb;

/// The CLI's generated directory.
const CLI_OUT_DIR: &str = "packages/d2b/src/generated";
/// The audit crate's generated directory.
const AUDIT_OUT_DIR: &str = "packages/d2b-audit/src/generated";
/// The provider contracts crate's generated directory.
const TELEMETRY_OUT_DIR: &str = "packages/d2b-contracts-provider/src/v3/generated";

/// The generated module file every directory carries.
const MOD_FILE: &str = "mod.rs";

/// The shared byte-exact header every generated artifact carries.
const HEADER: &str = concat!(
    "// @generated by `cargo run -p xtask -- gen-layer-catalogs`.\n",
    "// Do not hand-edit: the generator's `--check` form compares this file\n",
    "// byte-for-byte against its output.\n",
);

/// The committed broker operation rows.
const BROKER_OPERATIONS_PATH: &str = "docs/reference/policy/broker-operations.json";

/// The pseudo type name the audit and metric vocabularies admit for resources
/// whose type is outside the registry.
const VENDOR_TYPE: &str = "vendor";

/// The resource verb spellings that only read.
const READ_ONLY_VERBS: [RoleResourceVerb; 3] = [
    RoleResourceVerb::Get,
    RoleResourceVerb::List,
    RoleResourceVerb::Watch,
];

/// One process provider the layer vocabularies admit.
struct ProcessProvider {
    /// The label value the process surfaces carry.
    id: &'static str,
    /// Whether the process metric label domain admits the id.
    metric_label: bool,
}

/// The process-provider vocabulary.
///
/// The audit class admits every entry; the process metric families label the
/// subset their emitters serve. No crate keeps a second copy of either list.
const PROCESS_PROVIDERS: &[ProcessProvider] = &[
    ProcessProvider {
        id: "minijail",
        metric_label: true,
    },
    ProcessProvider {
        id: "systemd",
        metric_label: true,
    },
    ProcessProvider {
        id: "system-core-user",
        metric_label: false,
    },
];

/// The typed nouns and the resource type each addresses.
const TYPED_NOUNS: &[(&str, &str)] = &[
    ("volume", "Volume"),
    ("network", "Network"),
    ("device", "Device"),
    ("user", "User"),
    ("credential", "Credential"),
    ("quota", "Quota"),
    ("emergency-policy", "EmergencyPolicy"),
    ("guest", "Guest"),
    ("process", "Process"),
];

/// The typed verbs and the resource type each is available on.
const TYPED_VERB_TYPES: &[(&str, &str)] = &[
    ("verify", "Volume"),
    ("usb", "Device"),
    ("security-key", "Device"),
];

/// The resource types the controller owns: no operator authors one.
const CONTROLLER_OWNED_TYPES: &[&str] = &["Endpoint"];

/// The resource types that serve as an execution target.
const EXECUTION_TARGET_TYPES: &[&str] = &["Host", "Guest"];

/// The provider reference of a workload running without an isolation
/// boundary.
const UNSAFE_LOCAL_PROVIDER_REF: &str = "Provider/unsafe-local";

/// The provider kind a no-isolation row carries.
const UNSAFE_LOCAL_PROVIDER_KIND: &str = "unsafe-local";

/// The postures that mean the row has no isolation boundary.
const NO_ISOLATION_POSTURES: &[&str] = &["none", "unsafe-local"];

/// The execution targets that run without an isolation boundary.
const NO_ISOLATION_TARGET_TYPES: &[&str] = &["Host"];

/// Render the doc-comment lines of one generated item.
fn doc_lines(lines: &[&str]) -> String {
    let mut out = String::new();
    for line in lines {
        if line.is_empty() {
            out.push_str("///\n");
        } else {
            let _ = writeln!(out, "/// {line}");
        }
    }
    out
}

/// Render one `&[&str]` constant.
fn string_slice(name: &str, doc: &[&str], values: &[String]) -> String {
    let mut out = doc_lines(doc);
    let _ = writeln!(out, "pub const {name}: &[&str] = &[");
    for value in values {
        let _ = writeln!(out, "    \"{value}\",");
    }
    out.push_str("];\n");
    out
}

/// Render one closed `&[&str]` constant.

/// Render one `&[(&str, &str)]` constant.
fn string_pair_slice(name: &str, doc: &[&str], values: &[(&str, &str)]) -> String {
    let mut out = doc_lines(doc);
    let _ = writeln!(out, "pub const {name}: &[(&str, &str)] = &[");
    for (left, right) in values {
        let _ = writeln!(out, "    (\"{left}\", \"{right}\"),");
    }
    out.push_str("];\n");
    out
}

/// The kebab-case spelling of one role vocabulary entry.
fn verb_spelling(verb: &RoleResourceVerb) -> String {
    serde_json::to_value(verb)
        .expect("a contract verb serializes")
        .as_str()
        .expect("a contract verb is a string")
        .to_owned()
}

/// Every resource verb, in contract order.
fn resource_verbs() -> Vec<String> {
    RoleResourceVerb::ALL.iter().map(verb_spelling).collect()
}

/// The resource verbs that mutate, in contract order.
fn resource_mutation_verbs() -> Vec<String> {
    RoleResourceVerb::ALL
        .iter()
        .filter(|verb| !READ_ONLY_VERBS.contains(verb))
        .map(verb_spelling)
        .collect()
}

/// The audit record type vocabulary: the converted registry, then the vendor
/// pseudo type.
fn audit_resource_types() -> Vec<String> {
    let mut values = V3_CONVERTED_RESOURCE_TYPES
        .iter()
        .map(|value| (*value).to_owned())
        .collect::<Vec<_>>();
    values.push(VENDOR_TYPE.to_owned());
    values
}

/// The metric label resource type domain: the standard registry, then the
/// vendor pseudo type.
fn metric_resource_types() -> Vec<String> {
    let mut values = STANDARD_RESOURCE_TYPES
        .iter()
        .map(|value| (*value).to_owned())
        .collect::<Vec<_>>();
    values.push(VENDOR_TYPE.to_owned());
    values
}

/// One committed broker operation row, as far as the label domain needs it.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct BrokerOperationRow {
    /// The declared operation name.
    operation: String,
    /// The wire variant a broker request carries, when the row is callable
    /// over the wire at all.
    #[serde(default)]
    wire_variant: Option<String>,
}

/// The committed broker operation rows.
#[derive(Debug, Deserialize)]
struct BrokerOperations {
    version: u32,
    rows: Vec<BrokerOperationRow>,
}

/// The broker operation label domain: every wire variant the committed rows
/// declare, in row order.
///
/// The metric `op` label carries the wire request name, so a row that
/// declares no wire variant is not in the domain - nothing can emit it as a
/// label - and a row cannot be admitted as one without a wire variant. The
/// rows are the authority `gen-broker-operations` projects every broker view
/// from, so the domain moves with them or fails the drift target.
#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
fn broker_operation_values(repo_root: &Path) -> Result<Vec<String>, String> {
    let text = fs::read_to_string(repo_root.join(BROKER_OPERATIONS_PATH))
        .map_err(|error| format!("read {BROKER_OPERATIONS_PATH}: {error}"))?;
    let catalog: BrokerOperations = serde_json::from_str(&text)
        .map_err(|error| format!("parse {BROKER_OPERATIONS_PATH}: {error}"))?;
    if catalog.version != 1 {
        return Err(format!(
            "{BROKER_OPERATIONS_PATH}: unsupported catalog version {}",
            catalog.version
        ));
    }
    let mut values = Vec::new();
    for row in &catalog.rows {
        let Some(variant) = row.wire_variant.as_deref() else {
            continue;
        };
        if variant.is_empty()
            || !variant.bytes().all(|byte| byte.is_ascii_graphic())
            || values.iter().any(|value| value == variant)
        {
            return Err(format!(
                "{BROKER_OPERATIONS_PATH}: row {} does not carry a usable wire variant",
                row.operation
            ));
        }
        values.push(variant.to_owned());
    }
    if values.is_empty() {
        return Err(format!(
            "{BROKER_OPERATIONS_PATH}: no committed wire variants"
        ));
    }
    Ok(values)
}

/// The process-provider ids one consumer admits.
fn process_provider_ids(metric_label: Option<bool>) -> Vec<String> {
    PROCESS_PROVIDERS
        .iter()
        .filter(|provider| metric_label.is_none_or(|metric| provider.metric_label == metric))
        .map(|provider| provider.id.to_owned())
        .collect()
}

/// Render the CLI's surface catalog module.
fn surface_catalog_source() -> String {
    let mut source = String::from(HEADER);
    source.push_str(&string_slice(
        "RESOURCE_TYPES",
        &[
            "The resource types the CLI addresses, in registry order.",
            "",
            "The source of record is `V3_CONVERTED_RESOURCE_TYPES` in",
            "`d2b-contracts`, which the CLI does not link directly; the",
            "generator projects it entry for entry.",
        ],
        &V3_CONVERTED_RESOURCE_TYPES
            .iter()
            .map(|value| (*value).to_owned())
            .collect::<Vec<_>>(),
    ));
    source.push_str(&string_pair_slice(
        "TYPED_NOUNS",
        &["The typed nouns and the resource type each addresses."],
        TYPED_NOUNS,
    ));
    source.push_str(&string_pair_slice(
        "TYPED_VERB_TYPES",
        &["The typed verbs and the resource type each is available on."],
        TYPED_VERB_TYPES,
    ));
    source.push_str(&string_slice(
        "CONTROLLER_OWNED_TYPES",
        &["The resource types the controller owns: no operator authors one."],
        &CONTROLLER_OWNED_TYPES
            .iter()
            .map(|value| (*value).to_owned())
            .collect::<Vec<_>>(),
    ));
    source.push_str(&string_slice(
        "EXECUTION_TARGET_TYPES",
        &["The resource types that serve as an execution target."],
        &EXECUTION_TARGET_TYPES
            .iter()
            .map(|value| (*value).to_owned())
            .collect::<Vec<_>>(),
    ));
    source.push_str(&doc_lines(&[
        "The provider reference of a workload running without an isolation",
        "boundary.",
    ]));
    let _ = writeln!(
        source,
        "pub const UNSAFE_LOCAL_PROVIDER_REF: &str = \"{UNSAFE_LOCAL_PROVIDER_REF}\";"
    );
    source.push_str(&doc_lines(&[
        "The provider kind a no-isolation row carries.",
    ]));
    let _ = writeln!(
        source,
        "pub const UNSAFE_LOCAL_PROVIDER_KIND: &str = \"{UNSAFE_LOCAL_PROVIDER_KIND}\";"
    );
    source.push_str(&string_slice(
        "NO_ISOLATION_POSTURES",
        &["The postures that mean the row has no isolation boundary."],
        &NO_ISOLATION_POSTURES
            .iter()
            .map(|value| (*value).to_owned())
            .collect::<Vec<_>>(),
    ));
    source.push_str(&string_slice(
        "MUTATION_VERBS",
        &["The resource verbs that write an audit row, in contract order."],
        &resource_mutation_verbs(),
    ));
    source.push_str(&string_slice(
        "PROCESS_PROVIDERS",
        &["The process providers an audit record may name."],
        &process_provider_ids(None),
    ));
    source.push_str(&doc_lines(&[
        "The resource type a typed noun addresses.",
    ]));
    source.push_str(
        "pub fn typed_noun_type(noun: &str) -> Option<&'static str> {\n    \
         TYPED_NOUNS\n        .iter()\n        \
         .find_map(|(name, resource_type)| (*name == noun).then_some(*resource_type))\n}\n",
    );
    source.push_str(&doc_lines(&[
        "The resource type a typed verb is available on.",
    ]));
    source.push_str(
        "pub fn typed_verb_type(verb: &str) -> Option<&'static str> {\n    \
         TYPED_VERB_TYPES\n        .iter()\n        \
         .find_map(|(name, resource_type)| (*name == verb).then_some(*resource_type))\n}\n",
    );
    source.push_str(&doc_lines(&[
        "Whether the resource type is in the registry.",
    ]));
    source.push_str(
        "pub fn admits_resource_type(resource_type: &str) -> bool {\n    \
         RESOURCE_TYPES.contains(&resource_type)\n}\n",
    );
    source.push_str(&doc_lines(&["Whether the verb writes a resource row."]));
    source.push_str(
        "pub fn admits_mutation_verb(verb: &str) -> bool {\n    \
         MUTATION_VERBS.contains(&verb)\n}\n",
    );
    source.push_str(&doc_lines(&[
        "Whether the resource type is one the controller owns.",
    ]));
    source.push_str(
        "pub fn is_controller_owned(resource_type: &str) -> bool {\n    \
         CONTROLLER_OWNED_TYPES.contains(&resource_type)\n}\n",
    );
    source.push_str(&doc_lines(&[
        "Whether the resource type serves as an execution target.",
    ]));
    source.push_str(
        "pub fn is_execution_target(resource_type: &str) -> bool {\n    \
         EXECUTION_TARGET_TYPES.contains(&resource_type)\n}\n",
    );
    source.push_str(&doc_lines(&[
        "Whether the posture marks a row with no isolation boundary.",
    ]));
    source.push_str(
        "pub fn is_no_isolation_posture(posture: &str) -> bool {\n    \
         NO_ISOLATION_POSTURES.contains(&posture)\n}\n",
    );
    source.push_str(&doc_lines(&[
        "Whether the provider reference marks a no-isolation row.",
    ]));
    source.push_str(
        "pub fn is_unsafe_local_provider(reference: &str) -> bool {\n    \
         reference == UNSAFE_LOCAL_PROVIDER_REF\n}\n",
    );
    source.push_str(&doc_lines(&[
        "Whether the provider kind marks a no-isolation row.",
    ]));
    source.push_str(
        "pub fn is_unsafe_local_provider_kind(kind: &str) -> bool {\n    \
         kind == UNSAFE_LOCAL_PROVIDER_KIND\n}\n",
    );
    source.push_str(&string_slice(
        "NO_ISOLATION_TARGET_TYPES",
        &["The execution targets that run without an isolation boundary."],
        &NO_ISOLATION_TARGET_TYPES
            .iter()
            .map(|value| (*value).to_owned())
            .collect::<Vec<_>>(),
    ));
    source.push_str(&doc_lines(&[
        "Whether the execution target runs without an isolation boundary.",
    ]));
    source.push_str(
        "pub fn is_no_isolation_target(resource_type: &str) -> bool {\n    \
         NO_ISOLATION_TARGET_TYPES.contains(&resource_type)\n}\n",
    );
    source
}

/// Render the audit crate's catalog module.
fn audit_catalog_source() -> String {
    let mut source = String::from(HEADER);
    source.push_str(&string_slice(
        "RESOURCE_TYPES",
        &[
            "The resource types an audit record may name.",
            "",
            "The converted registry is projected in full, so a type the record",
            "classes can address is never missing from the vocabulary.",
        ],
        &audit_resource_types(),
    ));
    source.push_str(&string_slice(
        "MUTATION_VERBS",
        &["The resource verbs that write an audit row, in contract order."],
        &resource_mutation_verbs(),
    ));
    source.push_str(&string_slice(
        "PROCESS_PROVIDERS",
        &["The process providers a process effect record may name."],
        &process_provider_ids(None),
    ));
    source.push_str(&doc_lines(&[
        "Whether the resource type is in the registry.",
    ]));
    source.push_str(
        "pub fn admits_resource_type(resource_type: &str) -> bool {\n    \
         RESOURCE_TYPES.contains(&resource_type)\n}\n",
    );
    source.push_str(&doc_lines(&[
        "Whether the verb writes a resource row.",
    ]));
    source.push_str(
        "pub fn admits_mutation_verb(verb: &str) -> bool {\n    \
         MUTATION_VERBS.contains(&verb)\n}\n",
    );
    source
}

/// Render the provider contracts crate's telemetry catalog module.
fn telemetry_catalog_source(repo_root: &Path) -> Result<String, String> {
    let mut source = String::from(HEADER);
    source.push_str(&string_slice(
        "RESOURCE_TYPE_VALUES",
        &[
            "The resource type label domain, projected from the standard",
            "registry.",
            "",
            "The registry is projected in full, so a type the API or the store",
            "can carry is never missing from a metric label domain.",
        ],
        &metric_resource_types(),
    ));
    source.push_str(&string_slice(
        "API_VERBS",
        &["The API verb label domain, projected from the Role resource verbs."],
        &resource_verbs(),
    ));
    source.push_str(&string_slice(
        "PROCESS_PROVIDERS",
        &["The process provider label domain."],
        &process_provider_ids(Some(true)),
    ));
    source.push_str(&string_slice(
        "BROKER_OPERATION_VALUES",
        &[
            "The broker operation label domain: the committed operation rows'",
            "wire variants, in row order.",
            "",
            "The metric `op` label carries the wire request name, so the",
            "committed rows in `docs/reference/policy/broker-operations.json`",
            "are the authority this domain is projected from; a row the catalog",
            "retires leaves the domain with it.",
        ],
        &broker_operation_values(repo_root)?,
    ));
    Ok(source)
}

/// Render one generated directory's module file.
fn mod_source(module: &str, doc: &str) -> String {
    format!("{HEADER}\n//! {doc}\n\npub mod {module};\n")
}

/// The generated (path, content) pairs, in write order.
fn artifacts(repo_root: &Path) -> Result<Vec<(PathBuf, String)>, String> {
    Ok(vec![
        (
            PathBuf::from(CLI_OUT_DIR).join("surface_catalog.rs"),
            surface_catalog_source(),
        ),
        (
            PathBuf::from(CLI_OUT_DIR).join(MOD_FILE),
            mod_source(
                "surface_catalog",
                "The generated surface catalogs the CLI reads.",
            ),
        ),
        (
            PathBuf::from(AUDIT_OUT_DIR).join("audit_catalog.rs"),
            audit_catalog_source(),
        ),
        (
            PathBuf::from(AUDIT_OUT_DIR).join(MOD_FILE),
            mod_source(
                "audit_catalog",
                "The generated audit record catalogs the crate validates against.",
            ),
        ),
        (
            PathBuf::from(TELEMETRY_OUT_DIR).join("telemetry_catalog.rs"),
            telemetry_catalog_source(repo_root)?,
        ),
        (
            PathBuf::from(TELEMETRY_OUT_DIR).join(MOD_FILE),
            mod_source(
                "telemetry_catalog",
                "The generated telemetry label catalogs the crate validates against.",
            ),
        ),
    ])
}

/// Run `gen-layer-catalogs [--check|--write]`.
///
/// Writing is the default. `--check` compares every committed artifact
/// byte-for-byte against the generator output and fails on the first
/// difference, and either way the returned paths name what was written or
/// checked, so a caller cannot read silence as currency.
#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
pub fn run_cli(repo_root: &std::path::Path, args: &[String]) -> Result<Vec<PathBuf>, String> {
    let check = match args {
        [] => false,
        [flag] if flag == "--check" => true,
        [flag] if flag == "--write" => false,
        _ => {
            return Err(
                "usage: cargo run -p xtask -- gen-layer-catalogs [--check|--write]".to_owned(),
            );
        }
    };
    let mut written = Vec::new();
    for (relative, content) in artifacts(repo_root)? {
        let path = repo_root.join(&relative);
        if check {
            let committed = fs::read_to_string(&path).map_err(|error| {
                format!(
                    "{}: unreadable generated artifact: {error}",
                    relative.display()
                )
            })?;
            if committed != content {
                return Err(format!(
                    "{}: committed artifact differs from the generator output",
                    relative.display()
                ));
            }
        } else {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|error| format!("{}: {error}", relative.display()))?;
            }
            fs::write(&path, content)
                .map_err(|error| format!("{}: {error}", relative.display()))?;
        }
        written.push(path);
    }
    Ok(written)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The audit vocabulary carries the whole registry: a converted type the
    /// record classes can address is never missing from the list.
    #[test]
    fn audit_vocabulary_covers_the_registry() {
        let types = audit_resource_types();
        for resource_type in V3_CONVERTED_RESOURCE_TYPES {
            assert!(types.iter().any(|value| value == resource_type));
        }
        assert!(types.iter().any(|value| value == VENDOR_TYPE));
        assert_eq!(types.len(), V3_CONVERTED_RESOURCE_TYPES.len() + 1);
    }

    /// The metric label domain carries the whole standard registry.
    #[test]
    fn metric_vocabulary_covers_the_standard_registry() {
        let types = metric_resource_types();
        for resource_type in STANDARD_RESOURCE_TYPES {
            assert!(types.iter().any(|value| value == resource_type));
        }
        assert_eq!(types.len(), STANDARD_RESOURCE_TYPES.len() + 1);
    }

    /// The mutation verbs are the Role resource verbs minus the read-only
    /// three, so neither list can grow a verb the contract does not declare.
    #[test]
    fn mutation_verbs_are_the_role_verbs_minus_the_read_only_three() {
        let mutating = resource_mutation_verbs();
        assert_eq!(mutating.len(), RoleResourceVerb::ALL.len() - 3);
        for spelling in resource_verbs() {
            let read_only = READ_ONLY_VERBS
                .iter()
                .map(verb_spelling)
                .any(|verb| verb == spelling);
            assert_eq!(mutating.contains(&spelling), !read_only, "{spelling}");
        }
    }

    /// The typed surface entries name declared resource types.
    #[test]
    fn typed_surface_entries_name_declared_types() {
        for (noun, resource_type) in TYPED_NOUNS.iter().chain(TYPED_VERB_TYPES) {
            assert!(
                V3_CONVERTED_RESOURCE_TYPES.contains(resource_type),
                "{noun}: {resource_type} is not a converted resource type"
            );
        }
        assert!(!UNSAFE_LOCAL_PROVIDER_REF.is_empty());
        assert!(!UNSAFE_LOCAL_PROVIDER_KIND.is_empty());
        assert!(!CONTROLLER_OWNED_TYPES.is_empty());
        assert!(!NO_ISOLATION_TARGET_TYPES.is_empty());
        assert!(!EXECUTION_TARGET_TYPES.is_empty());
        assert!(!NO_ISOLATION_POSTURES.is_empty());
    }

    /// The process provider vocabulary projects both consumer domains.
    #[test]
    fn process_provider_domains_project_from_one_vocabulary() {
        assert_eq!(process_provider_ids(None).len(), PROCESS_PROVIDERS.len());
        assert_eq!(
            process_provider_ids(Some(true)),
            vec!["minijail".to_owned(), "systemd".to_owned()]
        );
    }

    /// The broker operation domain is the committed rows' wire variants: a row
    /// that gains, retires, or renames a wire variant moves the domain, and the
    /// drift target then refuses the stale generated copy.
    #[test]
    #[allow(clippy::disallowed_methods, reason = "cfg(test) helper")]
    fn broker_operation_domain_projects_the_committed_rows() {
        let root = crate::repo_root().expect("repository root");
        let values = broker_operation_values(root).expect("committed broker rows");
        let text = fs::read_to_string(root.join(BROKER_OPERATIONS_PATH)).expect("row catalog");
        let catalog: BrokerOperations = serde_json::from_str(&text).expect("row catalog parses");
        let expected = catalog
            .rows
            .iter()
            .filter_map(|row| row.wire_variant.clone())
            .collect::<Vec<_>>();
        assert_eq!(values, expected);
        assert!(
            values.iter().any(|value| value == "UsbipBind"),
            "a committed wire operation is in the domain"
        );
        // U10 retired the process-family wire variants: their rows stay
        // committed (audit history) but declare no wire variant, so the
        // domain - the wire request names nothing can emit as the metric
        // `op` label - leaves them with the wire enum.
        assert!(
            !values.iter().any(|value| value == "SpawnRunner"),
            "a row whose wire variant was retired is not in the domain"
        );
        assert!(
            !values.iter().any(|value| value == "vmStart"),
            "a name no committed row declares is not in the domain"
        );
    }
}
