//! The generated v3 converted-resource-type catalog.
//!
//! `gen-resource-type-catalog` projects the authority list
//! `d2b_contracts::identity::V3_CONVERTED_RESOURCE_TYPES` into the committed
//! crate-local catalog under `packages/d2b-contracts/src/generated/`. The
//! plane's startup cross-check compares the driver registry's registered
//! types against that artifact, so the artifact cannot drift from the list
//! the rest of the tree already fences against: the emitted module carries its
//! own fence against the authority list, and the `--check` form compares the
//! committed bytes against the generator output.
//!
//! Until the per-crate manifests own their declarations, that list stays the
//! source of record; nothing here restates a type name, so the catalog is a
//! projection and not a second authority.

use std::{
    fs,
    path::{Path, PathBuf},
};

use d2b_contracts::identity::V3_CONVERTED_RESOURCE_TYPES;

/// The crate-local directory the artifacts are committed under.
const OUT_DIR: &str = "packages/d2b-contracts/src/generated";

/// The generated catalog module.
const CATALOG_FILE: &str = "resource_type_catalog.rs";

/// The generated directory's module file.
const MOD_FILE: &str = "mod.rs";

/// The shared byte-exact header every generated artifact carries.
const HEADER: &str = concat!(
    "// @generated by `cargo run -p xtask -- gen-resource-type-catalog`.\n",
    "// Do not hand-edit: the generator's `--check` form compares this file\n",
    "// byte-for-byte against its output.\n",
);

/// Render the generated catalog module.
fn catalog_source() -> String {
    let mut source = String::from(HEADER);
    source.push_str(
        "\n/// The v3 converted resource types, in authority order.\n\
         ///\n\
         /// The source of record is\n\
         /// [`crate::identity::V3_CONVERTED_RESOURCE_TYPES`], which the\n\
         /// generator projects entry for entry; the fence below fails the\n\
         /// moment the two disagree.\n",
    );
    source.push_str(&format!(
        "pub const CONVERTED_RESOURCE_TYPES: [&str; {}] = [\n",
        V3_CONVERTED_RESOURCE_TYPES.len()
    ));
    for resource_type in V3_CONVERTED_RESOURCE_TYPES {
        source.push_str(&format!("    \"{resource_type}\",\n"));
    }
    source.push_str("];\n");
    source.push_str(
        "\n#[cfg(test)]\n\
         mod tests {\n\
         \x20   use super::CONVERTED_RESOURCE_TYPES;\n\
         \x20   use crate::identity::V3_CONVERTED_RESOURCE_TYPES;\n\
         \n\
         \x20   /// The generated catalog is the authority list entry for entry:\n\
         \x20   /// the generator projects that list, so a change that is not\n\
         \x20   /// regenerated cannot exist, and a generated change that does not\n\
         \x20   /// move the list fails here.\n\
         \x20   #[test]\n\
         \x20   fn generated_catalog_matches_the_authority_list() {\n\
         \x20       assert_eq!(\n\
         \x20           CONVERTED_RESOURCE_TYPES.len(),\n\
         \x20           V3_CONVERTED_RESOURCE_TYPES.len()\n\
         \x20       );\n\
         \x20       for (generated, authority) in\n\
         \x20           CONVERTED_RESOURCE_TYPES.iter().zip(V3_CONVERTED_RESOURCE_TYPES)\n\
         \x20       {\n\
         \x20           assert_eq!(generated, &authority);\n\
         \x20       }\n\
         \x20   }\n\
         }\n",
    );
    source
}

/// Render the generated directory's module file.
fn mod_source() -> String {
    format!("{HEADER}\n//! The generated crate-local catalogs.\n\npub mod resource_type_catalog;\n")
}

/// The generated (file name, content) pairs, in write order.
fn artifacts() -> [(&'static str, String); 2] {
    [(CATALOG_FILE, catalog_source()), (MOD_FILE, mod_source())]
}

/// Run `gen-resource-type-catalog [--check|--write]`.
///
/// Writing is the default. `--check` compares every committed artifact
/// byte-for-byte against the generator output and fails on the first
/// difference, and either way the returned paths name what was written or
/// checked, so a caller cannot read silence as currency.
pub fn run_cli(repo_root: &Path, args: &[String]) -> Result<Vec<PathBuf>, String> {
    let check = match args {
        [] => false,
        [flag] if flag == "--check" => true,
        [flag] if flag == "--write" => false,
        _ => {
            return Err(
                "usage: cargo run -p xtask -- gen-resource-type-catalog [--check|--write]"
                    .to_owned(),
            );
        }
    };
    let dir = repo_root.join(OUT_DIR);
    let mut paths = Vec::with_capacity(artifacts().len());
    if check {
        for (name, expected) in artifacts() {
            let path = dir.join(name);
            let committed = fs::read_to_string(&path)
                .map_err(|error| format!("{} is not committed: {error}", path.display()))?;
            if committed != expected {
                return Err(format!(
                    "{} drifted from the generator output; run \
                     `cargo run -p xtask -- gen-resource-type-catalog`",
                    path.display()
                ));
            }
            paths.push(path);
        }
    } else {
        fs::create_dir_all(&dir).map_err(|error| format!("{}: {error}", dir.display()))?;
        for (name, source) in artifacts() {
            let path = dir.join(name);
            fs::write(&path, source).map_err(|error| format!("{}: {error}", path.display()))?;
            paths.push(path);
        }
    }
    Ok(paths)
}

#[cfg(test)]
mod tests {
    use super::{catalog_source, mod_source, CATALOG_FILE, MOD_FILE};

    /// The catalog projects the authority list in order, one quoted entry per
    /// line, so the artifact's list-shaped body stays byte-stable.
    #[test]
    fn catalog_source_projects_the_authority_list() {
        let source = catalog_source();
        assert!(source.starts_with("// @generated"), "generated header first");
        assert!(source.contains("\npub const CONVERTED_RESOURCE_TYPES: [&str; 33] = [\n"));
        let mut expected_body = String::new();
        for resource_type in d2b_contracts::identity::V3_CONVERTED_RESOURCE_TYPES {
            expected_body.push_str(&format!("    \"{resource_type}\",\n"));
        }
        assert!(source.contains(&expected_body), "authority list projected verbatim");
        assert!(source.ends_with("}\n"));
    }

    /// The module file registers exactly the catalog module.
    #[test]
    fn mod_source_registers_the_catalog_module() {
        let source = mod_source();
        assert!(source.starts_with("// @generated"));
        assert!(source.ends_with("\npub mod resource_type_catalog;\n"));
        assert_eq!(CATALOG_FILE, "resource_type_catalog.rs");
        assert_eq!(MOD_FILE, "mod.rs");
    }
}
