//! The Nix closed-inventory generator.
//!
//! `gen-nix-inventories` emits the Nix modules whose contents are closed
//! inventories - lists a consumer must not restate:
//!
//! - `nixos-modules/generated/provider-projections.nix` - the Provider
//!   identities that publish a Nix resource projection, in the order the
//!   compiler folds them, and the `d2b._resourceCompiler` option key each
//!   projection lands on.
//! - `nixos-modules/generated/resource-inventories.nix` - the zone-control
//!   type set, the Role/RoleBinding vocabularies, the shared resource-envelope
//!   field vocabularies, the committed schema pointers, and the qualified
//!   types the compiler schema farm carries beyond the standard and semantic
//!   registries.
//! - `nixos-modules/host-users.nix` - the host accounts the committed
//!   principal allocation names.
//! - `nixos-modules/generated/process-role-providers.nix` and
//!   `packages/d2b-core/src/generated/process_roles.rs` - the process
//!   family's declared role-to-provider map and `ProcessRole` vocabulary
//!   (U4), rendered from the per-crate `resource-types.json` declarations by
//!   the resource-type authority and emitted here too so the standalone
//!   command and the layout check stay byte-identical.
//!
//! Every list is either projected from a committed authority (the standard
//! resource registry in `d2b-contracts`, the Role/RoleBinding contracts, the
//! Provider matrix, the committed schema artifacts, the principal
//! allocation) or declared by one table here. Nothing is restated in Nix
//! beside a generated copy, and each emitted file is compared byte-for-byte
//! against this generator by its drift target.

use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use d2b_contracts::identity::STANDARD_RESOURCE_TYPES;
#[cfg(test)]
use d2b_contracts_provider::v3::projection::PrivatePlanProjection;
use d2b_contracts_provider::v3::semantic_services::{SemanticRole, catalog};
use d2b_contracts_zone_session::v3::{BINDABLE_SUBJECT_TYPES, RoleResourceVerb, RoleSessionVerb};
use serde_json::Value;

/// The generated Provider projection inventory.
const PROVIDER_PROJECTIONS_OUT: &str = "nixos-modules/generated/provider-projections.nix";
/// The generated resource vocabulary inventory.
const RESOURCE_INVENTORIES_OUT: &str = "nixos-modules/generated/resource-inventories.nix";
/// The generated host account module.
const HOST_USERS_OUT: &str = "nixos-modules/host-users.nix";
/// The committed principal allocation document.
const PRINCIPAL_ALLOCATION: &str = "docs/reference/policy/principal-allocation.json";
/// The committed schema artifacts.
const SCHEMA_DIR: &str = "docs/reference/schemas/v3";
/// The Core schema namespace every standard ResourceType's artifact uses.
const CORE_NAMESPACE: &str = "core.d2bus.org";

const GENERATED_HEADER: &str = "# Generated by `bazel run //packages/xtask:xtask -- gen-nix-inventories`.\n\
# Do not hand-edit: `make test-drift` compares this file byte-for-byte\n\
# against the generator output.\n";

/// The Provider identities that publish a Nix resource projection, in the
/// order the compiler folds them into a Zone bundle.
///
/// The set is closed deliberately: a projection a consumer cannot name here
/// has no bundle owner, so an unlisted projection is a bundle error rather
/// than an implicit fallback. Every entry is a row of the closed Provider
/// matrix, and every one of them still projects Zone rows: a Provider whose
/// only projection was a worker template no signed artifact pinned leaves
/// this list rather than contributing an always-disabled projection.
const PROVIDER_PROJECTION_OWNERS: &[&str] = &[
    "volume-local",
    "volume-virtiofs",
    "device-gpu",
    "device-usbip",
    "device-security-key",
    "device-tpm",
    "display-wayland",
    "audio-pipewire",
    "clipboard-wayland",
    "notification-desktop",
    "activation-nixos",
    "shell-terminal",
    "runtime-qemu-media",
    "runtime-azure-container-apps",
    "runtime-azure-virtual-machine",
];

/// The ResourceTypes the zone-control projection owns.
///
/// The projection validates these types' closed spec keys itself, so the set
/// is a property of that projection rather than of the standard registry: a
/// type that moves out of the zone-control projection moves out of this list.
const CONTROL_TYPES: &[&str] = &[
    "Zone",
    "ZoneLink",
    "Provider",
    "Role",
    "RoleBinding",
    "Quota",
    "EmergencyPolicy",
];

/// The ResourceTypes a RoleBinding may bind relay authority on.
///
/// Relay authority is a ZoneLink transport grant: the session verb it carries
/// is meaningful only where a Zone boundary is being relayed.
const RELAY_BOUND_TYPES: &[&str] = &["ZoneLink"];

/// The runtime-managed resource fields no author may declare.
const RUNTIME_FIELDS: &[&str] = &[
    "uid",
    "revision",
    "generation",
    "finalizers",
    "managedBy",
    "configurationGeneration",
    "timestamp",
    "createdAt",
    "updatedAt",
    "status",
];

/// The top-level fields of one authored resource.
const RESOURCE_FIELDS: &[&str] = &["type", "metadata", "spec"];
/// The fields of one authored resource's metadata envelope.
const METADATA_FIELDS: &[&str] = &["ownerRef", "labels", "annotations"];
/// The fields of one authored resource's telemetry block.
const TELEMETRY_FIELDS: &[&str] = &["emitter"];
/// The fields of one authored telemetry emitter block.
const EMITTER_FIELDS: &[&str] = &["ringCapacityBytes"];
/// The fields of one authored resource's audit block.
const AUDIT_FIELDS: &[&str] = &["retentionDays", "maxSegmentBytes"];

/// The provider-owned qualified types the compiler schema farm carries beyond
/// the standard registry and the semantic catalog.
///
/// Farm membership is a schema-availability decision, not a registry: a type
/// enters the farm when its signed Provider schema is committed here, so the
/// list stays explicit rather than becoming "every qualified schema on disk".
const PROVIDER_FARM_TYPES: &[&str] = &[
    "display-wayland.d2bus.org.WaylandPolicy",
    "display-wayland.d2bus.org.WaylandSession",
];

/// One host account the generated module materializes.
///
/// The numeric identity is never written here: it comes from the committed
/// principal allocation, so an account cannot pin a colliding or
/// host-specific id. The description is part of the account's operator-visible
/// shape and is therefore declared rather than derived from the name.
struct HostAccountRow {
    principal: &'static str,
    description: &'static str,
}

/// The host accounts `host-users.nix` declares.
const HOST_ACCOUNT_ROWS: &[HostAccountRow] = &[HostAccountRow {
    principal: "d2b-zonert",
    description: "d2b Zone resource-store owner",
}];

/// The allocated principals whose account another module owns.
///
/// The daemon principal's account belongs to the modules that run the daemon
/// (`host-daemon.nix`, `guest-broker.nix`); the allocation pins its id so the
/// layout owner and the broker agree, and this module deliberately does not
/// declare a second account for it.
const DEFERRED_ACCOUNT_PRINCIPALS: &[&str] = &["d2bd"];

/// One allocated principal identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct PrincipalId {
    uid: u32,
    gid: u32,
}

fn render_error(message: impl Into<String>) -> Box<dyn std::error::Error> {
    message.into().into()
}

/// A Nix double-quoted string.
fn nix_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for character in value.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '$' => out.push_str("\\$"),
            _ => out.push(character),
        }
    }
    out.push('"');
    out
}

/// A Nix list of strings, one entry per line.
fn nix_string_list<'a>(values: impl IntoIterator<Item = &'a str>, indent: usize) -> String {
    let padding = " ".repeat(indent);
    let mut out = String::from("[\n");
    for value in values {
        out.push_str(&format!("{padding}  {}\n", nix_string(value)));
    }
    out.push_str(&format!("{padding}]"));
    out
}

/// The camel-case `d2b._resourceCompiler` key one Provider projection lands on.
fn projection_key(owner: &str) -> String {
    let mut key = String::from("providerProjection");
    for segment in owner.split('-') {
        let mut characters = segment.chars();
        if let Some(first) = characters.next() {
            key.extend(first.to_uppercase());
            key.push_str(characters.as_str());
        }
    }
    key
}

/// The kebab-case spelling of one role vocabulary entry.
fn verb_spelling<T: serde::Serialize>(verb: &T) -> String {
    serde_json::to_value(verb)
        .expect("a contract verb serializes")
        .as_str()
        .expect("a contract verb is a string")
        .to_owned()
}

/// The subject vocabulary, projected from the RoleBinding contract.
fn subject_types() -> Vec<&'static str> {
    BINDABLE_SUBJECT_TYPES.to_vec()
}

/// The resource verb vocabulary, projected from the Role contract.
fn resource_verbs() -> Vec<String> {
    RoleResourceVerb::ALL.iter().map(verb_spelling).collect()
}

/// The session verb vocabulary, projected from the Role contract.
fn session_verbs() -> Vec<String> {
    RoleSessionVerb::ALL.iter().map(verb_spelling).collect()
}

/// The committed schema file of one standard ResourceType.
fn core_schema_file(resource_type: &str) -> String {
    format!("{CORE_NAMESPACE}_{resource_type}.schema.json")
}

/// Split one qualified ResourceType into its schema namespace and local name.
///
/// A qualified type is `<namespace>.d2bus.org.<Name>`; the committed artifact
/// is `<namespace>.d2bus.org_<Name>.schema.json`.
fn qualified_schema_parts(
    resource_type: &str,
) -> Result<(&str, &str), Box<dyn std::error::Error>> {
    let (namespace, name) = resource_type
        .rsplit_once('.')
        .ok_or_else(|| render_error(format!("{resource_type}: not a qualified type")))?;
    if !namespace.ends_with(".d2bus.org") || name.is_empty() {
        return Err(render_error(format!(
            "{resource_type}: not a `<namespace>.d2bus.org.<Name>` type"
        )));
    }
    Ok((namespace, name))
}

/// The committed schema directory's file names.
#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
fn committed_schema_files(repo_root: &Path) -> Result<BTreeSet<String>, Box<dyn std::error::Error>> {
    let dir = repo_root.join(SCHEMA_DIR);
    let mut files = BTreeSet::new();
    for entry in
        fs::read_dir(&dir).map_err(|error| render_error(format!("read {}: {error}", dir.display())))?
    {
        let entry =
            entry.map_err(|error| render_error(format!("read {}: {error}", dir.display())))?;
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.ends_with(".schema.json") {
            files.insert(name);
        }
    }
    if files.is_empty() {
        return Err(render_error(format!(
            "{}: no committed schemas",
            dir.display()
        )));
    }
    Ok(files)
}

/// The semantic projection schema pointers, keyed by service type.
fn projection_schema_pointers(
    schemas: &BTreeSet<String>,
) -> Result<BTreeMap<String, String>, Box<dyn std::error::Error>> {
    let mut pointers = BTreeMap::new();
    for contract in catalog() {
        if contract.service().role() != SemanticRole::Service {
            return Err(render_error(
                "a semantic catalog entry names its service type first",
            ));
        }
        let service_type = contract.service().resource_type().as_str().to_owned();
        let (namespace, _) = qualified_schema_parts(&service_type)?;
        let file = format!("{namespace}_projection_spec.schema.json");
        if !schemas.contains(&file) {
            return Err(render_error(format!(
                "{service_type}: committed projection schema {file} is missing"
            )));
        }
        pointers.insert(service_type, file);
    }
    if pointers.is_empty() {
        return Err(render_error("the semantic catalog is empty"));
    }
    Ok(pointers)
}

/// Every standard ResourceType's committed schema file, keyed by type.
///
/// The standard set is passed in rather than read from
/// `identity::STANDARD_RESOURCE_TYPES` so the resource-type authority can
/// drive the same render from the per-crate `resource-types.json`
/// declarations; `gen-nix-inventories` passes the committed registry.
fn core_schema_pointers<S: AsRef<str> + std::fmt::Display>(
    schemas: &BTreeSet<String>,
    standard: &[S],
) -> Result<BTreeMap<String, String>, Box<dyn std::error::Error>> {
    let mut pointers = BTreeMap::new();
    for resource_type in standard {
        let file = core_schema_file(resource_type.as_ref());
        if !schemas.contains(&file) {
            return Err(render_error(format!(
                "{resource_type}: committed schema {file} is missing"
            )));
        }
        pointers.insert(resource_type.as_ref().to_string(), file);
    }
    Ok(pointers)
}

/// Every farm type's committed schema file, in declared order.
fn provider_farm_pointers(
    schemas: &BTreeSet<String>,
) -> Result<Vec<(&'static str, String)>, Box<dyn std::error::Error>> {
    let mut pointers = Vec::with_capacity(PROVIDER_FARM_TYPES.len());
    for resource_type in PROVIDER_FARM_TYPES {
        let (namespace, name) = qualified_schema_parts(resource_type)?;
        let file = format!("{namespace}_{name}.schema.json");
        if !schemas.contains(&file) {
            return Err(render_error(format!(
                "{resource_type}: committed schema {file} is missing"
            )));
        }
        pointers.push((*resource_type, file));
    }
    Ok(pointers)
}

/// Parse the committed principal allocation document.
#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
fn principal_allocation(
    repo_root: &Path,
) -> Result<BTreeMap<String, PrincipalId>, Box<dyn std::error::Error>> {
    let path = repo_root.join(PRINCIPAL_ALLOCATION);
    let text = fs::read_to_string(&path)
        .map_err(|error| render_error(format!("read {PRINCIPAL_ALLOCATION}: {error}")))?;
    let value: Value = serde_json::from_str(&text)
        .map_err(|error| render_error(format!("parse {PRINCIPAL_ALLOCATION}: {error}")))?;
    if value.get("version").and_then(Value::as_u64) != Some(1) {
        return Err(render_error(format!(
            "{PRINCIPAL_ALLOCATION}: unsupported version"
        )));
    }
    let entries = value
        .get("principals")
        .and_then(Value::as_object)
        .ok_or_else(|| render_error(format!("{PRINCIPAL_ALLOCATION}: no principals")))?;
    if entries.is_empty() {
        return Err(render_error(format!(
            "{PRINCIPAL_ALLOCATION}: no allocated principals"
        )));
    }
    let mut allocation = BTreeMap::new();
    let mut seen: BTreeMap<u32, String> = BTreeMap::new();
    for (name, entry) in entries {
        if !valid_principal_name(name) {
            return Err(render_error(format!(
                "{PRINCIPAL_ALLOCATION}: invalid principal name {name}"
            )));
        }
        let uid = entry
            .get("uid")
            .and_then(Value::as_u64)
            .and_then(|uid| u32::try_from(uid).ok())
            .filter(|uid| *uid != 0)
            .ok_or_else(|| render_error(format!("{PRINCIPAL_ALLOCATION}: {name} has no uid")))?;
        let gid = entry
            .get("gid")
            .and_then(Value::as_u64)
            .and_then(|gid| u32::try_from(gid).ok())
            .filter(|gid| *gid != 0)
            .ok_or_else(|| render_error(format!("{PRINCIPAL_ALLOCATION}: {name} has no gid")))?;
        if let Some(existing) = seen.insert(uid, name.clone())
            && existing != *name
        {
            return Err(render_error(format!(
                "{PRINCIPAL_ALLOCATION}: {name} reuses uid {uid} from {existing}"
            )));
        }
        allocation.insert(name.clone(), PrincipalId { uid, gid });
    }
    Ok(allocation)
}

/// Principal name grammar, mirroring the daemon's allocation loader.
fn valid_principal_name(name: &str) -> bool {
    let mut characters = name.chars();
    let Some(first) = characters.next() else {
        return false;
    };
    name.len() <= 63
        && first.is_ascii_lowercase()
        && characters.all(|character| {
            character.is_ascii_lowercase() || character.is_ascii_digit() || character == '-'
        })
}

#[allow(clippy::disallowed_methods, reason = "CLI-only path")]
fn write(
    repo_root: &Path,
    relative: &str,
    contents: String,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let path = repo_root.join(relative);
    fs::write(&path, contents).map_err(|error| render_error(format!("write {relative}: {error}")))?;
    Ok(path)
}

/// Render the Provider projection inventory.
fn provider_projections_module() -> String {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str(
        "#\n\
         # The Provider identities that publish a Nix resource projection, in the\n\
         # order the compiler folds them into a Zone bundle, and the\n\
         # `d2b._resourceCompiler` option key each projection lands on. The list is\n\
         # closed: a projection a consumer cannot name here has no bundle owner.\n",
    );
    out.push_str("{\n");
    out.push_str("  owners = ");
    out.push_str(&nix_string_list(
        PROVIDER_PROJECTION_OWNERS.iter().copied(),
        2,
    ));
    out.push_str(";\n\n");
    out.push_str("  keys = {\n");
    for owner in PROVIDER_PROJECTION_OWNERS {
        out.push_str(&format!(
            "    {} = {};\n",
            nix_string(owner),
            nix_string(&projection_key(owner))
        ));
    }
    out.push_str("  };\n}\n");
    out
}

/// Render the resource vocabulary inventory.
///
/// `pub(crate)` so the resource-type authority (`resource_type_authority.rs`)
/// drives the same render from the per-crate declarations, keeping one table
/// authority per vocabulary.
pub(crate) fn resource_inventories_module<S: AsRef<str> + std::fmt::Display>(
    repo_root: &Path,
    standard: &[S],
) -> Result<String, Box<dyn std::error::Error>> {
    let schemas = committed_schema_files(repo_root)?;
    let core = core_schema_pointers(&schemas, standard)?;
    let projections = projection_schema_pointers(&schemas)?;
    let farm = provider_farm_pointers(&schemas)?;
    let resource_verbs = resource_verbs();
    let session_verbs = session_verbs();

    let mut out = String::from(GENERATED_HEADER);
    out.push_str(
        "#\n\
         # The closed resource vocabularies the Nix authoring surface validates\n\
         # against: the zone-control projection's type set, the Role and RoleBinding\n\
         # vocabularies, the shared resource-envelope field lists, the committed\n\
         # schema pointers, and the qualified types the compiler schema farm\n\
         # carries.\n",
    );
    out.push_str("{\n");
    out.push_str("  # The ResourceTypes the zone-control projection owns.\n");
    out.push_str("  controlTypes = ");
    out.push_str(&nix_string_list(CONTROL_TYPES.iter().copied(), 2));
    out.push_str(";\n\n");
    out.push_str("  # The subject vocabulary a RoleBinding may name.\n");
    out.push_str("  subjectTypes = ");
    out.push_str(&nix_string_list(subject_types(), 2));
    out.push_str(";\n\n");
    out.push_str("  # The ResourceTypes a RoleBinding may bind relay authority on.\n");
    out.push_str("  relayBoundTypes = ");
    out.push_str(&nix_string_list(RELAY_BOUND_TYPES.iter().copied(), 2));
    out.push_str(";\n\n");
    out.push_str("  # The Role rule verbs, from the Role contract.\n");
    out.push_str("  resourceVerbs = ");
    out.push_str(&nix_string_list(
        resource_verbs.iter().map(String::as_str),
        2,
    ));
    out.push_str(";\n\n");
    out.push_str("  # The ComponentSession verbs, from the Role contract.\n");
    out.push_str("  sessionVerbs = ");
    out.push_str(&nix_string_list(
        session_verbs.iter().map(String::as_str),
        2,
    ));
    out.push_str(";\n\n");
    out.push_str("  # Runtime-managed fields no authored resource may carry.\n");
    out.push_str("  runtimeFields = ");
    out.push_str(&nix_string_list(RUNTIME_FIELDS.iter().copied(), 2));
    out.push_str(";\n\n");
    out.push_str("  # The top-level fields of one authored resource.\n");
    out.push_str(&format!(
        "  resourceFields = {};\n",
        nix_string_list(RESOURCE_FIELDS.iter().copied(), 2)
    ));
    out.push_str(&format!(
        "  metadataFields = {};\n",
        nix_string_list(METADATA_FIELDS.iter().copied(), 2)
    ));
    out.push_str(&format!(
        "  telemetryFields = {};\n",
        nix_string_list(TELEMETRY_FIELDS.iter().copied(), 2)
    ));
    out.push_str(&format!(
        "  emitterFields = {};\n",
        nix_string_list(EMITTER_FIELDS.iter().copied(), 2)
    ));
    out.push_str(&format!(
        "  auditFields = {};\n",
        nix_string_list(AUDIT_FIELDS.iter().copied(), 2)
    ));

    out.push_str("\n  # Standard ResourceType -> its committed schema artifact.\n");
    out.push_str("  coreSchemaPointers = {\n");
    for (resource_type, file) in &core {
        out.push_str(&format!(
            "    {} = {};\n",
            nix_string(resource_type),
            nix_string(file)
        ));
    }
    out.push_str("  };\n\n");
    out.push_str("  # Semantic service type -> its committed projection schema artifact.\n");
    out.push_str("  projectionSchemaPointers = {\n");
    for (service_type, file) in &projections {
        out.push_str(&format!(
            "    {} = {};\n",
            nix_string(service_type),
            nix_string(file)
        ));
    }
    out.push_str("  };\n\n");
    out.push_str(
        "  # Qualified types the compiler schema farm carries beyond the standard\n\
         # registry and the semantic catalog.\n",
    );
    out.push_str("  providerFarmTypes = [\n");
    for (resource_type, file) in &farm {
        out.push_str("    {\n");
        out.push_str(&format!("      type = {};\n", nix_string(resource_type)));
        out.push_str(&format!("      schema = {};\n", nix_string(file)));
        out.push_str("    }\n");
    }
    out.push_str("  ];\n}\n");
    Ok(out)
}

/// Render the host account module from the committed principal allocation.
fn host_users_module(
    allocation: &BTreeMap<String, PrincipalId>,
) -> Result<String, Box<dyn std::error::Error>> {
    for row in HOST_ACCOUNT_ROWS {
        if !allocation.contains_key(row.principal) {
            return Err(render_error(format!(
                "{PRINCIPAL_ALLOCATION}: host account principal {} is not allocated",
                row.principal
            )));
        }
    }
    for principal in DEFERRED_ACCOUNT_PRINCIPALS {
        if !allocation.contains_key(*principal) {
            return Err(render_error(format!(
                "{PRINCIPAL_ALLOCATION}: deferred principal {principal} is not allocated"
            )));
        }
    }

    let mut out = String::from(GENERATED_HEADER);
    out.push_str(&format!(
        "#\n\
         # The host accounts and groups the committed principal allocation names\n\
         # (`{PRINCIPAL_ALLOCATION}`). Numeric identity comes from\n\
         # the allocation, so an account cannot pin a colliding or host-specific id\n\
         # and a re-seed cannot renumber a live principal.\n\
         #\n\
         # The template-bound row accounts are not in the allocation: their\n\
         # names are derived per Zone from the same trusted Zone rows\n\
         # `d2b-core`'s `template_account` composes them from\n\
         # (`d2bLib.templateWorkerAccounts`), so they stay config-derived here.\n\
         {{ config, lib, ... }}:\n\n\
         let\n\
         \x20 cfg = config.d2b;\n\
         \x20 d2bLib = import ./lib.nix {{ inherit lib; }};\n\n\
         \x20 # The allocated principals this module materializes.\n\
         \x20 accountRows = [\n",
    ));
    for row in HOST_ACCOUNT_ROWS {
        let id = allocation
            .get(row.principal)
            .expect("host account rows were checked against the allocation");
        out.push_str("    {\n");
        out.push_str(&format!("      name = {};\n", nix_string(row.principal)));
        out.push_str(&format!("      uid = {};\n", id.uid));
        out.push_str(&format!("      gid = {};\n", id.gid));
        out.push_str(&format!(
            "      description = {};\n",
            nix_string(row.description)
        ));
        out.push_str("    }\n");
    }
    out.push_str("  ];\n\n");
    out.push_str(
        "\x20 # The allocated principals whose account another module owns: the\n\
         \x20 # allocation pins their ids, the daemon and guest-broker modules declare\n\
         \x20 # the accounts, and this module must not declare a second one.\n\
         \x20 deferredPrincipalIds = {\n",
    );
    for principal in DEFERRED_ACCOUNT_PRINCIPALS {
        let id = allocation
            .get(*principal)
            .expect("deferred principals were checked against the allocation");
        out.push_str(&format!(
            "    {} = {{ uid = {}; gid = {}; }};\n",
            nix_string(principal),
            id.uid,
            id.gid
        ));
    }
    out.push_str(
        "  };\n\n\
         \x20 # The host lifecycle users the site declares: the accounts exist outside\n\
         \x20 # this module, membership of the `d2b` admission group is what it grants.\n\
         \x20 lifecycleUsers = lib.unique (cfg.site.adminUsers ++ cfg.site.launcherUsers);\n\
         \x20 # The accounts every template-bound row class runs as, derived per Zone\n\
         \x20 # from the same trusted Zone rows `d2b-core`'s `template_account`\n\
         \x20 # composes its names from.\n\
         \x20 templateAccounts = d2bLib.templateWorkerAccounts cfg;\n\
         \x20 rows = accountRows ++ templateAccounts;\n\n\
         \x20 rowOf = name: lib.findFirst (row: row.name == name) null rows;\n\
         \x20 # The allocated identities and the derived per-Zone identities are two\n\
         \x20 # independent derivations, so a collision between them is checked here\n\
         \x20 # rather than assumed away.\n\
         \x20 distinct = f:\n\
         \x20   builtins.length (builtins.attrNames (builtins.listToAttrs\n\
         \x20     (map (row: { name = f row; value = true; }) rows)));\n\
         in\n\
         {\n\
         \x20 assertions = [\n\
         \x20   {\n\
         \x20     assertion = distinct (row: row.name) == builtins.length rows;\n\
         \x20     message = \"d2b host accounts: two provisioned rows compose the same\n\
         \x20       account name. Rename the Zone, Device or Provider they are derived\n\
         \x20       from; two row classes cannot share one identity.\";\n\
         \x20   }\n\
         \x20   {\n\
         \x20     assertion = distinct (row: toString row.uid) == builtins.length rows;\n\
         \x20     message = \"d2b host accounts: two provisioned accounts collide on a uid.\n\
         \x20       The allocated identities and the derived per-Zone identities are two\n\
         \x20       independent derivations, so rename the Zone, Device or Provider they\n\
         \x20       are derived from.\";\n\
         \x20   }\n\
         \x20   # The host account database carries a name of at most\n\
         \x20   # `d2bLib.accountNameLimit` bytes, and the derived per-Zone accounts\n\
         \x20   # are already bounded to it by `d2bLib.boundedAccountName`. This is\n\
         \x20   # where the allocated principals are proved to fit the same bound,\n\
         \x20   # rather than aborting the host's own evaluation at a length the\n\
         \x20   # account database cannot hold.\n\
         \x20   {\n\
         \x20     assertion = builtins.all\n\
         \x20       (row: builtins.stringLength row.name <= d2bLib.accountNameLimit)\n\
         \x20       rows;\n\
         \x20     message = \"d2b host accounts: a provisioned account name is longer\n\
         \x20       than the bytes the host account database carries. NixOS's own user\n\
         \x20       and group options refuse 32 bytes or more, so rename the principal\n\
         \x20       the allocation names; a name the host cannot hold is refused by\n\
         \x20       the resolver rather than truncated into another identity.\";\n\
         \x20   }\n\
         \x20 ];\n\n\
         \x20 users.groups = {\n\
         \x20   # Membership grants admission to the root daemon public socket. Object\n\
         \x20   # authorization remains the daemon's SO_PEERCRED and Zone policy check.\n\
         \x20   d2b = { };\n\
         \x20 } // lib.genAttrs (map (row: row.name) rows) (name: {\n\
         \x20   gid = (rowOf name).gid;\n\
         \x20 });\n\n\
         \x20 users.users = lib.mkMerge [\n\
         \x20   (lib.genAttrs lifecycleUsers (_: {\n\
         \x20     extraGroups = [ \"d2b\" ];\n\
         \x20   }))\n\
         \x20   (lib.listToAttrs (map\n\
         \x20     (row: lib.nameValuePair row.name {\n\
         \x20       isSystemUser = true;\n\
         \x20       uid = row.uid;\n\
         \x20       group = row.name;\n\
         \x20       description = row.description;\n\
         \x20     })\n\
         \x20     rows))\n\
         \x20 ];\n\
         }\n",
    );
    Ok(out)
}

/// The Nix projection a declaration projection produces (KTD1/U4).
///
/// The rendering is the private plan's own Nix view: the providers and their
/// signed manifest inputs, the service catalog, the registration rows, the
/// per-method graph rows with the presentation each method needs, and the
/// compiled consumer requests. Every list is sorted, so two evaluations of one
/// declaration produce the same bytes and no consumer can hand-order a
/// projection to make a diff.
///
/// The Nix surfaces read this rendering and nothing else:
/// `nix/provider-artifact.nix` accepts a `providers` row as the declaration a
/// package was published from and refuses a digest or identity that disagrees
/// with the bytes it built, `nixos-modules/provider-catalog.nix` asserts the
/// catalog selects exactly the `providers` this rendering produces, and
/// `nixos-modules/resources-zones-processes.nix` emits `consumerRequests` rows
/// in this spelling. Renaming a field here breaks that boundary, so the
/// rendered field set is asserted rather than documented.
///
/// The renderer is staged: the production entry point keeps the
/// pre-declaration inventory until the cutover, so this is exercised by its
/// owner-local tests rather than by a second generation command.
#[cfg(test)]
pub(crate) fn render_declaration_nix_projection(plan: &PrivatePlanProjection) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(&format!(
        "  contractVersion = \"{}\";\n",
        plan.contract_version()
    ));
    out.push_str("  providers = {\n");
    for input in plan.manifest_inputs() {
        out.push_str(&format!(
            "    \"{}\" = {{\n      providerRef = \"{}\";\n      declarationDigest = \"{}\";\n      executableSetDigest = \"{}\";\n      configDigest = \"{}\";\n      components = [\n",
            input.artifact_id(),
            input.provider_ref(),
            input.declaration_digest(),
            input.executable_set_digest(),
            input.config_digest()
        ));
        for component in input.components() {
            out.push_str(&format!(
                "        {{ componentId = \"{}\"; presentation = \"{}\"; setupRestrictions = {}; }}\n",
                component.component_id(),
                component.presentation_token(),
                nix_string_list(component.setup_restriction_tokens(), 0)
            ));
        }
        out.push_str("      ];\n    };\n");
    }
    out.push_str("  };\n");
    out.push_str("  serviceCatalog = {\n");
    for service in plan.services() {
        out.push_str(&format!(
            "    \"{}\" = \"{}\";\n",
            service.service_id(),
            service.provider_ref()
        ));
    }
    out.push_str("  };\n");
    out.push_str("  registrations = [\n");
    for registration in plan.registrations() {
        out.push_str(&format!(
            "    {{ artifactId = \"{}\"; providerRef = \"{}\"; services = {}; }}\n",
            registration.artifact_id(),
            registration.provider_ref(),
            nix_string_list(registration.services().iter().map(String::as_str), 0)
        ));
    }
    out.push_str("  ];\n");
    out.push_str("  operations = [\n");
    for operation in plan.operations() {
        out.push_str(&format!(
            "    {{ providerRef = \"{}\"; componentId = \"{}\"; method = \"{}\"; presentation = \"{}\"; }}\n",
            operation.implementation().provider().to_canonical_string(),
            operation.component_id(),
            operation.method(),
            operation.presentation_token()
        ));
    }
    out.push_str("  ];\n");
    out.push_str("  consumerRequests = [\n");
    for request in plan.consumer_requests() {
        out.push_str(&format!(
            "    {{ zone = \"{}\"; consumerRef = \"{}\"; slot = \"{}\"; kind = \"{}\"; fingerprint = \"{}\"; }}\n",
            request.zone(),
            request.consumer_ref(),
            request.slot(),
            request.kind_token(),
            request.fingerprint()
        ));
    }
    out.push_str("  ];\n");
    out.push_str("}\n");
    out
}

/// Write every Nix inventory the generator owns.
pub fn gen_nix_inventories(repo_root: &Path) -> Result<Vec<PathBuf>, Box<dyn std::error::Error>> {
    let allocation = principal_allocation(repo_root)?;
    // The provider-facts role artifacts (U4) are declaration-driven; the
    // resource-type authority renders them so the standalone command and the
    // layout check's --fix path emit identical bytes.
    let role_artifacts = crate::resource_type_authority::render_role_artifacts(repo_root)
        .map_err(|error| render_error(format!("role-artifact render failed: {error}")))?;
    let mut written = vec![
        write(
            repo_root,
            PROVIDER_PROJECTIONS_OUT,
            provider_projections_module(),
        )?,
        write(
            repo_root,
            RESOURCE_INVENTORIES_OUT,
            resource_inventories_module(
                repo_root,
                STANDARD_RESOURCE_TYPES.as_slice(),
            )?,
        )?,
        write(
            repo_root,
            HOST_USERS_OUT,
            host_users_module(&allocation)?,
        )?,
    ];
    for (relative, rendered) in role_artifacts {
        written.push(write(repo_root, &relative, rendered)?);
    }
    if written.is_empty() {
        return Err(render_error(
            "gen-nix-inventories wrote no artifact; refusing to report success",
        ));
    }
    Ok(written)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::provider_crate_policy::PROVIDER_MATRIX;

    /// The Nix projection is the private plan's own Nix view, so a provider
    /// method reaches the Nix surface without a hand-written inventory row.
    #[test]
    fn the_nix_projection_is_derived_from_the_declaration() {
        let plan = crate::resource_type_authority::declaration_fixture::plan(&["export", "close"]);
        let rendered = render_declaration_nix_projection(&plan);
        assert_eq!(rendered, render_declaration_nix_projection(&plan), "byte-stable");
        assert!(rendered.contains("contractVersion = \"d2b.zone.v3\""));
        assert!(rendered.contains("componentId = \"volume-virtiofs\""));
        assert!(
            rendered.contains("presentation = \"namespace-first-service-source\""),
            "the declared capability reaches Nix: {rendered}"
        );
        let extended = render_declaration_nix_projection(
            &crate::resource_type_authority::declaration_fixture::plan(&["export", "close", "reopen"]),
        );
        assert_ne!(rendered, extended, "one changed method moves the Nix projection");
    }

    /// The rendered field set is the contract the Nix surfaces read, so a
    /// rename here would break `nix/provider-artifact.nix`,
    /// `nixos-modules/provider-catalog.nix`, and
    /// `nixos-modules/resources-zones-processes.nix` silently. Each row is
    /// pinned to the exact keys it renders, in the exact spelling.
    #[test]
    fn the_rendered_projection_is_the_shape_the_nix_surfaces_read() {
        use crate::resource_type_authority::declaration_fixture;

        let rendered =
            render_declaration_nix_projection(&declaration_fixture::plan(&["export", "close"]));
        assert!(
            rendered.contains(
                "\"provider-volume-virtiofs\" = {\n      providerRef = \"Provider/provider-volume-virtiofs\";\n      declarationDigest = \""
            ),
            "nix/provider-artifact.nix reads exactly these provider fields: {rendered}"
        );
        assert!(
            rendered.contains(
                "{ componentId = \"volume-virtiofs\"; presentation = \"namespace-first-service-source\"; setupRestrictions = [\n  \"steady-state-mount-namespace\"\n  \"zero-host-capability\"\n]; }"
            ),
            "the capability reaches Nix on a component row with no inference field: {rendered}"
        );

        let requested = render_declaration_nix_projection(
            &declaration_fixture::plan_with_request(&["export", "close"]),
        );
        assert!(
            requested.contains(
                "{ zone = \"alpha\"; consumerRef = \"Process/worker\"; slot = \"root\"; kind = \"volume\"; fingerprint = \"sha256:"
            ),
            "the compiled request is the projection's own Nix view: {requested}"
        );
    }

    #[test]
    fn every_projection_owner_is_a_closed_provider_matrix_row() {
        let identities: BTreeSet<&str> = PROVIDER_MATRIX.iter().map(|row| row.identity).collect();
        let mut seen = BTreeSet::new();
        for owner in PROVIDER_PROJECTION_OWNERS {
            assert!(
                identities.contains(owner),
                "projection owner '{owner}' is not a Provider matrix row"
            );
            assert!(seen.insert(*owner), "projection owner '{owner}' repeats");
        }
    }

    #[test]
    fn projection_keys_follow_the_compiler_option_spelling() {
        for owner in PROVIDER_PROJECTION_OWNERS {
            let key = projection_key(owner);
            assert!(
                !key.contains('-'),
                "the compiler option key for '{owner}' keeps a hyphen: {key}"
            );
        }
        assert_eq!(
            projection_key("runtime-azure-container-apps"),
            "providerProjectionRuntimeAzureContainerApps"
        );
        assert_eq!(projection_key("device-tpm"), "providerProjectionDeviceTpm");
        assert_eq!(
            projection_key("shell-terminal"),
            "providerProjectionShellTerminal"
        );
    }

    #[test]
    fn the_control_types_are_a_subset_of_the_standard_registry() {
        let standard: BTreeSet<&str> = STANDARD_RESOURCE_TYPES.iter().copied().collect();
        let mut seen = BTreeSet::new();
        for control in CONTROL_TYPES {
            assert!(
                standard.contains(control),
                "zone-control type '{control}' is not a standard ResourceType"
            );
            assert!(seen.insert(*control), "zone-control type '{control}' repeats");
        }
    }

    #[test]
    fn the_vocabularies_are_the_contract_vocabularies() {
        assert_eq!(
            subject_types(),
            [
                "Zone",
                "User",
                "Provider",
                "Host",
                "Guest",
                "Process",
                "EphemeralProcess",
                "Group",
            ]
        );
        assert_eq!(
            resource_verbs(),
            [
                "get",
                "list",
                "watch",
                "create",
                "update-spec",
                "update-status",
                "update-metadata",
                "update-finalizers",
                "delete",
                "use-credential",
                "admin-credential",
            ]
        );
        assert_eq!(
            session_verbs(),
            [
                "connect",
                "invoke",
                "open-stream",
                "relay",
                "attach",
                "cancel",
                "observe",
                "audit-export",
                "support-bundle",
            ]
        );
        assert_eq!(RELAY_BOUND_TYPES, ["ZoneLink"]);
    }

    #[test]
    fn the_declared_vocabularies_are_unique() {
        for vocabulary in [
            RUNTIME_FIELDS,
            RESOURCE_FIELDS,
            METADATA_FIELDS,
            TELEMETRY_FIELDS,
            EMITTER_FIELDS,
            AUDIT_FIELDS,
            CONTROL_TYPES,
            RELAY_BOUND_TYPES,
            PROVIDER_FARM_TYPES,
        ] {
            let deduped: BTreeSet<&str> = vocabulary.iter().copied().collect();
            assert_eq!(
                deduped.len(),
                vocabulary.len(),
                "a declared vocabulary repeats an entry"
            );
        }
    }

    #[test]
    fn the_projection_inventory_is_byte_stable_across_renders() {
        let first = provider_projections_module();
        for _ in 0..4 {
            assert_eq!(first, provider_projections_module());
        }
        assert!(first.contains("providerProjectionVolumeLocal"));
    }
}
