//! `ApplyNmUnmanaged` op.
//!
//! Writes one nixling-prefixed file under
//! `/etc/NetworkManager/conf.d/00-nixling-unmanaged.conf` that
//! declares every nixling-owned bridge/TAP as `unmanaged`. Reload via
//! `nmcli general reload conf` (NM >= 1.20) with `systemctl reload
//! NetworkManager.service` fallback. Verify via `nmcli -t -f
//! DEVICE,STATE device status`. Rollback on failure. Foreign NM
//! files are never modified.
//!
//! The reload command is explicitly `nmcli general reload conf`, NOT
//! `nmcli connection reload` (the latter only reloads connection
//! profiles).

use crate::ops::exec_reconcile::ReconcileExecutor;
use crate::sys::path_safe;
use nixling_core::bundle_resolver::ResolvedNmUnmanagedIntent;
use nixling_core::host_w3::NmUnmanagedEntry;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;

pub const DEFAULT_NM_CONF_PATH: &str = "/etc/NetworkManager/conf.d/00-nixling-unmanaged.conf";
pub const NM_RELOAD_MIN_VERSION: (u32, u32) = (1, 20);

#[derive(Debug, Clone)]
pub struct ApplyNmRequest {
    pub conf_path: PathBuf,
    pub entries: Vec<NmUnmanagedEntry>,
    /// Detected NM version, if any. `None` means NM was not detected
    /// (no-op + log).
    pub nm_version: Option<String>,
    /// `nmcli -t -f DEVICE,STATE device status` output (so this
    /// function is unit-testable without invoking nmcli).
    pub device_status: String,
    /// `true` means `general reload conf` succeeded; `false` triggers
    /// the `systemctl reload NetworkManager.service` fallback.
    pub reload_succeeded: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ApplyNmResult {
    pub conf_path_hash: String,
    pub ifname_set: Vec<String>,
    pub reload_command: ReloadCommand,
    pub all_declared_unmanaged: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ReloadCommand {
    NmcliGeneralReloadConf,
    SystemctlReloadNetworkManager,
    NoOpManagerAbsent,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ApplyNmError {
    Io(String),
    DeviceNotUnmanaged { ifname: String, state: String },
    ManagedForeignConflict { ifname: String, state: String },
    ReloadFailed,
}

impl std::fmt::Display for ApplyNmError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(s) => write!(f, "nm-apply: io: {s}"),
            Self::DeviceNotUnmanaged { ifname, state } => {
                write!(f, "nm-apply: {ifname:?} is {state:?}, expected `unmanaged`")
            }
            Self::ManagedForeignConflict { ifname, state } => write!(
                f,
                "nm-managed-foreign-conflict: {ifname:?} held by foreign NM profile (state {state:?})"
            ),
            Self::ReloadFailed => write!(f, "nm-reload-required: reload command failed"),
        }
    }
}

impl std::error::Error for ApplyNmError {}

impl From<io::Error> for ApplyNmError {
    fn from(value: io::Error) -> Self {
        Self::Io(value.to_string())
    }
}

/// Renders the nixling-owned NM `conf.d` snippet body.
pub fn render_nm_conf(entries: &[NmUnmanagedEntry]) -> String {
    let mut out = String::new();
    out.push_str("# nixling-managed begin\n");
    out.push_str("# Generated by nixling-priv-broker; do not edit by hand.\n");
    out.push_str("[keyfile]\n");
    let unmanaged_devices: Vec<String> = entries
        .iter()
        .map(|e| format!("interface-name:{}", e.if_name.as_str()))
        .collect();
    out.push_str("unmanaged-devices=");
    out.push_str(&unmanaged_devices.join(";"));
    out.push('\n');
    for e in entries {
        out.push_str(&format!(
            "# marker-id={mid} ifname={ifn}\n",
            mid = e.marker_id,
            ifn = e.if_name.as_str()
        ));
    }
    out.push_str("# nixling-managed end\n");
    out
}

/// Returns the correct reload command for the detected NM version.
/// `None` NM means no-op.
pub fn select_reload_command(nm_version: Option<&str>) -> ReloadCommand {
    let Some(version) = nm_version else {
        return ReloadCommand::NoOpManagerAbsent;
    };
    let (major, minor) = split_major_minor(version).unwrap_or((0, 0));
    if (major, minor) >= NM_RELOAD_MIN_VERSION {
        ReloadCommand::NmcliGeneralReloadConf
    } else {
        ReloadCommand::SystemctlReloadNetworkManager
    }
}

fn split_major_minor(v: &str) -> Option<(u32, u32)> {
    let mut parts = v
        .split(|c: char| !c.is_ascii_digit())
        .filter(|s| !s.is_empty());
    let major: u32 = parts.next()?.parse().ok()?;
    let minor: u32 = parts.next().unwrap_or("0").parse().ok()?;
    Some((major, minor))
}

/// Parses `nmcli -t -f DEVICE,STATE device status` into a vec of
/// `(device, state)` rows. Lines that don't contain `:` are skipped.
pub fn parse_device_status(output: &str) -> Vec<(String, String)> {
    output
        .lines()
        .filter_map(|line| {
            let mut parts = line.splitn(2, ':');
            let device = parts.next()?.trim().to_owned();
            let state = parts.next()?.trim().to_owned();
            if device.is_empty() {
                None
            } else {
                Some((device, state))
            }
        })
        .collect()
}

/// Verifies every declared nixling ifname is in state `unmanaged`.
/// A state of `managed`/`connected`/`activated` for a declared
/// nixling ifname is reported as `nm-managed-foreign-conflict`.
pub fn verify_all_unmanaged(
    entries: &[NmUnmanagedEntry],
    device_status: &str,
) -> Result<(), ApplyNmError> {
    let rows = parse_device_status(device_status);
    for entry in entries {
        let ifn = entry.if_name.as_str();
        let row = rows.iter().find(|(d, _)| d == ifn);
        match row {
            None => {
                return Err(ApplyNmError::DeviceNotUnmanaged {
                    ifname: ifn.to_owned(),
                    state: "absent".into(),
                });
            }
            Some((_, state)) if state == "unmanaged" => {}
            Some((_, state))
                if state == "connected"
                    || state == "activated"
                    || state == "connecting"
                    || state == "managed" =>
            {
                return Err(ApplyNmError::ManagedForeignConflict {
                    ifname: ifn.to_owned(),
                    state: state.clone(),
                });
            }
            Some((_, state)) => {
                return Err(ApplyNmError::DeviceNotUnmanaged {
                    ifname: ifn.to_owned(),
                    state: state.clone(),
                });
            }
        }
    }
    Ok(())
}

pub fn apply_nm_unmanaged(req: &ApplyNmRequest) -> Result<ApplyNmResult, ApplyNmError> {
    path_safe::refuse_world_writable_parent(&req.conf_path)?;
    path_safe::refuse_symlink(&req.conf_path)?;
    let body = render_nm_conf(&req.entries);
    // Snapshot prior content for rollback if reload + verify fail.
    let prior = path_safe::read_to_string_nofollow(&req.conf_path).ok();
    path_safe::atomic_replace(&req.conf_path, body.as_bytes())?;
    let reload = select_reload_command(req.nm_version.as_deref());
    if matches!(reload, ReloadCommand::NoOpManagerAbsent) {
        return Ok(ApplyNmResult {
            conf_path_hash: super::hosts::stable_hash_str(&req.conf_path.display().to_string()),
            ifname_set: req
                .entries
                .iter()
                .map(|e| e.if_name.as_str().to_owned())
                .collect(),
            reload_command: reload,
            all_declared_unmanaged: true,
        });
    }
    if !req.reload_succeeded {
        rollback(&req.conf_path, prior.as_deref())?;
        return Err(ApplyNmError::ReloadFailed);
    }
    if let Err(err) = verify_all_unmanaged(&req.entries, &req.device_status) {
        rollback(&req.conf_path, prior.as_deref())?;
        return Err(err);
    }
    Ok(ApplyNmResult {
        conf_path_hash: super::hosts::stable_hash_str(&req.conf_path.display().to_string()),
        ifname_set: req
            .entries
            .iter()
            .map(|e| e.if_name.as_str().to_owned())
            .collect(),
        reload_command: reload,
        all_declared_unmanaged: true,
    })
}

fn rollback(path: &Path, prior: Option<&str>) -> io::Result<()> {
    match prior {
        Some(body) => path_safe::atomic_replace(path, body.as_bytes()),
        None => path_safe::remove_nofollow(path),
    }
}

/// Runtime entry-point for `ApplyNmUnmanaged`.
///
/// The dispatcher now lands on `ops::nm` even though the live path is
/// still a thin wrapper. That preserves a stable integration point for
/// future coexistence/reload-verification work.
pub fn apply_with_reload(
    executor: &dyn ReconcileExecutor,
    intent: &ResolvedNmUnmanagedIntent,
) -> Result<(), crate::live_handlers::LiveHandlerError> {
    crate::live_handlers::live_apply_nm_unmanaged(executor, intent)
}

pub fn remove_with_reload(
    intent: &ResolvedNmUnmanagedIntent,
) -> Result<(), crate::live_handlers::LiveHandlerError> {
    remove_with_reload_using(intent, systemctl_invoke)
}

#[cfg(test)]
fn apply_with_reload_using<F>(
    executor: &dyn ReconcileExecutor,
    intent: &ResolvedNmUnmanagedIntent,
    reload: F,
) -> Result<(), crate::live_handlers::LiveHandlerError>
where
    F: FnMut(&[&str]) -> Result<(), String>,
{
    crate::live_handlers::live_apply_nm_unmanaged_with_reload(executor, intent, reload)
}

fn remove_with_reload_using<F>(
    intent: &ResolvedNmUnmanagedIntent,
    mut reload: F,
) -> Result<(), crate::live_handlers::LiveHandlerError>
where
    F: FnMut(&[&str]) -> Result<(), String>,
{
    path_safe::refuse_world_writable_parent(&intent.file_path)
        .map_err(|err| io_to_live_handler(&intent.file_path, err))?;
    path_safe::refuse_symlink(&intent.file_path)
        .map_err(|err| io_to_live_handler(&intent.file_path, err))?;
    let prior = match path_safe::read_to_string_nofollow(&intent.file_path) {
        Ok(contents) => Some(contents),
        Err(err) if err.kind() == io::ErrorKind::NotFound => None,
        Err(err) => return Err(io_to_live_handler(&intent.file_path, err)),
    };
    match path_safe::remove_nofollow(&intent.file_path) {
        Ok(()) => {}
        Err(err) if err.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(err) => return Err(io_to_live_handler(&intent.file_path, err)),
    }
    if intent.reload_behavior == "atomic-reload"
        && let Err(err) = reload(&["reload", "NetworkManager"])
    {
        let _ = rollback(&intent.file_path, prior.as_deref());
        return Err(crate::live_handlers::LiveHandlerError::NmReload(err));
    }
    Ok(())
}

fn io_to_live_handler(path: &Path, err: io::Error) -> crate::live_handlers::LiveHandlerError {
    crate::live_handlers::LiveHandlerError::ReconcileExec(
        crate::ops::exec_reconcile::ReconcileExecError::Io {
            path: path.display().to_string(),
            detail: err.to_string(),
        },
    )
}

fn systemctl_invoke(args: &[&str]) -> Result<(), String> {
    let output = Command::new("/usr/bin/systemctl")
        .args(args)
        .env_remove("NOTIFY_SOCKET")
        .output()
        .map_err(|err| format!("systemctl spawn failed: {err}"))?;
    if !output.status.success() {
        let action = args.first().copied().unwrap_or("invoke");
        let target = args.get(1).copied().unwrap_or("");
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_owned();
        let detail = if target.is_empty() {
            stderr
        } else {
            format!("{target}: {stderr}")
        };
        return Err(format!("systemctl {action} failed: {detail}"));
    }
    Ok(())
}

// (parser inlined above as split_major_minor)

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ops::exec_reconcile::{FakeReconcileExecutor, ReconcileOp};
    use nixling_host::ifname::{DerivedRole, derive_from_env_vm};
    use std::cell::RefCell;

    fn entry(ifn_str: &str) -> NmUnmanagedEntry {
        NmUnmanagedEntry {
            if_name: nixling_core::host::IfName::new(ifn_str).unwrap(),
            marker_id: format!("marker-{ifn_str}"),
        }
    }

    #[test]
    fn reload_command_select_by_version() {
        assert_eq!(
            select_reload_command(Some("1.46.0")),
            ReloadCommand::NmcliGeneralReloadConf
        );
        assert_eq!(
            select_reload_command(Some("1.18.0")),
            ReloadCommand::SystemctlReloadNetworkManager
        );
        assert_eq!(
            select_reload_command(None),
            ReloadCommand::NoOpManagerAbsent
        );
    }

    #[test]
    fn render_conf_lists_interfaces() {
        let nl = derive_from_env_vm("e", None, DerivedRole::Bridge, None).unwrap();
        let body = render_nm_conf(&[NmUnmanagedEntry {
            if_name: nl.clone(),
            marker_id: "m1".into(),
        }]);
        assert!(body.contains(&format!("interface-name:{}", nl.as_str())));
        assert!(body.contains("# nixling-managed begin"));
        assert!(body.contains("# nixling-managed end"));
    }

    #[test]
    fn verify_all_unmanaged_passes_when_unmanaged() {
        let e = entry("nl-b-x");
        verify_all_unmanaged(&[e], "nl-b-x:unmanaged\nwlp0:connected\n").unwrap();
    }

    #[test]
    fn managed_foreign_conflict_detected() {
        let e = entry("nl-b-x");
        let err = verify_all_unmanaged(&[e], "nl-b-x:connected\n").unwrap_err();
        assert!(matches!(err, ApplyNmError::ManagedForeignConflict { .. }));
    }

    #[test]
    fn reload_failure_rolls_back() {
        let dir = std::env::temp_dir().join(format!(
            "nixling-w3-s2-nm-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("00-nixling-unmanaged.conf");
        std::fs::write(&path, "prior=value\n").unwrap();
        let nl = derive_from_env_vm("e", None, DerivedRole::Bridge, None).unwrap();
        let req = ApplyNmRequest {
            conf_path: path.clone(),
            entries: vec![NmUnmanagedEntry {
                if_name: nl,
                marker_id: "m1".into(),
            }],
            nm_version: Some("1.46.0".into()),
            device_status: String::new(),
            reload_succeeded: false,
        };
        let err = apply_nm_unmanaged(&req).unwrap_err();
        assert_eq!(err, ApplyNmError::ReloadFailed);
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "prior=value\n");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn apply_with_reload_writes_resolved_contents_and_reloads_nm() {
        let exec = FakeReconcileExecutor::new();
        let reloads = RefCell::new(Vec::<String>::new());
        let intent = ResolvedNmUnmanagedIntent {
            intent_id: "nm-unmanaged:host".to_owned(),
            file_path: PathBuf::from(DEFAULT_NM_CONF_PATH),
            contents: "# nixling-managed begin\n[keyfile]\nunmanaged-devices=interface-name:nl-b-x\n# nixling-managed end\n".to_owned(),
            mode: 0o644,
            owner: "root".to_owned(),
            group: "root".to_owned(),
            reload_behavior: "atomic-reload".to_owned(),
        };

        apply_with_reload_using(&exec, &intent, |args| {
            reloads.borrow_mut().push(args.join(" "));
            Ok(())
        })
        .unwrap();

        let log = exec.take_log();
        assert_eq!(log.len(), 1);
        match &log[0] {
            ReconcileOp::WriteAtomicFile {
                path,
                contents,
                mode,
            } => {
                assert_eq!(path, &PathBuf::from(DEFAULT_NM_CONF_PATH));
                assert_eq!(*mode, 0o644);
                assert!(String::from_utf8_lossy(contents).contains("unmanaged-devices"));
            }
            other => panic!("unexpected op: {other:?}"),
        }
        assert_eq!(
            reloads.into_inner(),
            vec!["reload NetworkManager".to_owned()]
        );
    }
}
