// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct ActivationServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl ActivationServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        ActivationServiceClient {
            client,
        }
    }

    pub async fn activate(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.activation.v2.ActivationService", "Activate", cres);
    }

    pub async fn inspect(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.activation.v2.ActivationService", "Inspect", cres);
    }

    pub async fn cancel(&self, ctx: ttrpc::context::Context, req: &super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        let mut cres = super::common::CancelResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.activation.v2.ActivationService", "Cancel", cres);
    }
}

struct ActivateMethod {
    service: Arc<dyn ActivationService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ActivateMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, activate);
    }
}

struct InspectMethod {
    service: Arc<dyn ActivationService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for InspectMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, inspect);
    }
}

struct CancelMethod {
    service: Arc<dyn ActivationService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CancelMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, CancelRequest, cancel);
    }
}

#[async_trait]
pub trait ActivationService: Sync {
    async fn activate(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.activation.v2.ActivationService/Activate is not supported".to_string())))
    }
    async fn inspect(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.activation.v2.ActivationService/Inspect is not supported".to_string())))
    }
    async fn cancel(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.activation.v2.ActivationService/Cancel is not supported".to_string())))
    }
}

pub fn create_activation_service(service: Arc<dyn ActivationService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("Activate".to_string(),
                    Box::new(ActivateMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Inspect".to_string(),
                    Box::new(InspectMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Cancel".to_string(),
                    Box::new(CancelMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("d2b.activation.v2.ActivationService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
