// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

#![allow(clippy::bool_comparison)]
#![allow(clippy::derivable_impls)]
#![allow(clippy::match_like_matches_macro)]
#![allow(clippy::match_ref_pats)]
#![allow(clippy::needless_borrow)]
#![allow(clippy::redundant_static_lifetimes)]
#![allow(clippy::vec_init_then_push)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `broker.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0cbroker.proto\x12\rd2b.broker.v2\x1a\x0ccommon.proto2\x81\x06\n\rBr\
    okerService\x12N\n\rValidateLease\x12\x1d.d2b.common.v2.ServiceRequest\
    \x1a\x1e.d2b.common.v2.ServiceResponse\x12I\n\x08Allocate\x12\x1d.d2b.co\
    mmon.v2.ServiceRequest\x1a\x1e.d2b.common.v2.ServiceResponse\x12I\n\x08D\
    elegate\x12\x1d.d2b.common.v2.ServiceRequest\x1a\x1e.d2b.common.v2.Servi\
    ceResponse\x12F\n\x05Spawn\x12\x1d.d2b.common.v2.ServiceRequest\x1a\x1e.\
    d2b.common.v2.ServiceResponse\x12M\n\x0cOpenResource\x12\x1d.d2b.common.\
    v2.ServiceRequest\x1a\x1e.d2b.common.v2.ServiceResponse\x12F\n\x05Apply\
    \x12\x1d.d2b.common.v2.ServiceRequest\x1a\x1e.d2b.common.v2.ServiceRespo\
    nse\x12H\n\x07Observe\x12\x1d.d2b.common.v2.ServiceRequest\x1a\x1e.d2b.c\
    ommon.v2.ServiceResponse\x12L\n\x0bRevokeLease\x12\x1d.d2b.common.v2.Ser\
    viceRequest\x1a\x1e.d2b.common.v2.ServiceResponse\x12L\n\x0bExportAudit\
    \x12\x1d.d2b.common.v2.ServiceRequest\x1a\x1e.d2b.common.v2.ServiceRespo\
    nse\x12E\n\x06Cancel\x12\x1c.d2b.common.v2.CancelRequest\x1a\x1d.d2b.com\
    mon.v2.CancelResponseb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::common::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
