// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct BrokerServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl BrokerServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        BrokerServiceClient {
            client,
        }
    }

    pub async fn validate_lease(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.broker.v2.BrokerService", "ValidateLease", cres);
    }

    pub async fn allocate(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.broker.v2.BrokerService", "Allocate", cres);
    }

    pub async fn delegate(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.broker.v2.BrokerService", "Delegate", cres);
    }

    pub async fn spawn(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.broker.v2.BrokerService", "Spawn", cres);
    }

    pub async fn open_resource(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.broker.v2.BrokerService", "OpenResource", cres);
    }

    pub async fn apply(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.broker.v2.BrokerService", "Apply", cres);
    }

    pub async fn observe(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.broker.v2.BrokerService", "Observe", cres);
    }

    pub async fn revoke_lease(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.broker.v2.BrokerService", "RevokeLease", cres);
    }

    pub async fn export_audit(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.broker.v2.BrokerService", "ExportAudit", cres);
    }

    pub async fn cancel(&self, ctx: ttrpc::context::Context, req: &super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        let mut cres = super::common::CancelResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.broker.v2.BrokerService", "Cancel", cres);
    }
}

struct ValidateLeaseMethod {
    service: Arc<dyn BrokerService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ValidateLeaseMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, validate_lease);
    }
}

struct AllocateMethod {
    service: Arc<dyn BrokerService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for AllocateMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, allocate);
    }
}

struct DelegateMethod {
    service: Arc<dyn BrokerService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for DelegateMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, delegate);
    }
}

struct SpawnMethod {
    service: Arc<dyn BrokerService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for SpawnMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, spawn);
    }
}

struct OpenResourceMethod {
    service: Arc<dyn BrokerService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for OpenResourceMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, open_resource);
    }
}

struct ApplyMethod {
    service: Arc<dyn BrokerService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ApplyMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, apply);
    }
}

struct ObserveMethod {
    service: Arc<dyn BrokerService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ObserveMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, observe);
    }
}

struct RevokeLeaseMethod {
    service: Arc<dyn BrokerService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for RevokeLeaseMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, revoke_lease);
    }
}

struct ExportAuditMethod {
    service: Arc<dyn BrokerService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ExportAuditMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, export_audit);
    }
}

struct CancelMethod {
    service: Arc<dyn BrokerService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CancelMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, CancelRequest, cancel);
    }
}

#[async_trait]
pub trait BrokerService: Sync {
    async fn validate_lease(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.broker.v2.BrokerService/ValidateLease is not supported".to_string())))
    }
    async fn allocate(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.broker.v2.BrokerService/Allocate is not supported".to_string())))
    }
    async fn delegate(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.broker.v2.BrokerService/Delegate is not supported".to_string())))
    }
    async fn spawn(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.broker.v2.BrokerService/Spawn is not supported".to_string())))
    }
    async fn open_resource(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.broker.v2.BrokerService/OpenResource is not supported".to_string())))
    }
    async fn apply(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.broker.v2.BrokerService/Apply is not supported".to_string())))
    }
    async fn observe(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.broker.v2.BrokerService/Observe is not supported".to_string())))
    }
    async fn revoke_lease(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.broker.v2.BrokerService/RevokeLease is not supported".to_string())))
    }
    async fn export_audit(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.broker.v2.BrokerService/ExportAudit is not supported".to_string())))
    }
    async fn cancel(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.broker.v2.BrokerService/Cancel is not supported".to_string())))
    }
}

pub fn create_broker_service(service: Arc<dyn BrokerService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("ValidateLease".to_string(),
                    Box::new(ValidateLeaseMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Allocate".to_string(),
                    Box::new(AllocateMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Delegate".to_string(),
                    Box::new(DelegateMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Spawn".to_string(),
                    Box::new(SpawnMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("OpenResource".to_string(),
                    Box::new(OpenResourceMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Apply".to_string(),
                    Box::new(ApplyMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Observe".to_string(),
                    Box::new(ObserveMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("RevokeLease".to_string(),
                    Box::new(RevokeLeaseMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ExportAudit".to_string(),
                    Box::new(ExportAuditMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Cancel".to_string(),
                    Box::new(CancelMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("d2b.broker.v2.BrokerService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
