// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct DaemonServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl DaemonServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        DaemonServiceClient {
            client,
        }
    }

    pub async fn resolve(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "Resolve", cres);
    }

    pub async fn list_realms(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::daemon::ListRealmsResponse> {
        let mut cres = super::daemon::ListRealmsResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "ListRealms", cres);
    }

    pub async fn list_workloads(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::daemon::ListWorkloadsResponse> {
        let mut cres = super::daemon::ListWorkloadsResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "ListWorkloads", cres);
    }

    pub async fn inspect(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::daemon::InspectResponse> {
        let mut cres = super::daemon::InspectResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "Inspect", cres);
    }

    pub async fn apply(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "Apply", cres);
    }

    pub async fn start(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "Start", cres);
    }

    pub async fn stop(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "Stop", cres);
    }

    pub async fn restart(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "Restart", cres);
    }

    pub async fn exec(&self, ctx: ttrpc::context::Context, req: &super::daemon::TerminalOpenRequest) -> ::ttrpc::Result<super::daemon::TerminalOpenResponse> {
        let mut cres = super::daemon::TerminalOpenResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "Exec", cres);
    }

    pub async fn shell(&self, ctx: ttrpc::context::Context, req: &super::daemon::TerminalOpenRequest) -> ::ttrpc::Result<super::daemon::TerminalOpenResponse> {
        let mut cres = super::daemon::TerminalOpenResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "Shell", cres);
    }

    pub async fn open_console(&self, ctx: ttrpc::context::Context, req: &super::daemon::TerminalOpenRequest) -> ::ttrpc::Result<super::daemon::TerminalOpenResponse> {
        let mut cres = super::daemon::TerminalOpenResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "OpenConsole", cres);
    }

    pub async fn export_audit(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "ExportAudit", cres);
    }

    pub async fn cancel(&self, ctx: ttrpc::context::Context, req: &super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        let mut cres = super::common::CancelResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.daemon.v2.DaemonService", "Cancel", cres);
    }
}

struct ResolveMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ResolveMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, resolve);
    }
}

struct ListRealmsMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ListRealmsMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, list_realms);
    }
}

struct ListWorkloadsMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ListWorkloadsMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, list_workloads);
    }
}

struct InspectMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for InspectMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, inspect);
    }
}

struct ApplyMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ApplyMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, apply);
    }
}

struct StartMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for StartMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, start);
    }
}

struct StopMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for StopMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, stop);
    }
}

struct RestartMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for RestartMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, restart);
    }
}

struct ExecMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ExecMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, daemon, TerminalOpenRequest, exec);
    }
}

struct ShellMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ShellMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, daemon, TerminalOpenRequest, shell);
    }
}

struct OpenConsoleMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for OpenConsoleMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, daemon, TerminalOpenRequest, open_console);
    }
}

struct ExportAuditMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ExportAuditMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, export_audit);
    }
}

struct CancelMethod {
    service: Arc<dyn DaemonService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CancelMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, CancelRequest, cancel);
    }
}

#[async_trait]
pub trait DaemonService: Sync {
    async fn resolve(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/Resolve is not supported".to_string())))
    }
    async fn list_realms(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::daemon::ListRealmsResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/ListRealms is not supported".to_string())))
    }
    async fn list_workloads(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::daemon::ListWorkloadsResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/ListWorkloads is not supported".to_string())))
    }
    async fn inspect(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::daemon::InspectResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/Inspect is not supported".to_string())))
    }
    async fn apply(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/Apply is not supported".to_string())))
    }
    async fn start(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/Start is not supported".to_string())))
    }
    async fn stop(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/Stop is not supported".to_string())))
    }
    async fn restart(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/Restart is not supported".to_string())))
    }
    async fn exec(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::daemon::TerminalOpenRequest) -> ::ttrpc::Result<super::daemon::TerminalOpenResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/Exec is not supported".to_string())))
    }
    async fn shell(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::daemon::TerminalOpenRequest) -> ::ttrpc::Result<super::daemon::TerminalOpenResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/Shell is not supported".to_string())))
    }
    async fn open_console(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::daemon::TerminalOpenRequest) -> ::ttrpc::Result<super::daemon::TerminalOpenResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/OpenConsole is not supported".to_string())))
    }
    async fn export_audit(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/ExportAudit is not supported".to_string())))
    }
    async fn cancel(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.daemon.v2.DaemonService/Cancel is not supported".to_string())))
    }
}

pub fn create_daemon_service(service: Arc<dyn DaemonService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("Resolve".to_string(),
                    Box::new(ResolveMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ListRealms".to_string(),
                    Box::new(ListRealmsMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ListWorkloads".to_string(),
                    Box::new(ListWorkloadsMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Inspect".to_string(),
                    Box::new(InspectMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Apply".to_string(),
                    Box::new(ApplyMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Start".to_string(),
                    Box::new(StartMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Stop".to_string(),
                    Box::new(StopMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Restart".to_string(),
                    Box::new(RestartMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Exec".to_string(),
                    Box::new(ExecMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Shell".to_string(),
                    Box::new(ShellMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("OpenConsole".to_string(),
                    Box::new(OpenConsoleMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ExportAudit".to_string(),
                    Box::new(ExportAuditMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Cancel".to_string(),
                    Box::new(CancelMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("d2b.daemon.v2.DaemonService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
