// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct GuestServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl GuestServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        GuestServiceClient {
            client,
        }
    }

    pub async fn bootstrap(&self, ctx: ttrpc::context::Context, req: &super::guest::GuestBootstrapRequest) -> ::ttrpc::Result<super::guest::GuestSessionResponse> {
        let mut cres = super::guest::GuestSessionResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.guest.v2.GuestService", "Bootstrap", cres);
    }

    pub async fn reconnect(&self, ctx: ttrpc::context::Context, req: &super::guest::GuestReconnectRequest) -> ::ttrpc::Result<super::guest::GuestSessionResponse> {
        let mut cres = super::guest::GuestSessionResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.guest.v2.GuestService", "Reconnect", cres);
    }

    pub async fn exec(&self, ctx: ttrpc::context::Context, req: &super::terminal::TerminalOpenRequest) -> ::ttrpc::Result<super::terminal::TerminalOpenResponse> {
        let mut cres = super::terminal::TerminalOpenResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.guest.v2.GuestService", "Exec", cres);
    }

    pub async fn cancel_exec(&self, ctx: ttrpc::context::Context, req: &super::guest::GuestCancelExecRequest) -> ::ttrpc::Result<super::guest::GuestCancelExecResponse> {
        let mut cres = super::guest::GuestCancelExecResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.guest.v2.GuestService", "CancelExec", cres);
    }

    pub async fn inspect_exec(&self, ctx: ttrpc::context::Context, req: &super::guest::GuestInspectExecRequest) -> ::ttrpc::Result<super::guest::GuestInspectExecResponse> {
        let mut cres = super::guest::GuestInspectExecResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.guest.v2.GuestService", "InspectExec", cres);
    }

    pub async fn open_shell(&self, ctx: ttrpc::context::Context, req: &super::terminal::TerminalOpenRequest) -> ::ttrpc::Result<super::terminal::TerminalOpenResponse> {
        let mut cres = super::terminal::TerminalOpenResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.guest.v2.GuestService", "OpenShell", cres);
    }

    pub async fn file_transfer(&self, ctx: ttrpc::context::Context, req: &super::guest::GuestFileTransferRequest) -> ::ttrpc::Result<super::terminal::TerminalOpenResponse> {
        let mut cres = super::terminal::TerminalOpenResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.guest.v2.GuestService", "FileTransfer", cres);
    }

    pub async fn security_key(&self, ctx: ttrpc::context::Context, req: &super::guest::GuestSecurityKeyRequest) -> ::ttrpc::Result<super::terminal::TerminalOpenResponse> {
        let mut cres = super::terminal::TerminalOpenResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.guest.v2.GuestService", "SecurityKey", cres);
    }

    pub async fn shutdown(&self, ctx: ttrpc::context::Context, req: &super::guest::GuestShutdownRequest) -> ::ttrpc::Result<super::guest::GuestShutdownResponse> {
        let mut cres = super::guest::GuestShutdownResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.guest.v2.GuestService", "Shutdown", cres);
    }

    pub async fn cancel(&self, ctx: ttrpc::context::Context, req: &super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        let mut cres = super::common::CancelResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.guest.v2.GuestService", "Cancel", cres);
    }
}

struct BootstrapMethod {
    service: Arc<dyn GuestService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for BootstrapMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, guest, GuestBootstrapRequest, bootstrap);
    }
}

struct ReconnectMethod {
    service: Arc<dyn GuestService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ReconnectMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, guest, GuestReconnectRequest, reconnect);
    }
}

struct ExecMethod {
    service: Arc<dyn GuestService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ExecMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, terminal, TerminalOpenRequest, exec);
    }
}

struct CancelExecMethod {
    service: Arc<dyn GuestService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CancelExecMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, guest, GuestCancelExecRequest, cancel_exec);
    }
}

struct InspectExecMethod {
    service: Arc<dyn GuestService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for InspectExecMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, guest, GuestInspectExecRequest, inspect_exec);
    }
}

struct OpenShellMethod {
    service: Arc<dyn GuestService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for OpenShellMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, terminal, TerminalOpenRequest, open_shell);
    }
}

struct FileTransferMethod {
    service: Arc<dyn GuestService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for FileTransferMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, guest, GuestFileTransferRequest, file_transfer);
    }
}

struct SecurityKeyMethod {
    service: Arc<dyn GuestService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for SecurityKeyMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, guest, GuestSecurityKeyRequest, security_key);
    }
}

struct ShutdownMethod {
    service: Arc<dyn GuestService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ShutdownMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, guest, GuestShutdownRequest, shutdown);
    }
}

struct CancelMethod {
    service: Arc<dyn GuestService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CancelMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, CancelRequest, cancel);
    }
}

#[async_trait]
pub trait GuestService: Sync {
    async fn bootstrap(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::guest::GuestBootstrapRequest) -> ::ttrpc::Result<super::guest::GuestSessionResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.guest.v2.GuestService/Bootstrap is not supported".to_string())))
    }
    async fn reconnect(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::guest::GuestReconnectRequest) -> ::ttrpc::Result<super::guest::GuestSessionResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.guest.v2.GuestService/Reconnect is not supported".to_string())))
    }
    async fn exec(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::terminal::TerminalOpenRequest) -> ::ttrpc::Result<super::terminal::TerminalOpenResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.guest.v2.GuestService/Exec is not supported".to_string())))
    }
    async fn cancel_exec(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::guest::GuestCancelExecRequest) -> ::ttrpc::Result<super::guest::GuestCancelExecResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.guest.v2.GuestService/CancelExec is not supported".to_string())))
    }
    async fn inspect_exec(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::guest::GuestInspectExecRequest) -> ::ttrpc::Result<super::guest::GuestInspectExecResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.guest.v2.GuestService/InspectExec is not supported".to_string())))
    }
    async fn open_shell(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::terminal::TerminalOpenRequest) -> ::ttrpc::Result<super::terminal::TerminalOpenResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.guest.v2.GuestService/OpenShell is not supported".to_string())))
    }
    async fn file_transfer(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::guest::GuestFileTransferRequest) -> ::ttrpc::Result<super::terminal::TerminalOpenResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.guest.v2.GuestService/FileTransfer is not supported".to_string())))
    }
    async fn security_key(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::guest::GuestSecurityKeyRequest) -> ::ttrpc::Result<super::terminal::TerminalOpenResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.guest.v2.GuestService/SecurityKey is not supported".to_string())))
    }
    async fn shutdown(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::guest::GuestShutdownRequest) -> ::ttrpc::Result<super::guest::GuestShutdownResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.guest.v2.GuestService/Shutdown is not supported".to_string())))
    }
    async fn cancel(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.guest.v2.GuestService/Cancel is not supported".to_string())))
    }
}

pub fn create_guest_service(service: Arc<dyn GuestService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("Bootstrap".to_string(),
                    Box::new(BootstrapMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Reconnect".to_string(),
                    Box::new(ReconnectMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Exec".to_string(),
                    Box::new(ExecMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("CancelExec".to_string(),
                    Box::new(CancelExecMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("InspectExec".to_string(),
                    Box::new(InspectExecMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("OpenShell".to_string(),
                    Box::new(OpenShellMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("FileTransfer".to_string(),
                    Box::new(FileTransferMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("SecurityKey".to_string(),
                    Box::new(SecurityKeyMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Shutdown".to_string(),
                    Box::new(ShutdownMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Cancel".to_string(),
                    Box::new(CancelMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("d2b.guest.v2.GuestService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
