// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct DeviceProviderServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl DeviceProviderServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        DeviceProviderServiceClient {
            client,
        }
    }

    pub async fn health(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.DeviceProviderService", "Health", cres);
    }

    pub async fn capabilities(&self, ctx: ttrpc::context::Context, req: &super::common::CapabilityRequest) -> ::ttrpc::Result<super::common::CapabilityResponse> {
        let mut cres = super::common::CapabilityResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.DeviceProviderService", "Capabilities", cres);
    }

    pub async fn plan_attach(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.DeviceProviderService", "PlanAttach", cres);
    }

    pub async fn attach(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.DeviceProviderService", "Attach", cres);
    }

    pub async fn inspect(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.DeviceProviderService", "Inspect", cres);
    }

    pub async fn adopt(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.DeviceProviderService", "Adopt", cres);
    }

    pub async fn detach(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.DeviceProviderService", "Detach", cres);
    }
}

struct HealthMethod {
    service: Arc<dyn DeviceProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for HealthMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, health);
    }
}

struct CapabilitiesMethod {
    service: Arc<dyn DeviceProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CapabilitiesMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, CapabilityRequest, capabilities);
    }
}

struct PlanAttachMethod {
    service: Arc<dyn DeviceProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for PlanAttachMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, plan_attach);
    }
}

struct AttachMethod {
    service: Arc<dyn DeviceProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for AttachMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, attach);
    }
}

struct InspectMethod {
    service: Arc<dyn DeviceProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for InspectMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, inspect);
    }
}

struct AdoptMethod {
    service: Arc<dyn DeviceProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for AdoptMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, adopt);
    }
}

struct DetachMethod {
    service: Arc<dyn DeviceProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for DetachMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, detach);
    }
}

#[async_trait]
pub trait DeviceProviderService: Sync {
    async fn health(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.DeviceProviderService/Health is not supported".to_string())))
    }
    async fn capabilities(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::CapabilityRequest) -> ::ttrpc::Result<super::common::CapabilityResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.DeviceProviderService/Capabilities is not supported".to_string())))
    }
    async fn plan_attach(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.DeviceProviderService/PlanAttach is not supported".to_string())))
    }
    async fn attach(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.DeviceProviderService/Attach is not supported".to_string())))
    }
    async fn inspect(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.DeviceProviderService/Inspect is not supported".to_string())))
    }
    async fn adopt(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.DeviceProviderService/Adopt is not supported".to_string())))
    }
    async fn detach(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.DeviceProviderService/Detach is not supported".to_string())))
    }
}

pub fn create_device_provider_service(service: Arc<dyn DeviceProviderService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("Health".to_string(),
                    Box::new(HealthMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Capabilities".to_string(),
                    Box::new(CapabilitiesMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("PlanAttach".to_string(),
                    Box::new(PlanAttachMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Attach".to_string(),
                    Box::new(AttachMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Inspect".to_string(),
                    Box::new(InspectMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Adopt".to_string(),
                    Box::new(AdoptMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Detach".to_string(),
                    Box::new(DetachMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("d2b.provider.v2.DeviceProviderService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
