// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct StorageProviderServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl StorageProviderServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        StorageProviderServiceClient {
            client,
        }
    }

    pub async fn health(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.StorageProviderService", "Health", cres);
    }

    pub async fn capabilities(&self, ctx: ttrpc::context::Context, req: &super::common::CapabilityRequest) -> ::ttrpc::Result<super::common::CapabilityResponse> {
        let mut cres = super::common::CapabilityResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.StorageProviderService", "Capabilities", cres);
    }

    pub async fn plan(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.StorageProviderService", "Plan", cres);
    }

    pub async fn ensure(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.StorageProviderService", "Ensure", cres);
    }

    pub async fn inspect(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.StorageProviderService", "Inspect", cres);
    }

    pub async fn adopt(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.StorageProviderService", "Adopt", cres);
    }

    pub async fn snapshot(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.StorageProviderService", "Snapshot", cres);
    }

    pub async fn destroy(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.StorageProviderService", "Destroy", cres);
    }
}

struct HealthMethod {
    service: Arc<dyn StorageProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for HealthMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, health);
    }
}

struct CapabilitiesMethod {
    service: Arc<dyn StorageProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CapabilitiesMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, CapabilityRequest, capabilities);
    }
}

struct PlanMethod {
    service: Arc<dyn StorageProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for PlanMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, plan);
    }
}

struct EnsureMethod {
    service: Arc<dyn StorageProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for EnsureMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, ensure);
    }
}

struct InspectMethod {
    service: Arc<dyn StorageProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for InspectMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, inspect);
    }
}

struct AdoptMethod {
    service: Arc<dyn StorageProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for AdoptMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, adopt);
    }
}

struct SnapshotMethod {
    service: Arc<dyn StorageProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for SnapshotMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, snapshot);
    }
}

struct DestroyMethod {
    service: Arc<dyn StorageProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for DestroyMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, destroy);
    }
}

#[async_trait]
pub trait StorageProviderService: Sync {
    async fn health(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.StorageProviderService/Health is not supported".to_string())))
    }
    async fn capabilities(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::CapabilityRequest) -> ::ttrpc::Result<super::common::CapabilityResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.StorageProviderService/Capabilities is not supported".to_string())))
    }
    async fn plan(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.StorageProviderService/Plan is not supported".to_string())))
    }
    async fn ensure(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.StorageProviderService/Ensure is not supported".to_string())))
    }
    async fn inspect(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.StorageProviderService/Inspect is not supported".to_string())))
    }
    async fn adopt(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.StorageProviderService/Adopt is not supported".to_string())))
    }
    async fn snapshot(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.StorageProviderService/Snapshot is not supported".to_string())))
    }
    async fn destroy(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.StorageProviderService/Destroy is not supported".to_string())))
    }
}

pub fn create_storage_provider_service(service: Arc<dyn StorageProviderService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("Health".to_string(),
                    Box::new(HealthMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Capabilities".to_string(),
                    Box::new(CapabilitiesMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Plan".to_string(),
                    Box::new(PlanMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Ensure".to_string(),
                    Box::new(EnsureMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Inspect".to_string(),
                    Box::new(InspectMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Adopt".to_string(),
                    Box::new(AdoptMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Snapshot".to_string(),
                    Box::new(SnapshotMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Destroy".to_string(),
                    Box::new(DestroyMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("d2b.provider.v2.StorageProviderService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
