// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct AudioProviderServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl AudioProviderServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        AudioProviderServiceClient {
            client,
        }
    }

    pub async fn health(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.AudioProviderService", "Health", cres);
    }

    pub async fn capabilities(&self, ctx: ttrpc::context::Context, req: &super::common::CapabilityRequest) -> ::ttrpc::Result<super::common::CapabilityResponse> {
        let mut cres = super::common::CapabilityResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.AudioProviderService", "Capabilities", cres);
    }

    pub async fn open(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.AudioProviderService", "Open", cres);
    }

    pub async fn set_state(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.AudioProviderService", "SetState", cres);
    }

    pub async fn inspect(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.AudioProviderService", "Inspect", cres);
    }

    pub async fn adopt(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.AudioProviderService", "Adopt", cres);
    }

    pub async fn close(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.AudioProviderService", "Close", cres);
    }
}

struct HealthMethod {
    service: Arc<dyn AudioProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for HealthMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, health);
    }
}

struct CapabilitiesMethod {
    service: Arc<dyn AudioProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CapabilitiesMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, CapabilityRequest, capabilities);
    }
}

struct OpenMethod {
    service: Arc<dyn AudioProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for OpenMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, open);
    }
}

struct SetStateMethod {
    service: Arc<dyn AudioProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for SetStateMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, set_state);
    }
}

struct InspectMethod {
    service: Arc<dyn AudioProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for InspectMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, inspect);
    }
}

struct AdoptMethod {
    service: Arc<dyn AudioProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for AdoptMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, adopt);
    }
}

struct CloseMethod {
    service: Arc<dyn AudioProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CloseMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, close);
    }
}

#[async_trait]
pub trait AudioProviderService: Sync {
    async fn health(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.AudioProviderService/Health is not supported".to_string())))
    }
    async fn capabilities(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::CapabilityRequest) -> ::ttrpc::Result<super::common::CapabilityResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.AudioProviderService/Capabilities is not supported".to_string())))
    }
    async fn open(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.AudioProviderService/Open is not supported".to_string())))
    }
    async fn set_state(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.AudioProviderService/SetState is not supported".to_string())))
    }
    async fn inspect(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.AudioProviderService/Inspect is not supported".to_string())))
    }
    async fn adopt(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.AudioProviderService/Adopt is not supported".to_string())))
    }
    async fn close(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.AudioProviderService/Close is not supported".to_string())))
    }
}

pub fn create_audio_provider_service(service: Arc<dyn AudioProviderService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("Health".to_string(),
                    Box::new(HealthMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Capabilities".to_string(),
                    Box::new(CapabilitiesMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Open".to_string(),
                    Box::new(OpenMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("SetState".to_string(),
                    Box::new(SetStateMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Inspect".to_string(),
                    Box::new(InspectMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Adopt".to_string(),
                    Box::new(AdoptMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Close".to_string(),
                    Box::new(CloseMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("d2b.provider.v2.AudioProviderService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
