// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct CredentialProviderServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl CredentialProviderServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        CredentialProviderServiceClient {
            client,
        }
    }

    pub async fn health(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.CredentialProviderService", "Health", cres);
    }

    pub async fn capabilities(&self, ctx: ttrpc::context::Context, req: &super::common::CapabilityRequest) -> ::ttrpc::Result<super::common::CapabilityResponse> {
        let mut cres = super::common::CapabilityResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.CredentialProviderService", "Capabilities", cres);
    }

    pub async fn status(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.CredentialProviderService", "Status", cres);
    }

    pub async fn acquire_lease(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.CredentialProviderService", "AcquireLease", cres);
    }

    pub async fn refresh_lease(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.CredentialProviderService", "RefreshLease", cres);
    }

    pub async fn revoke_lease(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.CredentialProviderService", "RevokeLease", cres);
    }
}

struct HealthMethod {
    service: Arc<dyn CredentialProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for HealthMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, health);
    }
}

struct CapabilitiesMethod {
    service: Arc<dyn CredentialProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CapabilitiesMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, CapabilityRequest, capabilities);
    }
}

struct StatusMethod {
    service: Arc<dyn CredentialProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for StatusMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, status);
    }
}

struct AcquireLeaseMethod {
    service: Arc<dyn CredentialProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for AcquireLeaseMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, acquire_lease);
    }
}

struct RefreshLeaseMethod {
    service: Arc<dyn CredentialProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for RefreshLeaseMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, refresh_lease);
    }
}

struct RevokeLeaseMethod {
    service: Arc<dyn CredentialProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for RevokeLeaseMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, revoke_lease);
    }
}

#[async_trait]
pub trait CredentialProviderService: Sync {
    async fn health(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.CredentialProviderService/Health is not supported".to_string())))
    }
    async fn capabilities(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::CapabilityRequest) -> ::ttrpc::Result<super::common::CapabilityResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.CredentialProviderService/Capabilities is not supported".to_string())))
    }
    async fn status(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.CredentialProviderService/Status is not supported".to_string())))
    }
    async fn acquire_lease(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.CredentialProviderService/AcquireLease is not supported".to_string())))
    }
    async fn refresh_lease(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.CredentialProviderService/RefreshLease is not supported".to_string())))
    }
    async fn revoke_lease(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.CredentialProviderService/RevokeLease is not supported".to_string())))
    }
}

pub fn create_credential_provider_service(service: Arc<dyn CredentialProviderService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("Health".to_string(),
                    Box::new(HealthMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Capabilities".to_string(),
                    Box::new(CapabilitiesMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Status".to_string(),
                    Box::new(StatusMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("AcquireLease".to_string(),
                    Box::new(AcquireLeaseMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("RefreshLease".to_string(),
                    Box::new(RefreshLeaseMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("RevokeLease".to_string(),
                    Box::new(RevokeLeaseMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("d2b.provider.v2.CredentialProviderService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
