// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct TransportProviderServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl TransportProviderServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        TransportProviderServiceClient {
            client,
        }
    }

    pub async fn health(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.TransportProviderService", "Health", cres);
    }

    pub async fn capabilities(&self, ctx: ttrpc::context::Context, req: &super::common::CapabilityRequest) -> ::ttrpc::Result<super::common::CapabilityResponse> {
        let mut cres = super::common::CapabilityResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.TransportProviderService", "Capabilities", cres);
    }

    pub async fn connect(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.TransportProviderService", "Connect", cres);
    }

    pub async fn listen(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.TransportProviderService", "Listen", cres);
    }

    pub async fn issue_binding(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.TransportProviderService", "IssueBinding", cres);
    }

    pub async fn revoke_binding(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.TransportProviderService", "RevokeBinding", cres);
    }

    pub async fn inspect(&self, ctx: ttrpc::context::Context, req: &super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        let mut cres = super::common::ProviderResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.provider.v2.TransportProviderService", "Inspect", cres);
    }
}

struct HealthMethod {
    service: Arc<dyn TransportProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for HealthMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, health);
    }
}

struct CapabilitiesMethod {
    service: Arc<dyn TransportProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CapabilitiesMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, CapabilityRequest, capabilities);
    }
}

struct ConnectMethod {
    service: Arc<dyn TransportProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ConnectMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, connect);
    }
}

struct ListenMethod {
    service: Arc<dyn TransportProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ListenMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, listen);
    }
}

struct IssueBindingMethod {
    service: Arc<dyn TransportProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for IssueBindingMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, issue_binding);
    }
}

struct RevokeBindingMethod {
    service: Arc<dyn TransportProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for RevokeBindingMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, revoke_binding);
    }
}

struct InspectMethod {
    service: Arc<dyn TransportProviderService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for InspectMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ProviderRequest, inspect);
    }
}

#[async_trait]
pub trait TransportProviderService: Sync {
    async fn health(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.TransportProviderService/Health is not supported".to_string())))
    }
    async fn capabilities(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::CapabilityRequest) -> ::ttrpc::Result<super::common::CapabilityResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.TransportProviderService/Capabilities is not supported".to_string())))
    }
    async fn connect(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.TransportProviderService/Connect is not supported".to_string())))
    }
    async fn listen(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.TransportProviderService/Listen is not supported".to_string())))
    }
    async fn issue_binding(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.TransportProviderService/IssueBinding is not supported".to_string())))
    }
    async fn revoke_binding(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.TransportProviderService/RevokeBinding is not supported".to_string())))
    }
    async fn inspect(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ProviderRequest) -> ::ttrpc::Result<super::common::ProviderResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.provider.v2.TransportProviderService/Inspect is not supported".to_string())))
    }
}

pub fn create_transport_provider_service(service: Arc<dyn TransportProviderService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("Health".to_string(),
                    Box::new(HealthMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Capabilities".to_string(),
                    Box::new(CapabilitiesMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Connect".to_string(),
                    Box::new(ConnectMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Listen".to_string(),
                    Box::new(ListenMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("IssueBinding".to_string(),
                    Box::new(IssueBindingMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("RevokeBinding".to_string(),
                    Box::new(RevokeBindingMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Inspect".to_string(),
                    Box::new(InspectMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("d2b.provider.v2.TransportProviderService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
