// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct RuntimeSystemdUserServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl RuntimeSystemdUserServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        RuntimeSystemdUserServiceClient {
            client,
        }
    }

    pub async fn ensure_scope(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.runtime.systemd-user.v2.RuntimeSystemdUserService", "EnsureScope", cres);
    }

    pub async fn start_process(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.runtime.systemd-user.v2.RuntimeSystemdUserService", "StartProcess", cres);
    }

    pub async fn inspect_process(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.runtime.systemd-user.v2.RuntimeSystemdUserService", "InspectProcess", cres);
    }

    pub async fn adopt_process(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.runtime.systemd-user.v2.RuntimeSystemdUserService", "AdoptProcess", cres);
    }

    pub async fn stop_process(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.runtime.systemd-user.v2.RuntimeSystemdUserService", "StopProcess", cres);
    }

    pub async fn open_terminal(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.runtime.systemd-user.v2.RuntimeSystemdUserService", "OpenTerminal", cres);
    }

    pub async fn cancel(&self, ctx: ttrpc::context::Context, req: &super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        let mut cres = super::common::CancelResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.runtime.systemd-user.v2.RuntimeSystemdUserService", "Cancel", cres);
    }
}

struct EnsureScopeMethod {
    service: Arc<dyn RuntimeSystemdUserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for EnsureScopeMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, ensure_scope);
    }
}

struct StartProcessMethod {
    service: Arc<dyn RuntimeSystemdUserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for StartProcessMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, start_process);
    }
}

struct InspectProcessMethod {
    service: Arc<dyn RuntimeSystemdUserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for InspectProcessMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, inspect_process);
    }
}

struct AdoptProcessMethod {
    service: Arc<dyn RuntimeSystemdUserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for AdoptProcessMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, adopt_process);
    }
}

struct StopProcessMethod {
    service: Arc<dyn RuntimeSystemdUserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for StopProcessMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, stop_process);
    }
}

struct OpenTerminalMethod {
    service: Arc<dyn RuntimeSystemdUserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for OpenTerminalMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, open_terminal);
    }
}

struct CancelMethod {
    service: Arc<dyn RuntimeSystemdUserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CancelMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, CancelRequest, cancel);
    }
}

#[async_trait]
pub trait RuntimeSystemdUserService: Sync {
    async fn ensure_scope(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.runtime.systemd-user.v2.RuntimeSystemdUserService/EnsureScope is not supported".to_string())))
    }
    async fn start_process(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.runtime.systemd-user.v2.RuntimeSystemdUserService/StartProcess is not supported".to_string())))
    }
    async fn inspect_process(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.runtime.systemd-user.v2.RuntimeSystemdUserService/InspectProcess is not supported".to_string())))
    }
    async fn adopt_process(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.runtime.systemd-user.v2.RuntimeSystemdUserService/AdoptProcess is not supported".to_string())))
    }
    async fn stop_process(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.runtime.systemd-user.v2.RuntimeSystemdUserService/StopProcess is not supported".to_string())))
    }
    async fn open_terminal(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.runtime.systemd-user.v2.RuntimeSystemdUserService/OpenTerminal is not supported".to_string())))
    }
    async fn cancel(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.runtime.systemd-user.v2.RuntimeSystemdUserService/Cancel is not supported".to_string())))
    }
}

pub fn create_runtime_systemd_user_service(service: Arc<dyn RuntimeSystemdUserService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("EnsureScope".to_string(),
                    Box::new(EnsureScopeMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("StartProcess".to_string(),
                    Box::new(StartProcessMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("InspectProcess".to_string(),
                    Box::new(InspectProcessMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("AdoptProcess".to_string(),
                    Box::new(AdoptProcessMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("StopProcess".to_string(),
                    Box::new(StopProcessMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("OpenTerminal".to_string(),
                    Box::new(OpenTerminalMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Cancel".to_string(),
                    Box::new(CancelMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("d2b.runtime.systemd-user.v2.RuntimeSystemdUserService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
