// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct SecurityKeyServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl SecurityKeyServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        SecurityKeyServiceClient {
            client,
        }
    }

    pub async fn begin_ceremony(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.security-key.v2.SecurityKeyService", "BeginCeremony", cres);
    }

    pub async fn exchange_report(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.security-key.v2.SecurityKeyService", "ExchangeReport", cres);
    }

    pub async fn approve(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.security-key.v2.SecurityKeyService", "Approve", cres);
    }

    pub async fn cancel_ceremony(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.security-key.v2.SecurityKeyService", "CancelCeremony", cres);
    }

    pub async fn inspect(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.security-key.v2.SecurityKeyService", "Inspect", cres);
    }

    pub async fn cancel(&self, ctx: ttrpc::context::Context, req: &super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        let mut cres = super::common::CancelResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.security-key.v2.SecurityKeyService", "Cancel", cres);
    }
}

struct BeginCeremonyMethod {
    service: Arc<dyn SecurityKeyService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for BeginCeremonyMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, begin_ceremony);
    }
}

struct ExchangeReportMethod {
    service: Arc<dyn SecurityKeyService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ExchangeReportMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, exchange_report);
    }
}

struct ApproveMethod {
    service: Arc<dyn SecurityKeyService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for ApproveMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, approve);
    }
}

struct CancelCeremonyMethod {
    service: Arc<dyn SecurityKeyService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CancelCeremonyMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, cancel_ceremony);
    }
}

struct InspectMethod {
    service: Arc<dyn SecurityKeyService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for InspectMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, inspect);
    }
}

struct CancelMethod {
    service: Arc<dyn SecurityKeyService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CancelMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, CancelRequest, cancel);
    }
}

#[async_trait]
pub trait SecurityKeyService: Sync {
    async fn begin_ceremony(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.security-key.v2.SecurityKeyService/BeginCeremony is not supported".to_string())))
    }
    async fn exchange_report(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.security-key.v2.SecurityKeyService/ExchangeReport is not supported".to_string())))
    }
    async fn approve(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.security-key.v2.SecurityKeyService/Approve is not supported".to_string())))
    }
    async fn cancel_ceremony(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.security-key.v2.SecurityKeyService/CancelCeremony is not supported".to_string())))
    }
    async fn inspect(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.security-key.v2.SecurityKeyService/Inspect is not supported".to_string())))
    }
    async fn cancel(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.security-key.v2.SecurityKeyService/Cancel is not supported".to_string())))
    }
}

pub fn create_security_key_service(service: Arc<dyn SecurityKeyService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("BeginCeremony".to_string(),
                    Box::new(BeginCeremonyMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("ExchangeReport".to_string(),
                    Box::new(ExchangeReportMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Approve".to_string(),
                    Box::new(ApproveMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("CancelCeremony".to_string(),
                    Box::new(CancelCeremonyMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Inspect".to_string(),
                    Box::new(InspectMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Cancel".to_string(),
                    Box::new(CancelMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("d2b.security-key.v2.SecurityKeyService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
