// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct UserServiceClient {
    client: ::ttrpc::r#async::Client,
}

impl UserServiceClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        UserServiceClient {
            client,
        }
    }

    pub async fn prompt(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.user.v2.UserService", "Prompt", cres);
    }

    pub async fn poll_prompt(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.user.v2.UserService", "PollPrompt", cres);
    }

    pub async fn cancel_prompt(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.user.v2.UserService", "CancelPrompt", cres);
    }

    pub async fn delete_credential(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.user.v2.UserService", "DeleteCredential", cres);
    }

    pub async fn revoke_export(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.user.v2.UserService", "RevokeExport", cres);
    }

    pub async fn inspect(&self, ctx: ttrpc::context::Context, req: &super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        let mut cres = super::common::ServiceResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.user.v2.UserService", "Inspect", cres);
    }

    pub async fn cancel(&self, ctx: ttrpc::context::Context, req: &super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        let mut cres = super::common::CancelResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "d2b.user.v2.UserService", "Cancel", cres);
    }
}

struct PromptMethod {
    service: Arc<dyn UserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for PromptMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, prompt);
    }
}

struct PollPromptMethod {
    service: Arc<dyn UserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for PollPromptMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, poll_prompt);
    }
}

struct CancelPromptMethod {
    service: Arc<dyn UserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CancelPromptMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, cancel_prompt);
    }
}

struct DeleteCredentialMethod {
    service: Arc<dyn UserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for DeleteCredentialMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, delete_credential);
    }
}

struct RevokeExportMethod {
    service: Arc<dyn UserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for RevokeExportMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, revoke_export);
    }
}

struct InspectMethod {
    service: Arc<dyn UserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for InspectMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, ServiceRequest, inspect);
    }
}

struct CancelMethod {
    service: Arc<dyn UserService + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for CancelMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, common, CancelRequest, cancel);
    }
}

#[async_trait]
pub trait UserService: Sync {
    async fn prompt(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.user.v2.UserService/Prompt is not supported".to_string())))
    }
    async fn poll_prompt(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.user.v2.UserService/PollPrompt is not supported".to_string())))
    }
    async fn cancel_prompt(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.user.v2.UserService/CancelPrompt is not supported".to_string())))
    }
    async fn delete_credential(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.user.v2.UserService/DeleteCredential is not supported".to_string())))
    }
    async fn revoke_export(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.user.v2.UserService/RevokeExport is not supported".to_string())))
    }
    async fn inspect(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::ServiceRequest) -> ::ttrpc::Result<super::common::ServiceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.user.v2.UserService/Inspect is not supported".to_string())))
    }
    async fn cancel(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::common::CancelRequest) -> ::ttrpc::Result<super::common::CancelResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/d2b.user.v2.UserService/Cancel is not supported".to_string())))
    }
}

pub fn create_user_service(service: Arc<dyn UserService + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("Prompt".to_string(),
                    Box::new(PromptMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("PollPrompt".to_string(),
                    Box::new(PollPromptMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("CancelPrompt".to_string(),
                    Box::new(CancelPromptMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("DeleteCredential".to_string(),
                    Box::new(DeleteCredentialMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("RevokeExport".to_string(),
                    Box::new(RevokeExportMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Inspect".to_string(),
                    Box::new(InspectMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("Cancel".to_string(),
                    Box::new(CancelMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("d2b.user.v2.UserService".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
