// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by pure
// @generated

#![allow(clippy::bool_comparison)]
#![allow(clippy::derivable_impls)]
#![allow(clippy::match_like_matches_macro)]
#![allow(clippy::match_ref_pats)]
#![allow(clippy::needless_borrow)]
#![allow(clippy::redundant_static_lifetimes)]
#![allow(clippy::vec_init_then_push)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `wayland.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\rwayland.proto\x12\x0ed2b.wayland.v2\x1a\x0ccommon.proto2\x93\x03\n\
    \x0eWaylandService\x12L\n\x0bOpenDisplay\x12\x1d.d2b.common.v2.ServiceRe\
    quest\x1a\x1e.d2b.common.v2.ServiceResponse\x12O\n\x0eInspectDisplay\x12\
    \x1d.d2b.common.v2.ServiceRequest\x1a\x1e.d2b.common.v2.ServiceResponse\
    \x12M\n\x0cCloseDisplay\x12\x1d.d2b.common.v2.ServiceRequest\x1a\x1e.d2b\
    .common.v2.ServiceResponse\x12L\n\x0bBridgeReady\x12\x1d.d2b.common.v2.S\
    erviceRequest\x1a\x1e.d2b.common.v2.ServiceResponse\x12E\n\x06Cancel\x12\
    \x1c.d2b.common.v2.CancelRequest\x1a\x1d.d2b.common.v2.CancelResponseb\
    \x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::common::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
