#!/usr/bin/env bash
# Hermetic W0b runner-shape snapshot gate.

set -euo pipefail

HERE=$(dirname "$(readlink -f "$0")")
ROOT=${ROOT:-$(dirname "$HERE")}
export NL_LOG=${NL_LOG:-$ROOT/.runner-shape-snapshot.log}
export TMPDIR=${TMPDIR:-$ROOT/.copilot-work}
mkdir -p "$TMPDIR"

# shellcheck source=lib.sh
. "$HERE/lib.sh"

runner_expr() {
  cat <<NIX
let
  root = builtins.getFlake (toString $ROOT);
  nixos = root.inputs.nixpkgs.lib.nixosSystem {
    system = "x86_64-linux";
    modules = [
      root.nixosModules.default
      (import $ROOT/examples/minimal/configuration.nix)
      ({ lib, ... }: {
        # W0b s1 audits Cloud Hypervisor runner shape. The current
        # minimal example remains otherwise unchanged; this test-only
        # module forces the backend selected by the portability plan.
        microvm.vms.corp-vm.config.microvm.hypervisor = lib.mkForce "cloud-hypervisor";
      })
    ];
  };
in nixos.config.microvm.vms.corp-vm.config.config.microvm.declaredRunner
NIX
}

build_runner() {
  if ! command -v nix >/dev/null 2>&1; then
    return 75
  fi
  nix --no-warn-dirty build --impure --no-link --print-out-paths --expr "$(runner_expr)"
}

declared_runner_snapshot() {
  local runner
  runner=$(build_runner) || return $?
  printf '# W0b s1 runner-shape snapshot generated by: nix --no-warn-dirty build --impure --no-link --print-out-paths --expr "$(tests/runner-shape-snapshot.sh runner_expr)"\n'
  printf '%s\n' "$runner"
}

cloud_hypervisor_argv_snapshot() {
  local runner argv
  runner=$(build_runner) || return $?
  if [ ! -r "$runner/bin/microvm-run" ]; then
    fail "runner missing bin/microvm-run: $runner"
    return 1
  fi
  argv=$(sed -n '/^exec -a /p' "$runner/bin/microvm-run")
  if [ -z "$argv" ]; then
    fail "could not extract cloud-hypervisor exec line from $runner/bin/microvm-run"
    return 1
  fi
  printf '# W0b s1 runner-shape snapshot generated by: build declaredRunner with tests/runner-shape-snapshot.sh and extract /^exec -a / from bin/microvm-run\n'
  printf '%s\n' "$argv"
}

compare_snapshot() {
  local name="$1" generator="$2" actual rc
  local golden="$ROOT/tests/golden/runner-shape/$name"
  if [ ! -r "$golden" ]; then
    fail "missing runner-shape golden: $golden"
    return 1
  fi

  set +e
  actual=$("$generator" 2> >(tee -a "$NL_LOG" >&2))
  rc=$?
  set -e
  if [ "$rc" -eq 75 ]; then
    # W0fu1 test-1: no "looks-unrelated" waivers. Only a missing nix
    # binary is an environmental skip; eval/build failures must fail closed.
    log "  SKIP: runner-shape snapshot $name (nix is not on PATH)"
    return 75
  elif [ "$rc" -ne 0 ]; then
    fail "runner-shape snapshot generator failed: $name"
    return 1
  fi

  if diff -u "$golden" <(printf '%s\n' "$actual") >&2; then
    ok "runner-shape snapshot: $name"
  else
    fail "runner-shape snapshot drift: $name"
  fi
}

case "${1:-check}" in
  runner_expr)
    runner_expr
    ;;
  declared-runner)
    declared_runner_snapshot
    ;;
  cloud-hypervisor-argv)
    cloud_hypervisor_argv_snapshot
    ;;
  check)
    log "==> W0b runner-shape snapshots"
    compare_snapshot examples-minimal-declaredRunner.txt declared_runner_snapshot
    compare_snapshot cloud-hypervisor-argv-minimal.txt cloud_hypervisor_argv_snapshot
    log "Runner-shape snapshots OK"
    ;;
  *)
    fail "usage: $0 [check|runner_expr|declared-runner|cloud-hypervisor-argv]"
    exit 2
    ;;
esac
