# Generated by `nix flake init -t github:vicondoa/d2b`.
#
# Walk through every numbered `TODO:` marker below and replace the
# sentinel value with one that matches YOUR host. There are 7 TODOs;
# the README next to this file enumerates them with rationale.
#
# TODOs 2 and 3 are gated by the `assertions = [ … ]` block at the
# bottom of this file — `nix flake check` will fail with an
# actionable message until you replace those sentinels. TODO 1
# (hardware) is gated by NixOS's own `fileSystems."/"` check.
# TODOs 4-7 ship with plausible defaults (waylandUser=user, an
# RFC 1918 host LAN, RFC 5737 doc-range uplink, etc.) that pass
# `nix flake check` — they need your judgement-level review
# before activation, NOT an eval gate. (The framework's CIDR
# validators in `nixos-modules/network.nix` parse the strings as
# IPv4 arithmetic and would crash eval before any TODO assertion
# could fire if we used non-numeric sentinels like
# `"TODO/REPLACE/CIDR"`; see templates/default/README.md for the
# full rationale.)
{ pkgs, lib, config, ... }:

let
  # Centralised so renaming the Wayland session user is a single
  # edit. Everything below (`users.users.${user}` and `d2b.site.*`)
  # reads this binding.
  user = "TODO-set-user";
in
{

  # ────────────────────────────────────────────────────────────────
  # TODO 1: boot, filesystems, hardware
  # ────────────────────────────────────────────────────────────────
  # d2b is host-shape-agnostic — bring your own bootloader,
  # disk layout, kernel modules, hardware-configuration.nix, etc.
  # For a fresh install the easiest starting point is:
  #
  #   sudo nixos-generate-config --root /mnt --no-filesystems
  #
  # then drop the resulting `hardware-configuration.nix` next to this
  # file and uncomment the import below.

  # imports = [ ./hardware-configuration.nix ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ────────────────────────────────────────────────────────────────
  # TODO 2: hostname + host networking
  # ────────────────────────────────────────────────────────────────
  networking.hostName = "TODO-set-hostname";
  networking.networkmanager.enable = true;

  # ────────────────────────────────────────────────────────────────
  # TODO 3: your Wayland user
  # ────────────────────────────────────────────────────────────────
  # This is the human who runs Plasma/Sway/Hyprland. Change the
  # `user` binding at the top of this file; every reference below
  # picks up the new name automatically. d2b does NOT create
  # this user — declare it normally here.
  users.users.${user} = {
    isNormalUser = true;
    uid = 1000;
    extraGroups = [ "wheel" "video" "audio" "networkmanager" ];
    # Required: at least one of `hashedPassword` or
    # `openssh.authorizedKeys.keys` must be set, or you'll have no
    # way to log in after first boot. Pick whichever matches your
    # workflow.
    # hashedPassword = "$y$j9T$...";          # mkpasswd -m yescrypt
    # openssh.authorizedKeys.keys = [ "ssh-ed25519 AAAA... you@host" ];
  };

  # ────────────────────────────────────────────────────────────────
  # d2b — site-level configuration
  # ────────────────────────────────────────────────────────────────
  d2b.site = {
    # TODO 4: keep at `user` (TODO 3) for a graphical host, or set
    # to `null` for a fully headless deployment (no graphics/audio
    # VMs).
    waylandUser = user;

    # Users who get the `d2b` lifecycle group for commands such as
    # `d2b vm start <vm> --apply` without `sudo`.
    launcherUsers = [ user ];

    # SSH public keys to inject into every d2b VM's
    # authorized_keys (alongside the framework-managed key). One
    # entry per operator-side public key. The assertion block at
    # the bottom of this file requires at least one.
    userAuthorizedKeys = [ ];

    # Flip to `true` if you plan to use `d2b usb <vm>` for
    # Yubikey USBIP passthrough. Default `true` keeps the Yubico
    # udev rules enabled; `usbip-host` loads only once an enabled VM
    # also opts into `usbip.yubikey`. Set `false` to skip them.
    yubikey.enable = false;
  };
  d2b.acceptDestructiveV2Cutover = true;

  # TODO 5: your host's primary LAN CIDR(s).
  # Look it up with `ip route` — a typical home LAN is
  # `192.168.1.0/24`. d2b uses this list to:
  #   - assert no env CIDR overlaps your real LAN at eval time
  #   - inject DROP rules into every env's net VM so workload VMs
  #     can't reach your printer / NAS / other workstations
  d2b.hostLanCidrs = [ "192.168.1.0/24" ];

  # ────────────────────────────────────────────────────────────────
  # d2b — one host-local realm
  # ────────────────────────────────────────────────────────────────
  d2b.realms.work = {
    path = "work";
    placement = "host-local";
    broker = {
      enable = true;
      hostMutation = true;
    };
    network = {
      # TODO 6: workload LAN CIDR. Must be a /24 ending in `.0`.
      mode = "declared";
      lanSubnet = "10.20.0.0/24";

      # TODO 7: host↔realm network-workload uplink.
      uplinkSubnet = "192.0.2.0/30";
    };
    providers.runtime = {
      type = "runtime";
      implementationId = "cloud-hypervisor";
    };
    workloads.corp-vm = {
      providerRefs.runtime = "runtime";
      config = { ... }: {
        networking.hostName = "corp-vm";

        users.users.${user} = {
          isNormalUser = true;
          uid = 1000;
          extraGroups = [ "wheel" ];
        };

        system.stateVersion = "25.11";
      };
    };
  };

  # NixOS state version on the host. See the top of `configuration.nix`
  # in any fresh `nixos-generate-config` output for the rationale.
  system.stateVersion = "25.11";

  # ────────────────────────────────────────────────────────────────
  # Sentinel assertions — fail eval until TODOs 2-3 are filled in.
  # ────────────────────────────────────────────────────────────────
  # TODOs 1 (hardware) and 4-7 (network CIDRs, waylandUser) ship
  # with plausible defaults that pass `nix flake check`; they need
  # operator review but are NOT eval-gated. See the file header for
  # the rationale. Each assertion below pairs with one of the
  # eval-gated TODOs; the message names the TODO so the operator
  # knows what to edit.
  assertions = [
    {
      assertion = config.networking.hostName != "TODO-set-hostname";
      message = "Edit configuration.nix — set networking.hostName (TODO 2).";
    }
    {
      assertion = !(lib.elem "TODO-set-user" config.d2b.site.launcherUsers);
      message = "Edit configuration.nix — rename the `user` let-binding at the top of the file (TODO 3); it propagates to users.users.<user> and d2b.site.{waylandUser,launcherUsers}.";
    }
    {
      assertion = config.d2b.site.userAuthorizedKeys != [ ];
      message = "Edit configuration.nix — add at least one SSH public key to d2b.site.userAuthorizedKeys (TODO 3 tail) so you can log in to the workload VM after first boot. (This assertion only inspects `d2b.site.userAuthorizedKeys`; if you intend to rely solely on a host-level password for the Wayland user, the assertion will still fire — flip it locally or supply a stub key.)";
    }
  ];
}
