# Generated by `nix flake init -t github:vicondoa/d2b`.
#
# Replace every TODO before switching the host. The template intentionally
# uses the current Zone resource graph: Nix authors a Guest and its selected
# artifacts; d2bd and the specialized controllers own child lifecycle.
{ pkgs, lib, config, ... }:

let
  user = "TODO-set-user";
  guestSystem = pkgs.runCommand "d2b-guest-system" { } ''
    mkdir -p "$out"
  '';
  cloudHypervisorProvider = pkgs.runCommand "d2b-cloud-hypervisor-provider" { } ''
    mkdir -p "$out"
  '';
in
{
  # TODO 1: replace these placeholders with your real host hardware config.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  networking.hostName = "TODO-set-hostname";
  networking.networkmanager.enable = true;

  # TODO 2: declare the host account used by the operator and Wayland
  # session. d2b does not create host users.
  users.users.${user} = {
    isNormalUser = true;
    uid = 1000;
    extraGroups = [ "wheel" "networkmanager" ];
  };

  d2b.site = {
    waylandUser = user;
    launcherUsers = [ user ];
    userAuthorizedKeys = [ ];
    yubikey.enable = false;
  };

  d2b.artifacts = {
    # TODO 3: replace both placeholder packages with your signed Guest system
    # and Cloud Hypervisor Provider artifacts.
    guest-system = {
      package = guestSystem;
      type = "nixos-system";
    };
    cloud-hypervisor-provider = {
      package = cloudHypervisorProvider;
      type = "provider";
    };
  };

  d2b.zones.local-root.resources = {
    host = {
      type = "Host";
      spec.providerRef = "Provider/system-core";
    };
    runtime-cloud-hypervisor = {
      type = "Provider";
      spec = {
        artifactId = "cloud-hypervisor-provider";
        config.controllerExecutionRef = "Host/host";
      };
    };
    corp-vm = {
      type = "Guest";
      spec = {
        providerRef = "Provider/runtime-cloud-hypervisor";
        systemArtifactId = "guest-system";
      };
    };
  };

  d2b.guestSystems.local-root.corp-vm = {
    config.system.build.toplevel = guestSystem;
  };

  system.stateVersion = "25.11";

  assertions = [
    {
      assertion = config.networking.hostName != "TODO-set-hostname";
      message = "Edit configuration.nix and set networking.hostName.";
    }
    {
      assertion = !(lib.elem "TODO-set-user" config.d2b.site.launcherUsers);
      message = "Edit configuration.nix and replace the user binding.";
    }
    {
      assertion = config.d2b.site.userAuthorizedKeys != [ ];
      message = "Edit configuration.nix and add at least one SSH public key.";
    }
  ];
}
