package(default_visibility = ["//visibility:public"])

load(
    "@rules_rust//cargo:defs.bzl",
    "cargo_build_script",
)
load(
    "@rules_rust//rust:defs.bzl",
    "rust_binary",
    "rust_clippy",
    "rust_doc",
    "rust_doc_test",
    "rust_library",
    "rust_test",
    "rust_unpretty",
    "rustfmt_test",
)

cc_binary(
    name = "inherited-fd-launcher",
    srcs = ["inherited_fd_launcher.c"],
)

cc_binary(
    name = "network-plant",
    srcs = ["network_plant.c"],
)

cc_binary(
    name = "environment-probe",
    srcs = ["environment_probe.c"],
)

genrule(
    name = "environment-probe-action",
    outs = ["environment-action.txt"],
    cmd = "$(location :environment-probe) $@",
    tools = [":environment-probe"],
)

cc_binary(
    name = "sandbox-crash-plant",
    srcs = ["//:tests/tools/d2b-bazel-exec-supervisor/sandbox-crash-plant.c"],
)

genrule(
    name = "network-plant-action",
    outs = ["network-plant-action.txt"],
    tools = [":network-plant"],
    cmd = "$(location :network-plant) > $@",
)

genrule(
    name = "crash-plant-action",
    outs = ["crash-plant-action.txt"],
    tools = [":sandbox-crash-plant"],
    cmd = "$(location :sandbox-crash-plant) --stage $(D2B_STAGE) --liveness-path $(D2B_LIVENESS_PATH) --barrier-path $(D2B_BARRIER_PATH) > $@",
)

cargo_build_script(
    name = "evidence-build-script",
    srcs = ["evidence_build.rs"],
    crate_name = "d2b_evidence_build",
    edition = "2021",
)

rust_library(
    name = "evidence-library",
    srcs = ["evidence_lib.rs"],
    crate_name = "d2b_rules_rust_evidence",
    deps = [":evidence-build-script"],
    edition = "2021",
)

rust_binary(
    name = "evidence-binary",
    srcs = ["evidence_main.rs"],
    crate_name = "d2b_rules_rust_evidence_bin",
    deps = [":evidence-library"],
    edition = "2021",
)

rust_test(
    name = "evidence-test",
    crate = ":evidence-library",
)

rust_doc(
    name = "evidence-doc",
    crate = ":evidence-library",
)

rust_doc_test(
    name = "evidence-doctest",
    crate = ":evidence-library",
)

rust_clippy(
    name = "evidence-clippy",
    deps = [":evidence-binary", ":evidence-library"],
)

rustfmt_test(
    name = "evidence-rustfmt",
    targets = [":evidence-binary", ":evidence-library"],
)

rust_unpretty(
    name = "evidence-unpretty",
    deps = [":evidence-library"],
    mode = "expanded",
)

filegroup(
    name = "rules-rust-evidence-build",
    srcs = [
        ":evidence-binary",
        ":evidence-build-script",
        ":evidence-clippy",
        ":evidence-doc",
    ],
)

filegroup(
    name = "rules-rust-evidence-nightly-build",
    srcs = [
        ":rules-rust-evidence-build",
        ":evidence-unpretty",
    ],
)

test_suite(
    name = "rules-rust-evidence-tests",
    tests = [
        ":evidence-doctest",
        ":evidence-rustfmt",
        ":evidence-test",
    ],
)
