package(default_visibility = ["//visibility:public"])

alias(
    name = "rust_toolchain_x86_64_linux",
    actual = "@default_rust_toolchains//rustc:default_linux_x86_64_1_97_0_rust_toolchain",
)

alias(
    name = "rust_toolchain_aarch64_linux",
    actual = "@default_rust_toolchains//rustc:default_linux_aarch64_1_97_0_rust_toolchain",
)
