load("@gazelle//:def.bzl", "gazelle", "gazelle_binary")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")

# gazelle:rust_cargo_lockfile Cargo.lock
# gazelle:rust_crates_prefix @crates//:
# gazelle:rust_default_edition 2024
# gazelle:rust_mode generate_from_cargo

gazelle_binary(
    name = "gazelle_rust",
    languages = ["@gazelle_rust//rust_language"],
)

gazelle(
    name = "gazelle",
    gazelle = ":gazelle_rust",
)

rust_library(
    name = "gazelle_layout_fixture",
    srcs = ["src/lib.rs"],
    compile_data = ["Cargo.toml"],
    visibility = ["//visibility:public"],
    deps = ["@crates//:serde_json"],
)

rust_binary(
    name = "gazelle_layout_fixture_bin",
    srcs = ["src/main.rs"],
    compile_data = ["Cargo.toml"],
    visibility = ["//visibility:public"],
    deps = [":gazelle_layout_fixture"],
)

# keep
rust_library(
    name = "explicit_exception",
    srcs = ["src/exception.rs"],
    crate_name = "explicit_exception",
)
