//! Session-bound Provider agent and bounded diagnostic audit bridge.

use d2b_contracts::v3::{
    ResourceRef,
    execution_policy::BoundedToken,
    zone_routing::{ZoneLabelId, ZonePath},
};
use d2b_provider_toolkit::ProviderAgentAuditLog;
pub use d2b_provider_toolkit::{ProviderAgentAuditEvent, ProviderAgentAuditOutcome};

/// Closed Provider-agent errors.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProviderAgentError {
    /// Session admission failed.
    SessionDenied,
    /// The bounded audit ring is full.
    AuditBackpressure,
    /// A required field was malformed.
    InvalidInput,
}

impl core::fmt::Display for ProviderAgentError {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str(match self {
            Self::SessionDenied => "provider-agent-session-denied",
            Self::AuditBackpressure => "provider-agent-audit-backpressure",
            Self::InvalidInput => "provider-agent-input-invalid",
        })
    }
}

impl std::error::Error for ProviderAgentError {}

/// A Provider agent bound to one Zone and one Provider reference.
///
/// The toolkit owns the event shape and bounded ring. This agent only adapts
/// the Provider's session lifecycle inputs to that admitted boundary; it does
/// not construct authoritative audit records or hold session authority.
#[derive(Debug)]
pub struct ProviderAgentProcess {
    zone: ZonePath,
    provider_ref: ResourceRef,
    audit: ProviderAgentAuditLog,
    capacity: usize,
}

impl ProviderAgentProcess {
    /// Construct a session-bound agent.
    pub fn new(
        zone: impl Into<String>,
        source: impl Into<String>,
        capacity: usize,
    ) -> Result<Self, ProviderAgentError> {
        let zone = zone.into();
        let source = source.into();
        if zone.is_empty() || source.is_empty() || capacity == 0 {
            return Err(ProviderAgentError::InvalidInput);
        }
        let zone = ZonePath::new(vec![
            ZoneLabelId::parse(zone).map_err(|_| ProviderAgentError::InvalidInput)?,
        ])
        .map_err(|_| ProviderAgentError::InvalidInput)?;
        let provider_ref = ResourceRef::parse(&format!("Provider/{source}"))
            .map_err(|_| ProviderAgentError::InvalidInput)?;
        let audit = ProviderAgentAuditLog::with_capacity(capacity)
            .map_err(|_| ProviderAgentError::InvalidInput)?;
        Ok(Self {
            zone,
            provider_ref,
            audit,
            capacity,
        })
    }

    /// Record a successful or denied session connection.
    pub fn session_connect(
        &mut self,
        event: impl Into<String>,
        authz_decision: impl Into<String>,
        outcome: impl Into<String>,
    ) -> Result<(), ProviderAgentError> {
        let method = parse_token(event)?;
        let _authz_decision = parse_token(authz_decision)?;
        let outcome = parse_outcome(outcome)?;
        self.push(method, outcome)
    }

    /// Record a ProcessEffect generated by the Provider agent.
    pub fn process_effect(
        &mut self,
        event: impl Into<String>,
        provider: impl Into<String>,
        domain: impl Into<String>,
        outcome: impl Into<String>,
    ) -> Result<(), ProviderAgentError> {
        let method = parse_token(event)?;
        let _provider = parse_token(provider)?;
        let _domain = parse_token(domain)?;
        let outcome = parse_outcome(outcome)?;
        self.push(method, outcome)
    }

    /// Drain the bounded diagnostic snapshot.
    pub fn drain(&mut self) -> impl Iterator<Item = ProviderAgentAuditEvent> {
        let events = self.audit.events().cloned().collect::<Vec<_>>();
        self.audit = ProviderAgentAuditLog::with_capacity(self.capacity)
            .expect("the existing Provider agent capacity remains valid");
        events.into_iter()
    }

    /// Number of retained events.
    pub fn len(&self) -> usize {
        self.audit.len()
    }

    /// Whether the diagnostic ring is empty.
    pub fn is_empty(&self) -> bool {
        self.audit.is_empty()
    }

    fn push(
        &mut self,
        method: BoundedToken,
        outcome: ProviderAgentAuditOutcome,
    ) -> Result<(), ProviderAgentError> {
        if self.audit.len() >= self.capacity {
            return Err(ProviderAgentError::AuditBackpressure);
        }
        self.audit.record(ProviderAgentAuditEvent::new(
            self.zone.clone(),
            self.provider_ref.clone(),
            method,
            outcome,
        ));
        Ok(())
    }
}

fn parse_token(value: impl Into<String>) -> Result<BoundedToken, ProviderAgentError> {
    BoundedToken::parse(value).map_err(|_| ProviderAgentError::InvalidInput)
}

fn parse_outcome(
    value: impl Into<String>,
) -> Result<ProviderAgentAuditOutcome, ProviderAgentError> {
    match value.into().as_str() {
        "ok" | "allowed" | "accepted" => Ok(ProviderAgentAuditOutcome::Accepted),
        "denied" | "rejected" => Ok(ProviderAgentAuditOutcome::Denied),
        "error" | "failed" => Ok(ProviderAgentAuditOutcome::Failed),
        _ => Err(ProviderAgentError::InvalidInput),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn agent_emits_session_connect_event_without_payload() {
        let mut agent = ProviderAgentProcess::new("work", "observability-otel", 2).unwrap();
        agent.session_connect("connect", "allowed", "ok").unwrap();
        let event = agent.drain().next().unwrap();
        assert_eq!(event.method().as_str(), "connect");
        assert_eq!(event.outcome(), ProviderAgentAuditOutcome::Accepted);
    }

    #[test]
    fn agent_rejects_unknown_outcomes_without_retaining_input() {
        let mut agent = ProviderAgentProcess::new("work", "observability-otel", 2).unwrap();
        assert_eq!(
            agent.session_connect("connect", "allowed", "unexpected-value"),
            Err(ProviderAgentError::InvalidInput)
        );
        assert!(agent.is_empty());
    }
}
