//! Session-bound Provider agent and bounded audit bridge.

use std::collections::VecDeque;

use d2b_audit::{
    AuditRecord, AuditRecordFields, ProcessEffectFields, SessionConnectFields, genesis_hash,
};

/// Closed Provider-agent errors.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProviderAgentError {
    /// Session admission failed.
    SessionDenied,
    /// The bounded audit ring is full.
    AuditBackpressure,
    /// A required field was malformed.
    InvalidInput,
}

impl core::fmt::Display for ProviderAgentError {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str(match self {
            Self::SessionDenied => "provider-agent-session-denied",
            Self::AuditBackpressure => "provider-agent-audit-backpressure",
            Self::InvalidInput => "provider-agent-input-invalid",
        })
    }
}

impl std::error::Error for ProviderAgentError {}

/// Bounded Provider-agent audit ring.
#[derive(Debug)]
pub struct ProviderAgentProcess {
    zone: String,
    source: String,
    events: VecDeque<AuditRecord>,
    capacity: usize,
    previous_hash: d2b_audit::AuditHash,
}

impl ProviderAgentProcess {
    /// Construct a session-bound agent.
    pub fn new(
        zone: impl Into<String>,
        source: impl Into<String>,
        capacity: usize,
    ) -> Result<Self, ProviderAgentError> {
        let zone = zone.into();
        let source = source.into();
        if zone.is_empty() || source.is_empty() || capacity == 0 {
            return Err(ProviderAgentError::InvalidInput);
        }
        Ok(Self {
            zone,
            source,
            events: VecDeque::new(),
            capacity,
            previous_hash: genesis_hash(),
        })
    }

    /// Record a successful or denied session connection.
    pub fn session_connect(
        &mut self,
        event: impl Into<String>,
        authz_decision: impl Into<String>,
        outcome: impl Into<String>,
    ) -> Result<(), ProviderAgentError> {
        let fields = SessionConnectFields {
            event: event.into(),
            profile: "NN".to_owned(),
            purpose_class: "local".to_owned(),
            transport_class: "zone_link".to_owned(),
            subject_digest: "sha256:subject".to_owned(),
            authz_decision: authz_decision.into(),
            authz_revision: 0,
            session_gen_digest: "sha256:session".to_owned(),
            outcome: outcome.into(),
            error_code: None,
        };
        self.push(AuditRecordFields::SessionConnect(fields))
    }

    /// Record a ProcessEffect generated by the provider agent.
    pub fn process_effect(
        &mut self,
        event: impl Into<String>,
        provider: impl Into<String>,
        domain: impl Into<String>,
        outcome: impl Into<String>,
    ) -> Result<(), ProviderAgentError> {
        self.push(AuditRecordFields::ProcessEffect(ProcessEffectFields {
            event: event.into(),
            provider: provider.into(),
            domain: domain.into(),
            no_isolation: false,
            execution_ref_digest: "sha256:execution".to_owned(),
            process_uid: "uid-digest".to_owned(),
            outcome: outcome.into(),
            exit_class: None,
        }))
    }

    /// Drain the bounded audit snapshot.
    pub fn drain(&mut self) -> impl Iterator<Item = AuditRecord> + '_ {
        self.events.drain(..)
    }

    /// Number of retained events.
    pub fn len(&self) -> usize {
        self.events.len()
    }

    fn push(&mut self, fields: AuditRecordFields) -> Result<(), ProviderAgentError> {
        if self.events.len() >= self.capacity {
            return Err(ProviderAgentError::AuditBackpressure);
        }
        let record = AuditRecord::new(
            0,
            self.zone.clone(),
            "operation-digest",
            "correlation-digest",
            None,
            self.source.clone(),
            self.previous_hash.clone(),
            fields,
        )
        .map_err(|_| ProviderAgentError::InvalidInput)?;
        self.previous_hash = record.record_hash().clone();
        self.events.push_back(record);
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn agent_emits_session_connect_record_without_payload() {
        let mut agent = ProviderAgentProcess::new("work", "observability-otel", 2).unwrap();
        agent.session_connect("connect", "allowed", "ok").unwrap();
        let record = agent.drain().next().unwrap();
        assert_eq!(record.zone(), "work");
        assert!(
            serde_json::to_string(&record)
                .unwrap()
                .contains("session-connect")
        );
    }
}
