# Generated by `bazel run //packages/xtask:xtask -- gen-nix-inventories`.
# Do not hand-edit: `make test-drift` compares this file byte-for-byte
# against the generator output.
#
# The host accounts and groups the committed principal allocation names
# (`docs/reference/policy/principal-allocation.json`). Numeric identity comes from
# the allocation, so an account cannot pin a colliding or host-specific id
# and a re-seed cannot renumber a live principal.
#
# The template-bound row accounts are not in the allocation: their
# names are derived per Zone from the same trusted Zone rows
# `d2b-core`'s `template_account` composes them from
# (`d2bLib.templateWorkerAccounts`), so they stay config-derived here.
{ config, lib, ... }:

let
  cfg = config.d2b;
  d2bLib = import ./lib.nix { inherit lib; };

  # The allocated principals this module materializes.
  accountRows = [
    {
      name = "d2b-zonert";
      uid = 2373244;
      gid = 2373244;
      description = "d2b Zone resource-store owner";
    }
  ];

  # The allocated principals whose account another module owns: the
  # allocation pins their ids, the daemon and guest-broker modules declare
  # the accounts, and this module must not declare a second one.
  deferredPrincipalIds = {
    "d2bd" = { uid = 997; gid = 997; };
  };

  # The host lifecycle users the site declares: the accounts exist outside
  # this module, membership of the `d2b` admission group is what it grants.
  lifecycleUsers = lib.unique (cfg.site.adminUsers ++ cfg.site.launcherUsers);
  # The accounts every template-bound row class runs as, derived per Zone
  # from the same trusted Zone rows `d2b-core`'s `template_account`
  # composes its names from.
  templateAccounts = d2bLib.templateWorkerAccounts cfg;
  rows = accountRows ++ templateAccounts;

  rowOf = name: lib.findFirst (row: row.name == name) null rows;
  # The allocated identities and the derived per-Zone identities are two
  # independent derivations, so a collision between them is checked here
  # rather than assumed away.
  distinct = f:
    builtins.length (builtins.attrNames (builtins.listToAttrs
      (map (row: { name = f row; value = true; }) rows)));
in
{
  assertions = [
    {
      assertion = distinct (row: row.name) == builtins.length rows;
      message = "d2b host accounts: two provisioned rows compose the same
        account name. Rename the Zone, Device or Provider they are derived
        from; two row classes cannot share one identity.";
    }
    {
      assertion = distinct (row: toString row.uid) == builtins.length rows;
      message = "d2b host accounts: two provisioned accounts collide on a uid.
        The allocated identities and the derived per-Zone identities are two
        independent derivations, so rename the Zone, Device or Provider they
        are derived from.";
    }
    # The host account database carries a name of at most
    # `d2bLib.accountNameLimit` bytes, and the derived per-Zone accounts
    # are already bounded to it by `d2bLib.boundedAccountName`. This is
    # where the allocated principals are proved to fit the same bound,
    # rather than aborting the host's own evaluation at a length the
    # account database cannot hold.
    {
      assertion = builtins.all
        (row: builtins.stringLength row.name <= d2bLib.accountNameLimit)
        rows;
      message = "d2b host accounts: a provisioned account name is longer
        than the bytes the host account database carries. NixOS's own user
        and group options refuse 32 bytes or more, so rename the principal
        the allocation names; a name the host cannot hold is refused by
        the resolver rather than truncated into another identity.";
    }
  ];

  users.groups = {
    # Membership grants admission to the root daemon public socket. Object
    # authorization remains the daemon's SO_PEERCRED and Zone policy check.
    d2b = { };
  } // lib.genAttrs (map (row: row.name) rows) (name: {
    gid = (rowOf name).gid;
  });

  users.users = lib.mkMerge [
    (lib.genAttrs lifecycleUsers (_: {
      extraGroups = [ "d2b" ];
    }))
    (lib.listToAttrs (map
      (row: lib.nameValuePair row.name {
        isSystemUser = true;
        uid = row.uid;
        group = row.name;
        description = row.description;
      })
      rows))
  ];
}
