# nixos-modules/niri-vm-borders.nix — opt-in niri window-rule include
# generation for realm workloads with mediated Wayland displays.
#
# When `d2b.site.ui.compositors.niri.enable = true` or the legacy
# `d2b.site.niriVmBorders.enable = true`, installs a KDL file
# at the configured path (default `/etc/d2b/niri-vm-borders.kdl`)
# containing:
#   - a rule to hide the host-side crosvm GPU sidecar scanout window;
#   - one window-rule per normalized Wayland display mapping, matching
#     workload-scoped app ids and applying the owning realm's accent.
#
# Operators source the file from their niri config with:
#   include "/etc/d2b/niri-vm-borders.kdl"
#
# Requires niri ≥ 0.1.9 for include-directive support.
{ lib, config, ... }:

let
  legacyCfg = config.d2b.site.niriVmBorders;
  cfg = config.d2b.site.ui.compositors.niri;
  index = config.d2b._index;
  colors = config.d2b._uiColors;

  niriEnabled = cfg.enable || legacyCfg.enable;
  outputPath = if cfg.enable then cfg.outputPath else legacyCfg.outputPath;

  displayMappings = lib.sort
    (left: right: lib.lessThan left.workloadId right.workloadId)
    index.providerRegistryV2Mappings.display;

  makeBorderBlock = border: ''
        border {
            on
            active-color "${border.active}"
            inactive-color "${border.inactive}"
            urgent-color "${border.urgent}"
        }
  '';

  makeWorkloadRule = mapping:
    let
      workload = index.workloads.byId.${mapping.workloadId};
      border = colors.vms.${mapping.workloadId}.border;
    in
    ''
      // Borders for workload: ${workload.canonicalTarget}
      window-rule {
          match app-id=r#"^d2b\.${mapping.workloadId}\."#
    ${makeBorderBlock border}
      }
    '';

  workloadRules = lib.concatMapStrings makeWorkloadRule displayMappings;

  # The path key for environment.etc is relative to /etc/.
  etcKey = lib.removePrefix "/etc/" outputPath;

  kdlContent = ''
    // Generated by d2b. Source this from your niri config with:
    //
    //   include "${outputPath}"
    //
    // Requires niri >= 0.1.9 (KDL include directive).
    //
    // Re-generate after adding or removing display-bound workloads by running
    // nixos-rebuild switch (or nixos-rebuild build to preview).

    // Hide the host-side crosvm GPU sidecar scanout window.
    // This window is created directly by the crosvm gpu runner on the
    // host compositor and is not part of the guest Wayland session.
    // It is typically a blank/invisible window that should not appear
    // in the niri overview or receive a border.
    window-rule {
        match app-id=r#"^crosvm$"#
        draw-border-with-background false
        border {
            off
        }
    }

    ${workloadRules}
  '';

in
{
  options.d2b.site.niriVmBorders = {
    enable = lib.mkEnableOption ''
      Generate a niri KDL window-rule include file for realm workload
      border coloring and crosvm scanout-window hiding.

      When enabled, installs a KDL file at `outputPath` (default
      `/etc/d2b/niri-vm-borders.kdl`) containing one
      `window-rule` per normalized Wayland display mapping. Rules match
      the workload-scoped app-id prefix written by the host-side Wayland
      proxy. Each rule applies the owning realm's resolved accent color.

      To activate the rules, add the following line to your niri
      `config.kdl`:

          include "/etc/d2b/niri-vm-borders.kdl"

      Requires niri ≥ 0.1.9 for include-directive support.

      This option does not mutate the user's niri config
      automatically — the `include` line must be added manually.
    '';

    outputPath = lib.mkOption {
      type = lib.types.strMatching "^/etc/.*";
      default = "/etc/d2b/niri-vm-borders.kdl";
      example = "/etc/d2b/niri-vm-borders.kdl";
      description = ''
        Absolute path under `/etc/` where the generated niri KDL
        window-rule file is installed.  Must start with `/etc/`.

        Reference this path in your niri config with:

            include "<outputPath>"

        The file is installed via NixOS `environment.etc` and is
        therefore owned by root and mode 0644.  It is recreated on
        every `nixos-rebuild switch`.
      '';
    };
  };

  config = lib.mkIf niriEnabled {
    assertions = [
      {
        assertion = lib.hasPrefix "/etc/" outputPath;
        message = ''
          d2b.site.ui.compositors.niri.outputPath must start with /etc/,
          because the file is installed via NixOS environment.etc.
          Current value: "${outputPath}"
        '';
      }
    ];

    environment.etc.${etcKey} = {
      text = kdlContent;
      mode = "0644";
    };
  };
}
