# nixos-modules/niri-vm-borders.nix — opt-in niri window-rule include
# generation for d2b graphics and qemu-media VMs.
#
# When `d2b.site.ui.compositors.niri.enable = true` or the legacy
# `d2b.site.niriVmBorders.enable = true`, installs a KDL file
# at the configured path (default `/etc/d2b/niri-vm-borders.kdl`)
# containing:
#   - a rule to hide the host-side crosvm GPU sidecar scanout window;
#   - one window-rule per enabled graphics VM, matching app-ids that
#     carry the `d2b.<vm>.` prefix and applying a per-VM border
#     color.
#   - one window-rule per enabled qemu-media VM, matching the app-id
#     prefix written by the Wayland filter proxy.
#
# Operators source the file from their niri config with:
#   include "/etc/d2b/niri-vm-borders.kdl"
#
# Requires niri ≥ 0.1.9 for include-directive support.
{ lib, config, ... }:

let
  legacyCfg = config.d2b.site.niriVmBorders;
  cfg = config.d2b.site.ui.compositors.niri;
  vmsCfg = config.d2b.vms;
  colors = config.d2b._uiColors;

  isQemuMediaVm = vm: (vm.runtime.kind or "nixos") == "qemu-media";
  niriEnabled = cfg.enable || legacyCfg.enable;
  outputPath = if cfg.enable then cfg.outputPath else legacyCfg.outputPath;

  # All enabled graphics VMs, sorted by name for a stable output order.
  graphicsVmNames = builtins.sort (a: b: a < b) (
    lib.attrNames (
      lib.filterAttrs
        (name: vm: vm.enable && vm.graphics.enable)
        vmsCfg
    )
  );

  # All enabled qemu-media VMs, sorted by name for a stable output order.
  qemuMediaVmNames = builtins.sort (a: b: a < b) (
    lib.attrNames (
      lib.filterAttrs
        (name: vm: vm.enable && isQemuMediaVm vm)
        vmsCfg
    )
  );

  makeBorderBlock = border: ''
        border {
            on
            active-color "${border.active}"
            inactive-color "${border.inactive}"
            urgent-color "${border.urgent}"
        }
  '';

  # KDL window-rule block for one graphics VM.
  # VM names match `^[a-z][a-z0-9-]*$` so they contain no regex
  # metacharacters other than `-`, which needs no escaping in a regex.
  makeGraphicsVmRule = name:
    let
      border = colors.vms.${name}.border;
    in
    ''
      // Borders for VM: ${name}
      window-rule {
          match app-id=r#"^d2b\.${name}\."#
    ${makeBorderBlock border}
      }
    '';

  # KDL window-rule block for one qemu-media VM host QEMU window.
  makeQemuMediaVmRule = name:
    let
      border = colors.vms.${name}.border;
    in
    ''
      // Borders for qemu-media VM host window: ${name}
      window-rule {
          match app-id=r#"^d2b\.${name}\."#
    ${makeBorderBlock border}
      }
    '';

  # Concatenated window-rule blocks for all enabled graphics and qemu-media VMs.
  vmRules =
    (lib.concatMapStrings makeGraphicsVmRule graphicsVmNames)
    + (lib.concatMapStrings makeQemuMediaVmRule qemuMediaVmNames);

  # The path key for environment.etc is relative to /etc/.
  etcKey = lib.removePrefix "/etc/" outputPath;

  kdlContent = ''
    // Generated by d2b. Source this from your niri config with:
    //
    //   include "${outputPath}"
    //
    // Requires niri >= 0.1.9 (KDL include directive).
    //
    // Re-generate after adding or removing graphics or qemu-media VMs by running
    // nixos-rebuild switch (or nixos-rebuild build to preview).

    // Hide the host-side crosvm GPU sidecar scanout window.
    // This window is created directly by the crosvm gpu runner on the
    // host compositor and is not part of the guest Wayland session.
    // It is typically a blank/invisible window that should not appear
    // in the niri overview or receive a border.
    window-rule {
        match app-id=r#"^crosvm$"#
        draw-border-with-background false
        border {
            off
        }
    }

    ${vmRules}
  '';

in
{
  options.d2b.site.niriVmBorders = {
    enable = lib.mkEnableOption ''
      Generate a niri KDL window-rule include file for per-VM border
      coloring, qemu-media host-window coloring, and crosvm
      scanout-window hiding.

      When enabled, installs a KDL file at `outputPath` (default
      `/etc/d2b/niri-vm-borders.kdl`) containing one
      `window-rule` per enabled graphics VM and qemu-media VM.
      Graphics rules match app-ids that carry the `d2b.<vm>.`
      prefix, which the host-side Wayland filter proxy writes onto
      every surface from that VM.  qemu-media also routes QEMU's host
      window through the same filter proxy, so its app-id carries the
      `d2b.<vm>.` prefix too. Each rule applies a configurable
      border color; the default color is derived deterministically from
      the VM name so every VM gets a stable, distinct color without
      operator configuration.

      To activate the rules, add the following line to your niri
      `config.kdl`:

          include "/etc/d2b/niri-vm-borders.kdl"

      Requires niri ≥ 0.1.9 for include-directive support.

      This option does not mutate the user's niri config
      automatically — the `include` line must be added manually.
    '';

    outputPath = lib.mkOption {
      type = lib.types.strMatching "^/etc/.*";
      default = "/etc/d2b/niri-vm-borders.kdl";
      example = "/etc/d2b/niri-vm-borders.kdl";
      description = ''
        Absolute path under `/etc/` where the generated niri KDL
        window-rule file is installed.  Must start with `/etc/`.

        Reference this path in your niri config with:

            include "<outputPath>"

        The file is installed via NixOS `environment.etc` and is
        therefore owned by root and mode 0644.  It is recreated on
        every `nixos-rebuild switch`.
      '';
    };
  };

  config = lib.mkIf niriEnabled {
    assertions = [
      {
        assertion = lib.hasPrefix "/etc/" outputPath;
        message = ''
          d2b.site.ui.compositors.niri.outputPath must start with /etc/,
          because the file is installed via NixOS environment.etc.
          Current value: "${outputPath}"
        '';
      }
    ];

    environment.etc.${etcKey} = {
      text = kdlContent;
      mode = "0644";
    };
  };
}
