# nixos-modules/niri-vm-borders.nix — opt-in niri window-rule include
# generation for nixling graphics VMs.
#
# When `nixling.site.niriVmBorders.enable = true`, installs a KDL file
# at the configured path (default `/etc/nixling/niri-vm-borders.kdl`)
# containing:
#   - a rule to hide the host-side crosvm GPU sidecar scanout window;
#   - one window-rule per enabled graphics VM, matching app-ids that
#     carry the `nixling.<vm>.` prefix and applying a per-VM border
#     color.
#
# Operators source the file from their niri config with:
#   include "/etc/nixling/niri-vm-borders.kdl"
#
# Requires niri ≥ 0.1.9 for include-directive support.
{ lib, config, ... }:

let
  cfg = config.nixling.site.niriVmBorders;
  vmsCfg = config.nixling.vms;

  # A small palette of visually distinct colors used when the operator
  # has not set a per-VM override. The index is derived deterministically
  # from the VM name so the same name always yields the same color across
  # rebuilds.
  colorPalette = [
    "#7fc8ff" # sky blue
    "#90d090" # sage green
    "#ffb347" # tangerine
    "#c8a0e0" # lavender
    "#ff8080" # salmon
    "#40e0d0" # turquoise
    "#ffd700" # gold
    "#ff69b4" # hot pink
    "#a0c8a0" # muted green
    "#d4a0ff" # purple
    "#ffa07a" # light salmon
    "#87ceeb" # light blue
  ];

  defaultActiveColor = name:
    let
      hashHex = builtins.hashString "sha256" "nixling-niri-border-${name}";
      idx = lib.mod
        (lib.fromHexString (builtins.substring 0 4 hashHex))
        (builtins.length colorPalette);
    in
    builtins.elemAt colorPalette idx;

  # All enabled graphics VMs, sorted by name for a stable output order.
  graphicsVmNames = builtins.sort (a: b: a < b) (
    lib.attrNames (
      lib.filterAttrs
        (name: vm: vm.enable && vm.graphics.enable)
        vmsCfg
    )
  );

  # KDL window-rule block for one VM.
  # VM names match `^[a-z][a-z0-9-]*$` so they contain no regex
  # metacharacters other than `-`, which needs no escaping in a regex.
  makeVmRule = name:
    let
      vm = vmsCfg.${name};
      activeColor =
        if vm.graphics.niriBorderColor != null
        then vm.graphics.niriBorderColor
        else defaultActiveColor name;
    in
    ''
      // Borders for VM: ${name}
      window-rule {
          match app-id=r#"^nixling\.${name}\."#
          border {
              on
              active-color "${activeColor}"
              inactive-color "#505050"
          }
      }
    '';

  # Concatenated window-rule blocks for all enabled graphics VMs.
  vmRules = lib.concatMapStrings makeVmRule graphicsVmNames;

  # The path key for environment.etc is relative to /etc/.
  etcKey = lib.removePrefix "/etc/" cfg.outputPath;

  kdlContent = ''
    // Generated by nixling. Source this from your niri config with:
    //
    //   include "${cfg.outputPath}"
    //
    // Requires niri >= 0.1.9 (KDL include directive).
    //
    // Re-generate after adding or removing graphics VMs by running
    // nixos-rebuild switch (or nixos-rebuild build to preview).

    // Hide the host-side crosvm GPU sidecar scanout window.
    // This window is created directly by the crosvm gpu runner on the
    // host compositor and is not part of the guest Wayland session.
    // It is typically a blank/invisible window that should not appear
    // in the niri overview or receive a border.
    window-rule {
        match app-id=r#"^crosvm$"#
        draw-border-with-background false
        border {
            off
        }
    }

    ${vmRules}
  '';

in
{
  options.nixling.site.niriVmBorders = {
    enable = lib.mkEnableOption ''
      Generate a niri KDL window-rule include file for per-VM border
      coloring and crosvm scanout-window hiding.

      When enabled, installs a KDL file at `outputPath` (default
      `/etc/nixling/niri-vm-borders.kdl`) containing one
      `window-rule` per enabled graphics VM.  Window rules match
      app-ids that carry the `nixling.<vm>.` prefix, which the
      host-side Wayland filter proxy writes onto every surface from
      that VM.  Each rule applies a configurable border color; the
      default color is derived deterministically from the VM name so
      every VM gets a stable, distinct color without operator
      configuration.

      To activate the rules, add the following line to your niri
      `config.kdl`:

          include "/etc/nixling/niri-vm-borders.kdl"

      Requires niri ≥ 0.1.9 for include-directive support.

      This option does not mutate the user's niri config
      automatically — the `include` line must be added manually.
    '';

    outputPath = lib.mkOption {
      type = lib.types.strMatching "^/etc/.*";
      default = "/etc/nixling/niri-vm-borders.kdl";
      example = "/etc/nixling/niri-vm-borders.kdl";
      description = ''
        Absolute path under `/etc/` where the generated niri KDL
        window-rule file is installed.  Must start with `/etc/`.

        Reference this path in your niri config with:

            include "<outputPath>"

        The file is installed via NixOS `environment.etc` and is
        therefore owned by root and mode 0644.  It is recreated on
        every `nixos-rebuild switch`.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = lib.hasPrefix "/etc/" cfg.outputPath;
        message = ''
          nixling.site.niriVmBorders.outputPath must start with /etc/,
          because the file is installed via NixOS environment.etc.
          Current value: "${cfg.outputPath}"
        '';
      }
    ];

    environment.etc.${etcKey} = {
      text = kdlContent;
      mode = "0644";
    };
  };
}
