# Compositor-agnostic nixling UI color contract and generated artifacts.
{ lib, config, ... }:

let
  cfg = config.nixling.site.ui;
  legacyNiri = config.nixling.site.niriVmBorders;
  vmsCfg = config.nixling.vms;
  envsCfg = config.nixling.envs;

  colorPalette = [
    "#7fc8ff"
    "#90d090"
    "#ffb347"
    "#c8a0e0"
    "#ff8080"
    "#40e0d0"
    "#ffd700"
    "#ff69b4"
    "#a0c8a0"
    "#d4a0ff"
    "#ffa07a"
    "#87ceeb"
  ];

  colorForName = seed: name:
    let
      hashHex = builtins.hashString "sha256" "${seed}-${name}";
      idx = lib.mod
        (lib.fromHexString (builtins.substring 0 4 hashHex))
        (builtins.length colorPalette);
    in
    builtins.elemAt colorPalette idx;

  normalizeColor = color: lib.toLower color;
  defaultVmColor = colorForName "nixling-niri-border";
  defaultEnvColor = colorForName "nixling-env-accent";

  enabledEnvNames = builtins.sort (a: b: a < b) (
    lib.attrNames (lib.filterAttrs (_: env: env.enable) envsCfg)
  );

  enabledVmNames = builtins.sort (a: b: a < b) (
    lib.attrNames (lib.filterAttrs (_: vm: vm.enable) vmsCfg)
  );

  legacyVmActiveColor = name: vm:
    if vm.graphics.niriBorderColor != null
    then vm.graphics.niriBorderColor
    else if vm.qemuMedia.window.niriBorderColor != null
    then vm.qemuMedia.window.niriBorderColor
    else null;

  resolvedVmBorder = name: vm:
    let
      active =
        if vm.ui.border.activeColor != null
        then vm.ui.border.activeColor
        else if legacyVmActiveColor name vm != null
        then legacyVmActiveColor name vm
        else defaultVmColor name;
      inactive =
        if vm.ui.border.inactiveColor != null
        then vm.ui.border.inactiveColor
        else active;
      urgent =
        if vm.ui.border.urgentColor != null
        then vm.ui.border.urgentColor
        else active;
    in
    {
      active = normalizeColor active;
      inactive = normalizeColor inactive;
      urgent = normalizeColor urgent;
    };

  resolved = {
    version = 1;
    host = {
      accent = normalizeColor cfg.colors.hostAccent;
    };
    states = lib.mapAttrs (_: normalizeColor) cfg.colors.states;
    envs = lib.genAttrs enabledEnvNames (name: {
      accent = normalizeColor (
        if envsCfg.${name}.ui.accentColor != null
        then envsCfg.${name}.ui.accentColor
        else defaultEnvColor name
      );
    });
    vms = lib.genAttrs enabledVmNames (name:
      let
        vm = vmsCfg.${name};
      in
      {
        env = vm.env;
        border = resolvedVmBorder name vm;
      });
  };

  artifactEnabled =
    cfg.enable
    || cfg.compositors.niri.enable
    || legacyNiri.enable;

  etcKey = path: lib.removePrefix "/etc/" path;

  cssLines =
    [
      "/* Generated by nixling. Do not edit by hand. */"
      ":root {"
      "  --nixling-host-accent: ${resolved.host.accent};"
    ]
    ++ (lib.mapAttrsToList
      (name: value: "  --nixling-state-${name}: ${value};")
      resolved.states)
    ++ (lib.concatMap
      (name: [ "  --nixling-env-${name}-accent: ${resolved.envs.${name}.accent};" ])
      enabledEnvNames)
    ++ (lib.concatMap
      (name:
        let
          border = resolved.vms.${name}.border;
        in
        [
          "  --nixling-vm-${name}-border-active: ${border.active};"
          "  --nixling-vm-${name}-border-inactive: ${border.inactive};"
          "  --nixling-vm-${name}-border-urgent: ${border.urgent};"
        ])
      enabledVmNames)
    ++ [ "}" ];

  cssContent = lib.concatStringsSep "\n" cssLines + "\n";

in
{
  options.nixling.site.ui = {
    enable = lib.mkEnableOption ''
      generic nixling UI color artifacts for compositors, bars, and
      desktop control tools
    '';

    colors = {
      hostAccent = lib.mkOption {
        type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
        default = "#89b4fa";
        example = "#89b4fa";
        description = ''
          Host accent color used by nixling-aware desktop surfaces as a
          six-digit CSS hex color. Resolved artifacts normalize the value
          to lowercase.
        '';
      };

      states = {
        running = lib.mkOption {
          type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
          default = "#a6e3a1";
          description = "Accent color for running VM state.";
        };
        transitioning = lib.mkOption {
          type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
          default = "#f9e2af";
          description = "Accent color for starting/stopping VM states.";
        };
        pendingRestart = lib.mkOption {
          type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
          default = "#fab387";
          description = "Accent color for VMs with a pending restart.";
        };
        error = lib.mkOption {
          type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
          default = "#f38ba8";
          description = "Accent color for error states.";
        };
        denied = lib.mkOption {
          type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
          default = "#cba6f7";
          description = "Accent color for authorization-denied states.";
        };
        unknown = lib.mkOption {
          type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
          default = "#6c7086";
          description = "Accent color for unknown or unavailable states.";
        };
      };
    };

    artifacts = {
      jsonPath = lib.mkOption {
        type = lib.types.strMatching "^/etc/.*";
        default = "/etc/nixling/ui-colors.json";
        example = "/etc/nixling/ui-colors.json";
        description = "Absolute `/etc` path for the resolved UI color JSON artifact.";
      };
      cssPath = lib.mkOption {
        type = lib.types.strMatching "^/etc/.*";
        default = "/etc/nixling/ui-colors.css";
        example = "/etc/nixling/ui-colors.css";
        description = "Absolute `/etc` path for the resolved UI color CSS custom-property artifact.";
      };
      css.enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Whether to emit the CSS custom-property artifact.";
      };
    };

    compositors.niri = {
      enable = lib.mkEnableOption "niri KDL output rendered from the generic nixling UI color model";
      outputPath = lib.mkOption {
        type = lib.types.strMatching "^/etc/.*";
        default = "/etc/nixling/niri-vm-borders.kdl";
        example = "/etc/nixling/niri-vm-borders.kdl";
        description = "Absolute `/etc` path for the generated niri KDL include.";
      };
    };
  };

  options.nixling._uiColors = lib.mkOption {
    type = lib.types.unspecified;
    default = { };
    internal = true;
    description = "Internal resolved nixling UI color model.";
  };

  config = {
    nixling._uiColors = resolved;

    warnings =
      (lib.optional legacyNiri.enable ''
        nixling.site.niriVmBorders.enable is deprecated; use nixling.site.ui.compositors.niri.enable instead.
      '')
      ++ (lib.optional (legacyNiri.outputPath != "/etc/nixling/niri-vm-borders.kdl") ''
        nixling.site.niriVmBorders.outputPath is deprecated; use nixling.site.ui.compositors.niri.outputPath instead.
      '');

    environment.etc = lib.mkIf artifactEnabled (
      {
        ${etcKey cfg.artifacts.jsonPath} = {
          text = builtins.toJSON resolved + "\n";
          mode = "0644";
        };
      }
      // lib.optionalAttrs cfg.artifacts.css.enable {
        ${etcKey cfg.artifacts.cssPath} = {
          text = cssContent;
          mode = "0644";
        };
      }
    );
  };
}
