//! v1.1.1 RenderDnsmasqEnvConf daemon-host-prep DAG op.
//!
//! Per ADR 0018: the net-VM bundle gate's ConfigMissing soft-defer (in
//! `packages/nixlingd/src/lib.rs::dispatch_broker_vm_start`)
//! requires a daemon op that renders
//! `/var/lib/nixling/dnsmasq/<env>.conf` from the trusted bundle
//! BEFORE the first net-VM SpawnRunner starts for each env.
//!
//! This module is pure Rust: it takes a typed
//! [`DnsmasqEnvConfInput`] (env name + reservations + LAN CIDR)
//! and renders the dnsmasq config text. The file write happens
//! via the broker (broker-only sole-writer invariant per
//! cgroup-delegation.md / ADR 0018; the daemon does not write
//! to /var/lib/nixling directly).
//!
//! The broker integration is wired through a new
//! `BrokerRequest::RenderDnsmasqEnvConf` op in
//! `nixling-ipc::broker_wire`; the broker writes
//! `/var/lib/nixling/dnsmasq/<env>.conf` atomically
//! (write-to-tempfile + rename) with mode `0640 root:nixlingd`
//! per the ADR 0018 spec. The daemon-side host-prep DAG calls
//! the broker op BEFORE the first net-VM SpawnRunner starts for
//! each env.

use serde::{Deserialize, Serialize};

/// One DHCP reservation: MAC ↔ static IP ↔ optional hostname.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DnsmasqReservation {
    /// Reservation MAC (IEEE format, e.g. `02:00:00:00:00:01`).
    pub mac: String,
    /// Static IPv4 address.
    pub ip: String,
    /// Optional DNS name (recorded via dnsmasq's
    /// `dhcp-host=...,set:hostname,<name>` syntax).
    pub hostname: Option<String>,
}

/// Per-env input to the dnsmasq config renderer.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DnsmasqEnvConfInput {
    /// Env name (e.g. `work`, `personal`).
    pub env: String,
    /// LAN bridge interface name (e.g. `br-work-lan`).
    pub lan_bridge: String,
    /// LAN CIDR (e.g. `10.20.0.0/24`).
    pub lan_cidr: String,
    /// DHCP pool first address.
    pub dhcp_range_start: String,
    /// DHCP pool last address.
    pub dhcp_range_end: String,
    /// Per-env DNS host names served back to clients.
    pub dns_hostnames: Vec<DnsmasqReservation>,
    /// Per-env DHCP reservations (subset of dns_hostnames that
    /// also map MAC → IP for the workload VMs).
    pub reservations: Vec<DnsmasqReservation>,
}

/// Errors the renderer can return.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case", tag = "kind")]
pub enum DnsmasqRenderError {
    /// Empty env name.
    EmptyEnv,
    /// Empty LAN bridge interface name.
    EmptyBridge,
    /// LAN CIDR doesn't parse.
    InvalidLanCidr { value: String },
    /// One of the reservation IPs doesn't parse.
    InvalidReservationIp { ip: String },
    /// One of the reservation MACs doesn't parse.
    InvalidReservationMac { mac: String },
}

/// Render the dnsmasq config text for a single env.
///
/// The output is consumed by `dnsmasq -C <env>.conf` running
/// inside the net-VM. The file is written by the broker (not the
/// daemon) per the broker-only sole-writer invariant on
/// `/var/lib/nixling`.
pub fn render_dnsmasq_env_conf(input: &DnsmasqEnvConfInput) -> Result<String, DnsmasqRenderError> {
    if input.env.is_empty() {
        return Err(DnsmasqRenderError::EmptyEnv);
    }
    if input.lan_bridge.is_empty() {
        return Err(DnsmasqRenderError::EmptyBridge);
    }
    if !input.lan_cidr.contains('/') {
        return Err(DnsmasqRenderError::InvalidLanCidr {
            value: input.lan_cidr.clone(),
        });
    }
    for r in input.reservations.iter().chain(input.dns_hostnames.iter()) {
        if r.ip.is_empty() || !r.ip.contains('.') {
            return Err(DnsmasqRenderError::InvalidReservationIp { ip: r.ip.clone() });
        }
        if r.mac.is_empty() || r.mac.matches(':').count() != 5 {
            return Err(DnsmasqRenderError::InvalidReservationMac { mac: r.mac.clone() });
        }
    }

    let mut out = String::new();
    out.push_str(&format!(
        "# nixling-rendered dnsmasq config for env={}\n",
        input.env
    ));
    out.push_str("# DO NOT EDIT; regenerated by `RenderDnsmasqEnvConf` broker op.\n");
    out.push_str(&format!(
        "# Source: /etc/nixling/bundle.json (env={})\n\n",
        input.env
    ));
    out.push_str("# Bind to the LAN bridge interface only.\n");
    out.push_str(&format!("interface={}\n", input.lan_bridge));
    out.push_str("bind-interfaces\n\n");
    out.push_str("# DHCP pool — clients on the LAN bridge get an address from this range.\n");
    out.push_str(&format!(
        "dhcp-range={},{},12h\n\n",
        input.dhcp_range_start, input.dhcp_range_end
    ));

    if !input.reservations.is_empty() {
        out.push_str("# Static DHCP reservations (MAC → IP).\n");
        for r in &input.reservations {
            if let Some(hostname) = &r.hostname {
                out.push_str(&format!("dhcp-host={},{},{}\n", r.mac, r.ip, hostname));
            } else {
                out.push_str(&format!("dhcp-host={},{}\n", r.mac, r.ip));
            }
        }
        out.push('\n');
    }

    if !input.dns_hostnames.is_empty() {
        out.push_str("# DNS hostname mappings.\n");
        for r in &input.dns_hostnames {
            if let Some(hostname) = &r.hostname {
                out.push_str(&format!("address=/{}/{}\n", hostname, r.ip));
            }
        }
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fake_input() -> DnsmasqEnvConfInput {
        DnsmasqEnvConfInput {
            env: "work".to_owned(),
            lan_bridge: "br-work-lan".to_owned(),
            lan_cidr: "10.20.0.0/24".to_owned(),
            dhcp_range_start: "10.20.0.100".to_owned(),
            dhcp_range_end: "10.20.0.200".to_owned(),
            dns_hostnames: vec![],
            reservations: vec![DnsmasqReservation {
                mac: "02:00:00:00:00:01".to_owned(),
                ip: "10.20.0.10".to_owned(),
                hostname: Some("personal-dev".to_owned()),
            }],
        }
    }

    #[test]
    fn render_emits_dhcp_range_and_reservation() {
        let input = fake_input();
        let out = render_dnsmasq_env_conf(&input).expect("render");
        assert!(out.contains("interface=br-work-lan"));
        assert!(out.contains("dhcp-range=10.20.0.100,10.20.0.200,12h"));
        assert!(out.contains("dhcp-host=02:00:00:00:00:01,10.20.0.10,personal-dev"));
    }

    #[test]
    fn render_rejects_empty_env() {
        let mut input = fake_input();
        input.env = String::new();
        match render_dnsmasq_env_conf(&input).unwrap_err() {
            DnsmasqRenderError::EmptyEnv => {}
            other => panic!("expected EmptyEnv, got {other:?}"),
        }
    }

    #[test]
    fn render_rejects_invalid_mac() {
        let mut input = fake_input();
        input.reservations[0].mac = "not-a-mac".to_owned();
        match render_dnsmasq_env_conf(&input).unwrap_err() {
            DnsmasqRenderError::InvalidReservationMac { .. } => {}
            other => panic!("expected InvalidReservationMac, got {other:?}"),
        }
    }

    #[test]
    fn render_rejects_invalid_cidr() {
        let mut input = fake_input();
        input.lan_cidr = "no-slash".to_owned();
        match render_dnsmasq_env_conf(&input).unwrap_err() {
            DnsmasqRenderError::InvalidLanCidr { value } => assert_eq!(value, "no-slash"),
            other => panic!("expected InvalidLanCidr, got {other:?}"),
        }
    }

    #[test]
    fn render_is_deterministic() {
        let input = fake_input();
        let a = render_dnsmasq_env_conf(&input).expect("first");
        let b = render_dnsmasq_env_conf(&input).expect("second");
        assert_eq!(a, b);
    }
}
