// nixling ACA + Wayland POC — Azure deployment (ADR 0032, Wave P0).
//
// Subscription-scoped orchestrator. Every resource in this POC is regional
// (each has a location), so they all live in the regional resource group
// rg-<workload>-<region> (e.g. rg-nixling-centralus). The common resource
// group rg-common is RESERVED by the naming scheme for genuinely-global
// resources; this POC has none, so it is not created here.
//
// Two modules deploy into the regional group:
//   1. registry.bicep — container registry + managed identity (+ AcrPull)
//   2. sandbox.bicep  — Container Apps sandbox group + Azure Relay (+ the
//                       SandboxGroup Data Owner role for the identity)
// The Wayland image is pushed to the registry and registered as a sandbox
// disk image through the data plane; the repo's deploy.sh sequences
// registry -> push image -> sandbox.
//
// Deploy (one-shot, requires a working `az deployment sub create`):
//   az deployment sub create \
//     --location <region> \
//     --template-file main.bicep \
//     --parameters main.bicepparam
//
// Customize by editing main.bicepparam (you do not edit this file).

targetScope = 'subscription'

@description('Azure region (canonical long name, e.g. centralus). Drives the regional resource group name and all regional resources. Must be a region where Container Apps sandboxes are available.')
param location string = 'centralus'

@description('Stable workload token used in every resource name.')
param workload string = 'nixling'

@description('Resource-type name prefixes. Defaults follow the Azure CAF recommended abbreviations; override any field to suit a house style. The two types CAF does not define use nixling-chosen prefixes: sandboxGroup (casbx) and relayNamespace (relns).')
param prefixes object = {
  resourceGroup: 'rg'
  registry: 'cr'
  managedIdentity: 'id'
  sandboxGroup: 'casbx'
  relayNamespace: 'relns'
  hybridConnection: 'hc'
}

@description('Regional resource group name: rg-<workload>-<region> by default.')
param regionalResourceGroupName string = '${prefixes.resourceGroup}-${workload}-${location}'

@description('Container image repository inside the registry (registered as a sandbox disk image via the data plane).')
param imageRepository string = 'nixling-wayland'

@description('Container image tag.')
param imageTag string = 'latest'

@description('Optional object id of an operator (user/group) to grant the SandboxGroup Data Owner role, so a human can drive sandboxes in the portal/CLI. Leave empty to skip.')
param operatorPrincipalId string = ''

@description('Principal type for operatorPrincipalId (User or Group).')
@allowed([
  'User'
  'Group'
])
param operatorPrincipalType string = 'User'

@description('Tags applied to every resource.')
param tags object = {
  workload: workload
  component: 'nixling-aca-wayland-poc'
  managedBy: 'bicep'
}

resource regionalResourceGroup 'Microsoft.Resources/resourceGroups@2024-03-01' = {
  name: regionalResourceGroupName
  location: location
  tags: tags
}

module registry 'modules/registry.bicep' = {
  name: 'nixling-registry'
  scope: regionalResourceGroup
  params: {
    workload: workload
    prefixes: prefixes
    tags: tags
  }
}

module sandbox 'modules/sandbox.bicep' = {
  name: 'nixling-sandbox'
  scope: regionalResourceGroup
  params: {
    workload: workload
    prefixes: prefixes
    tags: tags
    managedIdentityPrincipalId: registry.outputs.managedIdentityPrincipalId
    operatorPrincipalId: operatorPrincipalId
    operatorPrincipalType: operatorPrincipalType
  }
}

// ---- Outputs an operator / gateway-enrollment step consumes ----
output regionalResourceGroup string = regionalResourceGroup.name
output registryName string = registry.outputs.registryName
output registryLoginServer string = registry.outputs.registryLoginServer
output imageReference string = '${registry.outputs.registryLoginServer}/${imageRepository}:${imageTag}'
output managedIdentityClientId string = registry.outputs.managedIdentityClientId
output managedIdentityResourceId string = registry.outputs.managedIdentityResourceId
output sandboxGroupName string = sandbox.outputs.sandboxGroupName
output sandboxGroupResourceId string = sandbox.outputs.sandboxGroupResourceId
output relayNamespaceName string = sandbox.outputs.relayNamespaceName
output hybridConnectionName string = sandbox.outputs.hybridConnectionName
output relayListenRuleName string = sandbox.outputs.relayListenRuleName
output relaySendRuleName string = sandbox.outputs.relaySendRuleName
