# Compositor-agnostic d2b UI color contract and generated artifacts.
{ lib, config, ... }:

let
  cfg = config.d2b.site.ui;
  legacyNiri = config.d2b.site.niriVmBorders;
  vmsCfg = config.d2b.vms;
  envsCfg = config.d2b.envs;
  realmsCfg = config.d2b.realms;

  colorPalette = [
    "#7fc8ff"
    "#90d090"
    "#ffb347"
    "#c8a0e0"
    "#ff8080"
    "#40e0d0"
    "#ffd700"
    "#ff69b4"
    "#a0c8a0"
    "#d4a0ff"
    "#ffa07a"
    "#87ceeb"
  ];

  colorForName = seed: name:
    let
      hashHex = builtins.hashString "sha256" "${seed}-${name}";
      idx = lib.mod
        (lib.fromHexString (builtins.substring 0 4 hashHex))
        (builtins.length colorPalette);
    in
    builtins.elemAt colorPalette idx;

  normalizeColor = color: lib.toLower color;
  defaultVmColor = colorForName "d2b-niri-border";
  defaultEnvColor = colorForName "d2b-env-accent";
  defaultRealmColor = colorForName "d2b-realm-accent";

  enabledEnvNames = builtins.sort (a: b: a < b) (
    lib.attrNames (lib.filterAttrs (_: env: env.enable) envsCfg)
  );

  enabledVmNames = builtins.sort (a: b: a < b) (
    lib.attrNames (lib.filterAttrs (_: vm: vm.enable) vmsCfg)
  );

  enabledRealmNames = builtins.sort (a: b: a < b) (
    lib.attrNames (lib.filterAttrs (_: realm: realm.enable) realmsCfg)
  );

  legacyVmActiveColor = name: vm:
    if vm.graphics.niriBorderColor != null
    then vm.graphics.niriBorderColor
    else if vm.qemuMedia.window.niriBorderColor != null
    then vm.qemuMedia.window.niriBorderColor
    else null;

  resolvedVmBorder = name: vm:
    let
      active =
        if vm.ui.border.activeColor != null
        then vm.ui.border.activeColor
        else if legacyVmActiveColor name vm != null
        then legacyVmActiveColor name vm
        else defaultVmColor name;
      inactive =
        if vm.ui.border.inactiveColor != null
        then vm.ui.border.inactiveColor
        else active;
      urgent =
        if vm.ui.border.urgentColor != null
        then vm.ui.border.urgentColor
        else active;
    in
    {
      active = normalizeColor active;
      inactive = normalizeColor inactive;
      urgent = normalizeColor urgent;
    };

  resolved = {
    version = 1;
    host = {
      accent = normalizeColor cfg.colors.hostAccent;
    };
    states = lib.mapAttrs (_: normalizeColor) cfg.colors.states;
    envs = lib.genAttrs enabledEnvNames (name: {
      accent = normalizeColor (
        if envsCfg.${name}.ui.accentColor != null
        then envsCfg.${name}.ui.accentColor
        else defaultEnvColor name
      );
    });
    vms = lib.genAttrs enabledVmNames (name:
      let
        vm = vmsCfg.${name};
      in
      {
        env = vm.env;
        border = resolvedVmBorder name vm;
      });
    realms = lib.genAttrs enabledRealmNames (name:
      let
        realm = realmsCfg.${name};
      in
      {
        path = realm.path;
        accent = normalizeColor (
          if realm.network.ui.accentColor != null
          then realm.network.ui.accentColor
          else defaultRealmColor name
        );
      });
  };

  artifactEnabled =
    cfg.enable
    || cfg.compositors.niri.enable
    || legacyNiri.enable;

  etcKey = path: lib.removePrefix "/etc/" path;
  cssIdent = name: builtins.replaceStrings [ "-" ] [ "_" ] name;
  cssStateIdent = name:
    if name == "pendingRestart"
    then "pending_restart"
    else cssIdent name;

  cssLines =
    [
      "/* Generated by d2b. Do not edit by hand. */"
      "@define-color d2b_host_accent ${resolved.host.accent};"
    ]
    ++ (lib.mapAttrsToList
      (name: value: "@define-color d2b_state_${cssStateIdent name} ${value};")
      resolved.states)
    ++ (lib.concatMap
      (name: [ "@define-color d2b_env_${cssIdent name}_accent ${resolved.envs.${name}.accent};" ])
      enabledEnvNames)
    ++ (lib.concatMap
      (name: [ "@define-color d2b_realm_${cssIdent name}_accent ${resolved.realms.${name}.accent};" ])
      enabledRealmNames)
    ++ (lib.concatMap
      (name:
        let
          border = resolved.vms.${name}.border;
          vmIdent = cssIdent name;
        in
        [
          "@define-color d2b_vm_${vmIdent}_border_active ${border.active};"
          "@define-color d2b_vm_${vmIdent}_border_inactive ${border.inactive};"
          "@define-color d2b_vm_${vmIdent}_border_urgent ${border.urgent};"
        ])
      enabledVmNames)
    ;

  cssContent = lib.concatStringsSep "\n" cssLines + "\n";

in
{
  options.d2b.site.ui = {
    enable = lib.mkEnableOption ''
      generic d2b UI color artifacts for compositors, bars, and
      desktop control tools
    '';

    colors = {
      hostAccent = lib.mkOption {
        type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
        default = "#89b4fa";
        example = "#89b4fa";
        description = ''
          Host accent color used by d2b-aware desktop surfaces as a
          six-digit CSS hex color. Resolved artifacts normalize the value
          to lowercase.
        '';
      };

      states = {
        running = lib.mkOption {
          type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
          default = "#a6e3a1";
          description = "Accent color for running VM state.";
        };
        transitioning = lib.mkOption {
          type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
          default = "#f9e2af";
          description = "Accent color for starting/stopping VM states.";
        };
        pendingRestart = lib.mkOption {
          type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
          default = "#fab387";
          description = "Accent color for VMs with a pending restart.";
        };
        error = lib.mkOption {
          type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
          default = "#f38ba8";
          description = "Accent color for error states.";
        };
        denied = lib.mkOption {
          type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
          default = "#cba6f7";
          description = "Accent color for authorization-denied states.";
        };
        unknown = lib.mkOption {
          type = lib.types.strMatching "^#[0-9a-fA-F]{6}$";
          default = "#6c7086";
          description = "Accent color for unknown or unavailable states.";
        };
      };
    };

    artifacts = {
      jsonPath = lib.mkOption {
        type = lib.types.strMatching "^/etc/.*";
        default = "/etc/d2b/ui-colors.json";
        example = "/etc/d2b/ui-colors.json";
        description = "Absolute `/etc` path for the resolved UI color JSON artifact.";
      };
      cssPath = lib.mkOption {
        type = lib.types.strMatching "^/etc/.*";
        default = "/etc/d2b/ui-colors.css";
        example = "/etc/d2b/ui-colors.css";
        description = "Absolute `/etc` path for the resolved UI color GTK CSS artifact.";
      };
      css.enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Whether to emit the GTK CSS color-definition artifact.";
      };
    };

    compositors.niri = {
      enable = lib.mkEnableOption "niri KDL output rendered from the generic d2b UI color model";
      outputPath = lib.mkOption {
        type = lib.types.strMatching "^/etc/.*";
        default = "/etc/d2b/niri-vm-borders.kdl";
        example = "/etc/d2b/niri-vm-borders.kdl";
        description = "Absolute `/etc` path for the generated niri KDL include.";
      };
    };
  };

  options.d2b._uiColors = lib.mkOption {
    type = lib.types.unspecified;
    default = { };
    internal = true;
    description = "Internal resolved d2b UI color model.";
  };

  config = {
    d2b._uiColors = resolved;

    warnings =
      (lib.optional legacyNiri.enable ''
        d2b.site.niriVmBorders.enable is deprecated; use d2b.site.ui.compositors.niri.enable instead.
      '')
      ++ (lib.optional (legacyNiri.outputPath != "/etc/d2b/niri-vm-borders.kdl") ''
        d2b.site.niriVmBorders.outputPath is deprecated; use d2b.site.ui.compositors.niri.outputPath instead.
      '');

    environment.etc = lib.mkIf artifactEnabled (
      {
        ${etcKey cfg.artifacts.jsonPath} = {
          text = builtins.toJSON resolved + "\n";
          mode = "0644";
        };
      }
      // lib.optionalAttrs cfg.artifacts.css.enable {
        ${etcKey cfg.artifacts.cssPath} = {
          text = cssContent;
          mode = "0644";
        };
      }
    );
  };
}
