//! Post-handshake stream-mux driver (ADR 0032).
//!
//! [`PeerSession`](crate::PeerSession) proves that the byte transport completed
//! protocol/codec negotiation. [`MuxSession`] is the next boundary: every
//! post-handshake stream frame is applied to the pure
//! [`d2b_realm_core::StreamMux`] state machine before it is exposed
//! to a caller (inbound) or written to the peer (outbound). This is the
//! fail-closed runtime seam between semantic frames and transport I/O.

use std::collections::{BTreeMap, VecDeque};

use d2b_realm_core::{
    AdmissionAuditRecord, AuthorizationScope, Capability, CapabilitySet, ConstellationError,
    ConstellationFrame, CorrelationId, ErrorKind, NodeId, OpaquePayload, OperationId,
    OperationKind, OperationRequest, OperationResponse, PrincipalId, RealmPath, StreamChannel,
    StreamClose, StreamCloseReason, StreamData, StreamFlow, StreamId, StreamKind, StreamMux,
    StreamOpen, StreamResume, TraceContext,
};
use d2b_realm_provider::error::ProviderResult;
use d2b_realm_provider::provider::ProtocolCodec;

use crate::{PeerSession, operation_route_plan, supported_stream_kind};

/// Maximum operation contexts retained by one mux session.
pub const MAX_OPERATION_CONTEXTS: usize = 4096;

#[derive(Clone)]
struct OperationStreamContext {
    kind: OperationKind,
    correlation_id: CorrelationId,
    realm: RealmPath,
    node: NodeId,
    principal: PrincipalId,
    trace: Option<TraceContext>,
    stream_kinds: &'static [StreamKind],
}

/// A peer session with stream-mux accounting attached.
pub struct MuxSession<C: ProtocolCodec> {
    peer: PeerSession<C>,
    mux: StreamMux,
    capabilities: CapabilitySet,
    operations: BTreeMap<OperationId, OperationStreamContext>,
    operation_order: VecDeque<OperationId>,
    last_admission_denial: Option<AdmissionAuditRecord>,
}

impl<C: ProtocolCodec> MuxSession<C> {
    /// Wrap a successfully-handshaken peer session with a fresh mux.
    pub fn new(peer: PeerSession<C>) -> Self {
        let capabilities = peer.negotiated().capabilities.capabilities.clone();
        Self {
            peer,
            mux: StreamMux::new(),
            capabilities,
            operations: BTreeMap::new(),
            operation_order: VecDeque::new(),
            last_admission_denial: None,
        }
    }

    /// Wrap a peer with an explicit mux (used by tests and restored sessions).
    pub fn with_mux(peer: PeerSession<C>, mux: StreamMux) -> Self {
        let capabilities = peer.negotiated().capabilities.capabilities.clone();
        Self {
            peer,
            mux,
            capabilities,
            operations: BTreeMap::new(),
            operation_order: VecDeque::new(),
            last_admission_denial: None,
        }
    }

    /// Borrow the mux state for reconciliation/observability.
    pub fn mux(&self) -> &StreamMux {
        &self.mux
    }

    /// Borrow the latest stream-open admission denial generated by this mux.
    pub fn last_admission_denial(&self) -> Option<&AdmissionAuditRecord> {
        self.last_admission_denial.as_ref()
    }

    /// Register an accepted operation before any streams bound to it can open.
    pub fn register_operation(&mut self, req: &OperationRequest) -> Result<(), ConstellationError> {
        let Some(plan) = operation_route_plan(req.kind) else {
            return Err(ConstellationError::new(
                ErrorKind::UnsupportedFeature,
                format!("operation kind '{}' is not supported", req.kind.code()),
            )
            .with_correlation_id(req.correlation_id.clone()));
        };
        if plan.requires_workload && req.workload.is_none() {
            return Err(ConstellationError::new(
                ErrorKind::InvalidTarget,
                format!(
                    "operation kind '{}' requires a workload target",
                    req.kind.code()
                ),
            )
            .with_correlation_id(req.correlation_id.clone()));
        }
        if self.operations.contains_key(&req.operation_id) {
            return Err(ConstellationError::new(
                ErrorKind::MalformedFrame,
                format!(
                    "operation id '{}' is already registered on this mux session",
                    req.operation_id.as_str()
                ),
            )
            .with_correlation_id(req.correlation_id.clone()));
        }
        self.operation_order.push_back(req.operation_id.clone());
        self.operations.insert(
            req.operation_id.clone(),
            OperationStreamContext {
                kind: req.kind,
                correlation_id: req.correlation_id.clone(),
                realm: req.realm.clone(),
                node: req.node.clone(),
                principal: req.principal.clone(),
                trace: req.trace.clone(),
                stream_kinds: plan.stream_kinds,
            },
        );
        while self.operation_order.len() > MAX_OPERATION_CONTEXTS {
            if let Some(expired) = self.operation_order.pop_front() {
                self.operations.remove(&expired);
            } else {
                break;
            }
        }
        Ok(())
    }

    /// Remove an operation context once the operation reaches a terminal state.
    pub fn unregister_operation(&mut self, operation_id: &OperationId) {
        self.operations.remove(operation_id);
        self.operation_order.retain(|id| id != operation_id);
    }

    fn unregister_operations_by_correlation_id(&mut self, correlation_id: &CorrelationId) {
        self.operations
            .retain(|_, context| context.correlation_id != *correlation_id);
        self.operation_order
            .retain(|operation_id| self.operations.contains_key(operation_id));
    }

    /// Send an operation request after registering its accepted stream policy.
    pub async fn send_operation_request(&mut self, req: OperationRequest) -> ProviderResult<()> {
        self.register_operation(&req)?;
        self.peer
            .send(&ConstellationFrame::OperationRequest(req))
            .await
    }

    /// Send an operation response and clear local stream policy state for it.
    pub async fn send_operation_response(
        &mut self,
        response: OperationResponse,
    ) -> ProviderResult<()> {
        self.unregister_operation(&response.operation_id);
        self.peer
            .send(&ConstellationFrame::OperationResponse(response))
            .await
    }

    /// Send a typed error frame and clear matching operation contexts.
    pub async fn send_typed_error(&mut self, error: ConstellationError) -> ProviderResult<()> {
        if let Some(correlation_id) = error.correlation_id() {
            self.unregister_operations_by_correlation_id(correlation_id);
        }
        self.peer.send(&ConstellationFrame::TypedError(error)).await
    }

    /// Alias for callers that treat typed errors as the generic error frame.
    pub async fn send_error(&mut self, error: ConstellationError) -> ProviderResult<()> {
        self.send_typed_error(error).await
    }

    /// Open a stream initiated by this endpoint: validate/register it locally,
    /// then send the `StreamOpen` frame to the peer.
    pub async fn open_stream(&mut self, open: StreamOpen) -> ProviderResult<()> {
        if let Err(err) = self.ensure_stream_admitted(&open) {
            self.record_stream_denial(&open, &err);
            return Err(err.into());
        }
        self.mux.open_with_capabilities(&open, &self.capabilities)?;
        self.peer.send(&ConstellationFrame::StreamOpen(open)).await
    }

    /// Grant inbound credit to the peer and send the resulting flow frame.
    pub async fn grant_inbound(&mut self, stream: &StreamId, credits: u32) -> ProviderResult<()> {
        let flow = self.mux.grant_inbound(stream, credits)?;
        self.send_stream_flow(flow).await
    }

    /// Send a stream flow frame after the caller has validated/accounted it.
    pub async fn send_stream_flow(&mut self, flow: StreamFlow) -> ProviderResult<()> {
        self.peer.send(&ConstellationFrame::StreamFlow(flow)).await
    }

    /// Send one bounded data chunk after spending outbound credit.
    pub async fn send_data(
        &mut self,
        stream: &StreamId,
        channel: StreamChannel,
        data: OpaquePayload,
    ) -> ProviderResult<()> {
        let sequence = self.mux.reserve_send(stream, channel)?;
        let frame = StreamData {
            stream: stream.clone(),
            sequence,
            channel,
            cursor: None,
            data,
        };
        self.peer.send(&ConstellationFrame::StreamData(frame)).await
    }

    /// Close a stream locally, then tell the peer. Idempotency is owned by the
    /// mux: a double-close is rejected fail-closed.
    pub async fn close_stream(
        &mut self,
        stream: &StreamId,
        reason: StreamCloseReason,
    ) -> ProviderResult<()> {
        let close = StreamClose {
            stream: stream.clone(),
            reason,
        };
        self.send_stream_close(close).await
    }

    /// Apply the local mux close transition, then send the close frame.
    pub async fn send_stream_close(&mut self, close: StreamClose) -> ProviderResult<()> {
        self.mux.close(&close)?;
        self.peer
            .send(&ConstellationFrame::StreamClose(close))
            .await
    }

    /// Send a stream resume request after validating the stream/cursor shape.
    pub async fn resume_stream(&mut self, resume: StreamResume) -> ProviderResult<()> {
        self.mux.validate_resume(&resume)?;
        self.peer
            .send(&ConstellationFrame::StreamResume(resume))
            .await
    }

    /// Cancel a stream idempotently and notify the peer only for the first
    /// cancel transition.
    pub async fn cancel_stream(&mut self, stream: &StreamId) -> ProviderResult<bool> {
        let first_cancel = self.mux.cancel(stream)?;
        if first_cancel {
            self.peer
                .send(&ConstellationFrame::StreamClose(StreamClose {
                    stream: stream.clone(),
                    reason: StreamCloseReason::Cancelled,
                }))
                .await?;
        }
        Ok(first_cancel)
    }

    /// Receive one frame and apply the mux state transition before exposing it.
    pub async fn recv(&mut self) -> ProviderResult<ConstellationFrame> {
        let frame = self.peer.recv().await?;
        if let Err(err) = self.apply_inbound(&frame) {
            if matches!(frame, ConstellationFrame::StreamOpen(_)) {
                let _ = self.send_last_admission_denial().await;
            }
            return Err(err.into());
        }
        Ok(frame)
    }

    async fn send_last_admission_denial(&mut self) -> ProviderResult<()> {
        let Some(record) = self.last_admission_denial.clone() else {
            return Ok(());
        };
        self.peer
            .send(&ConstellationFrame::AdmissionAudit(record))
            .await
    }

    fn apply_inbound(&mut self, frame: &ConstellationFrame) -> Result<(), ConstellationError> {
        match frame {
            ConstellationFrame::StreamOpen(open) => {
                if let Err(err) = self.ensure_stream_admitted(open) {
                    self.record_stream_denial(open, &err);
                    return Err(err);
                }
                match self.mux.open_with_capabilities(open, &self.capabilities) {
                    Ok(()) => Ok(()),
                    Err(err) => {
                        let err = if let Some(context) = self.operations.get(&open.operation_id) {
                            err.with_correlation_id(context.correlation_id.clone())
                        } else {
                            err
                        };
                        self.record_stream_denial(open, &err);
                        Err(err)
                    }
                }
            }
            ConstellationFrame::OperationResponse(response) => {
                self.unregister_operation(&response.operation_id);
                Ok(())
            }
            ConstellationFrame::OperationRequest(_) => Ok(()),
            ConstellationFrame::StreamData(data) => self.mux.accept_data(data),
            ConstellationFrame::StreamFlow(flow) => self.mux.receive_flow(flow),
            ConstellationFrame::StreamClose(close) => self.mux.close(close),
            ConstellationFrame::StreamResume(resume) => self.mux.validate_resume(resume),
            ConstellationFrame::TypedError(error) => {
                if let Some(correlation_id) = error.correlation_id() {
                    self.unregister_operations_by_correlation_id(correlation_id);
                }
                Ok(())
            }
            ConstellationFrame::Handshake(_)
            | ConstellationFrame::HandshakeAccepted(_)
            | ConstellationFrame::HandshakeRejected(_)
            | ConstellationFrame::AdmissionAudit(_) => Ok(()),
        }
    }

    fn ensure_stream_admitted(&self, open: &StreamOpen) -> Result<(), ConstellationError> {
        let context = self.operations.get(&open.operation_id);
        if open.descriptor.kind == StreamKind::Control {
            let expected_principal = self.connection_principal();
            if open.authz.principal != expected_principal || open.authz.realm != RealmPath::local()
            {
                return Err(ConstellationError::new(
                    ErrorKind::Unauthorized,
                    "control stream authorization context does not match the peer session",
                ));
            }
            if !self.capabilities.has(Capability::Lifecycle) {
                return Err(ConstellationError::capability_denied(Capability::Lifecycle));
            }
            return Ok(());
        }
        let Some(context) = context else {
            return Err(ConstellationError::new(
                ErrorKind::InvalidTarget,
                format!(
                    "stream kind '{}' has no accepted operation context",
                    open.descriptor.kind.code()
                ),
            ));
        };
        if open.authz.principal != context.principal || open.authz.realm != context.realm {
            return Err(ConstellationError::new(
                ErrorKind::InvalidTarget,
                format!(
                    "stream kind '{}' has no accepted operation context",
                    open.descriptor.kind.code()
                ),
            ));
        }
        if !supported_stream_kind(open.descriptor.kind) {
            return Err(ConstellationError::new(
                d2b_realm_core::ErrorKind::UnsupportedFeature,
                format!(
                    "stream kind '{}' is not supported",
                    open.descriptor.kind.code()
                ),
            )
            .with_correlation_id(context.correlation_id.clone()));
        }
        if !context.stream_kinds.contains(&open.descriptor.kind) {
            return Err(ConstellationError::new(
                ErrorKind::MalformedFrame,
                format!(
                    "stream kind '{}' is not permitted for operation kind '{}'",
                    open.descriptor.kind.code(),
                    context.kind.code()
                ),
            )
            .with_correlation_id(context.correlation_id.clone()));
        }
        Ok(())
    }

    fn record_stream_denial(&mut self, open: &StreamOpen, err: &ConstellationError) {
        let context = self.operations.get(&open.operation_id);
        let safe_context = err.correlation_id().and(context);
        let correlation_id = err
            .correlation_id()
            .cloned()
            .or_else(|| safe_context.map(|ctx| ctx.correlation_id.clone()))
            .unwrap_or_else(|| CorrelationId::parse("stream-open-denied").unwrap());
        let node = safe_context
            .map(|ctx| ctx.node.clone())
            .unwrap_or_else(|| NodeId::parse("unknown").unwrap());
        let audit_realm = safe_context
            .map(|ctx| ctx.realm.clone())
            .unwrap_or_else(RealmPath::local);
        let audit_principal = self.audit_principal_for_denial(safe_context, err);
        let mut record = AdmissionAuditRecord::denied(
            open.operation_id.clone(),
            correlation_id.clone(),
            audit_realm.clone(),
            node.clone(),
            AuthorizationScope::capability(open.authz.capability),
            err.kind(),
        )
        .with_principal(audit_principal.clone());
        if let Some(context) = safe_context
            && let Some(trace) = context.trace.clone()
        {
            record = record.with_trace(trace);
        }
        self.last_admission_denial = Some(record);
        let operation_kind = safe_context.map(|ctx| ctx.kind.code()).unwrap_or("unbound");
        let trace_id = safe_context
            .and_then(|ctx| ctx.trace.as_ref())
            .map(TraceContext::trace_id);
        let span_id = safe_context
            .and_then(|ctx| ctx.trace.as_ref())
            .map(TraceContext::span_id);
        tracing::warn!(
            event = "stream-open-denied",
            stream = %open.descriptor.id.as_str(),
            "stream-kind" = %open.descriptor.kind.code(),
            "operation-id" = %open.operation_id.as_str(),
            "operation-kind" = %operation_kind,
            "correlation-id" = %correlation_id.as_str(),
            principal = %audit_principal.as_str(),
            realm = %audit_realm.target_form(),
            node = %node.as_str(),
            "trace-id" = trace_id,
            "span-id" = span_id,
            reason = %err.kind().code(),
            "stream open denied by mux admission"
        );
    }

    fn negotiated_principal(&self) -> Option<PrincipalId> {
        self.peer
            .negotiated()
            .peer
            .as_ref()
            .and_then(|peer| peer.peer_principal.clone())
    }

    fn unverified_principal() -> PrincipalId {
        PrincipalId::parse("unverified").expect("`unverified` is a valid principal id")
    }

    fn connection_principal(&self) -> PrincipalId {
        self.negotiated_principal()
            .unwrap_or_else(Self::unverified_principal)
    }

    fn audit_principal_for_denial(
        &self,
        context: Option<&OperationStreamContext>,
        err: &ConstellationError,
    ) -> PrincipalId {
        let _ = (context, err);
        self.negotiated_principal()
            .unwrap_or_else(Self::unverified_principal)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use d2b_realm_codec_protobuf::ProtobufCodec;
    use d2b_realm_core::{
        Capability, CapabilitySet, CorrelationId, IdempotencyKey, NodeId, OperationId,
        OperationKind, OperationRequest, PrincipalId, RealmId, RealmPath, StreamAuthz,
        StreamDescriptor, StreamFlow, StreamKind, WorkloadId,
    };
    use d2b_realm_provider::provider::TransportProvider;
    use d2b_realm_provider::types::{NodeRegistration, TransportSession, TransportTarget};
    use d2b_realm_transport::LoopbackTransport;
    use std::sync::Arc;

    async fn connected_pair() -> (TransportSession, TransportSession) {
        let transport = Arc::new(LoopbackTransport::new());
        let listener = transport
            .listen(NodeRegistration {
                node: d2b_realm_core::NodeId::parse("gateway").unwrap(),
            })
            .await
            .unwrap();
        let connect = {
            let transport = Arc::clone(&transport);
            tokio::spawn(async move {
                transport
                    .connect(TransportTarget {
                        endpoint: "loopback".to_owned(),
                    })
                    .await
            })
        };
        let server = listener.accept().await.unwrap();
        let client = connect.await.unwrap().unwrap();
        (client, server)
    }

    fn stream_id() -> StreamId {
        StreamId::parse("display-1").unwrap()
    }

    fn display_open() -> StreamOpen {
        let principal = PrincipalId::parse("alice").unwrap();
        StreamOpen {
            descriptor: StreamDescriptor {
                id: stream_id(),
                kind: StreamKind::Display,
            },
            operation_id: d2b_realm_core::OperationId::parse("op-1").unwrap(),
            authz: StreamAuthz::for_kind(principal, RealmPath::local(), StreamKind::Display),
        }
    }

    fn display_open_for(principal: &str, realm: RealmPath) -> StreamOpen {
        StreamOpen {
            descriptor: StreamDescriptor {
                id: stream_id(),
                kind: StreamKind::Display,
            },
            operation_id: d2b_realm_core::OperationId::parse("op-1").unwrap(),
            authz: StreamAuthz::for_kind(
                PrincipalId::parse(principal).unwrap(),
                realm,
                StreamKind::Display,
            ),
        }
    }

    fn display_open_for_work_realm() -> StreamOpen {
        display_open_for(
            "alice",
            RealmPath::new(vec![RealmId::parse("work").unwrap()]).expect("valid realm"),
        )
    }

    fn operation_request(kind: OperationKind, operation_id: &str) -> OperationRequest {
        OperationRequest {
            operation_id: OperationId::parse(operation_id).unwrap(),
            correlation_id: CorrelationId::parse("corr-1").unwrap(),
            idempotency_key: kind
                .is_mutating()
                .then(|| IdempotencyKey::parse(format!("{operation_id}-key")).unwrap()),
            realm: RealmPath::local(),
            node: NodeId::parse("gateway").unwrap(),
            workload: crate::operation_route_plan(kind).and_then(|plan| {
                plan.requires_workload
                    .then(|| WorkloadId::parse("work").unwrap())
            }),
            principal: PrincipalId::parse("alice").unwrap(),
            kind,
            trace: None,
            body: OpaquePayload::new(Vec::new()).unwrap(),
        }
    }

    fn display_operation() -> OperationRequest {
        operation_request(OperationKind::DisplaySessionOpen, "op-1")
    }

    fn workload_start_operation() -> OperationRequest {
        operation_request(OperationKind::WorkloadStart, "op-1")
    }

    fn cross_realm_workload_start_operation() -> OperationRequest {
        let mut request = workload_start_operation();
        request.realm = RealmPath::new(vec![RealmId::parse("work").unwrap()]).expect("valid realm");
        request.node = NodeId::parse("remote").unwrap();
        request
    }

    fn display_caps() -> CapabilitySet {
        CapabilitySet::empty().with(Capability::WindowForwarding)
    }

    fn clipboard_open() -> StreamOpen {
        let principal = PrincipalId::parse("alice").unwrap();
        StreamOpen {
            descriptor: StreamDescriptor {
                id: StreamId::parse("clipboard-1").unwrap(),
                kind: StreamKind::Clipboard,
            },
            operation_id: d2b_realm_core::OperationId::parse("op-clipboard-1").unwrap(),
            authz: StreamAuthz::for_kind(principal, RealmPath::local(), StreamKind::Clipboard),
        }
    }

    fn control_open() -> StreamOpen {
        let principal = PrincipalId::parse("unverified").unwrap();
        StreamOpen {
            descriptor: StreamDescriptor {
                id: StreamId::parse("control-1").unwrap(),
                kind: StreamKind::Control,
            },
            operation_id: d2b_realm_core::OperationId::parse("control-op-1").unwrap(),
            authz: StreamAuthz::for_kind(principal, RealmPath::local(), StreamKind::Control),
        }
    }

    fn operation_response(operation_id: &str) -> OperationResponse {
        OperationResponse {
            operation_id: OperationId::parse(operation_id).unwrap(),
            correlation_id: CorrelationId::parse("corr-1").unwrap(),
            body: OpaquePayload::new(b"ok".to_vec()).unwrap(),
        }
    }

    #[tokio::test]
    async fn mux_session_gates_open_flow_data_close_round_trip() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            let peer = PeerSession::accept_with_capabilities(
                server_s,
                ProtobufCodec::new(),
                display_caps(),
            )
            .await
            .unwrap();
            let mut s = MuxSession::new(peer);
            s.register_operation(&display_operation()).unwrap();
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::StreamOpen(_)
            ));
            assert!(s.mux().is_open(&stream_id()));
            s.grant_inbound(&stream_id(), 1).await.unwrap();
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::StreamData(_)
            ));
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::StreamClose(_)
            ));
            assert_eq!(
                s.mux().close_reason(&stream_id()),
                Some(StreamCloseReason::Completed)
            );
        });

        let peer =
            PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap();
        let mut client = MuxSession::new(peer);
        client.register_operation(&display_operation()).unwrap();
        client.open_stream(display_open()).await.unwrap();
        assert!(matches!(
            client.recv().await.unwrap(),
            ConstellationFrame::StreamFlow(StreamFlow { credits: 1, .. })
        ));
        client
            .send_data(
                &stream_id(),
                StreamChannel::Primary,
                OpaquePayload::new(b"wayland".to_vec()).unwrap(),
            )
            .await
            .unwrap();
        client
            .close_stream(&stream_id(), StreamCloseReason::Completed)
            .await
            .unwrap();

        server.await.unwrap();
    }

    #[tokio::test]
    async fn inbound_data_before_credit_is_rejected() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            let peer = PeerSession::accept_with_capabilities(
                server_s,
                ProtobufCodec::new(),
                display_caps(),
            )
            .await
            .unwrap();
            let mut s = MuxSession::new(peer);
            let request = match s.recv().await.unwrap() {
                ConstellationFrame::OperationRequest(request) => request,
                other => panic!("expected operation request, got {other:?}"),
            };
            s.register_operation(&request).unwrap();
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::StreamOpen(_)
            ));
            s.recv().await.unwrap_err()
        });

        let mut peer =
            PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap();
        peer.send(&ConstellationFrame::OperationRequest(display_operation()))
            .await
            .unwrap();
        peer.send(&ConstellationFrame::StreamOpen(display_open()))
            .await
            .unwrap();
        peer.send(&ConstellationFrame::StreamData(StreamData {
            stream: stream_id(),
            sequence: 0,
            channel: StreamChannel::Primary,
            cursor: None,
            data: OpaquePayload::new(b"without-credit".to_vec()).unwrap(),
        }))
        .await
        .unwrap();

        let err = server.await.unwrap();
        assert_eq!(err.kind(), d2b_realm_core::ErrorKind::Backpressure);
    }

    #[tokio::test]
    async fn send_data_without_outbound_credit_is_rejected() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            let peer = PeerSession::accept_with_capabilities(
                server_s,
                ProtobufCodec::new(),
                display_caps(),
            )
            .await
            .unwrap();
            let mut s = MuxSession::new(peer);
            s.register_operation(&display_operation()).unwrap();
            let _ = s.recv().await.unwrap();
        });

        let peer =
            PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap();
        let mut client = MuxSession::new(peer);
        client.register_operation(&display_operation()).unwrap();
        client.open_stream(display_open()).await.unwrap();
        let err = client
            .send_data(
                &stream_id(),
                StreamChannel::Primary,
                OpaquePayload::new(b"without-credit".to_vec()).unwrap(),
            )
            .await
            .unwrap_err();
        assert_eq!(err.kind(), d2b_realm_core::ErrorKind::Backpressure);
        server.await.unwrap();
    }

    #[tokio::test]
    async fn duplicate_stream_open_denial_preserves_operation_audit_context() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            let peer = PeerSession::accept_with_capabilities(
                server_s,
                ProtobufCodec::new(),
                display_caps(),
            )
            .await
            .unwrap();
            let mut s = MuxSession::new(peer);
            s.register_operation(&display_operation()).unwrap();
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::OperationRequest(_)
            ));
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::StreamOpen(_)
            ));
            let err = s.recv().await.unwrap_err();
            let denial = s
                .last_admission_denial()
                .expect("duplicate stream denial audit record");
            assert_eq!(denial.correlation_id.as_str(), "corr-1");
            assert_eq!(denial.node.as_str(), "gateway");
            assert_eq!(denial.realm, RealmPath::local());
            err
        });

        let mut peer =
            PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap();
        peer.send(&ConstellationFrame::OperationRequest(display_operation()))
            .await
            .unwrap();
        peer.send(&ConstellationFrame::StreamOpen(display_open()))
            .await
            .unwrap();
        peer.send(&ConstellationFrame::StreamOpen(display_open()))
            .await
            .unwrap();
        assert!(matches!(
            peer.recv().await.unwrap(),
            ConstellationFrame::AdmissionAudit(record)
                if record.correlation_id.as_str() == "corr-1"
                    && record.node.as_str() == "gateway"
                    && record.realm == RealmPath::local()
        ));
        let err = server.await.unwrap();
        assert_eq!(err.kind(), d2b_realm_core::ErrorKind::MalformedFrame);
    }

    #[tokio::test]
    async fn unsupported_stream_kind_is_rejected_even_when_capability_is_advertised() {
        let (client_s, server_s) = connected_pair().await;
        let caps = CapabilitySet::empty().with(Capability::Clipboard);
        let server_caps = caps.clone();
        let server = tokio::spawn(async move {
            let peer =
                PeerSession::accept_with_capabilities(server_s, ProtobufCodec::new(), server_caps)
                    .await
                    .unwrap();
            let mut s = MuxSession::new(peer);
            let err = s.recv().await.unwrap_err();
            let denial = s
                .last_admission_denial()
                .expect("unknown stream denial audit record");
            assert_eq!(denial.reason, d2b_realm_core::ErrorKind::InvalidTarget);
            assert_eq!(denial.correlation_id.as_str(), "stream-open-denied");
            assert_eq!(
                denial.principal.as_ref().map(PrincipalId::as_str),
                Some("unverified")
            );
            assert_eq!(denial.realm, RealmPath::local());
            err
        });

        let peer = PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), caps)
            .await
            .unwrap();
        let mut client = MuxSession::new(peer);
        let err = client.open_stream(clipboard_open()).await.unwrap_err();
        assert_eq!(err.kind(), d2b_realm_core::ErrorKind::InvalidTarget);
        let mut peer = client.peer;
        peer.send(&ConstellationFrame::StreamOpen(clipboard_open()))
            .await
            .unwrap();
        assert!(matches!(
            peer.recv().await.unwrap(),
            ConstellationFrame::AdmissionAudit(record)
                if record.reason == d2b_realm_core::ErrorKind::InvalidTarget
                    && record.correlation_id.as_str() == "stream-open-denied"
                    && record.principal.as_ref().map(PrincipalId::as_str) == Some("unverified")
        ));
        let err = server.await.unwrap();
        assert_eq!(err.kind(), d2b_realm_core::ErrorKind::InvalidTarget);
    }

    #[tokio::test]
    async fn cancel_stream_is_idempotent() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            let peer = PeerSession::accept_with_capabilities(
                server_s,
                ProtobufCodec::new(),
                display_caps(),
            )
            .await
            .unwrap();
            let mut s = MuxSession::new(peer);
            s.register_operation(&display_operation()).unwrap();
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::StreamOpen(_)
            ));
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::StreamClose(StreamClose {
                    reason: StreamCloseReason::Cancelled,
                    ..
                })
            ));
        });

        let peer =
            PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap();
        let mut client = MuxSession::new(peer);
        client.register_operation(&display_operation()).unwrap();
        client.open_stream(display_open()).await.unwrap();
        assert!(client.cancel_stream(&stream_id()).await.unwrap());
        assert!(!client.cancel_stream(&stream_id()).await.unwrap());
        server.await.unwrap();
    }

    #[tokio::test]
    async fn stream_kind_must_match_authorizing_operation_plan() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            let peer = PeerSession::accept_with_capabilities(
                server_s,
                ProtobufCodec::new(),
                display_caps(),
            )
            .await
            .unwrap();
            let mut s = MuxSession::new(peer);
            s.register_operation(&cross_realm_workload_start_operation())
                .unwrap();
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::OperationRequest(_)
            ));
            let err = s.recv().await.unwrap_err();
            let denial = s
                .last_admission_denial()
                .expect("stream denial audit record");
            assert_eq!(denial.reason, d2b_realm_core::ErrorKind::MalformedFrame);
            assert_eq!(denial.operation_id.as_str(), "op-1");
            assert_eq!(denial.realm.target_form(), "work");
            assert_eq!(denial.node.as_str(), "remote");
            err
        });

        let mut peer =
            PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap();
        peer.send(&ConstellationFrame::OperationRequest(
            cross_realm_workload_start_operation(),
        ))
        .await
        .unwrap();
        peer.send(&ConstellationFrame::StreamOpen(
            display_open_for_work_realm(),
        ))
        .await
        .unwrap();
        assert!(matches!(
            peer.recv().await.unwrap(),
            ConstellationFrame::AdmissionAudit(record)
                if record.reason == d2b_realm_core::ErrorKind::MalformedFrame
        ));

        let err = server.await.unwrap();
        assert_eq!(err.kind(), d2b_realm_core::ErrorKind::MalformedFrame);
        assert!(err.message().contains("workload-start"));
    }

    #[tokio::test]
    async fn stream_authz_must_match_operation_principal_and_realm() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            let peer = PeerSession::accept_with_capabilities(
                server_s,
                ProtobufCodec::new(),
                display_caps(),
            )
            .await
            .unwrap();
            let mut s = MuxSession::new(peer);
            s.register_operation(&display_operation()).unwrap();
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::OperationRequest(_)
            ));
            let err = s.recv().await.unwrap_err();
            let denial = s
                .last_admission_denial()
                .expect("authz mismatch audit record");
            assert_eq!(denial.reason, d2b_realm_core::ErrorKind::InvalidTarget);
            assert_eq!(
                denial.principal.as_ref().map(PrincipalId::as_str),
                Some("unverified")
            );
            err
        });

        let mut peer =
            PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap();
        peer.send(&ConstellationFrame::OperationRequest(display_operation()))
            .await
            .unwrap();
        peer.send(&ConstellationFrame::StreamOpen(display_open_for(
            "mallory",
            RealmPath::local(),
        )))
        .await
        .unwrap();
        assert!(matches!(
            peer.recv().await.unwrap(),
            ConstellationFrame::AdmissionAudit(record)
                if record.reason == d2b_realm_core::ErrorKind::InvalidTarget
                    && record.principal.as_ref().map(PrincipalId::as_str) == Some("unverified")
        ));

        let err = server.await.unwrap();
        assert_eq!(err.kind(), d2b_realm_core::ErrorKind::InvalidTarget);
    }

    #[tokio::test]
    async fn operation_contexts_are_bounded_and_can_be_unregistered() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            PeerSession::accept_with_capabilities(server_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap()
        });
        let peer =
            PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap();
        let mut mux = MuxSession::new(peer);
        for idx in 0..=MAX_OPERATION_CONTEXTS {
            let req = operation_request(OperationKind::DisplaySessionOpen, &format!("op-{idx}"));
            mux.register_operation(&req).unwrap();
        }
        assert_eq!(mux.operations.len(), MAX_OPERATION_CONTEXTS);
        assert_eq!(mux.operation_order.len(), MAX_OPERATION_CONTEXTS);
        let first = OperationId::parse("op-0").unwrap();
        assert!(!mux.operations.contains_key(&first));
        let last = OperationId::parse(format!("op-{MAX_OPERATION_CONTEXTS}")).unwrap();
        mux.unregister_operation(&last);
        assert!(!mux.operations.contains_key(&last));
        drop(mux);
        server.await.unwrap();
    }

    #[tokio::test]
    async fn completed_operation_churn_keeps_eviction_queue_bounded() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            PeerSession::accept_with_capabilities(server_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap()
        });
        let peer =
            PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap();
        let mut mux = MuxSession::new(peer);
        for idx in 0..(MAX_OPERATION_CONTEXTS * 2) {
            let id = format!("op-{idx}");
            let req = operation_request(OperationKind::DisplaySessionOpen, &id);
            mux.register_operation(&req).unwrap();
            mux.unregister_operation(&req.operation_id);
        }
        assert_eq!(mux.operations.len(), 0);
        assert!(mux.operation_order.len() <= MAX_OPERATION_CONTEXTS);
        drop(mux);
        server.await.unwrap();
    }

    #[tokio::test]
    async fn duplicate_operation_ids_are_rejected_fail_closed() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            PeerSession::accept_with_capabilities(server_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap()
        });
        let peer =
            PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap();
        let mut mux = MuxSession::new(peer);
        let req = display_operation();
        mux.register_operation(&req).unwrap();
        let err = mux.register_operation(&req).unwrap_err();
        assert_eq!(err.kind(), d2b_realm_core::ErrorKind::MalformedFrame);
        assert_eq!(
            err.correlation_id().map(CorrelationId::as_str),
            Some("corr-1")
        );
        drop(mux);
        server.await.unwrap();
    }

    #[tokio::test]
    async fn typed_error_with_correlation_clears_matching_operation_context() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            PeerSession::accept_with_capabilities(server_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap()
        });
        let peer =
            PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap();
        let mut mux = MuxSession::new(peer);
        let request = display_operation();
        let operation_id = request.operation_id.clone();
        mux.register_operation(&request).unwrap();
        assert!(mux.operations.contains_key(&operation_id));
        mux.apply_inbound(&ConstellationFrame::TypedError(
            ConstellationError::new(d2b_realm_core::ErrorKind::InvalidTarget, "denied")
                .with_correlation_id(request.correlation_id.clone()),
        ))
        .unwrap();
        assert!(!mux.operations.contains_key(&operation_id));
        drop(mux);
        server.await.unwrap();
    }

    #[tokio::test]
    async fn control_streams_are_connection_scoped() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            let peer = PeerSession::accept_with_capabilities(
                server_s,
                ProtobufCodec::new(),
                CapabilitySet::empty().with(Capability::Lifecycle),
            )
            .await
            .unwrap();
            let mut s = MuxSession::new(peer);
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::StreamOpen(open)
                    if open.descriptor.kind == StreamKind::Control
            ));
        });

        let peer = PeerSession::connect_with_capabilities(
            client_s,
            ProtobufCodec::new(),
            CapabilitySet::empty().with(Capability::Lifecycle),
        )
        .await
        .unwrap();
        let mut mux = MuxSession::new(peer);
        mux.open_stream(control_open()).await.unwrap();
        server.await.unwrap();
    }

    #[tokio::test]
    async fn mux_session_sends_operation_control_frames_and_cleans_context() {
        let (client_s, server_s) = connected_pair().await;
        let server = tokio::spawn(async move {
            let peer = PeerSession::accept_with_capabilities(
                server_s,
                ProtobufCodec::new(),
                display_caps(),
            )
            .await
            .unwrap();
            let mut s = MuxSession::new(peer);
            let request = match s.recv().await.unwrap() {
                ConstellationFrame::OperationRequest(request) => request,
                other => panic!("expected operation request, got {other:?}"),
            };
            s.register_operation(&request).unwrap();
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::StreamOpen(_)
            ));
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::OperationResponse(response)
                    if response.operation_id.as_str() == "op-1"
            ));
            assert!(matches!(
                s.recv().await.unwrap(),
                ConstellationFrame::TypedError(err)
                    if err.kind() == d2b_realm_core::ErrorKind::Cancelled
            ));
        });

        let peer =
            PeerSession::connect_with_capabilities(client_s, ProtobufCodec::new(), display_caps())
                .await
                .unwrap();
        let mut client = MuxSession::new(peer);
        client
            .send_operation_request(display_operation())
            .await
            .unwrap();
        assert!(
            client
                .operations
                .contains_key(&OperationId::parse("op-1").unwrap())
        );
        client.open_stream(display_open()).await.unwrap();
        client
            .send_operation_response(operation_response("op-1"))
            .await
            .unwrap();
        assert!(
            !client
                .operations
                .contains_key(&OperationId::parse("op-1").unwrap())
        );
        client
            .send_typed_error(ConstellationError::new(
                d2b_realm_core::ErrorKind::Cancelled,
                "operation cancelled",
            ))
            .await
            .unwrap();
        server.await.unwrap();
    }
}
